### ISSUE TITLE
Old DB schema

### ISSUE THREAD

**Issue by MosinAnton** [sipcapture/homer-app#1]
Homer UI use 'gid' field in requests, but it was deleted in heplify-server.

`{"msec":13.167360999621451,"error":"select \"id\", \"sid\", \"gid\", \"protocol_header\", \"data_header\", ROUND(EXTRACT(epoch FROM create_date)*1000) as create_date from \"hep_proto_1_call\" where \"create_date\" between $1 and $2 - column \"gid\" does not exist","data":{"name":"error","length":206,"severity":"ERROR","code":"42703","hint":"Perhaps you meant to reference the column \"hep_proto_1_call.id\" or the column \"hep_proto_1_call.sid\".","position":"21","file":"parse_relation.c","line":"3311","routine":"errorMissingColumn","isBoom":true,"isServer":true,"output":{"statusCode":503,"payload":{"statusCode":503,"error":"Service Unavailable","message":"select \"id\", \"sid\", \"gid\", \"protocol_header\", \"data_header\", ROUND(EXTRACT(epoch FROM create_date)*1000) as create_date from \"hep_proto_1_call\" where \"create_date\" between $1 and $2 - column \"gid\" does not exist"},"headers":{}}}}`

**Comment by lmangani** [comment]
@MosinAnton this is intentional - GID has no longer a role in HOMER. Thanks for the report.

**Comment by lmangani** [comment]
@MosinAnton to make sure i did not misunderstand, what's the bundle you are using? This might have to be reopened accordingly :)

**Comment by lmangani** [comment]
Reopened pending fix to drop the query option

**Comment by lmangani** [comment]
This issue has been fixed but outlined a couple more adjustments we'll open in parallel.
Thanks again for your precious report!
