### ISSUE TITLE
Prometheus chart failure

### ISSUE THREAD

**Issue by ognyenius** [sipcapture/homer-app#109]
On Panels:test page 
"prometheus chart" seams to be broken

<img width="1033" alt="Screen Shot 2019-03-11 at 14 22 32" src="https://user-images.githubusercontent.com/47450374/54127506-37eab080-440a-11e9-820e-1ce1d240a16f.png">

**Comment by adubovikov** [comment]
did you test the latest one ? I have pulled today

**Comment by ognyenius** [comment]
@adubovikov yes. actually I think it is all right now with just a small latency when the chart is loading

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/47450374/54128569-aa5c9000-440c-11e9-9bdb-d0dbc96274d9.gif)

**Comment by adubovikov** [comment]
this is resizing "post event" How quick data is arriving ?

**Comment by ognyenius** [comment]
@adubovikov less than 2 seconds

**Comment by adubovikov** [comment]
please check it in the web console of your browser (F12) -> network tab. If it takes so longer = 2 seconds - probably is something or with backend (Prometheus) or your network

**Comment by ognyenius** [comment]
It loads fast. Seams to be ok. Probably was something with my network
