### ISSUE TITLE
Panels section bug (version 7.0.4)

### ISSUE THREAD

**Issue by ognyenius** [sipcapture/homer-app#110]
When in "Panels" section "Test" is selected and after this we go back to "Home" by pressing HOMER logo in the upper left corner, "Panels" section is showing - Panels: Test instead of Panels: Home

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/47450374/54135281-cdda0780-4419-11e9-8c9c-c7c1e5a02b62.gif)

**Comment by adubovikov** [comment]
ok. I will assign to Denis, he will check it.
