### ISSUE TITLE
Search columns missing (ver 7.0.4)

### ISSUE THREAD

**Issue by ognyenius** [sipcapture/homer-app#114]
When we filter search (home page - call sip search) by entering "Src port" number or "Session ID", more than a half "search columns" aren't visible at the Search Results page
See the screenshot bellow for more details:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/47450374/54356811-cb1b2480-465c-11e9-9254-aade798da2c8.gif)

**Comment by adubovikov** [comment]
please check the response of API - if there are all headers

**Comment by ognyenius** [comment]
```
HTTP/1.1 200 OK
content-length: 2640
content-type: text/html; charset=utf-8
last-modified: Fri, 08 Mar 2019 16:02:36 GMT
etag: "f4430f8924e0f3f991d2912b7cf7fbd82f4b6dd0"
cache-control: no-cache
accept-ranges: bytes
vary: accept-encoding
Date: Fri, 15 Mar 2019 13:09:36 GMT
Connection: keep-alive
```

This is the response header
