### ISSUE TITLE
No "Limit Result" is found in "call sip search" widget (ver 7.0.4)  

### ISSUE THREAD

**Issue by ognyenius** [sipcapture/homer-app#115]
In the "call sip search" widget - settings - add from field section, no "Limit Result" option is found at the drop-down menu
See the screenshot for details:

<img width="1272" alt="Screen Shot 2019-03-14 at 13 39 12" src="https://user-images.githubusercontent.com/47450374/54357570-a7f17480-465e-11e9-990d-cd3fe40cd033.png">
<img width="707" alt="Screen Shot 2019-03-14 at 13 39 31" src="https://user-images.githubusercontent.com/47450374/54357597-b0e24600-465e-11e9-84e3-50f8830b9039.png">

**Comment by adubovikov** [comment]
confirmed. The fields are from DB only. I will check it

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/commit/2fe1fd8d83962b14fbd859ddbd72b780fb063015 
fixed please check
