### ISSUE TITLE
Proto column in search results

### ISSUE THREAD

**Issue by Dazez** [sipcapture/homer-app#118]
Hello,
When I have searched, for example, a call, column Proto is UDP in all cells. But the calls are over TCP/TLS/WS. I had the same topology with H5 and the same column was filled with "ws" correctly, so I think that this is a bug.

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
