### ISSUE TITLE
Heplify-server and Homer7 call correlation

### ISSUE THREAD

**Issue by nevian427** [sipcapture/homer-app#119]
Hi,

After some experiments I see Alexander’s advice is not working:
Query execution failed

Reason:
SQL Error [42703]: ERROR: column "data_header.callid" does not exist

If we change mapping to more correct Postgres notation (->>) we again got same error
Query execution failed

Reason:
SQL Error [42703]: ERROR: column "data_header->>'callid'" does not exist

To get it working we need somehow to get rid of quotes around data_header->>’callid'

select "id", "sid", "protocol_header", "data_header", "raw", ROUND(EXTRACT(epoch FROM create_date)*1000) as create_date from "hep_proto_1_call" where data_header->>callid' in ($1, $2)

====
unfortunately i can only give you an advice and link to the code. You can do any X-CID correlation, and here is the way:

https://github.com/sipcapture/homer-app/blob/master/seeds/02_Mapping.js#L434

you can take any header and make own correlation lookup in any tables:

{
      source_field: 'data_header.callid',
      lookup_id: 5,
      lookup_profile: 'default',
      lookup_field: 'data_header.x-cid',
      lookup_range: [-300, 200],
},

the last version of UI should also include "Mapping interface" Let me know if it doesn't

_Originally posted by @adubovikov in https://github.com/sipcapture/homer-app/issues/50#issuecomment-466374336_

**Comment by lmangani** [comment]
@nevian427 that's not old, `correlation_id` within the `hep` is used by agents (mostly within or around B2BUAs or RTP Relays) to forward leg correlation when they can, often based on SDP determinations. This offloads the lookup for cases where the link is known already at the source.

**Comment by nevian427** [comment]
It's not a HEP chunk, it's (old?) db scheme 
https://github.com/sipcapture/homer-app/blob/2fe1fd8d83962b14fbd859ddbd72b780fb063015/server/classes/searchdata.js#L195

**Comment by lmangani** [comment]
That's not old @nevian427 the content of that field comes out of a `hep` chunk whenever available first hand, or it can be filled by the capture server either. `sid` is just a common unique identifier to host the same function in homer seven

**Comment by nevian427** [comment]
But now there is no such column in DB. Is it traces from H5 or future of H7?
I can see such subfield in protocol_header definition but it's not used either (shouldn't heplify fill this?)

**Comment by lmangani** [comment]
In `H7` the concept is simply non-static. The header can contain any correlation id, and the backend can loop them together regardless of their name. It's an abstraction developers can use with more freedom, particularly when different or multiple correlations methods are required (cross-protocol case)
That's what the `source field` parameter in correlation is for - so anything can be elected to a `correlation_id` equivalent under the new design.

**Comment by lmangani** [comment]
I see activity in the mailing list related to this issue - I would suggest re-testing with the latest codebase and using the included correlation examples for validation - channel any input in here, this is an active issue and will be followed up - Thanks!

**Comment by fpiccinin** [comment]
@lmangani can you please provide more details about the configuration needed to acheive the result and where we can find the examples you are referring to?
Thanks!

**Comment by vandykew** [comment]
How can we do this ?

I am using hom7-hep-prom-graf

**Comment by vance-od** [comment]
We started using Homer7, and lack of this feature is quite inconvenient comparing to Homer5.
is there are any estimates when it can be implemented?

**Comment by adubovikov** [comment]
@vance-od sorry, can you please provide more info what doesn't work for you ?

@nevian427 Are you sure what you have to lookup ID: 5 for correlation ?

`{
source_field: 'data_header.callid', // This is SOURCE field from first table. I.e. SIP-CALL = hep_proto_1_call
lookup_id: 5, // this is DESTINATION lookup table i.e. hep_proto_5
lookup_profile: 'default', // this is profile -> hep_proto_5_default
lookup_field: 'data_header.x-cid', // THIS IS LOOKUP DESTINATION field 
lookup_range: [-300, 200], // THIS IS LOOKUP RANGE from+=-300 , to+=200
},`

I think we should start put this information to WIKI here.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/wiki/Examples:-Correlation-MAPPING

**Comment by vance-od** [comment]
> @vance-od sorry, can you please provide more info what doesn't work for you ?
> 
> @nevian427 Are you sure what you have to lookup ID: 5 for correlation ?
> 
> ```
> {
> source_field: 'data_header.callid', // This is SOURCE field from first table. I.e. SIP-CALL = hep_proto_1_call
> lookup_id: 5, // this is DESTINATION lookup table i.e. hep_proto_5
> lookup_profile: 'default', // this is profile -> hep_proto_5_default
> lookup_field: 'data_header.x-cid', // THIS IS LOOKUP DESTINATION field 
> lookup_range: [-300, 200], // THIS IS LOOKUP RANGE from+=-300 , to+=200
> }
> ```
> 
> I think we should start put this information to WIKI here.

hi Alex!
thx for the quick reply!
this is definitely what is missing in the Wiki. Our current target is SIP leg correlation
We will give it a try today - and give you feedback

**Comment by fpiccinin** [comment]
Hi all, thanks for all the updates about the issue.
Anyway I'm trying to edit mapping settings through web-app but it does not save any changes.
Is there any permissions or flag setting that I need to change?
Thanks

**Comment by adubovikov** [comment]
@fpiccinin please be sure that your syntax in the editor is correct.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/commit/c2e212acd1ad445e07d79e9e5ddad54b1a1364ee

fixed. Please recheck!

**Comment by vladislavvvvvvv** [comment]
> @vance-od sorry, can you please provide more info what doesn't work for you ?
> 
> @nevian427 Are you sure what you have to lookup ID: 5 for correlation ?
> 
> ```
> {
> source_field: 'data_header.callid', // This is SOURCE field from first table. I.e. SIP-CALL = hep_proto_1_call
> lookup_id: 5, // this is DESTINATION lookup table i.e. hep_proto_5
> lookup_profile: 'default', // this is profile -> hep_proto_5_default
> lookup_field: 'data_header.x-cid', // THIS IS LOOKUP DESTINATION field 
> lookup_range: [-300, 200], // THIS IS LOOKUP RANGE from+=-300 , to+=200
> }
> ```
> 
if I right understand hep_proto_5_default have rtcp information, but not sip information.
Also  heplify-server in default not save x-cid information of sip message in data_header field - save in raw field.

Maybe leg correlation in default case :
  {
    "source_field": "data_header.callid",
    "lookup_id": 100,
    "lookup_profile": "default",
    "lookup_filed": "raw.x-cid",
    "lookup_range": [
      -300,
      200
    ]
  }

**Comment by negbie** [comment]
It seems there is a lot of confusion about the aleg correlation. Just to make sure there is no x-cid field. At least not in heplify-server. Right now there are following protocol_header source_field:
	(`"protocolFamily":`)
	(`"protocol":`)
	(`"srcIp":"`)
	(`"dstIp":"`)
	(`"srcPort":`)
	(`"dstPort":`)
	(`"timeSeconds":`)
	(`"timeUseconds":`)
	(`"payloadType":`)
	(`"captureId":"`)
	(`"capturePass":"`)
	(`"correlation_id":"`)

And following data_header source_field:
	(`"ruri_domain":"`)
	(`"ruri_user":"`)
	(`"from_user":"`)
	(`"to_user":"`)
	(`"pid_user":"`)
	(`"auth_user":"`)
	(`"callid":"`)
	(`"method":"`)
	(`"user_agent":"`)

**Comment by negbie** [comment]
Best way would be if someone could provide a pcap with alegID so we can test it.

**Comment by vladislavvvvvvv** [comment]
@negbie 
ok. I try use correlation id . Siptrace  send  good correlation_id.  In decoder.go h.CID of protoType: 1 I get correlation id (h.CID in decoder.go), but then h.CID was rewritten on CallID and in postgres.go corrid is empty (and not write correlation_id) . In attachments file dump of packets to heplify-server.

[test890.zip](https://github.com/sipcapture/homer-app/files/3227234/test890.zip)

**Comment by vladislavvvvvvv** [comment]
To @negbie
In siptrace of kamailio  (client side) we send correlation_id like sip_trace("sip:10.1.1.2:5085", "$bleg_cid");
On server side we get in decoder.go correlation_id in h.CID then in sip.go set up h.CID=h.SIP.CallID, if  heplify-server didn't get XCallID (in this moment we break our correlation_id for insert into database).
Maybe need set up push request for changing in sip.go ?
before  change
	if h.SIP.XCallID == "" {
		h.CID = h.SIP.CallID
	} else {
		h.CID = h.SIP.XCallID
	}
after change
	if h.SIP.XCallID != "" {
		h.CID = h.SIP.XCallID
	}

**Comment by negbie** [comment]
Hi @vladislavvvvvvv 
sorre for the delay but had to finish some other stuff but now I have some time to assist you. I've changed the handling to this
https://github.com/sipcapture/heplify-server/blob/master/decoder/sip.go#L23

**Comment by vladislavvvvvvv** [comment]
@negbie
Thank you.
Now we see correct draw the flow  b_leg with a_leg, thanks to fix the correlation_id.

**Comment by vladislavvvvvvv** [comment]
But have another problem with homer-app (about leg correlation),
if I set in mapping settings - call SIP with parameters
{    "source_field": "data_header.callid",
    "lookup_id": 1,
    "lookup_profile": "call",
    "lookup_field": "sid",
    "lookup_range": [
      -300,
      200]  }
I have result with some duplicate message of sip such as:
215019 | 04-06-2019 | 11:01:27.282 | 0.000s | 407 | 505 | 127.0.0.1 | 5061 | 127.0.0.1 | 40167 | UDP | SIP
215018 | 04-06-2019 | 11:01:27.282 | 0.000s | INVITE | 5962 | 127.0.0.1 | 40167 | 127.0.0.1 | 5061 | UDP | SIP
215018 | 04-06-2019 | 11:01:27.282 | 0.000s | INVITE | 5962 | 127.0.0.1 | 40167 | 127.0.0.1 | 5061 | UDP | SIP
215019 | 04-06-2019 | 11:01:27.282 | 0.000s | 407 | 505 | 127.0.0.1 | 5061 | 127.0.0.1 | 40167 | UDP | SIP
But in call table no duplicate records:
select id from hep_proto_1_call where id::text like '2501%' limit 100;
  id   
-------
  2501
 25010
 25011
 25012
 25013
 25014
 25015
 25016
 25017
 25018
 25019
(11 rows)

**Comment by vladislavvvvvvv** [comment]
But have another problem with homer-app (about leg correlation),
if I set in mapping settings - call SIP with parameters
{ "source_field": "data_header.callid",
"lookup_id": 1,
"lookup_profile": "call",
"lookup_field": "sid",
"lookup_range": [
-300,
200] }
I have result with some duplicate message of sip such as:
215019 | 04-06-2019 | 11:01:27.282 | 0.000s | 407 | 505 | 127.0.0.1 | 5061 | 127.0.0.1 | 40167 | UDP | SIP
215018 | 04-06-2019 | 11:01:27.282 | 0.000s | INVITE | 5962 | 127.0.0.1 | 40167 | 127.0.0.1 | 5061 | UDP | SIP
215018 | 04-06-2019 | 11:01:27.282 | 0.000s | INVITE | 5962 | 127.0.0.1 | 40167 | 127.0.0.1 | 5061 | UDP | SIP
215019 | 04-06-2019 | 11:01:27.282 | 0.000s | 407 | 505 | 127.0.0.1 | 5061 | 127.0.0.1 | 40167 | UDP | SIP
But in call table no duplicate records:
select id from hep_proto_1_call where id::text like '2501%' limit 100;
id
2501
25010
25011
25012
25013
25014
25015
25016
25017
25018
25019
(11 rows)

**Comment by vladislavvvvvvv** [comment]
Hello! Have any news about duplicate sip messages ?

**Comment by adubovikov** [comment]
In the correlation mapping you do a second request that retrieve same sip
session (same calif in the sid). If you tell us that exactly you are trying
to do, we can give you an advise.

Wbr,
Alexandr

**Comment by vladislavvvvvvv** [comment]
I want see sip messages for A leg with B leg when I use correlation id. Correlation id I have in database. When I use mapping settings 
{ "source_field": "data_header.callid",
"lookup_id": 1,
"lookup_profile": "default",
"lookup_field": "sid",
"lookup_range": [
-300,
200] }
I didn't see b-leg . When I use in settings "lookup_profile": "call" - we see b-leg but with some duplicate sip messages. How to see a and b leg without some duplicate sip messages.

**Comment by aqsyonas** [comment]
@vladislavvvvvvv as said before it looks like you are doing a lookup for the same leg again. Check your data_header and adjust your query accordingly.

**Comment by os11k** [comment]
Hi! First of all thank you for all of your efforts building Homer. I really enjoying it!!!

Nevertheless I still do not understand how I can correlate separate calls based on call-id in header? Is it even possible or it is possible only via inserting data to HEP header???

**Comment by lmangani** [comment]
Hi @os11k and thanks for the kind words!

If the call-ids are already the same (proxy) the correlation should be automatic. If they are not, there's multiple approaches - a common one is to insert an X-Header in the B-Leg containing the A-Leg call-id and letting HOMER do the correlation by configuring the `AlegIDs` parameter in `heplify-server`, ie:

```
AlegIDs = ["X-CID", "x-cid"]
```

**Comment by os11k** [comment]
Hi @lmangani !

Is it possible to configure in docker-compose via environment variables? Like this:

`"HEPLIFYSERVER_ALEGIDS=X-CID"`

**Comment by lmangani** [comment]
@os11k yes check the examples

**Comment by os11k** [comment]
@lmangani it worked thank you! But quite often call is not glued correctly in Web app. Somehow it glues only INVITE, but not whole call. Should I open new bug for this? Nevertheless for some other calls it works as expected...

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
