### ISSUE TITLE
Search Params edit mode

### ISSUE THREAD

**Issue by lmangani** [sipcapture/homer-app#12]
Search Params edit (via SweetAlert) are only partially implemented, missing the edit Functionality:
![image](https://user-images.githubusercontent.com/1423657/45918787-58d73d80-be8c-11e8-9249-735764327cf5.png) 

Clicking the EDIT or double-clicking the Filter should render the edit mode and resubmit search

**Comment by lmangani** [comment]
PS: Are we using [SweetAlert2](https://sweetalert2.github.io/) as per original plan?

**Comment by sergibondarenko** [comment]
@lmangani How can I create this notification you have in the screenshot?
