### ISSUE TITLE
install: root permissions: eslint, knex

### ISSUE THREAD

**Issue by dpocock** [sipcapture/homer-app#120]
I followed the installation procedure in https://github.com/sipcapture/homer-app/blob/master/docs/dev/README.md

When I run this command during the installation:

npm install -g knex eslint eslint-plugin-html eslint-plugin-json eslint-config-google

it wants to write to /usr/local/bin and /usr/local/lib with root permissions.  The command aborts.

This is for knex and eslint

knex and eslint are not available as packages yet, although there is an RFP for eslint:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=743404

Some users might be willing to run that command as root, especially if the box is only used for HOMER.  I don't think any other commands need root permissions during installation, except things like using apt to install PostgreSQL and Prometheus

Can you please update the docs to note the requirement for root permissions and maybe suggest alternatives such as fakeroot and a file copy?

**Comment by lmangani** [comment]
@dpocock this is a circumstance only relevant to app developers really, currently impacting all users while we are in pre-release stage excluding those on Docker. The intention is to distribute a prepacked version of `homer-app` next for installation next. Might change the issue title to reflect this perhaps.

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
