### ISSUE TITLE
extra search panel vanishes

### ISSUE THREAD

**Issue by dpocock** [sipcapture/homer-app#122]
The search panel installed by default only searches calls.

I added a registration search panel and used it to make a search.

When I return to the main screen, the registration search panel has vanished and I have to add it again.

**Comment by lmangani** [comment]
@dpocock you need to `save` panels after modifications for them to be retained. This is done from the dashboard menu under the time selection part on the `top-right` of the panel

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
