### ISSUE TITLE
server/config.js includes both influxdb and prometheus

### ISSUE THREAD

**Issue by dpocock** [sipcapture/homer-app#123]
Both influxdb and prometheus appear to be enabled in server/config.js

It is not clear how to disable one of them when the other is being used.

**Comment by lmangani** [comment]
@dpocock both can be used at the same time and more might appear, too. Those are defaults to reach the back-ends and are not used unless a widget specifically attempts to fetch from either. FYI Homer is able to display also data it did not create itself and this is the main reason why this is possible.
