### ISSUE TITLE
display error if database not in good state

### ISSUE THREAD

**Issue by dpocock** [sipcapture/homer-app#124]
It would be useful if the homer-app web interface displays a prominent error when the database isn't initialized.

**Comment by lmangani** [comment]
@dpocock Are you referring to the login page? when the database is not initialized or down, most likely users would be prevented from accessing the system at all.

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
