### ISSUE TITLE
errors on console: stats data has been not found

### ISSUE THREAD

**Issue by dpocock** [sipcapture/homer-app#125]
```
Debug: handler, error 
    {"msec":5.0548858642578125,"error":"stats data has been not found","data":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":404,"payload":{"statusCode":404,"error":"Not Found","message":"stats data has been not found"},"headers":{}}}}



```

**Comment by lmangani** [comment]
This is a simple debug message stating there were no stats found for a session being pulled AFAIK, 
If you think this is a symptom for a different issue, please extend with more details about the preconditions of this appearing.

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
