### ISSUE TITLE
web user logged out sometimes

### ISSUE THREAD

**Issue by dpocock** [sipcapture/homer-app#127]
Sometimes the web user is logged out by a timeout.  Is it possible to eliminate timeouts by default?

**Comment by lmangani** [comment]
This is not really a logout but rather a session expiration detected upon activity. Each access is governed by a JWT token with a default duration of 1h. I'm not a big fan of non-expiring logins, so I would exclude eliminating this mechanism but I'm happy to extend it if the audience approves. 

The expiration value can be modified here at this time: https://github.com/sipcapture/homer-app/blob/master/server/private/jwt_settings.json

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
