### ISSUE TITLE
Homer7 evaluation - No MoS and no User-Agent

### ISSUE THREAD

**Issue by Si-Richards** [sipcapture/homer-app#128]
Homer5 frontend listed UserAgent in the grid-view which is useful.  The MoS score is not clear and on the QoS tab.

Are there plans to build this into Homer7?

**Comment by adubovikov** [comment]
@Si-Richards good point :-) normaly you can add any header in the https://github.com/sipcapture/heplify-server/blob/master/database/postgres.go#L404-L431
but 100% agree we should add this to the config file. Let us do it ASAP. About MOS score, can you please provide more details ?

**Comment by adubovikov** [comment]
sb.WriteString("\",\"user_agent\":\"")
 sb.WriteString(h.SIP.UserAgent)

**Comment by adubovikov** [comment]
https://github.com/sipcapture/heplify-server/commit/a2d4d83e7ea6a9a064078cd0c89e0d43823c78e8

**Comment by Si-Richards** [comment]
> @Si-Richards good point :-) normaly you can add any header in the https://github.com/sipcapture/heplify-server/blob/master/database/postgres.go#L404-L431
> but 100% agree we should add this to the config file. Let us do it ASAP. About MOS score, can you please provide more details ?

I'm not sure how to interpret the MoS for this call or perhaps i've missed something or need to change the config...

![image](https://user-images.githubusercontent.com/20224397/57014734-433baa80-6c09-11e9-9305-a7f9e0ac497d.png)

**Comment by fourti** [comment]
Just pushing this one, because it would be very helpful to have the MOS values in homer7

**Comment by lmangani** [comment]
This is going to be part of the upcoming 7.7 release. Mind the MOS we're discussing here is a pseudo calculation resulting from the RTCP messages so its not 100% reliable. 

For a 100% reliable MOS based on actual RTP, our `RTPAgent` add-on should be deployed.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.8
https://github.com/sipcapture/heplify-server/releases/tag/1.14

**Comment by adubovikov** [comment]
https://github.com/sipcapture/heplify-server/releases/tag/1.15
https://github.com/sipcapture/homer-app/releases/tag/1.1.12

**Comment by adubovikov** [comment]
any updates here ?

**Comment by adubovikov** [comment]
I will close, please reopen if needed
