### ISSUE TITLE
Legacy QOS Tab

### ISSUE THREAD

**Issue by lmangani** [sipcapture/homer-app#13]
The high-level former RTCP stats flow reference is below:

- QOS RTCP API [trigger](https://github.com/sipcapture/homer-app/blob/master/public/app/search/call-detail/call-detail/controllers/call-detail.controller.js#L248) (baseline implemented)
- QOS RTCP Parser [TBD](https://github.com/sipcapture/homer-ui/blob/858424f138a56f7d8c4a6f152c92e4a2acbef7e3/share/controller.js#L69)
- QOS RTCP Template [TBD](https://github.com/sipcapture/homer-ui/blob/858424f138a56f7d8c4a6f152c92e4a2acbef7e3/share/index.html#L129)

Task: Angularize Functions & Template basics (boxes left + chart right)
Exclude: Everything except RTCP stats in prototype

**Comment by adubovikov** [comment]
should we close it or move ?
