### ISSUE TITLE
The field name couldn't be cofigured at homer7 "Search Results" page

### ISSUE THREAD

**Issue by qdzhuning** [sipcapture/homer-app#130]
There's one field name shown as "from_user" at homer7 "Search Results" page. How to let it shown as "From User"? We couldn't find the modified point.

**Comment by adubovikov** [comment]
@qdzhuning in the mapping schema. Go to Profile->Mapping->SIP call and configure it there

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
