### ISSUE TITLE
Ldap authentication on Homer 7

### ISSUE THREAD

**Issue by vladislavvvvvvv** [sipcapture/homer-app#131]
Hello! 
How can provide ldap authentication on homer 7 ?

**Comment by adubovikov** [comment]
@vladislavvvvvvv the AUTH is here, need to test it
https://github.com/sipcapture/homer-app/blob/master/server/classes/ldap.js
do you use openLDAP ?

**Comment by vladislavvvvvvv** [comment]
yes , we use openldap and we try ldap.js. thanks

**Comment by adubovikov** [comment]
It should work for TLS because ldapjs has ssl support. Can you please check?

**Comment by adubovikov** [comment]
var tlsOptions = {
// This is necessary only if the server uses the self-signed certificate
ca: [ fs.readFileSync('/etc/ldap/cacert.pem') ]
};

var ldap = require('ldapjs');
var client = ldap.createClient({url: 'ldaps://plat.com:636',tlsOptions: tlsOptions});

**Comment by adubovikov** [comment]
can you check that code ? if it works, I will add

**Comment by adubovikov** [comment]
Or  this way:

var options = {
    'rejectUnauthorized': false, 
};

var client= ldap.createClient({
    url: 'ldap://127.0.0.1:389' 
    tlsOptions: options
});     

client.starttls(options,[], function(err) {
    console.log('inside the starttls callback');
    client.bind('cn=admin,dc=example,dc=com', 'admin',callback );
});

**Comment by vladislavvvvvvv** [comment]
the best work way is second variant
 var options = {
'rejectUnauthorized': false,
};

var client= ldap.createClient({
url: 'ldap://127.0.0.1:389'
tlsOptions: options
});

client.starttls(options,[], function(err) {
console.log('inside the starttls callback');
client.bind('cn=admin,dc=example,dc=com', 'admin',callback );
});

**Comment by teeby** [comment]
Hi.
I see my ldap.js file but I don't see what to do with this file.
Would you be so kind as to provide the list of files that need to be amended to specify authentication to be done by ldap and examples of the settings in those files?

**Comment by adubovikov** [comment]
@teeby you have to open config.js and put ldap url information to the URL of ldapauth object. 

https://github.com/sipcapture/homer-app/blob/master/server/config.js#L45-L53

```
const ldapauth = {
   url: 'ldap://127.0.0.1:389',
   strictDN: true,
   dn: 'dc=qxip,dc=net',
   userdn: 'uid=%USERNAME%',
   filter: '(uid=%USERNAME%)',
   scope: 'sub',
   uidNumber: 'uidNumber'
}
```


after the auth local should false and ldap param have to be true

https://github.com/sipcapture/homer-app/blob/master/server/config.js#L65
```

auth: {
    internal: false,
    ldap: true,
  },

```

**Comment by adubovikov** [comment]
any feedback ?

**Comment by vladislavvvvvvv** [comment]
Hello! As I wrote 28 days for us best working second variant by tls and no problem with ldap connections.

**Comment by adubovikov** [comment]
oki, I will check and add this as an option. Thank you.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/commit/6d34d74ff84e2411e96e32cd89f4f6c6ea202438

@vladislavvvvvvv can you please check the changes ?

**Comment by vance-od** [comment]
Alex, thank you for the change you've done, at the moment @vladislavvvvvvv is on vacation atm,
we will try to check earlier, but if no free time it will be checked in 1.5 weeks - July 22

**Comment by aqsyonas** [comment]
Thanks, @vance-od.

**Comment by adubovikov** [comment]
so, it works in our setup. Closing the ticket, please repopen if needed
