### ISSUE TITLE
add new mapping: fail to add a living being: insert into "mapping_schema

### ISSUE THREAD

**Issue by aqsyonas** [sipcapture/homer-app#135]
I was unable to add new mapping into homer-app. It was giving below error upon saving. 

message: "add new mapping: fail to add a living being: insert into "mapping_schema" ("correlation_mapping", "create_index", "create_table", "fields_mapping", "hep_alias", "hepid", "mapping_settings", "partid", "partition_step", "profile", "retention", "schema_mapping", "schema_settings", "version") values (DEFAULT, DEFAULT, DEFAULT, DEFAULT, $1, $2, DEFAULT, $3, $4, $5, $6, DEFAULT, DEFAULT, DEFAULT) - null value in column "version" violates not-null constraint"

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/commit/c2e212acd1ad445e07d79e9e5ddad54b1a1364ee

please check

**Comment by aqsyonas** [comment]
I see adding a new mapping perfectly works fine. But I am unable to delete the added mapping and also changes in added mappings are not getting persistent.

**Comment by adubovikov** [comment]
What do you see in the web console ?

**Comment by aqsyonas** [comment]
Upon deletion. 

["AppPreferencesMapping"]0: "AppPreferencesMapping"length: 1__proto__: Array(0) "fail to delete advanced settings: The resource isn’t available on this server.

Upon edit. 
{guid: null, profile: "default", hepid: 10, hep_alias: "aqsremotetest", partid: 10, …}
bundle.js:208128 PUT http://nyc01.sipcapture.io:88/api/v3/mapping/protocol/ 404 (Not Found)
(anonymous) @ bundle.js:208128
sendReq @ bundle.js:207855
serverRequest @ bundle.js:207603
processQueue @ bundle.js:212452
(anonymous) @ bundle.js:212500
$digest @ bundle.js:213635
$apply @ bundle.js:213932
(anonymous) @ bundle.js:222763
dispatch @ bundle.js:171227
elemData.handle @ bundle.js:171034
bundle.js:210083 ["RequestResponseInterceptor"] ["reponseError"] {data: {…}, status: 404, headers: ƒ, config: {…}, statusText: "Not Found", …}
(anonymous) @ bundle.js:210083
responseError @ bundle.js:369520
processQueue @ bundle.js:212452
(anonymous) @ bundle.js:212500
$digest @ bundle.js:213635
$apply @ bundle.js:213932
done @ bundle.js:207910
completeRequest @ bundle.js:208154
requestLoaded @ bundle.js:208071
load (async)
(anonymous) @ bundle.js:208054
sendReq @ bundle.js:207855
serverRequest @ bundle.js:207603
processQueue @ bundle.js:212452
(anonymous) @ bundle.js:212500
$digest @ bundle.js:213635
$apply @ bundle.js:213932
(anonymous) @ bundle.js:222763
dispatch @ bundle.js:171227
elemData.handle @ bundle.js:171034
bundle.js:210083 ["AppPreferencesMappingAddEdit"] "fail to update advanced settings: The resource isn’t available on this server.

**Comment by adubovikov** [comment]
sorry, guid was null. Please take last git and remove the bad records:

delete from homer_config.mapping_schema where guid is null;

**Comment by aqsyonas** [comment]
Thanks, I see mapping functions working fine now and will close this issue. I will continue my testing and open another issue if I came across anything else.

**Comment by adubovikov** [comment]
thank you
