### ISSUE TITLE
curl: (7) Failed to connect to localhost port 8001: Connection refused

### ISSUE THREAD

**Issue by saydulk** [sipcapture/homer-app#136]
I am using Amazon Linux. Homer app 7 running well and i have install JWT Web Tokens using 
$ npm i jsonwebtoken

to get JWT token when i run 

curl -X POST localhost:8001/api/v3/auth \
-d "username=admin&password=password"

it shows curl: (7) Failed to connect to localhost port 8001: Connection refused

8001 port is open but no service is listening  

For this i am also getting Error: Something went wrong, no JWT token received, probably wrong credentials used to login
 
I am using this link for setup - https://github.com/sipcapture/homer-app/blob/master/docs/dev/README.md

Need help

![Screenshot from 2019-05-22 05-34-42](https://user-images.githubusercontent.com/1058663/58137225-50b9e280-7c53-11e9-97cd-86c5e8e23ce0.png)

**Comment by aqsyonas** [comment]
@saydulk you need to change port according to below settings. 
https://github.com/sipcapture/homer-app/blob/master/server/config.js#L55
For the wrong credentials, we have replied to you in your previous thread.
