### ISSUE TITLE
use string for captureId

### ISSUE THREAD

**Issue by negbie** [sipcapture/homer-app#137]
Right now captureId could be not only a int but string too. Mappings should reflect that.
https://github.com/sipcapture/homer-app/blob/master/seeds/02_Mapping.js

**Comment by lmangani** [comment]
AFAIK `captureID` will always be converted to INT and `hepNodeName` will always be converted to CHAR at chunk level when being encapsulated - is this assumption correct @adubovikov

**Comment by adubovikov** [comment]
it's a good point. Should we just replace captureId with hepNodename if the last exists or add a new field ?

**Comment by lmangani** [comment]
I think it should be up to the HEP library or client. In `hep-js` for pure testing when `hepNodeName` does not exist in the source, the library will use `captureId` in string format to fill-in, but I'm not even sure this is right for a real-life scenario as it sounds like a server side decision rather. I'd go for no change and leaving it optional for the client to use/send.

**Comment by negbie** [comment]
I would just use string and convert int to string in the json output.

**Comment by negbie** [comment]
Clients could send what ever they want. Server needs to convert int to string anyway to form the json header. So I would just change to mapping type to string and in heplify-server change
sb.WriteString(",\"captureID\":")
to
sb.WriteString(",\"captureID\":\"")

**Comment by negbie** [comment]
Of course this means a schema change but since it's json it's not so painful.

**Comment by adubovikov** [comment]
for mapping - int -> str(text)

**Comment by negbie** [comment]
type: 'string'

**Comment by lmangani** [comment]
This seems to have been satisfied as implemented with `hepNodeName` can we close this issue?

**Comment by lmangani** [comment]
Reopen if needed ;)
