### ISSUE TITLE
{"error":"Not found"}

### ISSUE THREAD

**Issue by UbuntuEvangelist** [sipcapture/homer-app#139]
Looks like the API service might not be running: POST http://homer7.domain.com/api/v3/search/call/data

DNS has been cut over from homer 5 to new homer 7 setup so CaptureAgents should be sending traffic to homer7.domain.com now but not working

![Screenshot from 2019-05-29 05-22-09](https://user-images.githubusercontent.com/1058663/58518637-bd902800-81d1-11e9-97aa-4fca916a2b8c.png)
 503 (Service Unavailable)

**Comment by aqsyonas** [comment]
@saydulk github issues are for bug reporting. Please use homer google group for any kind of configuration issue so other people could also get benefit out if it. 
Create a thread over there with console logs and whatever info you have.

**Comment by saydulk** [comment]
@aqsyonas thanks for your response. after report this thread i have seen this thread https://github.com/sipcapture/homer-app/issues/69 which match with my problem and  @lmangani added this as bug label on Jan 30. Also @adubovikov assigned almukhametovd on Mar 8 for this issue #104

**Comment by lmangani** [comment]
@saydulk this seems completely unrelated to #69 
Could you detail best your current status? Is the entire API non functional? Can you login or search?

**Comment by adubovikov** [comment]
IMHO here is a problem of GET. The API supports POST request and if you just do get - the answer is "NOT FOUND". That we can do: implement GET that will get back data from the call table of last 10 minutes.

**Comment by saydulk** [comment]
@adubovikov is GET implemented as you says ?

**Comment by adubovikov** [comment]
will finish it today

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!

**Comment by UbuntuEvangelist** [comment]
@adubovikov @lmangani 
will finish it today

You guy's did not keep commitment as says.

**Comment by lmangani** [comment]
@UbuntuEvangelist I'm sorry? Have you even tried the new release or you're just here shooting judgements? Do not come here expecting commitment, open-source is a two way street sir.
