### ISSUE TITLE
SIP call flow display abnormally

### ISSUE THREAD

**Issue by TaurusXY** [sipcapture/homer-app#140]
Hello,

I sent some SIP messages towards HOMER7 and checked the SIP call Flow.
Besides the IP address of the last entity can not display entirely, the width of the last two entities is smaller than the front ones obviously. Seems the call flow could not adjust to the screen automatically.
Below is the printscreen. Is this one issue or not?  

![image](https://user-images.githubusercontent.com/49503708/58544651-48a20a00-8234-11e9-8f14-386c7bbe0120.png)

Thanks,
TaurusXY

**Comment by lmangani** [comment]
Try `hover` the hidden item, it should display. This definitely needs improvement.

**Comment by TaurusXY** [comment]
Thanks for your info! Yes, when the mouse point enters the element, the IP address can be displayed entirely.
