### ISSUE TITLE
The “Timezone” function didn't work.

### ISSUE THREAD

**Issue by qdzhuning** [sipcapture/homer-app#141]
When we set the "Timezone" to "GMT+8 CCT", the create_data is "2019-05-29 10:22:49.000 +0800".
If we change the  "Timezone" to "GMT-1",  the create_data is still "2019-05-29 10:22:49.000 +0800".
So it seems the timezone function didn't work well.

**Comment by qdzhuning** [comment]
![New Bitmap Image](https://user-images.githubusercontent.com/50348863/58622103-71da9d00-82fd-11e9-8e36-4a398f1ebf2e.jpg)

**Comment by lmangani** [comment]
Hi - Internally all data is in UTC format as you can see, so the display part should not change.
For clarity, could you confirm if when you change timezone, you get the *exact* same results out?

**Comment by qdzhuning** [comment]
> Hi - Internally all data is in UTC format as you can see, so the display part should not change.
> For clarity, could you confirm if when you change timezone, you get the _exact_ same results out?

We change the timezone from one to another, we could get the exact same results out.
Please see below two pictures.


![Uploading 1.jpg…]()

**Comment by qdzhuning** [comment]
![New Bitmap Image](https://user-images.githubusercontent.com/50348863/58674824-25867000-8384-11e9-92c5-54f0f3e0ac2f.jpg)
![1](https://user-images.githubusercontent.com/50348863/58674834-36cf7c80-8384-11e9-9b29-f455e0b56409.jpg)

**Comment by qdzhuning** [comment]
@adubovikov Do you have any update for this issue? Thanks a lot.

**Comment by qdzhuning** [comment]
@adubovikov  Would you mind sharing us any idea about how to fix this issue?

**Comment by aqsyonas** [comment]
@qdzhuning thanks for reporting the issue. We are working on your request.

**Comment by lmangani** [comment]
Please re-test in 7.7 feel free to try it - any input is welcome!
