### ISSUE TITLE
Feature request: Export pcap for search on IP

### ISSUE THREAD

**Issue by hafkensite** [sipcapture/homer-app#143]
We are currently using the HOMER 5 [`/api/v1/search/export/data/pcap`](https://github.com/sipcapture/homer-api/blob/master/api/RestApi/Search.php#L785) endpoint to get a pcap file with all captured packets from/to an IP within the last hour. We use the `orand` search parameter to use it IP in both the source and destination fields.

Sadly this endpoint has changed in HOMER 7. The only endpoint I could find that exposes pcaps is [`/api/v3/export/call/messages/pcap`](https://github.com/sipcapture/homer-app/blob/456033a01d6b82dec206d6bf96d9fdf7b04041f5/server/routes/export.js#L10). But that does not allow searching for other fields than the correlation id (callid in our case). 

It is currently possible to support these kinds of queries?

**Comment by hafkensite** [comment]
Can you give any indication as to when API endpoint will be implemented?

**Comment by aqsyonas** [comment]
@hafkensite We will update this ticket once mentioned feature is implemented. Thanks for your patience.
