### ISSUE TITLE
question about the value of "Limit Query".

### ISSUE THREAD

**Issue by qdzhuning** [sipcapture/homer-app#144]
Hi,

I found the value of "Limit Query" keep change same value in different widget.
Could you please check if this is one issue or enhancement needed?
Here is the procedure to reproduce this phenomenon:

1. We wrote "2222" in "Limit Query" field of "call sip search" widget, 
2. Meanwhile, the"Limit Query" field of "log search" widget changed to same value("2222"). 
<img width="567" alt="Capture" src="https://user-images.githubusercontent.com/50348863/59318791-d7b22600-8cfa-11e9-8137-f38a8c1b1d49.PNG">

In my opinion, the value of "Limit Query" of "log search" widget should keep to default value "200" if we don't change this vaule in "log search" widget .
Please correct me if my understanding is improper.

**Comment by adubovikov** [comment]
I think we can close this ticket, since you have opened another two
