### ISSUE TITLE
No horizontal scroll on search results

### ISSUE THREAD

**Issue by teeby** [sipcapture/homer-app#146]
Hi
After I run a search I find all the columns are crushed small to fit them all on the page. I see I can turn the columns on and off to reduce the number of columns. If I want lots of columns and to see all the data in the column by expanding their size, the last column disappears off the page and there is no horizontal scroll bar.  I can make the main window bigger but this is only useful for a few columns.  A horizontal scroll bar is the standard solution for this. I am new to Homer so I'm not sure if this is a bug, or missing feature or configurable in a config file. Any help would be gratefully received.

**Comment by gedia** [comment]
It would also be great if font size for the search results page could be selected in user's settings page. I think the default font size in homer7 leads to much less information density than in homer5.

**Comment by lmangani** [comment]
@gedia please open a feature request! We're absolutely open to suggestions from users.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/commit/4e6c3a0ca170c1885e9c84a41c068582c138a0f7
Should be fixed!

**Comment by adubovikov** [comment]
unforuntately UI-grid doesnt support this well: you will have some space if the sum of column's widths is less then the width of grid. In this case you have to do resize it manualy

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
