### ISSUE TITLE
"Search" function work abnormally after change protocol and profile at widget setting page.

### ISSUE THREAD

**Issue by qdzhuning** [sipcapture/homer-app#147]
Hi,
We found "search" function work abnormally after change protocol and profile at widget setting page.
Could you please check if this is one issue or enhancement needed?
Here is the procedure to reproduce this phenomenon:

1. Keep the default values of "Proto" (SIP) and "Profile"(call) at widget settings page.
2. Then, click "Search" button. The data of "1_call" tables were shown.
3. Change the values of "Proto" (SIP) and "Profile"(call) to  "Proto" (LOG) and "Profile"(default) at widget settings page.
4. Then, click "Search" button. The data of "1_call" tables still were shown.

In my opinion, it should show  the data of "100_default" tables. 

Please correct me if my understanding is improper.
Unfortunately, this issue happened randomly.  We're trying to find the regularity.

**Comment by qdzhuning** [comment]
I closed this issue because it was same with #152

**Comment by qdzhuning** [comment]
Sorry type error, it shouldn't be closed because it hasn't been fixed.

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
