### ISSUE TITLE
Two "Limit Query" fields appear in field list after change protocol and profile at widget setting page.

### ISSUE THREAD

**Issue by qdzhuning** [sipcapture/homer-app#148]
Hi,
We two "Limit Query" fields appear in field list after change protocol and profile at widget setting page.
Could you please check if this is one issue or enhancement needed?
Here is the procedure to reproduce this phenomenon:

1. Keep the default values of "Proto" (SIP) and "Profile"(call) at widget settings page.
2. Change the values of "Proto" (SIP) and "Profile"(call) to  "Proto" (LOG) and "Profile"(default) at widget settings page.
3. Then, try to click empty field to add some fields. Two "Limit Query" fields were shown.
![New Bitmap Image](https://user-images.githubusercontent.com/50348863/59407530-0d7f0980-8de4-11e9-9314-53fa03da4c1e.jpg)

In my opinion, only one "Limit Query" field should be shown in the field list. 
Please correct me if my understanding is improper.

**Comment by adubovikov** [comment]
fixed in the branch "fix_limit". Please check!

**Comment by qdzhuning** [comment]
@adubovikov Thanks a lot! This issue has been fixed in branch "fix_limit" after checked. Do you have any plan to merge this code change to master branch?

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/commit/a433f5317dbe1f3671fb6bcdc4781a4db30c4009

done
