### ISSUE TITLE
"Limit Query" keep same value even in different widget

### ISSUE THREAD

**Issue by qdzhuning** [sipcapture/homer-app#149]
Hi,

We found the value of "Limit Query" keep same value even in different widget.
Could you please check if this is one issue or enhancement needed?
Here is the procedure to reproduce this phenomenon:

1. We wrote "500" in "Limit Query" field of "call sip search" widget.
2. Meanwhile, we found the"Limit Query" field of "log search" widget changed to same value("500").
<img width="948" alt="Capture" src="https://user-images.githubusercontent.com/50348863/59408126-d01b7b80-8de5-11e9-9c5e-1a451126c067.PNG">

In my opinion, the value of "Limit Query" of "log search" widget should keep to default value(for example: 200) if we don't change this value in "log search" widget.
Please correct me if my understanding is improper.

**Comment by adubovikov** [comment]
The problem is here the such values are universal and have same name. Is it a problem or just a discomfort ?

**Comment by qdzhuning** [comment]
@adubovikov @lmangani Since the "Limit Query" field is in different widget according to different protocol configuration, we think it should keep same behaviour as other fields in different widget. 
For example, "Src Port" field. 
If we change "Src Port" field in "call sip search" widget, the same name field in "log search" widget will not change.

**Comment by adubovikov** [comment]
@qdzhuning can you please check the branch "fix_limit" ? We have fixed the issue. I hope :)

**Comment by qdzhuning** [comment]
@adubovikov Thanks a lot! This issue has been fixed in branch "fix_limit" after checked. Do you have any plan to merge this code change to master branch?

**Comment by adubovikov** [comment]
yes, I will merge it ASAP ;-)

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/commit/a433f5317dbe1f3671fb6bcdc4781a4db30c4009
done
