### ISSUE TITLE
The panel name was shown wrong after click back the logo Homer

### ISSUE THREAD

**Issue by qdzhuning** [sipcapture/homer-app#150]
Hi,

We found the panel name was shown wrong after click back the logo Homer.
Could you please check if this is one issue or enhancement needed?
Here is the procedure to reproduce this phenomenon:

1. Log in the default panel "Home", and the panel's name is "Home".
<img width="713" alt="1" src="https://user-images.githubusercontent.com/50348863/59414559-4c1cc000-8df4-11e9-8107-b28d1fae98a6.PNG">

2. Click the panel "RTC", it will change to "RTC" panel page.
<img width="693" alt="2" src="https://user-images.githubusercontent.com/50348863/59414569-5212a100-8df4-11e9-9807-59bca74bb430.PNG">

3. Click the logo Homer, it changed to "Home" panel page, but the panel's name still was shown as "RTC".
<img width="687" alt="3" src="https://user-images.githubusercontent.com/50348863/59414668-87b78a00-8df4-11e9-9795-bf9f8de5007e.PNG">

In my opinion, the panel's name should be shown as "Home" because it has changed to "Home" panel page.
Please correct me if my understanding is improper.

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
