### ISSUE TITLE
question about "create_data" format in message-details page

### ISSUE THREAD

**Issue by qdzhuning** [sipcapture/homer-app#151]
Hi,

We found the "create_data" format wasn't normal data format(for example: yyyy-MM-dd HH:mm:ss) in message-details page.
Could you please check if this is one issue or enhancement needed?
Here is the procedure to reproduce this phenomenon:

1. At "Search Results" page, click "id" field in one message, then get the Message page.
2. In Message "Details" page, the "create_data" was "1560146712630". It didn't the normal data format although it may be linux data format.
<img width="349" alt="3" src="https://user-images.githubusercontent.com/50348863/59485765-a166d900-8ea9-11e9-9208-32fb06004b11.PNG">

In my opinion, the data format should be shown as "yyyy-MM-dd HH:mm:ss" format in Web page.
Please correct me if my understanding is improper.

**Comment by lmangani** [comment]
Thanks for the report @qdzhuning 

That's simply a timestamp detail. The information in the "DETAILS" tab in unchanged/raw and not intended for interpolation or printing formats. The actual date, is displayed in the flow.
