### ISSUE TITLE
Search field didn't be clear automatically after change protocol and profile at widget setting page.

### ISSUE THREAD

**Issue by qdzhuning** [sipcapture/homer-app#152]
Hi,
We found search field didn't be clear automatically after change protocol and profile at widget setting page.
Could you please check if this is one issue or enhancement needed?
Here is the procedure to reproduce this phenomenon:

1. Keep the default values of "Proto" (SIP) and "Profile"(call) at widget settings page.
Here were four search fields:  Src IP, Src Port, Dest IP, Dest Port.
<img width="571" alt="1" src="https://user-images.githubusercontent.com/50348863/59576126-1841e300-90f1-11e9-8eb7-2d722a6a00b8.PNG">

2. Then, click "Search" button. The data of "1_call" tables were shown.

3. Come back to Home dashboard and click "settings" button at widget.
Then, change the values of "Proto" (SIP) and "Profile"(call) to "Proto" (LOG) and "Profile"(default) at widget settings page.
The contents of four search fields for SIP changed to empty, but they didn't be clear automatically. 
<img width="785" alt="2" src="https://user-images.githubusercontent.com/50348863/59576088-f0eb1600-90f0-11e9-8566-e6f27172f5a5.PNG">

Then, click "Save" button. We found the search fields of SIP still here and didn't be clear.
<img width="566" alt="3" src="https://user-images.githubusercontent.com/50348863/59576105-04967c80-90f1-11e9-8e21-c66eb00a01e8.PNG">

4. Set value of Dest Port field to "5060", then click "Search" button, we found the data of "1_call" tables were shown.
<img width="569" alt="4" src="https://user-images.githubusercontent.com/50348863/59576190-62c35f80-90f1-11e9-9dda-8478b7cbf3b5.PNG">
<img width="731" alt="5" src="https://user-images.githubusercontent.com/50348863/59576195-66ef7d00-90f1-11e9-9054-987a82f77735.PNG">

In my opinion, search field should be cleared automatically after change protocol and profile at widget setting page.
Otherwise, the search result will be wrong if we search data by field.

Please correct me if my understanding is improper.

**Comment by qdzhuning** [comment]
@lmangani @adubovikov Hello, do you have any idea for this issue? Thanks a lot.

**Comment by lmangani** [comment]
Please re-test in 7.7 feel free to try it - any input is welcome!
