### ISSUE TITLE
hepsub mapping schema error 

### ISSUE THREAD

**Issue by Demon-DK** [sipcapture/homer-app#154]
I'm using default deploy of following stack in the docker images:
- image: sipcapture/heplify:master
- image: sipcapture/heplify-server:master
- image: sipcapture/homer-app:master
- image: postgres:10-alpine 

In the postgreSQL log I'm constantly observe the following error which is caused as I think by heplify-server calls:
```
[198] ERROR:  relation "hepsub_mapping_schema" does not exist at character 23
[198] STATEMENT:  select "mapping" from "hepsub_mapping_schema" where "hepid" = $1 and "profile" = $2
```
But in the heplify-server repo I got the note that this is related to homer-app https://github.com/sipcapture/heplify-server/issues/251#issuecomment-502573748

What is this mapping schema ?
How to resolve this error ? #

**Comment by adubovikov** [comment]
Looks like you didnt create some tables during installation. Please check the homer_config DB

**Comment by Demon-DK** [comment]
> Looks like you didnt create some tables during installation. Please check the homer_config DB

Right, mentioned table isn't exist in DB.
As I understand heplify-server during start had to create it, hadn't it ?
I can also recheck this behavior in older versions.

**Comment by adubovikov** [comment]
heplify-server will create tables only for data, the users/configs tables you should create during homer-app install - knex: 
https://github.com/sipcapture/homer-app/blob/master/docs/dev/README.md


```
sudo su - postgres
createuser homer --pwprompt
createdb -O homer homer_config
createdb -O homer homer_data
psql
postgres=# GRANT ALL PRIVILEGES ON DATABASE "homer_config" to homer;
postgres=# GRANT ALL PRIVILEGES ON DATABASE "homer_data" to homer;
```

and after

```
knex migrate:latest
knex seed:run

```

**Comment by adubovikov** [comment]
sorry, can you run:

`knex seed:make 06_HepSubmapping
`

**Comment by Demon-DK** [comment]
So, in any case this tasks are manually and doesn't tailored in container deployment, right.

I can try yo automate it during compose or kubernetes command arguments, but exactly these db's were created by server:
* homer_config
* homer_data

The issue is that it doesn't create exactly this "hepsub_mapping_schema".

**Comment by lmangani** [comment]
@Demon-DK I'm working on a method to update the containers tables by mounting the scripts in a standalone container for that purpose, right now changes would only be reflected on a new setup when CI rebuilds the baseline.

**Comment by adubovikov** [comment]
it looks like need find a best way for knex/update

**Comment by adubovikov** [comment]
@Demon-DK can you please show the result of: 

knex migrate:currentVersion

**Comment by Demon-DK** [comment]
@adubovikov 
> @Demon-DK can you please show the result of:
> knex migrate:currentVersion

Sure
```
# kubectl exec -it homer-web-server-66c97ff56-w82qn -- **knex migrate:currentVersion**                                         
Using environment: development
Current Version: none 
```

**Comment by adubovikov** [comment]
not good - the version should be 

```
Using environment: development
Current Version: 20190401143156

```

if you do: 

```
knex migrate:latest
knex seed:run

```

what are you getting ?

**Comment by Demon-DK** [comment]
**# kubectl exec -it homer-web-server -- knex migrate:latest**
```
Using environment: development
migration file "20190401143156_Datastructure.js" failed
migration failed with error: create table "users" ("id" serial primary key, "username" varchar(50) not null, "partid" integer not null default '10', "email" varchar(250) not null, "firstname" varchar(50) not null, "lastname" varchar(50) not null, "department" varchar(50) not null default 'NOC', "usergroup" varchar(250) not null, "hash" varchar(128) not null, "guid" varchar(50) not null, "created_at" timestamptz not null default CURRENT_TIMESTAMP) - relation "users" already exists
error: relation "users" already exists
    at Connection.parseE (/app/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:113:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
command terminated with exit code 1 
```

**# kubectl exec -it homer-web-server -- knex seed:run**
```
Using environment: development
error: relation "agent_location_session" does not exist
    at Connection.parseE (/app/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:113:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
command terminated with exit code 1
```

**Comment by aqsyonas** [comment]
@Demon-DK looks like tables were created during the previous installation. Could you try to manually remove them and then run above-mentioned commands.

**Comment by adubovikov** [comment]
Did you recreate it ?

**Comment by Demon-DK** [comment]
> @adubovikov 
> Did you recreate it ?

Yes, I've tried but without success.
Actually for every new test I'm typically recreating new container so I'm checking every suggestions from the scratch

**Comment by adubovikov** [comment]
@lmangani can we please check if the table agent_location_session has been created in the container ?

**Comment by judyQD** [comment]
@Demon-DK @lmangani @adubovikov any update for this issue? We have met the same error too. Thanks.

**Comment by lmangani** [comment]
I just forced a full rebuild and pushed a new image to docker hub - could you try from scratch?

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
