### ISSUE TITLE
search filter didn't be clear automatically after search another protocol date

### ISSUE THREAD

**Issue by qdzhuning** [sipcapture/homer-app#156]
Hi,

We found the search filter didn't be clear automatically after back to the Home page and search another protocol data.
Could you please check if this is one issue or enhancement needed?
Here is the procedure to reproduce this phenomenon:
1. In Home page, click "SIP" search button. Then, type in some filter in search result page, take the "sport" as an example.
<img width="666" alt="1" src="https://user-images.githubusercontent.com/50348863/59812853-fe4b0f00-9341-11e9-9099-10b0b062f39f.PNG">

2. Back to the Home page and click "Log" search button. In the search result page, the filter "sport" I typed before was still here.
<img width="622" alt="2" src="https://user-images.githubusercontent.com/50348863/59812859-0440f000-9342-11e9-942b-054e9e6f92f5.PNG">

In my opinion, the filter should be cleared as I've searched another protocol data.
Please correct me if my understanding is improper.

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
