### ISSUE TITLE
fields appeared twice in field list after change protocol and profile at widget setting page. 

### ISSUE THREAD

**Issue by qdzhuning** [sipcapture/homer-app#157]
Hi,
We found fields appear twice in field list after change protocol and profile at widget setting page.
Could you please check if this is one issue or enhancement needed?
Here is the procedure to reproduce this phenomenon:

1. Keep the default values of "Proto" (SIP) and "Profile"(call) at widget settings page.
2. Change the values of "Proto" (SIP) and "Profile"(call) to  "Proto" (LOG) and "Profile"(default) at widget settings page.
3. Then, change the values to "Proto" (SIP) and "Profile"(call) again, all fields appeared twice in field list.
![New Bitmap Image](https://user-images.githubusercontent.com/50348863/59837482-e85c3f00-937f-11e9-8183-f85ebfdc6672.jpg)

In my opinion, all fields shouldn't appear twice in field list for one specific protocol. 
Please correct me if my understanding is improper.

**Comment by adubovikov** [comment]
I think the issue has been fixed in the last git

**Comment by lmangani** [comment]
Please re-test in 7.7 feel free to try it - any input is welcome!
