### ISSUE TITLE
SIP message couldn't be shown fully in Flow page.

### ISSUE THREAD

**Issue by qdzhuning** [sipcapture/homer-app#158]
Hi,
We found SIP message couldn't be show fully in Flow page.
Could you please check if this is one issue or enhancement needed?
Here is the procedure to reproduce this phenomenon:

1. Click one SIP message and the Flow page was shown. The message was shown as "INVITE sip:+17053200". 
2. Click this message at flow page, we found the message should be shown as "INVITE sip:+17053200002@imsate.lucentlab.com SIP/2".
<img width="279" alt="Capture" src="https://user-images.githubusercontent.com/50348863/59903823-90cbdb00-9434-11e9-9359-6173fb3bd535.PNG">

Please correct me if my understanding is improper.

**Comment by adubovikov** [comment]
There is not enough space to display full URL, therefore it was limited to 20 characters, we can change it to 50 if it's so critical :-)

**Comment by qdzhuning** [comment]
@adubovikov We propose change it to 50 characters because it's one important information.

**Comment by lmangani** [comment]
We can get the full string and have use CSS `text-overflow` do the limiting

```
{
  white-space: nowrap; 
  width: 50px; 
  overflow: hidden;
  text-overflow: ellipsis; 
  border: 1px solid #000000;
}
```

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/commit/46ae654d59d2643c323bf2eae260b00685395334

**Comment by adubovikov** [comment]
should be ok
