### ISSUE TITLE
"Limit Query" value didn't be clear after click "Clear" button at widget page. 

### ISSUE THREAD

**Issue by qdzhuning** [sipcapture/homer-app#159]
Hi,
We found "Limit Query" value didn't be clear after click "Clear" button at widget page.
Could you please check if this is one issue or enhancement needed?
Here is the procedure to reproduce this phenomenon:

1. Set "Limit Query" value to 10, click "Search" button, we got 10 items in search results page.
2. Came back to Home page and click "Clear" button. Then, click "Search" button, we still got 10 items.

In my opinion, "Limit Query" value should be set to default value after click "Clear" button.
By the way, this issue was found after fix_limit branch was merged into master branch.

Please correct me if my understanding is improper.

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
