### ISSUE TITLE
$$hashKey was shown at Details page of Message ID

### ISSUE THREAD

**Issue by qdzhuning** [sipcapture/homer-app#161]
Hi,
We found $$hashKey was shown at Details page of Message ID while there was no this field at database.
Could you please check if this is one issue or enhancement needed?
Here is the procedure to reproduce this phenomenon:

1. Click one SIP message by sid,then the Call-ID page was shown.
2. Click one item at the Call-ID page, we found $$hashKey was shown at Details page of Message ID.
<img width="746" alt="Capture" src="https://user-images.githubusercontent.com/50348863/60062251-084a8480-972b-11e9-852d-90b751fadf03.PNG">

In my opinion, it shouldn't be shown because there was no $$hashKey field at database.

Please correct me if my understanding is improper.

**Comment by adubovikov** [comment]
this is object that existing in your "Message" tab. Normaly should be skipped

**Comment by adubovikov** [comment]
no no, it should not be closed, just skipped the haskey to display. Leave it to me

**Comment by qdzhuning** [comment]
@adubovikov  I changed below source code of homer-app and the $$hashKey has been hided.

homer7-app/public/app/search/call-message-detail/controllers/call-message-detail.controller.js 
<img width="357" alt="1" src="https://user-images.githubusercontent.com/50348863/60143431-ca179880-97f0-11e9-822c-3c8b9f65e67c.PNG">
<img width="398" alt="2" src="https://user-images.githubusercontent.com/50348863/60143436-ce43b600-97f0-11e9-9395-e45e478f4e95.PNG">
<img width="422" alt="3" src="https://user-images.githubusercontent.com/50348863/60143442-d26fd380-97f0-11e9-83d8-e6cb0296c0e7.PNG">

**Comment by aqsyonas** [comment]
@qdzhuning Ah, great.

**Comment by adubovikov** [comment]
@qdzhuning can you please do a PR ?

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
