### ISSUE TITLE
search field shows uncomfortable when add more fields at widget

### ISSUE THREAD

**Issue by qdzhuning** [sipcapture/homer-app#163]
Hi,
We found search field shows uncomfortable when add more fields at widget.
For example, the "clear" and "Search" buttons cover the search field after we added more field in the search list.
We know we could pull the widget page down to resolve this issue manually.
It will great if it could self-adaption, I mean, adjust the widget page to suitable size based on fields' amount automatically. 

<img width="567" alt="Capture" src="https://user-images.githubusercontent.com/50348863/60332473-79a76300-99c9-11e9-810c-65ae4dfe73a8.PNG">

**Comment by adubovikov** [comment]
thanks for report!

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
