### ISSUE TITLE
Feature request: API endpoint for pcap export based on search

### ISSUE THREAD

**Issue by hafkensite** [sipcapture/homer-app#176]
We require an API endpoint that returns search results for an account in PCAP format. Possibly spanning multiple tables, so that we can get all messages based for an account. 

The account id could be in the from/to or authentication headers

**Comment by adubovikov** [comment]
@hafkensite so, normaly you would like get make first API request, receive all callids and second send a request with callid that return pcap ?

**Comment by rsanting** [comment]
@adubovikov I work together with @hafkensite, we would like an endpoint that gives all messages that contain a specific account over a period of time. This would mostly be used for accounts that are unable to register for example. The per callid function would be nice as an additional functionality.

**Comment by adubovikov** [comment]
@rsanting but this functionality already exists - just send a 2 API calls and receive pcap. I am working now on the documentation in the swanger branch, if somebody can help migrate to hapi 18, the documentation will be ready early....

**Comment by rsanting** [comment]
@adubovikov @hafkensite is away from the office for a few more days, I am not 100% sure if I understood him correctly if this functionality already exists. Maybe we can wait for his response when he is back?

**Comment by adubovikov** [comment]
https://github.com/sipcapture/heplify-server/releases/tag/1.15
https://github.com/sipcapture/homer-app/releases/tag/1.1.12
