### ISSUE TITLE
how to show Tabs QoS and Logs in Homer7 app

### ISSUE THREAD

**Issue by judyQD** [sipcapture/homer-app#177]
use homer7, but in homer-app webpage, there is no QoS and Logs shown in page. How to config it to make them visibility?

**Comment by lmangani** [comment]
Hi @judyQD the QoS and Logs tab only show up when there's corresponding data. So this would most likely suggest you're not capturing or streaming any RTCP stats or logs.

Feel free to share your configuration, but closing as this is not an issue rather a condition.

Thanks!

**Comment by judyQD** [comment]
@lmangani Thanks very much for your support. Yes, this is not a issue. 
But I am wondering if I just install homer 7 with heplify-server docker image, webapp docker image and Postgres docker image. Will my homer 7 be with the function to show tab qos and logs?
Or in other words, do I need some other special packages to support show these two function?

**Comment by lmangani** [comment]
It's all about the HEP agents and what they're sending. So it depends on your capture setup, not just the collector part.

**Comment by judyQD** [comment]
@lmangani Thanks for your kind reply. 
If I want to show logs in my webapp, do I need install influxDB? Here is my configuration: heplify + postgres + webapp. Do my configuration can meet the requirement to show logs tab in webapp?
Looking forward to your support.

**Comment by lmangani** [comment]
Anyone w/ this doubt, please validate your setup using `hepgen.js` and you will be able to tell if the QoS and Logs work: https://github.com/sipcapture/hepgen.js/blob/master/README.md#run
