### ISSUE TITLE
Date disappear when remove hour or minute during selecting time range in Custom Range

### ISSUE THREAD

**Issue by lauraliq** [sipcapture/homer-app#179]
![Time range select](https://user-images.githubusercontent.com/38939679/63074936-4b261d00-bf62-11e9-8ec3-1b5225555b3c.jpg)
Hello, when I choose Custom Range to select the time range on HOMER7, I encountered a problem. That is when I remove the number shown in hour or minute frame to change the time, the date which shown above the hour frame disappear. I uploade the screeshot for it. Could you please help to check that? Thanks much!

**Comment by aqsyonas** [comment]
@lauraliq, I don't think this a bug, since it needs to adjust according to new values that is why it disappears unless you enter new correct values. Did it appear correctly when you enter the right values?

**Comment by lauraliq** [comment]
Yes, that's right. But it's confused that when I remove the number in seconds frame, the date is still there. i mean the behavior is different between remove hour/minute and seconds.
![seconds selection](https://user-images.githubusercontent.com/38939679/63080694-52562680-bf74-11e9-9168-f42e41dbbd0b.jpg)

**Comment by aqsyonas** [comment]
@lauraliq, thanks, I will add this to enhancement bucket.

**Comment by lauraliq** [comment]
@aqsyonas That's great! Thanks so much!

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
