### ISSUE TITLE
All the items in Admin Settings(users/alias...) cannot be deleted

### ISSUE THREAD

**Issue by lauraliq** [sipcapture/homer-app#180]
Just take the items in alias for example, i can add and update the items, but cannot delete it. And the logs in console say that "fail to delete user: fail to delete user: fail to delete a living being: The operator "undefined" is not permitted". Could you please help to check this?
![图片](https://user-images.githubusercontent.com/38939679/63084712-656df400-bf7e-11e9-8a09-60cbd3103a0e.png)

**Comment by aqsyonas** [comment]
@lauraliq thanks for reporting this.

**Comment by lauraliq** [comment]
@adubovikov Hello, is there any clue for this issue? Thanks a lot!

**Comment by aqsyonas** [comment]
@lauraliq we are working on your request. Thanks for the patience.

**Comment by lauraliq** [comment]
Thanks much for your support!

**Comment by rayj-pgi** [comment]
Thanks for the help on this. I'm seeing a similar issue with the subscribe api call.

`delete agent_subscribe: fail to delete a living being: The operator \"undefined\" is not permitted`

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
