### ISSUE TITLE
Question: I am using Homer-app with https, but always get the error about ssl3_read_bytes:sslv3 alert certificate unknown

### ISSUE THREAD

**Issue by judyQD** [sipcapture/homer-app#182]
I use the config https port to 443. But when app server start, using https://<IP>:443 to access homer, will get the error info in console log as below:
Server started
Debug: connection, client, error
    Error: 140437753862016:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/s3_pkt.c:1494:SSL alert number 46
140437753862016:error:140940E5:SSL routines:ssl3_read_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:1217:

This error seems cannot find the cert or the cert is invalid. I found the cert and key was generated by below function. I added debug info, and the cert and key were generated correctly.
pem.createCertificate({
  days: config.certificate.days,
  selfSigned: config.certificate.self_signed,
}, function(error, keys) {
  if (error) {
    throw error;
  }

So I am wondering why the error log was report? Could u pl help have a check? Thanks.

**Comment by judyQD** [comment]
Or how to config webapp with HTTPS? As my problem happened when I want to config webapp with HTTPS. Thanks

**Comment by aqsyonas** [comment]
@judyQD the best way would be to use at nginx at front-end handling ssl configurations and relaying traffic to homer-app un-encrypted.

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
