### ISSUE TITLE
homer7-QOS

### ISSUE THREAD

**Issue by changzx** [sipcapture/homer-app#183]
hello！
    I'm use homer7,the qos has some prombles. The talk time is less than 1 minute, and the time on the QOS side is not related to the time.
   
![1567066453](https://user-images.githubusercontent.com/42836671/63922879-2066b900-ca78-11e9-91f3-166d2e7e3ebc.jpg)

**Comment by lmangani** [comment]
@changzx Homer has nothing to do with generating those timestamps, this is just a display of what your packets contain. The timing of RTCP is probably in a format not converted - can you capture some raw packets to share from the devices? Can other users confirm if they experience a similar issue?

**Comment by changzx** [comment]
> @changzx Homer has nothing to do with generating those timestamps, this is just a display of what your packets contain. The timing of RTCP is probably in a format not converted - can you capture some raw packets to share from the devices? Can other users confirm if they experience a similar issue?

the messages time is right,but qos not.for example:
![1567067015(1)](https://user-images.githubusercontent.com/42836671/63923619-6a9c6a00-ca79-11e9-9eb0-2fa9cc4f0942.jpg)

**Comment by lmangani** [comment]
You are comparing Apples and Oranges or in other words, confusing two protocols here. The timestamp of signaling events and the timestamp of RTP and RTCP packets are completely different, and unrelated to each other. For RTP this is determined by the packet and the sniffer. For RTCP those are determined by the User-Agent generating them. In order to know anything, we would need to see the actual packets.

I hope this helps understand this further a bit,

LM

**Comment by changzx** [comment]
> You are comparing Apples and Oranges or in other words, confusing two protocols here. The timestamp of signaling events and the timestamp of RTP and RTCP packets are completely different, and unrelated to each other. For RTP this is determined by the packet and the sniffer. For RTCP those are determined by the User-Agent generating them. In order to know anything, we would need to see the actual packets.
> 
> I hope this helps understand this further a bit,
> 
> LM

How to give the actual packets to you?

**Comment by lmangani** [comment]
Please re-test in 7.7 feel free to try it - any input is welcome!
