### ISSUE TITLE
Problem with Homer 7 webap

### ISSUE THREAD

**Issue by mcebey1891** [sipcapture/homer-app#184]
Hi,

I'm running the docker container hom7-hep-influx on a Ubuntu Server 18.04 and when I try to create somthing on the web interface its not save and the graph are not shown.

I run the command
 `sudo docker logs --follow homer-webapp
`
And I have a lot of lines like:

`Debug: handler, error
    {"msec":1.0339829996228218,"error":"Not Found","data":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":404,"payload":{"statusCode":404,"error":"Not Found","message":"Not Found"},"headers":{}},"message":"Not Found"}}`

Any idea what is wrong?

Thanks in adavance for your support.

**Comment by VolhaRS** [comment]
I have the same problem, I have not found a solution yet.

**Comment by mcebey1891** [comment]
In Homer 5 a similar problem, I solved it by modifying permissions.
But with Docker in the middle, I'm not sure it's the same problem.

**Comment by VolhaRS** [comment]
With Homer5 i have not problem.

**Comment by os11k** [comment]
I have same problem, when adding to call sip search at main page form field.

**Comment by lmangani** [comment]
Please provide a step-by-step procedure to reproduce your issue.

**Comment by mcebey1891** [comment]
Hi,

The procedure was:

- First I did a fresh installation of Ubuntu Server 18.04.3.

- Next, I followed the procedure to install docker from the official website [https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04](url). Except for the part of **Executing the Docker Command Without Sudo** 

- Then, I download the directory with the containers to a personal folder and from there run:
`sudo docker-compose up -d` Then I went to the browser, and upon entering the web interface, the search engine, a clock and a graphics widjet that had no data were displayed.

At this point the _Visalize Widget_ do not load data unless they are given a specific query, neither users nor aliases can be added (SAVE button is disabled). If I modify a widget of search, the new field are not displayed if reload the page.
You can search for calls and see the callflow.
I have a CaptureAgent taking traffic and it puts data in the database and I think statistics are being made.

Please tell me if you need data, records or any other type of information.

Thank's

**Comment by os11k** [comment]
Hi,

To reproduces. Clean Ubuntu 18:

1 .apt-get install docker-compose
2. apt-get upgrade
3.  apt-get update
4. cd /usr/src/
5. git clone https://github.com/sipcapture/homer7-docker.git
6. cd /usr/src/homer7-docker/
7. cd ./heplify-server/hom7-hep-elastic/
8. docker-compose up -d --build

Please check below gif. After adding call-id in call sip search and saving it I pressed F5 for refresh and new search field disappears.

![homer7](https://user-images.githubusercontent.com/6322576/64099869-00364300-cd73-11e9-9f7f-097db50408fd.gif)

**Comment by os11k** [comment]
> 
> 
> I have same problem, when adding to call sip search at main page form field.

Hi, my fault I needed to press save on right top corner - "save changes". It seems to work now. Very sorry for this.

**Comment by lmangani** [comment]
@os11k glad you got this working! If you feel this should be improved, please open a proposal separately.
