### ISSUE TITLE
homer7 and AD authentication

### ISSUE THREAD

**Issue by salehhoushangi** [sipcapture/homer-app#185]
actually now i switched to H7 but unfortunately after configured /opt/homer-app/server/config.js like below :
const ldapauth = {
url: 'ldap://10.0.xxx:389',
strictDN: true,
dn: 'dc=xx,dc=net',
userdn: 'uid=%USERNAME%',
filter: '(uid=%USERNAME%)',
scope: 'sub',
uidNumber: 'uidNumber'

and
auth: {
ldap: true,
i cant success to authenticate via AD. and giving error "Error: Something went wrong, no JWT token received, probably wrong credentials used to login"
any more change must be need to do ?
i dont know where we should define user that can authenticate homer7 with and how to define user as admin to authenticate in homer 7 via AD

**Comment by lmangani** [comment]
Check this ticket and see if it helps: https://github.com/sipcapture/homer-app/issues/131

**Comment by salehhoushangi** [comment]
ok i have checked it one of the different between my problem and this post #131 is to using openldap instead of AD Microsoft. but as you know  there is no different in type of protocol and connection way although may be different in user attribute value .any way i did configure same as mentioned in this post  and my question still unanswered  that where do we define cn in homer 7 and how should we define user(from Ad) as administrator in homer 7 . for example if i could to join AD . which user permit to login in homer 7 and can permit to other user to login.

**Comment by lmangani** [comment]
@salehhoushangi we can only help if you make configuration attempts and they fail or show bugs we can discuss here. if you need professional support you can email sales@qxip.net for a quote anytime - Thanks!

**Comment by salehhoushangi** [comment]
My problem is very clear. No output to view login process or any other errors. just getting error in logging page with "Error: Something went wrong, no JWT token received, probably wrong credentials used to login".
This is the most basic way you can guide someone.and anyone who has a question on git here has certainly reviewed the previous posts.it is good to refer someone to an old post but not enough.
any way thank you for advise!

**Comment by lmangani** [comment]
We're helping everyone but opensource does not necessarily mean unlimited availability - How about checking the error on your server side to begin with?

**Comment by salehhoushangi** [comment]
I definitely agree with you but don't remember open source philosophy is open your mind to other and sharing your knowledge with other, those who strive to expand the culture of open source software.This is not a law, but a principle concept .

**Comment by lmangani** [comment]
Feel free to take a look at my github profile, and judge for yourself - I dedicate my life to sharing knowledge and time :) This said, this is a very open and "hacktive" community, and its really open meaning there's nothing to be assumed :) Just do more testing give us more details and you'll be suprised at the results

**Comment by salehhoushangi** [comment]
I'm not going to judge anyone, and as you know, the open source world is not just about git.Here as a small member of the large open source world Thanks for your time in the open source world.
let me to talk about  one of the open source world problem.

I was only able to monitor the network packets on the server side and saw an error
T xx.x.x.x:389 -> 1x.xx.xx.xx:58064 [AP] #5
  0....h...a...._..1...X80090308: LdapErr: DSID-0C09042A, comment: AcceptSecurityContext error, data 52e, v3839.

**Comment by lmangani** [comment]
Thanks @salehhoushangi 
@adubovikov does this suggest anything to you?

**Comment by salehhoushangi** [comment]
yes but actually his advice was limited to monitoring the packages. But my problem still exist.

**Comment by salehhoushangi** [comment]
@lmangani  could you tell me how can i check and monitor authenticate ongoing step?  i means Is there at least a place to store authentication logs?

**Comment by lmangani** [comment]
The error is the same you saw by sniffing the port. You need to troubleshoot server-side, we can't help you without knowing the input to the output.

**Comment by salehhoushangi** [comment]
thank you  . finally i do it.
