### ISSUE TITLE
Password resets daily to sipcapture

### ISSUE THREAD

**Issue by os11k** [sipcapture/homer-app#186]
After setting-up new password via gui at next day it again reset to sipcapture.

**Comment by lmangani** [comment]
Is any of the containers is restarting daily?

**Comment by os11k** [comment]
No, all containers are up except "hepsub-elastic", that problem I explained separately on google groups.

**Comment by os11k** [comment]
I re-fetch my docker images and seems issue is not there anymore, so you can close this. Not sure who and when fixed it or maybe I was just not lucky and I got some-kind of random glitch...

**Comment by os11k** [comment]
Strange, I just did:

docker-compose down
docker-compose up -d --build

And password again was reset to sipcapture

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
