### ISSUE TITLE
Correct times not exported in PCAP

### ISSUE THREAD

**Issue by compuwizz** [sipcapture/homer-app#187]
When finding a call, the ladder graph shows the correct timing for the SIP packets on the transaction. When the transaction is exported to PCAP, the resulting PCAP has the packets at the wrong time intervals. So duration of call is incorrect as well as when packets were replied to.

**Comment by lmangani** [comment]
Thanks for the report @compuwizz - This might depend on your PCAP unless otherwise proven. You're also not mentioning which of our tools you're using - please document your case and attach some elements for reproducing so we can assist.

**Comment by compuwizz** [comment]
I'm using Homer 7.0.4. Here is an example. I have used sngrep to capture the call and compare it against the PCAP that Homer exports for the same call. In Wireshark, the times associated with the sngrep capture are correct. The times with the Homer capture are incorrect.
[Archive.zip](https://github.com/sipcapture/homer-app/files/3585187/Archive.zip)

**Comment by aqsyonas** [comment]
@compuwizz we are working on your request. Thanks for your patience.

**Comment by lmangani** [comment]
Should be fixed now! Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
