### ISSUE TITLE
RTP-FULL-REPORT is null

### ISSUE THREAD

**Issue by changzx** [sipcapture/homer-app#188]
rtp-full-report is null？
![image](https://user-images.githubusercontent.com/42836671/64474509-59a1d600-d1a8-11e9-9c0e-f9a0c71ab00f.png)
![image](https://user-images.githubusercontent.com/42836671/64474523-91108280-d1a8-11e9-8a06-bf9965c040fd.png)

**Comment by lmangani** [comment]
Was this a question?

**Comment by changzx** [comment]
> Was this a question?

What conditions trigger, will there be data?

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
