### ISSUE TITLE
Choose a different prometheus data source

### ISSUE THREAD

**Issue by changzx** [sipcapture/homer-app#189]
Dear:
 Is it possible to choose different prometheus data sources for different voip servers?
![image](https://user-images.githubusercontent.com/42836671/64949659-4380cd80-d8ac-11e9-9053-5f869219b4d8.png)

**Comment by lmangani** [comment]
Hi @changzx you should be able to add multiple datasources form the Admin panel where the current one is configured. Have you attempted to do so already?

**Comment by changzx** [comment]
> Admin panel

Admin panel?
where?
![image](https://user-images.githubusercontent.com/42836671/65014554-9e203500-d951-11e9-901e-14ad422a2b1b.png)

**Comment by lmangani** [comment]
Please re-test in 7.7 feel free to try it - any input is welcome!
