### ISSUE TITLE
Ui aliases maximum mask 32, too short for IPV6 

### ISSUE THREAD

**Issue by dvillaume** [sipcapture/homer-app#192]
Hello,

Alias maximum mask is set to 32 on UI, is not pertinent for IPV6, may you have a look ? 

Thanks.

**Comment by negbie** [comment]
@dvillaume I have added the mask field only to possibly use it in the future. It never worked so you can just ignore it.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/heplify-server/releases/tag/1.15
https://github.com/sipcapture/homer-app/releases/tag/1.1.12
