### ISSUE TITLE
Call Correlation using Session-ID header

### ISSUE THREAD

**Issue by runelucica** [sipcapture/homer-app#196]
First of all, I would like to thank everyone at sipcapture for Homer. It was (back in the Homer 5 days) and continues to be a great product.

Now, going back to my issue at hand.
I am using Homer 7 (more exactly: hom7-hep-elastic docker compose setup) and would like to use the Session-ID header value for correlating call legs. The call legs have Session-ID header populated with the same value and this is maintained across all B2BUA the call goes through.

I have read previous Issues submitted on this topic, as well as the Correlation Mapping wiki, however I think I am still having a hard time understanding how this works.

I have tried without success configuring the heplify-server to use the Session-ID header for correlation ("HEPLIFYSERVER_ALEGIDS=SESSION-ID").

I have also tried using the Homer Web-UI mapping interface to edit one of the existing mapping but I was not successful, as I am trying to match calls that have the same Session-ID header value and I don't know what source field provides access to this.

I am sure I am doing something wrong here and could you use a bit of guidance if possible.

**Comment by runelucica** [comment]
Here are 2 sample call legs that would need to be correlated.
Leg 1 - Source 172.Y.T.11 Destination 172.Y.X.165:

INVITE sip:70006000@172.Y.X.165:5060 SIP/2.0
Via: SIP/2.0/UDP 172.Y.T.11:5060;branch=z9hG4bKcee4d167fbc333
From: "UserA" <sip:74912864@customer.com>;tag=23987083~be9d2c70-b173-4e5f-b1e5-cc7a3b86db78-28251532
To: <sip:70006000@172.Y.X.165>
Date: Tue, 29 Oct 20Y 09:11:25 GMT
Call-ID: 13d22200-db81023d-8de265-b8913ac@172.Y.T.11
Supported: timer,resource-priority,replaces
Min-SE:  1800
User-Agent: Cisco-CUCM11.5
Allow: INVITE, OPTIONS, INFO, BYE, CANCEL, ACK, PRACK, UPDATE, REFER, SUBSCRIBE, NOTIFY
CSeq: 101 INVITE
Expires: 180
Allow-Events: presence, kpml
Supported: X-cisco-srtp-fallback,X-cisco-original-called
Call-Info: <sip:172.Y.T.11:5060>;method="NOTIFY;Event=telephone-event;Duration=500"
Call-Info: <urn:x-cisco-remotecc:callinfo>;x-cisco-video-traffic-class=DESKTOP
**Session-ID: 309b5fa900105000a000042ae2063482;remote=00000000000000000000000000000000**
Cisco-Guid: 0332538368-0000065536-0008509607-0Y3532844
Session-Expires:  1800
Remote-Party-ID: "UserA" <sip:74912864@customer.com>;party=calling;screen=yes;privacy=off
Contact: <sip:74912864@172.Y.T.11:5060>;
Max-Forwards: 68
Content-Length: 0

Leg 2 - Source 172.Y.X.165 Destination 172.Y.X.186:

INVITE sip:70006000@172.Y.X.186:5060 SIP/2.0
Via: SIP/2.0/UDP 172.Y.X.165:5060;branch=z9hG4bK3ee5f51a1Y
From: "UserA" <sip:74912864@172.Y.X.165>;tag=1083~26e1093b-693d-4f60-b996-7588cb857cc5-17Y7392
To: <sip:70006000@172.Y.X.186>
Date: Tue, 29 Oct 20Y 09:11:25 GMT
Call-ID: 13d22200-db81023d-1ea-a5a013ac@172.Y.X.165
Supported: timer,resource-priority,replaces
Min-SE:  1800
User-Agent: Cisco-CUCM11.5
Allow: INVITE, OPTIONS, INFO, BYE, CANCEL, ACK, PRACK, UPDATE, REFER, SUBSCRIBE, NOTIFY
CSeq: 101 INVITE
Expires: 180
Allow-Events: presence, kpml
Supported: X-cisco-srtp-fallback,X-cisco-original-called
Call-Info: <sip:172.Y.X.165:5060>;method="NOTIFY;Event=telephone-event;Duration=500"
Call-Info: <urn:x-cisco-remotecc:callinfo>;x-cisco-video-traffic-class=DESKTOP
**Session-ID: 309b5fa900105000a000042ae2063482;remote=00000000000000000000000000000000**
Cisco-Guid: 0332538368-0000065536-0000000490-2778731436
Session-Expires:  1800
P-Asserted-Identity: "UserA" <sip:74912864@172.Y.X.165>
Remote-Party-ID: "UserA" <sip:74912864@172.Y.X.165>;party=calling;screen=yes;privacy=off
Contact: <sip:74912864@172.Y.X.165:5060>;
Max-Forwards: 67
Content-Length: 0

The Session-ID header is what I would like to use for correlation of call legs. 
It might be that Homer is doing this by default and I am missing something in my configuration.

**Comment by runelucica** [comment]
Could you please let me know if this issue/request should have been submitted somewhere else (i.e. heplify-server)?

Any feedback would be appreciated.

**Comment by lmangani** [comment]
Hi @runelucica 
Your question requires a faceted response. The Correlation ID can be extracted by an Agent (such as HEPlify) a Server (HEPlify-server extract X-CID) or determined by the API/UI based on mapping settings.

Please make sure your `Session-ID` header is configured in a case-sensitive fashion and verify if this is extracted into the `correlation_id` or `SID` field in Database. Your example suggests this being the error possibly:
```
("HEPLIFYSERVER_ALEGIDS=SESSION-ID").
```

If this is the case and you correct your config, correlation should be automatically sorted. If not, we'll have to figure out at which stage this is breaking.

**Comment by runelucica** [comment]
Thank you for the reply. Will give this a try. 

Since some of my questions I know can't be handled via github issues (they are more suited in a training class) I sent an email asking for a training quote (to QXIP ticket ID 13631). Not sure if anyone is following that. Would be great if you guys are still hosting them as I am interested in attending.

**Comment by lmangani** [comment]
Please re-test in 7.7 feel free to try it - any input is welcome!
