### ISSUE TITLE
IPV6 format is wrong in call flow

### ISSUE THREAD

**Issue by aleczmw** [sipcapture/homer-app#201]
the ipv6 is **1:2:3:4:5::7:8**  but it show **7:8::1:2:3:4:5**   in call follow(destination IP) 
**div ng-if="$last == true" class="info info_gateway" style="margin-right:-4px;"**
            div class="wr-info-text cflow-bubble">
              div class="info-text ng-binding" style="color:#fff;"></div>
              div class="info-text-port ng-binding">**1:2:3:4:5::7:8**</div>
            /div>
          /div>

if ipv6 is 1:2:3:4:5:6:7:8, it shows correctly in call follow(destination IP)

From the observation, once there is **::** in ipv6, the destination IP in call flow is always wong.

i suspect it is related to **class="info info_gateway"**, the wrong ipv6 format only happened when **ng-if=$last**
Could you please have a check.

**Comment by aleczmw** [comment]
<div ng-if="$first" **### class="wr-info-text wr-info-text_left cflow-bubble"** style="margin-left:-2px;">
               <div class="info-text" style="color:#fff;">{{item.description}}</div>



           <div ng-if="$last == true" **class="info {{$ctrl.lasthosts.type}}"** style="margin-right:-4px;">
             <div class="wr-info-text cflow-bubble">
               <div class="info-text" style="color:#fff;">{{$ctrl.lasthosts.description}}</div>



what's the difference among the highted parts?
thank you for your support.

**Comment by lmangani** [comment]
Thanks for the report! The version you're using has known issues and is about to be hotswapped.
Any chance you could test this against a 7.7 alpha release using the `server-only` branch please?

**Comment by aleczmw** [comment]
> 
> 
> Thanks for the report! The version you're using has known issues and is about to be hotswapped.
> Any chance you could test this against a 7.7 alpha release using the `server-only` branch please?

Thank you for your response.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/heplify-server/releases/tag/1.15
https://github.com/sipcapture/homer-app/releases/tag/1.1.12
