### ISSUE TITLE
Search results page: make font size and table cell padding configurable

### ISSUE THREAD

**Issue by gedia** [sipcapture/homer-app#202]
Hello,

I've redeployed homer-app from master today, and most of the shortcomings I encountered the last time I tried it out (which was a few months ago), mainly LDAP integration, seem to be resolved.

One aspect I find a little inconvenient is the density of displayed information in (Proto) search results. I believe the text size is too large which leads to text being truncated in table view. I think it would be useful to:

* Be able to configure font size for the table displaying protocol search results in user preferences
* Be able to configure cell padding for the same table in user preferences, so that users have the option to reclaim screen real estate currently lost to cell padding
* Have configurable row height, which is also significantly larger than on Homer5

I'm available for testing if needed. Thanks!

**Comment by lmangani** [comment]
The entire display setup has been redesigned in 7.7 please check there to see if the experience improved -thanks!

**Comment by gedia** [comment]
@lmangani 

This ticket concerned testing of commit 076237a03f4b1a0dade9dbd69a148fb87b001d84 from the master branch. There have been no newer commits since then. Is version 7.7 available in a different branch? Thanks!

**Comment by gedia** [comment]
Never mind, I found this line in installer script of 7.7 branch of homer-installer:

`repo_clone_or_update "$src_base_dir" "$src_homer_app_dir" "https://github.com/sipcapture/homer-app" "server-only"`
