### ISSUE TITLE
Support Homer5-style layout of Search dashboard

### ISSUE THREAD

**Issue by gedia** [sipcapture/homer-app#203]
Hello,

I realise Homer7 has a much larger scope of applications than Homer5, but I think users would be more inclined to try it out if the default knex seeds provided a "Search" dashboard for SIP which replicates the structure found in Homer5.

Right now I believe the following is missing:
* One cannot position search fields in a columns/rows layout, sharing a single Search and Clear button
* Searching for the user-part of the RURI does not seem to be supported out of the box on a clean installation of Homer7
* Similarly for filtering on User-Agent header
* It would be nice for the SIP Method field to feature a drop down widget with as-you-type filtering, similar to Homer5
  * It would also be useful if the drop-down list values were configurable by the user (so that she can add/remove values used most often/rarely)
* Would it be possible to have a single dashboard with a table selection widget that allows one to search in multiple tables, or a subset of them? (Similar to Homer5's Calls, Registrations, Other, which are Ctrl+click selectable). So far I've been under the impression that one has to choose the target of a ProtoSearch widget by selecting a profile upon its creation (call, registration or default).

As stated in the other issue I opened earlier, I'm available for testing. Thank you and keep up the great work!

**Comment by lmangani** [comment]
It would be incredibly useful if you could try and open issues for 7.7 - the display experience and the mapping of fileds changed slightly and might already fit the bill. Feel free to re-open for 7.7 anytime!

**Comment by gedia** [comment]
@lmangani 

This ticket concerned testing of commit 076237a03f4b1a0dade9dbd69a148fb87b001d84 from the master branch. There have been no newer commits since then. Is version 7.7 available in a different branch? Thanks!

**Comment by lmangani** [comment]
Things are going to be shuffled around a bit and we'll go back to the main `homer` repo but you can test using the `server-only` branch of homer-app right now. Thanks in advance!

**Comment by gedia** [comment]
Never mind, I found this line in installer script of 7.7 branch of homer-installer:

`repo_clone_or_update "$src_base_dir" "$src_homer_app_dir" "https://github.com/sipcapture/homer-app" "server-only"`

**Comment by games130** [comment]
I have just loaded the new homer-app (via docker). I guess this is HOMER 7.7? I believe the question posted by @gedia is still there.

I too would like to have an option to use back HOMER5 search dashboard. 
The new search is widget is only one column and if we add too much rows, it goes missing as you are not able to scroll down.

**Comment by adubovikov** [comment]
@games130 you can change the loyout in the dashboard settings:
![Screenshot from 2020-01-15 12-04-56](https://user-images.githubusercontent.com/4513061/72429038-4a064f80-378f-11ea-9178-1264f9c2b4ed.png)

**Comment by gedia** [comment]
The request concerns, among others, the possibility of choosing a grid layout for the search widget, in addition to the grid layout already available for dashboards.

**Comment by adubovikov** [comment]
@gedia interesting request. Would you like do define amount of columns ?

**Comment by gedia** [comment]
I believe anything above 2 columns would find very few use cases out there. But that's just my opinion.

While columns will vastly improve usability of the search widget in my opinion, it would also be useful, to a lesser extent, to have the ability to define rows. What I mean by rows is the ability to add visual horizontal separators between rows at specified points. Such a setting (e.g. add horizontal separator at positions: 4,6, which would result in the following grouping: 3 rows with search fields, then separator, then 1 row with fields, then separator, then any remaining number of rows with search fields) would most likely allow for any layout of practical value. To complement this, one would also need to be able to add dummy "empty" fields in order to push other fields in the desired positions. The advantage of visual grouping would be in cases where one needs a dashboard with a large number of search fields, say as many as the default Search dashboard in Homer5: having the fields visually separated (in columns as stated earlier or in groups of fields separated by a horizontal visual separator) allows users to quickly navigate to the field they intend to use for searching by visual guidance alone. Right now, where everything is organized in a single column without any visual grouping, I often find myself having to read the label to determine if that's the right one, even after having used the interface for a while. In homer5, due to this visual grouping, this automation would take place a lot sooner. Here's a reminder of what the search dashboard used to be like:

![this](
https://camo.githubusercontent.com/3497282612363f3e71c359c2eec6cb07853524a6/687474703a2f2f692e696d6775722e636f6d2f423247555078762e706e67)

However, please also note the remaining points I outlined in my original post would also contribute to a better user experience in my opinion, namely searching within Call/Reg/Other tables from the same Search widget and having support for drop-down lists in search fields (e.g. for sip METHOD) with autocompletion.

**Comment by games130** [comment]
May i suggest to have exactly the same search layout as HOMER5, then build a new search layout for HOMER7.7. (I guess you can have a link on a corner to use the new search layout - like how i see it being done when i upgrade to the latest prometheus)

![Untitled](https://user-images.githubusercontent.com/32865575/72496569-f6663580-3864-11ea-94b6-a9d76598f8e6.png)

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.8

**Comment by games130** [comment]
I notice that now we can specify the columns. Still quite different from HOMER5. 
![Capture](https://user-images.githubusercontent.com/32865575/72964156-0d240380-3df4-11ea-87b9-1dd21797b72d.JPG)

is it possible to make it so that we can arrange the parameters on which row and column.
is it possible to have multiple widget but when we click search it will take all search parameter from all the search widget in that perticular dashboard?
![Capture2](https://user-images.githubusercontent.com/32865575/72964465-f631e100-3df4-11ea-89c3-30821dde6fb3.JPG)

**Comment by adubovikov** [comment]
currently each widget is an isolete scope. In one of next releases we will add "connections" between widget, but for now you can just make widget bigger and add multiple columns

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.12

**Comment by adubovikov** [comment]
https://github.com/sipcapture/heplify-server/releases/tag/1.15
https://github.com/sipcapture/homer-app/releases/tag/1.1.12

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.20

**Comment by adubovikov** [comment]
the version 1.3.0 has been released. Please install it and retest it.
