### ISSUE TITLE
can't import json dashboard

### ISSUE THREAD

**Issue by akam-it** [sipcapture/homer-app#206]
Hello, I have just installed homer 7 docker-compose and trying to import dashboard SIP_Overview.json
But I can't, something wrong with interface, then I press Save nothing happens

![Screenshot from 2019-11-28 16-42-44](https://user-images.githubusercontent.com/1487709/69813775-f00ff180-1203-11ea-9b85-66ca1d69774c.png)

**Comment by lmangani** [comment]
This has been much improved and resolved in 7.7 - feel free to switch to the branch anytime its already superior to 7.0 by far

**Comment by akam-it** [comment]
thank you for answer, so master is older than 7.7 right?

**Comment by lmangani** [comment]
@akam-it that's correct the `server-only` branch is currently ahead in homer-app or `7.7` branch in `homer-docker` examples & templates which are the most feature complete examples

**Comment by ryan99alero** [comment]
> @akam-it that's correct the `server-only` branch is currently ahead in homer-app or `7.7` branch in `homer-docker` examples & templates which are the most feature complete examples

I'm not seeing a server-only branch nor did I find any examples & templates.  Was wanting to see if they had any alternate options for the Dash Board vs the stock one.  Has this been moved?  I've found several dashboard files but I think they are for Prometheus not homer web app.

**Comment by adubovikov** [comment]
server-only is obsolete. You have to use homer-app-go - the new version of
our API
