### ISSUE TITLE
custom ssl certificate in homer-app

### ISSUE THREAD

**Issue by Rico29** [sipcapture/homer-app#210]
Hello,
I'm looking for the syntax to use in homer-app/server/config.js to use a custom SSL certificate. Did not find doc about that : 

```
export default {
  http_host: '0.0.0.0',
  http_port: 80,
  https_host: '0.0.0.0',
  https_port: 443,
  certificate: {
    self_signed: true,
    days: 1
  },
...
```
is there any doc about that ?
Regards

**Comment by lmangani** [comment]
I'll add some docs in the next days/weeks but in real-life scenarios for ease of operation, support and feature we would suggest simply deploying NGINX or any other lightweight production-grade proxy in front of the application.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/heplify-server/releases/tag/1.15
https://github.com/sipcapture/homer-app/releases/tag/1.1.12
