### ISSUE TITLE
ctrl.shareLinkDisabled

### ISSUE THREAD

**Issue by Rico29** [sipcapture/homer-app#211]
hello,
I see in code "ctrl.shareLinkDisabled" which seems to be true as "export > share link" is disabled.
how do I change this param ?
Regards
Cédric

**Comment by lmangani** [comment]
Hello Cedric,

Which version are you using? This is disabled in 7.01 and will be re-enabled in 7.7 at some point.

**Comment by Rico29** [comment]
Hello,
I'm using git master branch
Regards

**Comment by adubovikov** [comment]
the button share link has been enabled in the dev. We will release it today.

but the link will be availble only for homer's users. For an external user you have to use Homer-View project

https://github.com/sipcapture/homer-view-react
