### ISSUE TITLE
Support more postgres logical operators

### ISSUE THREAD

**Issue by negbie** [sipcapture/homer-app#213]
Allow all kind of logical postgres operators (OR,NOT...) per search field.

**Comment by negbie** [comment]
Allow concatenation of them.

**Comment by negbie** [comment]
Like call-id1;call-id2;call-id3, !call-id1;!call-id2;call-id3

**Comment by adubovikov** [comment]
![Screenshot from 2020-01-24 18-41-07](https://user-images.githubusercontent.com/4513061/73090763-44201500-3ed9-11ea-87b9-d0dd1998cbfd.png)
it's in the master

**Comment by adubovikov** [comment]
![Screenshot from 2020-01-24 18-58-43](https://user-images.githubusercontent.com/4513061/73091852-95c99f00-3edb-11ea-845f-6f56c1ce23ff.png)
and ! - NOT IN

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.12

**Comment by negbie** [comment]
Nice and thanks. Will take a look later.

**Comment by adubovikov** [comment]
once you have opened another ticket - I will close it as DONE
