### ISSUE TITLE
 homer-app 7.7: knex seed:run fails with 'relation "agent_location_session" does not exist'

### ISSUE THREAD

**Issue by gedia** [sipcapture/homer-app#217]
Hello,

On a new installation from 'server-only' branch (commit b9ec1160f97f306471dff3effad11f1880b870d7), I'm getting the following error upon running knex seed:

```
Using environment: development
Error: Error while executing "/opt/homer-app/seeds/05_AgentLocation.js" seed: delete from "agent_location_session" - relation "agent_location_session" does not exist
    at /opt/homer-app/node_modules/knex/lib/seed/Seeder.js:146:25
error: relation "agent_location_session" does not exist
    at Connection.parseE (/opt/homer-app/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (/opt/homer-app/node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (/opt/homer-app/node_modules/pg/lib/connection.js:113:22)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
```

**Comment by lmangani** [comment]
Hello @gedia thanks for the report! Could you confirm this is still the case with the most recent `server-only` branch?

**Comment by gedia** [comment]
You're welcome :-)

Well as I said it's commit b9ec1160f97f306471dff3effad11f1880b870d7, which I believe to be the latest already?

P.S. in case it matters:
* I'm using nodeJS 12.x, which I'm assuming is the new target version for Homer 7.7 judging from recent commits?
* Knex --version prints out:
  * Knex CLI version: 0.20.4
  * Knex Local version: 0.19.5

**Comment by lmangani** [comment]
That seems in line with our setup, but I no longer has this error in knex.
See Dockerfile: https://github.com/sipcapture/homer-app/blob/server-only/Dockerfile

**Comment by gedia** [comment]
Hm, the dockerfile you linked to seems to be using a different repository at gitlab: https://gitlab.com/qxip/hepic-ui-3, which seems to be quite different from the server-only branch from this repository.

Other than that, I wasn't able to find any significant differences with my deployment, which is based on the homer_installer.sh script from branch 7.7 of homer-installer repo.

I'll give it another try in the following days...

**Comment by lmangani** [comment]
The UI is already included in the `homer-app` public folder, so you can skip that step.
The 7.7. installer should fetch the `server-only` branch of this project which includes the UI.

**Comment by gedia** [comment]
OK, got it. I'm assuming it's for the same reason that homer_installer.sh won't do ```npm install -g @angular/cli && ng build```?

The only other difference I was able to spot was that the dockerfile will also run ```npm install -g modclean && modclean -r``` which the bash installer script doesn't. Is this an omission or on purpose?

Lastly, an instance of heplify-server was already configured to use the same databases as homer-app. I believe upon starting heplify-server for the first time, it will install the schema on the database. Is it possible that the knex seeding fails because of previous schema entries inserted by heplify-server?

**Comment by lmangani** [comment]
Spot on. `modclean` is just a tool removing all unecessary duplicates and non-vital files installed under node_modules, in an effort to make the container smaller. About knex and the existing tables, the seeding actions should allow for existing tables and produce no errors, so I need to review them next.

**Comment by adubovikov** [comment]
i am clossing it. The issue has been fixed

**Comment by abv** [comment]
I've run into this too. Using the latest build. I've tracked the problem down to the error `function date_add(timestamp with time zone, interval) does not exist` which is eaten by `knex:migrate` and not exposed in the logs.

I think its something related to this... (via https://www.postgresql.org/docs/7.2/datatype-datetime.html)
> Note: As of PostgreSQL version 7.2, 'current' is no longer supported as a date/time constant. Previously, 'current' was stored as a special value, and evaluated to 'now' only when used in an expression or type conversion.

After some experimenting, it seems that the `agentLocationSession.timestamp('expire_date')` line in the migrate script is the problem. I updated that line to `agentLocationSession.timestamp('expire_date').notNullable().defaultTo(knex.raw('? + (? * interval \'1 second\')', [knex.fn.now(), "86400"]));` and the table was properly created.

I'm still getting my bearings w/ homer and postgres, so I'm not sure this is the _best_ fix. But if it looks good, I'd be happy to make a PR.

**Comment by lmangani** [comment]
Thanks @abv much appreciated and well spotted! I just punched this in to master, let us know if this sorts it in real life :)

**Comment by abv** [comment]
@lmangani Turns out there were some other problems w/ `knex:migrate` not properly creating tables, which I resolved here https://github.com/sipcapture/homer-app/pull/226

**Comment by adubovikov** [comment]
@abv did you migrate to the new homer-app golang ?

**Comment by abv** [comment]
@adubovikov Yes. 7.7 golang seems to be working well.
