### ISSUE TITLE
Homer-app 7.7 server only- Cannot login over https

### ISSUE THREAD

**Issue by rgiskard85** [sipcapture/homer-app#218]
Hello,
I have Homer-app 7.7 server-only branch installed and listening on ports 

- http://127.0.0.1:8080

- https://127.0.0.1:8443

The http port works and I can login without issues. I installed nginx and configure it as a typical reverse proxy
http port 80 redirects to https port 443 that uses proxy pass to http://127.0.0.1:8080
After those changes, the login page loads normally but when trying to login I  get an "Unknown Error" at the top left of the screen with nothing logged from homer-app. I used developer tools on Firefox and saw that Firefox blocked the connection due to the existence of the mixed (HTTP and HTTPS) environment.
I disabled the browser's feature and tried again and there I saw the following errors:

```
Dec 17 18:35:48 server_hostname[12481]: Debug: handler, error
Dec 17 18:35:48 server_hostname[12481]:     {"msec":0.5887359976768494,"error":"CORS error: Missing Origin header","data":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":404,"payload":{"statusCode":404,"error":"Not Found","message":"CORS error: Missing Origin header"},"headers":{}}}}
Dec 17 18:35:48 server_hostname nginx: 172.17.172.57 - - [17/Dec/2019:18:35:48 +0200] "OPTIONS /api/v3/auth HTTP/1.1" 404 111 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
```
I have added 
```
   location / {
        proxy_pass http://127.0.0.1:8080;
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Headers' 'Cache-Control, X-Requested-With';
        }
    }  
```
But the error persists.

**Comment by aqsyonas** [comment]
@rgiskard85 please, try the latest code from the very branch.

**Comment by adubovikov** [comment]
I am clossing the ticket. The issue has been fixed
