### ISSUE TITLE
Version 7.7 : Search Widget Configuration shows a mispelt word " Saves" instead of "Save"

### ISSUE THREAD

**Issue by ruchi1912** [sipcapture/homer-app#220]
Steps to reproduce

1. Login to GUI
2. Go to Add Widget 
3. Select Search and add Proto Search
4. Go to recently added Widget's Settings
5. Save button has mispelt spelling

Actual Output

- It is showing "Saves" 

Expected Output

- It should be "Save"

![HOMER1](https://user-images.githubusercontent.com/59015660/71081246-d5062100-21b4-11ea-89d1-c66f7958c140.png)

**Comment by adubovikov** [comment]
fixed
