### ISSUE TITLE
Version 7.7 : Widget Display Chart - Misspelt word "Add Serias" instead of " Add Series"

### ISSUE THREAD

**Issue by ruchi1912** [sipcapture/homer-app#221]
Steps to reproduce

1. Login to GUI
2. Go to Add Widget 
3. Select Visualize and add Display Results Chart
4. "Add Series" has mispelt spelling

Actual Output
- It is showing " Add Serias"

Expected Output
- It should show "Add Series"

![HOMER 2](https://user-images.githubusercontent.com/59015660/71081377-172f6280-21b5-11ea-9c9f-566ac88d90ae.png)

**Comment by adubovikov** [comment]
fixed
