### ISSUE TITLE
Multiple Search Nodes in H7

### ISSUE THREAD

**Issue by jvb187** [sipcapture/homer-app#222]
Hello,

Is it possible to have multiple search nodes in the H7 web front end like we could in H5?  I currently have H5 setup with a Heplify-Server instance in each of a number of countries and store the data locally, using one web front end to search calls in the different nodes.

In H5 it was as simple as disabling single node and then just adding the nodes in admin.  I am not seeing anything similar in H7. I would like to avoid using many web front ends, especially when it is not clear which node the call might be in.  The other option seems to be to ship HEP packets all to a single Heplify-Server, but then I lose the ability to only search a single node if I am certain which node the call is in.

Thanks,
Jeremy

**Comment by adubovikov** [comment]
Hi Jeremy,

yes, it has been planned and it will be availble untill end of this year.

**Comment by jvb187** [comment]
Thank you Alexandr!

**Comment by adubovikov** [comment]
due date 07.01.2020

**Comment by adubovikov** [comment]
some delays.. updates are comming

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/commit/8e88e029ee336101751057f234ba0764f4ee5932

**Comment by adubovikov** [comment]
implemented in the homer App Go

**Comment by jvb187** [comment]
Thank you very much!

**Comment by adubovikov** [comment]
please install the package and test it https://github.com/sipcapture/homer-app/releases

**Comment by lmangani** [comment]
config reference: https://github.com/sipcapture/homer-app/blob/master/CONFIGURE.md

**Comment by jvb187** [comment]
I installed the latest package, and the actual remote database connection is working great.  When I search I receive results as expected.

I am having issues when clicking on a Session ID link, however. The results window appears, but the loader spins forever and I receive the following in Chrome Dev Tools:

ERROR TypeError: Cannot read property 'protocol_id' of null
    at SearchGridCallComponent.push../src/app/components/search-grid-call/search-grid-call.component.ts.SearchGridCallComponent.queryBuilderQOS (main.8eded70ae1b56a655ac6.js:321859)
    at SearchGridCallComponent.push../src/app/components/search-grid-call/search-grid-call.component.ts.SearchGridCallComponent.openTransactionDialog (main.8eded70ae1b56a655ac6.js:322175)
    at SearchGridCallComponent.push../src/app/components/search-grid-call/search-grid-call.component.ts.SearchGridCallComponent.openTransactionForSelectedRows (main.8eded70ae1b56a655ac6.js:322117)
    at ColumnCallidRenderer.push../src/app/components/search-grid-call/renderer/column-callid-renderer.component.ts.ColumnCallidRenderer.openTransactionPopup (main.8eded70ae1b56a655ac6.js:321458)
    at ColumnCallidRenderer_Template_a_click_0_listener (template.html:1)
    at executeListenerWithErrorHandling (main.8eded70ae1b56a655ac6.js:86868)
    at wrapListenerIn_markDirtyAndPreventDefault (main.8eded70ae1b56a655ac6.js:86896)
    at HTMLAnchorElement.<anonymous> (main.8eded70ae1b56a655ac6.js:160133)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (polyfills.d0bc6345c48047064637.js:3428)
    at Object.onInvokeTask (main.8eded70ae1b56a655ac6.js:97771)
defaultErrorLogger @ main.8eded70ae1b56a655ac6.js:75516
push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.ErrorHandler.handleError @ main.8eded70ae1b56a655ac6.js:75564
handleError @ main.8eded70ae1b56a655ac6.js:80599
executeListenerWithErrorHandling @ main.8eded70ae1b56a655ac6.js:86871
wrapListenerIn_markDirtyAndPreventDefault @ main.8eded70ae1b56a655ac6.js:86896
(anonymous) @ main.8eded70ae1b56a655ac6.js:160133
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.d0bc6345c48047064637.js:3428
onInvokeTask @ main.8eded70ae1b56a655ac6.js:97771
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.d0bc6345c48047064637.js:3427
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ polyfills.d0bc6345c48047064637.js:3200
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ polyfills.d0bc6345c48047064637.js:3503
invokeTask @ polyfills.d0bc6345c48047064637.js:4698
globalZoneAwareCallback @ polyfills.d0bc6345c48047064637.js:4724

The same data loads fine on the local H7.7 instance.


Thanks,
Jeremy

**Comment by adubovikov** [comment]
We will check ASAP

**Comment by adubovikov** [comment]
Do you have something in the homer-app's console ? On our lab all looks.
If you will see something like this: pq: out of shared memory, you have to increase 
 max_locks_per_transaction = 384
in your /etc/postgresql/11/main/postgresql.conf

**Comment by jvb187** [comment]
Would I increase this on the remote node, or on the homer-app server?   I tried increasing it on the homer-app server, but still get the same results, "Cannot read property 'protocol_id' of null"

If it is on the remote node, I am not quite sure how to do that as the remote is one of your homer7-docker images.

I do see the following in the console when I click a session ID, so I know it is retrieving the data correctly:

{row: {…}}
row:
data:
aliasDst: "xxx.xxx.xxx.xxx:5060"
aliasSrc: "xxx.xxx.xxx.xxx:39352"
callid: "529208639433308573018585"
captureId: "108"
correlation_id: "529208639433308573018585"
create_date: 1579023866779
dstIp: "xxx.xxx.xxx.xxx"
dstPort: 5060
from_domain: "xxx.xxx.xxx.xxx"
from_user: "100"
id: 1
method: "INVITE"
payloadType: 1
protocol: 17
protocolFamily: 2
ruri_domain: "xxx.xxx.xxx.xxx"
ruri_user: "100"
sid: "529208639433308573018585"
srcIp: "xxx.xxx.xxx.xxx"
srcPort: 39352
table: "hep_proto_1_call"
timeSeconds: 1579023866
timeUseconds: 779509
to_user: "100"
user_agent: "Cisco"
__proto__: Object
__proto__: Object
__proto__: Object

Thanks,
Jeremy

**Comment by adubovikov** [comment]
wait wait... this is not the homer-app go ? Are you sure that you run the latest goapp ?

**Comment by jvb187** [comment]
I am running a homer7-docker image that is collecting SIP via HEP from one of my SBC's.

I then set up a dedicated VM and installed the latest homer-app go DEB package and configured it to use the homer7-docker instance as a remote node.

I am doing all of my searching on the dedicated VM with only homer-app go latest and I am getting results pulling from my remote homer7-docker node.  It is only when I click on a session ID to get the pop up window with all of the call details and the export tab, etc.. that I receive the error.

**Comment by adubovikov** [comment]
@lmangani any update here ?

**Comment by lmangani** [comment]
Docker image of `homer-app` has been updated and should be now at the latest build. Please retest!

**Comment by jvb187** [comment]
I have upgrade my remote node to the latest docker images and I still receive the same error when trying to search the remote node from my local copy of the latest homer-app go.

main.8eded70ae1b56a655ac6.js:75516 ERROR TypeError: Cannot read property 'protocol_id' of null

Just to be on the same page, I have a remote node in NYC that I am running the very latest H7.7 docker images on.  This node receives HEP packets from my SBC and stores them.

I have a server local to me elsewhere in NY that I am running only the latest homer-app go version on.  I have configured this local homer-app server to use my remote NYC node for it's homer_data  information.  I am able to successfully search using my local homer-app server and see records that are actually on the remote NYC node.  It is when I click on one of the Session ID links in my results when I receive the javascript error.

I can also try switching to using docker for the local homer-app server if you think that will help, instead of just installing the DEB file on a bare Ubuntu server with Postgres 12.

Thanks,
Jeremy

**Comment by adubovikov** [comment]
Jeremy,

can you please open F12 in  your browser and click on the callid, after
check the Network tab if you have any API request and any exists, check the
path and the result and paste here

thank you

**Comment by jvb187** [comment]
No, there is no network request made when I click on the callid.  Only the javascript error.

Thanks,
Jeremy

**Comment by adubovikov** [comment]
ghmm, ok, can you show us the result of the AIP that you have if you do
messages search  ?
The API is api/v3/search/call/data

**Comment by jvb187** [comment]
I receive all of the expected data in the api/v3/search/call/data API call that happens when I press Search. There is a data object with a data array and a keys array inside.

There is quite a bit of data and I am not sure how to display it here, is there something in particular that you are looking for?

Thanks,
Jeremy

**Comment by lmangani** [comment]
pastebin the whole thing if you can

**Comment by jvb187** [comment]
I am going to work on getting an example that I don't have to worry about sanitizing and then I will put it in a pastebin and upload.

Thanks,
Jeremy

**Comment by jvb187** [comment]
Here is the pastebin:

https://pastebin.com/rQKmhXB2

Thanks,
Jeremy

**Comment by jvb187** [comment]
For a comparison, here is a patebin of the same API call when I do the same exact search on the remote node's homer-app instance, which works fine:

https://pastebin.com/MH32bw0B

It looks like there are some casting differences with the data when pulled remotely compared to local. I wonder if that has something to do with it..

Thanks,
Jeremy

**Comment by adubovikov** [comment]
so, looks like this  https://pastebin.com/MH32bw0B has been served by
nodejs server-only application  and the  https://pastebin.com/rQKmhXB2 -
webapp-go

Can you confirm ?

**Comment by jvb187** [comment]
https://pastebin.com/MH32bw0B  is from the latest homer7-docker from Github.  I am using the hom7-hep-prom-graf version.

https://pastebin.com/rQKmhXB2  is just a fresh install of Ubuntu 18.04 with Postgres and the latest homer-webapp go DEB file installed.

Thanks,
Jeremy

**Comment by adubovikov** [comment]
and who is populating the DB for "DEB" ? or do you use same DB ?

Wbr,
Alexandr

P.S. the homer7-docker that you use is 100% with nodejs API server. Please
update it

**Comment by jvb187** [comment]
I will try to update the docker images again.

No HEP data will be in the homer-webapp database. I plan on only using the app to search remote nodes. All HEP data is inserted into each remote node from its local SBC.

Thanks,
Jeremy

**Comment by jvb187** [comment]
I was able to get a little further.  It appears that the protocol_id javascript error only occurs when using the home page search results widget.  When I change the Results Container to Default so that it opens up a new page with the results, I no longer get the javascript error.

I am still just getting the spinning loader animation and no results.  I do now see that API calls are made successfully to api/v3/call/report/qos and to api/v3/call/transaction now, but never to api/v3/advanced

Thanks,
Jeremy

**Comment by jvb187** [comment]
I think I have it all working now.

It looks like I used the "LocalNode" section of the webapp_config.json file instead of "RemoteNode".

Once I moved my remote node configuration settings to "RemoteNode" and removed "LocalNode" section completely (since I will have no local node) and restarted the homer-app server, everything worked fine.

I am able to pull up the call details on both the widget results container as well as the Default from my remote node.

Last thing, is there any way to select specific nodes from the GUI to search on?  Or is it just going to always search on all remote nodes specified in the configuration?

Thank you for all of your help,
Jeremy

**Comment by adubovikov** [comment]
Great that you have figured it out. About selection - we will implemented
in the next minor release

**Comment by adubovikov** [comment]
I will close the ticket because now it very huge and we have lost the track. For the selection of node, please open an additonal ticket - i will explain how to do it even with current widget.

**Comment by bhatguru** [comment]
Hi @adubovikov 

We have a 2 data node homer setup, currently when we search for the packets, search happens across both the data nodes and whenever one of the data node goes down we will not able to access any packets from other node as well. Saw  that from the above conversations some feature has been added to select the data source for searching, can you please point me which release has this feature and how to enable this, where this option is located in Dashboard.
