### ISSUE TITLE
knex fails to create homer-app tables

### ISSUE THREAD

**Issue by ccmsi** [sipcapture/homer-app#225]
Greetings.
Im running homer-app commit 3679d8e98018590a0d6484d5e0364b4085e732b0 on a dedicated VM against a remote postgresql server.

When running
knex migrate:latest
on an empty DB

response is:
Using environment: development
Batch 1 run: 1 migrations

However, no homer-app tables are created.
originally empty DB now contains:

homer_config_700=# \dt
                List of relations
 Schema |         Name         | Type  |  Owner  
--------+----------------------+-------+---------
 public | knex_migrations      | table | heplify
 public | knex_migrations_lock | table | heplify
(2 rows)

Subsequent knex seed:run expectably fails to insert data.

--debug outpu for knex migrate:latest is:

[ { sql: 'select * from information_schema.tables where table_name = ? and table_schema = current_schema()',
    bindings: [ 'knex_migrations' ],
    output: [Function: output] } ]
[ { sql: 'create table "knex_migrations" ("id" serial primary key, "name" varchar(255), "batch" integer, "migration_time" timestamptz)',
    bindings: [] } ]
[ { sql: 'select * from information_schema.tables where table_name = ? and table_schema = current_schema()',
    bindings: [ 'knex_migrations_lock' ],
    output: [Function: output] } ]
[ { sql: 'create table "knex_migrations_lock" ("index" serial primary key, "is_locked" integer)',
    bindings: [] } ]
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '13b5e826-a0d0-4ff2-936b-40968e63c31f',
  sql: 'select * from "knex_migrations_lock"' }
{ method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 0 ],
  __knexQueryUid: '98e30ba7-9dec-4b18-b6ce-87e5b683774d',
  sql: 'insert into "knex_migrations_lock" ("is_locked") values (?)',
  returning: undefined }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '59e5cc3b-aa1a-4b3a-b879-4db6b2f72a7e',
  sql: 'select "name" from "knex_migrations" order by "id" asc' }
{ method: 'update',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1, 0 ],
  __knexQueryUid: 'e9f437e5-4305-4c2d-bc78-e2c90abafdf2',
  sql: 'update "knex_migrations_lock" set "is_locked" = ? where "is_locked" = ?',
  returning: undefined }
[ { sql: 'select * from information_schema.tables where table_name = ? and table_schema = current_schema()',
    bindings: [ 'knex_migrations' ],
    output: [Function: output] } ]
[ { sql: 'select * from information_schema.tables where table_name = ? and table_schema = current_schema()',
    bindings: [ 'knex_migrations_lock' ],
    output: [Function: output] } ]
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '015b4a01-fd2d-4075-8826-b31d008f072a',
  sql: 'select * from "knex_migrations_lock"' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '46b22da2-5899-4cc9-bebf-b8b72a9a15ea',
  sql: 'select "name" from "knex_migrations" order by "id" asc' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'cfe4c027-3947-4fdb-b049-d8b38dea3436',
  sql: 'select max("batch") as "max_batch" from "knex_migrations"' }
[ { sql: 'select * from information_schema.tables where table_name = ? and table_schema = current_schema()',
    bindings: [ 'users' ],
    output: [Function: output] },
  { sql: 'select * from information_schema.tables where table_name = ? and table_schema = current_schema()',
    bindings: [ 'mapping_schema' ],
    output: [Function: output] },
  { sql: 'select * from information_schema.tables where table_name = ? and table_schema = current_schema()',
    bindings: [ 'hepsub_mapping_schema' ],
    output: [Function: output] },
  { sql: 'select * from information_schema.tables where table_name = ? and table_schema = current_schema()',
    bindings: [ 'user_settings' ],
    output: [Function: output] },
  { sql: 'select * from information_schema.tables where table_name = ? and table_schema = current_schema()',
    bindings: [ 'global_settings' ],
    output: [Function: output] },
  { sql: 'select * from information_schema.tables where table_name = ? and table_schema = current_schema()',
    bindings: [ 'agent_location_session' ],
    output: [Function: output] },
  { sql: 'select * from information_schema.tables where table_name = ? and table_schema = current_schema()',
    bindings: [ 'alias' ],
    output: [Function: output] } ]
{ method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: 
   [ 1,
     2020-01-08T11:26:04.507Z,
     '20191126194600_Datastructure.js' ],
  __knexQueryUid: 'cd5cd110-9a61-4123-9279-795de118229d',
  sql: 'insert into "knex_migrations" ("batch", "migration_time", "name") values (?, ?, ?)',
  returning: undefined }
{ method: 'update',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 0 ],
  __knexQueryUid: 'bb89e3ce-37b6-4c07-83d3-b178929f3533',
  sql: 'update "knex_migrations_lock" set "is_locked" = ?',
  returning: undefined }

Appears to check for the tables, however doesnt create them.

**Comment by lmangani** [comment]
As a starter, do you have a populated `bootstrap` file by any chance? This will prevent re-provisioning. Could you try emptying out the file and running again?


This said, we should get rid of this inherited hell in a few weeks time hopefully solving all those issues at once.

**Comment by ccmsi** [comment]
# cat bootstrap.js 
require('babel-core/register');
require('babel-polyfill');
require('./server/server');


this is the file referenced for starting the service. do i understand correctly that i should empty it for a file size of 0 ?

**Comment by ccmsi** [comment]
Meanwhile i tried rerunning with aforementionned bootstratp.js both emptied and removed. However result is the same as in original description.

**Comment by inmula** [comment]
I ran into the same issue. I believe it's related to the `hasTable` calls in the migration file, but I wasn't able to fix it properly. I ended up stripping the migration file of all the `hasTable` calls and just ran the `createTable` function directly without checking if the tables already exist (and since Knex remembers which migration files have been executed, this shouldn't cause any problems later on).

**Comment by ccmsi** [comment]
after some googling i decided to give it a try to modify 20191126194600_Datastructure.js which seems to give me some progress. the change is such that:

exports.up = function(knex) {
  return Promise.all([
            knex.schema.createTable('users', function(usersTable) {
              // Primary Key
              usersTable.increments();
              // Data
...
              usersTable.timestamp('created_at').notNullable().defaultTo(knex.fn.now());
            }),
            knex.schema.createTable('mapping_schema', function(mappingTable) {
...
...
              aliasTable.timestamp('create_date').notNullable().defaultTo(knex.fn.now());
            })
        ]);
};

exports.down = function(knex) {
  return Promise.all ([
    knex.schema.dropTableIfExists( 'mapping_schema' ),
...
    knex.schema.dropTableIfExists( 'users' )
    ]);
};

with these changes

knex --debug migrate:latest
gets into producing  create table statements, however still does not complete as it runs into

migration file "20191126194600_Datastructure.js" failed
migration failed with error: create table "agent_location_session" ("id" serial primary key, "guid" uuid, "gid" integer not null, "host" varchar(250) not null default '127.0.0.1', "port" integer not null default '8080', "protocol" varchar(50) not null default 'log', "path" varchar(250) not null default '/api/search', "node" varchar(100) not null default 'testnode', "type" varchar(200) not null default 'type', "create_date" timestamptz not null default CURRENT_TIMESTAMP, "expire_date" timestamptz not null default 'CURRENT_TIMESTAMP86400', "active" integer not null default '1') - date/time value "current" is no longer supported

which i guess will be fixable

**Comment by ccmsi** [comment]
aboce timestamp error refers to:
"expire_date" timestamptz not null default CURRENT_TIMESTAMP86400,

and at least completes if changed to:
"expire_date" timestamptz not null default CURRENT_TIMESTAMP,

**Comment by abv** [comment]
I ran into the same problems yesterday/today. The timestamp and migrate scripts issues should both be resolved by https://github.com/sipcapture/homer-app/commit/8942e8ecfd7fadfad0c9ff3964a773b62b3f898c

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.8
https://github.com/sipcapture/heplify-server/releases/tag/1.14

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.12
