### ISSUE TITLE
Fix version of the Datastructure.js file

### ISSUE THREAD

**Issue by hbokh** [sipcapture/homer-app#227]
When starting todays latest homer-app container image (`Homer 7.7.004`)

```
# docker images
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
sipcapture/homer-app   server              bd37049ba257        19 hours ago        653MB
```

we get this error:

```
homer-webapp    | Error: The migration directory is corrupt, the following files are missing: 20190401143156_Datastructure.js
```

Our workaround: enter the container; cd into `/app/migrations`; run `cp 20191126194600_Datastructure.js 20190401143156_Datastructure.js`; `cd ..` and run `knex migrate:latest` things are OK.

Can this please be fixed permanently?
Or is there another way to get around this?

**Comment by adubovikov** [comment]
we have migrated to homer-app-go. Please take look at this

**Comment by lmangani** [comment]
nodejs app and knex are decommissioned. Please migrate to the new GO homer-app and feel free to open new issues if you experience glitches. Thanks!
