### ISSUE TITLE
Homer Logo/Link not returning to dashboard

### ISSUE THREAD

**Issue by farmorg** [sipcapture/homer-app#229]
Fresh install of 7.7 hom7-prom-all

1. Login using default admin account
2. Perform a search with no filters and results container set to default
3. Results are displayed in the results page
4. Click the Homer logo top left (expect to return to dashboard)
5. A page with the black dashboard header but otherwise blank.

HTH
Mark.

<img width="471" alt="Screenshot 2020-01-09 at 13 56 47" src="https://user-images.githubusercontent.com/22026604/72073503-f6f05080-32e7-11ea-974f-4bd7833017f2.png">

<img width="1413" alt="Screenshot 2020-01-09 at 13 54 35" src="https://user-images.githubusercontent.com/22026604/72073423-c5778500-32e7-11ea-8445-b08dd5366c24.png">

_Originally posted by @farmorg in https://github.com/sipcapture/homer7-docker/issues/54#issuecomment-572573149_

**Comment by adubovikov** [comment]
it has been fixed already.
