### ISSUE TITLE
FLOW messages out of order

### ISSUE THREAD

**Issue by kpribic** [sipcapture/homer-app#231]
When SIP messages are recorded in the same millisecond they may appear out of order when rendered in as ladder diagram (flow). Correct ordering could be achieved by using timeUseconds property however it appears to be ordered based on timeSeconds.
Noticed first on 7.0, retested on 7.7 (7.7.001)

Example: 403 response appears to come before OPTIONS message. Same timeSeconds value but it is visible based on timeUseconds that OPTIONS came first.

![image](https://user-images.githubusercontent.com/50572561/72265882-8ade5700-361d-11ea-82de-5c3b5208dc47.png)

**Comment by lmangani** [comment]
Hi @kpribic thanks! This should have already been fixed, are you running the latest GO API?

**Comment by adubovikov** [comment]
in the go it should be fixed, since we did sort.Slice 
https://github.com/sipcapture/homer-app/blob/b0c48b9ae6019f8b89eaf38569bfba25bffcdafb/data/service/search.go#L339

**Comment by kpribic** [comment]
@adubovikov according to git blame that was changed 2 days ago, so I didn't test with that code base. My system was installed via script last friday (4 days ago)

I tried to use the latest packages today but everything fell apart, It will take some time to fix it and test again.

**Comment by kpribic** [comment]
Couldn't get homer to run properly with homer-app-1.0.1-amd64.rpm, weird bugs:
1) Won't correlate options - I just get blank popup when I click on session ID - so I couldn't retry the test.
2) When correlating regular SIP calls arrows and messages are offset to the right by about 5 cm (basically one node to the right)

Just saw there is a new release, so I'll try 1.0.5 tomorrow.

**Comment by adubovikov** [comment]
can you make a screenshot ?

**Comment by adubovikov** [comment]
can you please also share your current correlation map ?

**Comment by kpribic** [comment]
SIP call flow render offset example. also direction is weird, right to left, not sure if that is intentional :-)
![image](https://user-images.githubusercontent.com/50572561/72359660-f7755680-36ee-11ea-9ed0-e8f88aac53a1.png)

Emtpy windows example when trying to correlate OPTIONS flow
![image](https://user-images.githubusercontent.com/50572561/72359796-36a3a780-36ef-11ea-8aac-e55a9b3f2bcd.png)

Mapping is default, didn't change anything
[mapping_default_sip.txt](https://github.com/sipcapture/homer-app/files/4060118/mapping_default_sip.txt)
 (attached file)

**Comment by lmangani** [comment]
@kpribic are you familiar with the correlation mapping settings already?

**Comment by kpribic** [comment]
Unfortunately no, I'm stuck at trying to recreate functionality that our support staff is used to now with previous Homer release. WebUI bugs and lack of search across multiple homer DB instances was a definite blocker in the past, I was motivated to try again by Alexandrs promise to enhance search functionality couple of days ago :-)
I do have some plans for correlation in the future - I'd like to correlate SIP and Graylog for start and ideally do correlation based on p-charging-vector icid tag specifically.

**Comment by kpribic** [comment]
Retried with version 1.1.2 and got similar results.

**Test 1** - Correlate OPTIONS on Chrome Version 79.0.3945.117 (Official Build) (64-bit)
Result: empty windows, as in the screenshot above.
Console log: [Chrome_correlate_options_fail_console.txt](https://github.com/sipcapture/homer-app/files/4063919/Chrome_correlate_options_fail_console.txt)

**Test 2** - Correlate SIP calls on Chrome Version 79.0.3945.117 (Official Build) (64-bit)
Result: offset in flow, same as in the screenshot above.
Console log: no errors.

**Test 3** - Correlate OPTIONS on Firefox 72.0.1 (64-bit)
Result: same as chrome

**Test 4** - Correlate calls on Firefox  72.0.1 (64-bit)
Result: same as chrome

**Comment by games130** [comment]
@kpribic on homer5, i was doing p-charging-vector icid correlation - this was done by running cronjob script. 
1. If you are using heplify-server, set the AlegIDs = ["P-Charging-Vector"]
2. Now the data stored in mysql have the value icid="xxxxxx"xxxxx
3. your script will need to do some string manipulation to remove the icid so that only the value remain.
4. Then corellate CallID to the AlegIDs.

**Comment by adubovikov** [comment]
guys, can you update your homer-app ?
https://github.com/sipcapture/homer-app/releases/tag/1.1.4
the callflow should be OK now. About the transaction - need to investigatge, but let first update

**Comment by kpribic** [comment]
Call flow is better in 1.1.4
![image](https://user-images.githubusercontent.com/50572561/72446698-4f29c580-37b4-11ea-8e3b-a2d4fc3b0410.png)

I kinda expected some offset on the verticals, ideally half the size of one hostname box or something like that. I looked at homer5, there it appears that first and last vertical have fixed offset to window borders, and those in the middle are set at the middle of the appropriate hostname box.

**Comment by lmangani** [comment]
This specific visualization is highly dynamic (now it supports multiple protocols, types, etc) so there will be differences inevitably. The alignment in this case is one of the trickiest tricks and we prefer starting with this clean approach. We're not here to emulate the old Homer rather evolve it to cover a broader scope.  This being said, all improvements are super welcome, so feel free to send a PR or further document/mockup your proposal here.

**Comment by kpribic** [comment]
I understand, I just mentioned homer5 because that particular feature (vertical line offset logic) works fine. Maybe for that feature screenshot from homer5 is a good enough mockup.
Unlike, for example, vertical flow scrolling where hostnames go off screen -  this is done waaay better in homer7. I'm very happy about that scrolling part :-)

**Comment by kpribic** [comment]
> @kpribic on homer5, i was doing p-charging-vector icid correlation - this was done by running cronjob script.
> 
> 1. If you are using heplify-server, set the AlegIDs = ["P-Charging-Vector"]
> 2. Now the data stored in mysql have the value icid="xxxxxx"xxxxx
> 3. your script will need to do some string manipulation to remove the icid so that only the value remain.
> 4. Then corellate CallID to the AlegIDs.

How often do you run the cronjob on the DB? I presume you just update rows timestamped after the last run?

This seems like a common case. Maybe we should talk to @negbie to include it in heplify-server :-)

**Comment by adubovikov** [comment]
I am not 100% sure, but in the heplify-server you can add custom header extraction and populate this information and do corrleation.

**Comment by games130** [comment]
> How often do you run the cronjob on the DB? I presume you just update rows timestamped after the last run?

I run mine every 5 minute and to check the past 20min worth of calls - this is becasue the P-Charging-Vector might not be available at the very first INVITE. So after you have enough data you will need to go back in time to update the all the callID. So far with my setup my correlations seems great.. i get end-to-end call corellation (UE--SBC---P/S/I-CSCF---ATS----MGCF) -- I am on IMS network.

I have just done a PR to extract the icid value from P-Charging-Vector, once that is accepted, lets start a discuss on how we can implement this corellation out of the box.

**Comment by adubovikov** [comment]
in the Homer7 you can do correlation on any message and not only first
INVITE and not only on INVITE.....

**Comment by kpribic** [comment]
@adubovikov could you please change the default orientation of the first arrow (first message between two nodes)? 
Now it points right-to-left and it's really weird because the whole flow is read left-to-right.
Noted with red in screenshot:
![image](https://user-images.githubusercontent.com/50572561/72539429-9466f980-387f-11ea-917b-23143c242fc8.png)

**Comment by lmangani** [comment]
@kpribic the orientation depends on the package source/destination and the first displayed package is probably NOT the invite. What's above it? That's the issue.

**Comment by adubovikov** [comment]
@kpribic fixed in 
https://github.com/sipcapture/homer-app/commit/1da5bbae6ec52d0a50650100a1f094b46152d7cb

**Comment by kpribic** [comment]
@lmangani INVITE was the first message, I think it was a bug. Anyways: tested with latest release, arrow orientation is sensible now thanks to @adubovikov fix

Now all that remains as open issue in this thread is lack of flow correlation on SIP DEFAULT, or specifically OPTIONS messages.

**Comment by adubovikov** [comment]
we will provide today couple changes, so, please wait

**Comment by adubovikov** [comment]
please take the new package and test it

**Comment by kpribic** [comment]
Flow doesn't render for OPTIONS messages.

# ./homer-app -version
VERSION: 1.1.6

![image](https://user-images.githubusercontent.com/50572561/72712557-9379e480-3b6b-11ea-92b4-af05e64d4e0b.png)

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.8

**Comment by kpribic** [comment]
Works now!
