### ISSUE TITLE
Which one to use? NodeJS or GO?

### ISSUE THREAD

**Issue by kevin-olbrich** [sipcapture/homer-app#232]
Hi!

I noticed that a lot of changes were made to homer-app.
The current version seems to be very new and a replacement to the NodeJS version.

Which one should I use if I want to replace my old kamailio based setup?

Kind regards
Kevin

**Comment by lmangani** [comment]
Hi Kevin,

You should install `homer-app` and `heplify-server` on top of `postgres` to get a basic HOMER 7.7 stack. In tandem, they replace all the UI and Capture Server functionality, removing the need for any 3rd party element. In addition you can connect them to either `prometheus` or `influxdb` for timeseries and `loki` for logs to both components.

We are upgrading the installers and components, but you can already find full configuration examples in our docker containers as a reference (without necessarily using them) while we get this done.

I hope this helps! Feel free to chain further questions

**Comment by kevin-olbrich** [comment]
Hi!

Thanks for your prompt reply!
We have multiple locations but would like to see them in one interface while making sure, all locations still record data if the VPN connection is lost.

I would like to set up a heplify-server in each location with a local database and configure the frontend to connect to n databases. In homer 5, this was very simple - in webapp_config.json I only found one entry.

Thank you again.

**Comment by lmangani** [comment]
The nodejs version of the API is now decommissioned and fully replaced by the GO version, which also includes the Javascript frontend code for the User-Interface. We'll publish instructions on building a "soft-cluster" or star connect system like the previous in the upcoming weeks.

**Comment by kevin-olbrich** [comment]
I'm talking about the GO version:
https://github.com/sipcapture/homer-app/releases/tag/1.0.3

The deb file contains a webapp_config.json.

> We'll publish instructions on building a "soft-cluster" or star connect system like the previous in the upcoming weeks.

Does this mean it's not yet suported or just not documented?
I am a software developer (neither nodejs. nor go), missing docs are fine, some hints where to look at would already help me.

I did some research in the code but did not find multi-db support. As my go skills suck, it might be a fail on my side.

**Comment by lmangani** [comment]
@kevin-olbrich standby for an extended config example. We're pushing things out of the oven as we speak so it shouldn't be long.

**Comment by kevin-olbrich** [comment]
Can I use this repo instead of building the app myself?
https://packagecloud.io/qxip/sipcapture

Or, is there a reason not to use it?

I am building images using CI, pulling apps directly from a repo is easier to track.

**Comment by lmangani** [comment]
Absolutely! Just be aware, the package generation and push it not yet fully automated so it might lag behind the master
