### ISSUE TITLE
Export pcap/text doesn't work

### ISSUE THREAD

**Issue by kpribic** [sipcapture/homer-app#235]
Export pcap results in empty pcap file.
Export to text results in empty text file.
Tested on current master, latest chrome, exporting correlated SIP call. Same behavior for report and widget display.

![image](https://user-images.githubusercontent.com/50572561/72599469-09830f00-3912-11ea-8594-08b045ffdc8b.png)

**Comment by adubovikov** [comment]
please check F12 web console if you return any data
also check the text export

**Comment by kpribic** [comment]
Text export empty as well, console doesn't show anything.
![image](https://user-images.githubusercontent.com/50572561/72600011-19e7b980-3913-11ea-932e-0b368667bba9.png)

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.8

**Comment by kpribic** [comment]
Same behavior as before.

**Comment by adubovikov** [comment]
@kpribic can you activate debug in the homer-app and check if you have any exceptions ?

**Comment by kpribic** [comment]
There is one error that appears when homer starts:
`
{"level":"error","msg":"Error by updating application tablepq: relation \"applications\" does not exist","time":"2020-01-23T10:38:43Z"}
`
No errors when I do pcap export (replaced my IP with 5.5.5.5 and server with 6.6.6.6):

`
**Click to correlate**
{"time":"2020-01-23T10:47:43.928102455Z","id":"","remote_ip":"5.5.5.5","host":"6.6.6.6:9080","method":"POST","uri":"/api/v3/call/report/qos","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36","status":201,"error":"","latency":19980384,"latency_human":"19.980384ms","bytes_in":303,"bytes_out":58}
{"time":"2020-01-23T10:47:44.087908423Z","id":"","remote_ip":"5.5.5.5","host":"6.6.6.6:9080","method":"POST","uri":"/api/v3/call/transaction","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36","status":201,"error":"","latency":177524708,"latency_human":"177.524708ms","bytes_in":304,"bytes_out":26493}
{"time":"2020-01-23T10:47:44.206800505Z","id":"","remote_ip":"5.5.5.5","host":"6.6.6.6:9080","method":"GET","uri":"/api/v3/advanced","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36","status":201,"error":"","latency":1052020,"latency_human":"1.05202ms","bytes_in":0,"bytes_out":496}

**click download pcap:**
{"time":"2020-01-23T10:47:49.42621241Z","id":"","remote_ip":"5.5.5.5","host":"6.6.6.6:9080","method":"POST","uri":"/api/v3/export/call/messages/pcap","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36","status":200,"error":"","latency":99052802,"latency_human":"99.052802ms","bytes_in":303,"bytes_out":24}
`

**Comment by adubovikov** [comment]
please run:
```
homer-app -create-table-db-config
``
and after
```
homer-app -version
```
after restart homer-app
and check the result

**Comment by kpribic** [comment]
This solved the error about "applications" table, but pcap/text export still doesn't work, same as before.

`$ ./homer-app -create-table-db-config
 
HOMER - creating table for the config DB [dbname=homer_config] 
 
DONE 
`

`
$ homer-app -version
VERSION: 1.1.8
`

I also ran populate just in case:
`
# ./homer-app -populate-table-db-config -force-populate                               
 
HOMER - filling tables for the config DB [dbname=homer_config] 
 reinstalling users 
 reinstalling global_settings 
 reinstalling agent_location_session 
 reinstalling hepsub_mapping_schema 
 reinstalling user_settings 
 reinstalling mapping_schema 
 reinstalling versions 
 
DONE 
`

**Comment by kpribic** [comment]
OK it appears that I can get pcap for some sessions and not for others.
When I find one session for which I can get a pcap then it's findable in search using callid. Ones I can't export (most of them) are not found when I search via Call SIP search widget by callid.
They are visible when I just search certain time period with no constraints.

Something is wrong here, I'll try to figure out what is common to calls that can't be found.

**Comment by kpribic** [comment]
After upgrading UI to 7.7.011 (prod) I think issue here is sliding relative time window.

In a nutshell if you go to export a pcap and selected time window actually contains that call then it works. Problems arise when your call is at the edge of the selected relative timewindow (eg. 30mins) and that windows slides while you have an open window. After a short period of time that pcap button doesn't work any more because that call doesn't exist within that time window.

**Comment by lmangani** [comment]
@kpribic nice catch here! let us try reproduce and fix this

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.12

**Comment by kpribic** [comment]
Confirmed, it works now!
