### ISSUE TITLE
Editing mapping schema via GUI

### ISSUE THREAD

**Issue by kpribic** [sipcapture/homer-app#236]
I tried to add a new SIP field via field GUI for call SIP mapping and after changing it my widgets broke. After I removed the changes via GUI widgets still report that configuration is broken.

![image](https://user-images.githubusercontent.com/50572561/72601608-025e0000-3916-11ea-918e-1cca2c0bbc8b.png)

In the configuration tables in DB it looks like web GUI added \n newlines after editing that field, I'm guessing that maybe broke everything because other mappings don't have them.

![image](https://user-images.githubusercontent.com/50572561/72601534-e3f80480-3915-11ea-99f2-7c949bef7c04.png)

**Comment by adubovikov** [comment]
Thank you for your report, but as I said, we are working on it right now. Please wait a bit and we will push all changes to the master and packages after testing.

**Comment by kpribic** [comment]
OK, sorry I didn't realize that this is the same problem, thought this was something unrelated.

**Comment by adubovikov** [comment]
please take the new package and test it

**Comment by kpribic** [comment]
Same behavior on 1.1.6. 
I reset the whole config DB with
`/homer-app -populate-table-db-config  -force-populate`
to have a clean starting point.
Search widget is broken on simple open and save of mapping config via gui. It looks like this in DB:

![image](https://user-images.githubusercontent.com/50572561/72712877-40ecf800-3b6c-11ea-86d9-4965f4008eff.png)

**Comment by adubovikov** [comment]
sorry, did you run heplify-server after that ?

**Comment by kpribic** [comment]
No I didn't before, but I tried now and it duplicated all entries in mapping table. Is that intentional?
Editing via GUI still breaks data even with duplicated entries.

**Comment by adubovikov** [comment]
Kosta,

please take the latest heplify-server (1.14)  and clean up the
configuration database using homer-app with --force-populate. It should
solve the problem

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.8
https://github.com/sipcapture/heplify-server/releases/tag/1.14

**Comment by kpribic** [comment]
@adubovikov New versions you refer fixed the duplicated entries issue. However editing mapping still fails, same issue as before: there is escaping in JSON in DB after saving via WebGUI.

**Comment by adubovikov** [comment]
@kpribic How did you edit that ? Did you make copy & paste from an external editor ?
If you open an existing record and just change a param and press save - will it save correct ?

**Comment by kpribic** [comment]
I just opened, did a minor edit in one field and saved.  Consequence is that both saved fields are incorrect. Same as in initial report:

> ![image](https://user-images.githubusercontent.com/50572561/72712877-40ecf800-3b6c-11ea-86d9-4965f4008eff.png)

**Comment by adubovikov** [comment]
tested on FF and Chrome - no issues 
Can you please catch in the Webconsole F12 what did you send in the PUT /api/v3/mapping/protocol/:guid ?

**Comment by kpribic** [comment]
It actually sends the escaping characters:

![image](https://user-images.githubusercontent.com/50572561/72979349-6a11c080-3dd8-11ea-9f0d-fe370570a959.png)

**Comment by adubovikov** [comment]
it should send as an array. Whats version of UI do you use ?

**Comment by kpribic** [comment]
By GUI you mean heplify-app? 1.1.8

**Comment by adubovikov** [comment]
GUI - Graphic User Interface - the version you could find in  title  of
your browser [image: Screenshot from 2020-01-23 14-33-21.png]

**Comment by adubovikov** [comment]
![Screenshot from 2020-01-23 14-33-21](https://user-images.githubusercontent.com/4513061/72988910-8409ce00-3ded-11ea-820a-16db37b4e977.png)

**Comment by kpribic** [comment]
7.7.004(prod)

**Comment by adubovikov** [comment]
shall I tell you to upgrade ? :-) or you know already ? 
https://github.com/sipcapture/homer-app/releases/tag/1.1.8
or use or package cloud - they have correct packages as well

**Comment by kpribic** [comment]
Yeah, I figured out I should upgrade :-D. I'll install the package.

I was just trying to figure out if it was part of homer-app or not because the system was initially setup by your script and I was unsure why this wasn't upgraded when I upgraded homer-app.

Probably because last time I just copied the binary an thought that is it :-/. Bravo me.
So if I understand correctly UI is actually content of /usr/local/homer/dist?

**Comment by kpribic** [comment]
So.... that was it. Editing works now. :-) Thanks @adubovikov !

Maybe it wouldn't be a bad idea to sync UI versioning with homer-app in some way.
I wouldn't have known anything was wrong if you didn't tell me that exact version of UI to expect and chrome cache (in this case) loaded old version of UI.

**Comment by lmangani** [comment]
@kpribic the `homer-ui` is already bundled in each `homer-app` build, so you can't go wrong when using the latest packages (or latest homer-ui build) either

**Comment by kpribic** [comment]
Yes, that is clear now. :-)

**Comment by adubovikov** [comment]
the chrome cache will not work in this case because we have new md5
extensions for each new build :-) Just FYI
