### ISSUE TITLE
Incomplete data inserted from heplify client to Homer7

### ISSUE THREAD

**Issue by donweasel** [sipcapture/homer-app#238]
Hello,
i have successfully able to insert data from a Centos6 / FreeSwitch 1.4 to HOMER7 using heplify client but the data seems to be incomplete, attached some logs.

this is the command and running from the FreeSwitch server
./heplify -i any -pr 5060-5080 -hs 192.168.2.222:9060

homerui_2 happens when i try to click on any of the ID so show the graphics 

![homerui_2](https://user-images.githubusercontent.com/25114110/72731972-1cdce700-3b6b-11ea-82c0-177d4946c111.JPG)
![homerui_1](https://user-images.githubusercontent.com/25114110/72731973-1cdce700-3b6b-11ea-82ac-2f12a817e9c9.JPG)
[homer7_1.log](https://github.com/sipcapture/homer-app/files/4086481/homer7_1.log)

**Comment by donweasel** [comment]
any one?

**Comment by adubovikov** [comment]
a new update is coming....

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.8

**Comment by adubovikov** [comment]
https://github.com/sipcapture/heplify-server/releases/tag/1.14

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.12

**Comment by donweasel** [comment]
Thanks ill try it and let you know :)

**Comment by adubovikov** [comment]
https://github.com/sipcapture/heplify-server/releases/tag/1.15

**Comment by adubovikov** [comment]
any updates ?

**Comment by donweasel** [comment]
Hi @adubovikov ill do it in the next hours. sorry for the delay.

**Comment by donweasel** [comment]
Hi @adubovikov ,

this is working perfectly fine !! thanks !!

**Comment by adubovikov** [comment]
Perfect. I close the ticket
