### ISSUE TITLE
utf-8-validate version 4.0.0 is not supported

### ISSUE THREAD

**Issue by NinoFares** [sipcapture/homer-app#239]
Hi,

utf-8-validate on version < 4 is not supported anymore, i try it with 5.0.2 (the lastest version) and it's work with it.

https://github.com/sipcapture/homer-app/blob/cbf95c5390e4472e35ff7aae02be4989c7b69205/package.json#L59

**Comment by lmangani** [comment]
Hi @NinoFares - We no longer use nodejs for the backend. Please upgrade to the latest swap-in node-app using a binary release or a package and you should be good to go.
