### ISSUE TITLE
logpath in system_settings being overwritten

### ISSUE THREAD

**Issue by ghmj2417** [sipcapture/homer-app#240]
I believe the following code in main.go is overwriting my log settings in webapp_config.json/system_settings.  You check if appFlags.LogPathWebApp is not empty, and it won't be because you are setting a default value, so it assigns logPath as appFlags.LogPathWebApp.  The workaround would be to add the param when starting homer-app, but I would much rather keep the config in webapp_config.json.  Are my assumptions correct why the logPath and logName aren't being set to my config values?

logPath is being set to `/usr/local/homer/log` and logName is being set to `homer-webapp.log` even though my system_settings have something different.

main.go
```
	logPath := viper.GetString("system_settings.logpath")
	logName := viper.GetString("system_settings.logname")
	logLevel := viper.GetString("system_settings.loglevel")
	logStdout := viper.GetBool("system_settings.logstdout")

	if *appFlags.LogPathWebApp != "" {
		logPath = *appFlags.LogPathWebApp
	} else if logPath == "" {
		logPath = "log"
	}

	if *appFlags.LogName != "" {
		logName = *appFlags.LogName
	} else if logPath == "" {
		logName = "webapp.log"
	}

	// initialize logger
	logger.InitLogger(logPath, logName, logLevel, logStdout)
```

webapp_config.json
```
  "system_settings": {
    "help": "Settings for HOMER logs",
    "logpath": "/var/log/homer",
    "logname" : "homer-app.log",
    "_loglevels": "can be: fatal, error, warn, info, debug, trace",
    "loglevel": "info",
    "logstdout": false
  },
```

**Comment by adubovikov** [comment]
fixed. Will be realeased today in the new package

**Comment by ghmj2417** [comment]
@adubovikov I saw the commit.  Thank you,  You may want to do the same thing for LogName as that has the same problem.

**Comment by adubovikov** [comment]
done

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.8

**Comment by ghmj2417** [comment]
Thank you very much Alexandr
