### ISSUE TITLE
Frontend needs a local homer_data database

### ISSUE THREAD

**Issue by kevin-olbrich** [sipcapture/homer-app#242]
I've set up two collector (heplify-server) nodes with local pg server and one standalone frontend host with homer-app.

Looks like homer-app references this database locally but it only exists on both remote nodes. The frontend only has homer_config.

```
root@capt-fe01 ~ # tail /usr/local/homer/log/homer-webapp.log
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"192.168.30.9\", user \"homer\", database \"homer_data\", SSL off","time":"2020-01-21T22:59:05+01:00"}
{"level":"error","msg":"pq: no pg_hba.conf entry for host \"192.168.30.9\", user \"homer\", database \"homer_data\", SSL off","time":"2020-01-21T22:59:16+01:00"}
```
192.168.30.9: Frontend server

**Comment by kevin-olbrich** [comment]
Nvm, my fault. I've not used pgsql a lot recently and forgot to allow remote pg_hba config.

**Comment by adubovikov** [comment]
Just for the future, if somebody seen such error , this means, you have to add your host to 

**/etc/postgresql/11/main/pg_hba.conf** (depends on the version of your postgres - here is 11)

something like this
```
host    all             homer_user      192.168.30.9/24         md5

```
