### ISSUE TITLE
influxdb_config is mandatory

### ISSUE THREAD

**Issue by kevin-olbrich** [sipcapture/homer-app#243]
If influxdb_config is removed from the config, the app won't start:

```
root@capt-fe01 ~ # homer-app
{"level":"error","msg":"Unsupported protocol scheme: , your address must start with http:// or https://","time":"2020-01-22T00:15:08+01:00"}
panic: failed to connect influx database

goroutine 1 [running]:
main.getInfluxDBSession(0xc000351ef0, 0xdc5b10)
	/home/shurik/go/src/github.com/sipcapture/homer-app/main.go:524 +0x396
main.main()
	/home/shurik/go/src/github.com/sipcapture/homer-app/main.go:210 +0x30a
```

Leaving the setting in it, without changing the values, works.

**Comment by lmangani** [comment]
TODO: add an 'enable' parameter to the configs to skip them entirely.

**Comment by adubovikov** [comment]
I will take a look

**Comment by adubovikov** [comment]
{"level":"info","msg":"InfluxDB functions disabled","time":"2020-01-22T12:00:32+01:00"}
{"level":"info","msg":"Prometheus functions disabled","time":"2020-01-22T12:00:32+01:00"}

**Comment by adubovikov** [comment]
so, please take the latest binary 
https://github.com/sipcapture/homer-app/blob/master/homer-app
