### ISSUE TITLE
Role-based access control

### ISSUE THREAD

**Issue by ghmj2417** [sipcapture/homer-app#246]
In HOMER 5 you have the option to assign a user as an admin or a user which then limits what they can and cannot do using the UI.  Will (or does) HOMER 7 have the same functionality?  I searched through the code for usergroup, admin, etc but couldn't find anything that prevents access to administrative settings.

**Comment by adubovikov** [comment]
in H5 only admin can edit Settings. In the H7 will be same. The rest functionality for user and admin is identical

**Comment by ghmj2417** [comment]
I want to make sure I am understanding correctly.  "In the H7 will be same." meaning this functionality isn't there yet but will be in the future?

If it is not there yet, do you know what you will name the usergroup that has limited rights? user? users?  As of now, I see user `admin` and `support` added to a usergroup called `admin`.  So going with the singular theme I would guess it would be `user`?

**Comment by lmangani** [comment]
@ghmj2417 a few advanced features are being adjusted and this is one, but the schema and the design include basic roles. As Alexandr said, there will be an admin bit determining visibility of certain options and menus for each user.

**Comment by ghmj2417** [comment]
Got it.  Not available yet, feature is coming, don't worry about `usergroup` yet.  Thank you for the responses.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/commit/e887ec4ab3a256be699cba6d01698f41764a32a6
implemented in homer-app. Tomorrow we will add this in UI to have correct visibility

**Comment by ghmj2417** [comment]
That is truly amazing how quickly you put that together.  Big kudos to you for doing that.

**Comment by lmangani** [comment]
This is now in testing phase, please contribute back your feedback and experiences to lock this down. Thanks!

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.12

**Comment by adubovikov** [comment]
I will close the ticket

**Comment by s-schumann** [comment]
I tested it and it worked well for me. Had the same issue of non-admin user not working before. Thanks!
