### ISSUE TITLE
Document database table mapping

### ISSUE THREAD

**Issue by electroniceel** [sipcapture/homer-app#247]
I have installed heplify-server-1.13 and homer-app-1.1.8 from your RPMs on CentOS 7. 
heplify-server successfully receives sip call data and stores it into the homer_data database.

I can see in the database that the data is being stored into tables with a timestamp-based table name, like hep_proto_1_default_20200122_1900. I guess this has something to with the "DBPartSip" parameter in the heplify-server configuration. I left this at the default of "1h".

When I now try to search for data in the homer-app, I can't see any results. The log of homer-app shows that  queries to tables like "hep_proto_1_default" are being made - so there is no timestamp in the table name:

"SELECT * FROM \"hep_proto_1_default\"  WHERE (create_date between $1 and $2 and data_header-\u003e\u003e'method'='INVITE') LIMIT 200"

So the homer-app seems to not know how the table names are partitioned by time. There seems to be some Mapping configuration in the settings dialog of the homer app, but it is not obvious to me how to configure it to access the tables partitioned by timestamp.

Please document how to configure this.

I also suggest to change the default configuration so that the defaults of heplify-server and homer-app match without having to change the mapping.

**Comment by lmangani** [comment]
Our platform will "partition" messages based on their session type - if your messages belongs to calls (vs registrations, keep-alives, etc) they will be in the `hep_proto_1_call` partition most likely. Try adjust your widget and search with no parameters, or reset the provisioning to get a default dashboard which does this already and let us know if it sorts it.

**Comment by electroniceel** [comment]
When looking into the database dump, I see content in the hep_proto_1_registration_<date-and-hour> and  hep_proto_1_default_<date-and-hour> tables.

When I tell the widget to search in "default", it searches in the "hep_proto_1_default" database table. But that does not exist.

To me it looks like I somehow have to tell the homer-app to add the requested date and hour to the names of the database tables. And I do not know how to do that.

It does not look to me like the problem is the different session types (like default, registration, calls,...).

**Comment by lmangani** [comment]
Just to make sure I can replicate this somehow, have you created all the databases and tables as per readme steps? https://github.com/sipcapture/homer-app#create-homer-dbs or just installed and ran the packages?

**Comment by electroniceel** [comment]
I first installed heplify-server. I manually created a database user and databases for it with the tools postgres commandline tools. Then I started heplify-server. It created a basic database schema for itself on startup. Then I began to feed data into it and made sure that the data is stored into the database.

After this was completed I began to look at homer-app. I found out that it is not working with just the database schema created by heplify server. So I ran homer-app -create-table-db-config and homer-app -populate-table-db-config. I restarted heplify-server afterwards.

Now homer-app allows logins, shows a default dashboard and so on.

But when looking at the homer-app log, I see that searches got to the wrong tables as described above.

Should heplify-server use these date-and-hour named tables or should it just use database tables without them?

**Comment by lmangani** [comment]
You definitely have the wrong mapping tables. Let us look into an easy fix - this should NOT affect new installs, only those with an older heplify-server migrating up at this time.

**Comment by electroniceel** [comment]
So for new installs, heplify-server should use these date-and-hour named tables, and homer-app automatically use them?

And homer-app using database table names without date-and-hour is just something for old installs which are migrated?

So the fault is in the mapping tables of homer-app?

**Comment by electroniceel** [comment]
Because you suggested that this problem could be caused by some database migration logic, I just stopped both services and deleted both databases. Then I recreated them and filled them with homer-app -create-table-db-config and homer-app -populate-table-db-config.

After that I restarted heplify-server and sent some new data to it. It is still stores in database tables with the date and hour in their name.

Then I restarted homer-app and logged in. Unfortunately it still searches in the "hep_proto_1_default" table and does not use the date-and-hour tablenames.

So this migration thing does not seem to depend on my order of populating the database with heplify-server before runnting the database tools of homer-app.

**Comment by lmangani** [comment]
Could you try with heplify-server-1.14 see if it makes any difference? We appreciate your effort and will surely figure this out for everyone's benefit - thanks!

**Comment by adubovikov** [comment]
now you can do this way:
homer-app -populate-table-db-config -populate-table=mapping_schema
can be also multiple parameters:
homer-app -populate-table-db-config -populate-table=mapping_schema -populate-table=global_settings

**Comment by electroniceel** [comment]
> Could you try with heplify-server-1.14 see if it makes any difference?

heplify-server-1.14 doesn't make a difference, exactly the same problem.

I'd like to know if heplify-server or homer-app is at fault here. Please tell me if the date-and-hour named tables are something heplify-server should create or not.

**Comment by electroniceel** [comment]
> now you can do this way:
> homer-app -populate-table-db-config -force-populate -populate-table=mapping_schema

this seems to be implemented in recent checkins. I do not have a build environment set up, so for now I can just test something if you build me a rpm package.

**Comment by adubovikov** [comment]
you can always download a binary from our repo: https://github.com/sipcapture/homer-app/blob/master/homer-app

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.12

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.15

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.16
