### ISSUE TITLE
Changing Protosearch "Proto" parameter doesn't work. 

### ISSUE THREAD

**Issue by AlexeyOplachko** [sipcapture/homer-app#248]
Whenever I try to switch "Proto" parameter it does reset to previous one. 
![2020-01-23_14-59-28](https://user-images.githubusercontent.com/45398541/72986570-1f507280-3df1-11ea-8096-b2ec237e7d39.gif)

**Comment by AlexeyOplachko** [comment]
Small update: It doesn't happen on new widget, only on old copy or on default one.

**Comment by RFbkak37y3kIY** [comment]
fixed in devel, waiting merge to master branch
