### ISSUE TITLE
Return from new window popup bugged

### ISSUE THREAD

**Issue by AlexeyOplachko** [sipcapture/homer-app#250]
When you're returning from a new window popup it breaks regular popup. Whenever you interact with it, it closes.
Edit: added gif
![2020-01-27_17-00-39](https://user-images.githubusercontent.com/45398541/73185362-9ace5e80-4126-11ea-9f9a-3d2d991c7892.gif)

**Comment by RFbkak37y3kIY** [comment]
fixed in devel, waiting merge to master branch
