### ISSUE TITLE
Send full loki query to backend

### ISSUE THREAD

**Issue by negbie** [sipcapture/homer-app#252]
{job="heplify-server"} 63kjpmim66o6mjbhlfo23eppbj2sksfk@UAC |= "TEEEEEST"

will just send

{"level":"error","msg":"Couldn't  query:http://127.0.0.1:3100/api/prom/query?end=1579993199000000000\u0026limit=100\u0026query=%7Bjob%3D%22heplify-server%22%7D\u0026regexp=63kjpmim66o6mjbhlfo23eppbj2sksfk%40UAC\u0026start=1579388400000000000","time":"2020-01-25T21:03:24+01:00"}

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/commit/c1272d3eff557be5a62e0305d20a5432775dfa3a
fixed
