### ISSUE TITLE
Minor cosmetic issue - flow

### ISSUE THREAD

**Issue by kpribic** [sipcapture/homer-app#255]
When using flow to display ladder diagram the list of callid on the bottom covers the arrow from the last message.

![image](https://user-images.githubusercontent.com/50572561/73173422-99406e80-4105-11ea-8509-0df248ab317b.png)

**Comment by kpribic** [comment]
It just occurred to me that I should have posted this on homer-ui git.
Should I close it and reopen there or should I leave it here?

**Comment by lmangani** [comment]
It's fine here - close enough. @RFbkak37y3kIY could you take a look at this once possible?

**Comment by RFbkak37y3kIY** [comment]
fixed in devel, waiting merge to master branch

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.15

**Comment by adubovikov** [comment]
fixed
