### ISSUE TITLE
New window popup graphical issue

### ISSUE THREAD

**Issue by AlexeyOplachko** [sipcapture/homer-app#256]
When you open "message" in new window popup, underline which shows which tab is selected is shown longer than it should be until "decoded" tab loads in. 
![2020-01-27_16-00-55](https://user-images.githubusercontent.com/45398541/73180998-13312180-411f-11ea-9265-db98353ad130.gif)
![Без имени-1](https://user-images.githubusercontent.com/45398541/73182504-d9ade580-4121-11ea-830f-34a7b637fcfd.png)

**Comment by RFbkak37y3kIY** [comment]
fixed on devel, waiting merge to master
