### ISSUE TITLE
users and user_settings model - username gorm unique or unique_index

### ISSUE THREAD

**Issue by ghmj2417** [sipcapture/homer-app#258]
Would there be any issues with column `username` in `homer_config/users` and `homer_config/user_settings` having a unique or unique_index added to it's gorm model definition?

I would assume all usernames should be unique?  As of right now, they are not.  I can add multiple users with the same username.  I am automating our build/deploy and would like to add INSERT...ON CONFLICT for the username.  (There's potential that multiple instances can be trying to update the database at the same time)

I am not 100% positive on the differences between `unique` and `unique_index` and how it will effect postgres.  I'm pretty sure `unique` still creates an index.

My workaround right now is creating a unique index after the database and tables are created.

**Comment by adubovikov** [comment]
yes, please do PR!

**Comment by adubovikov** [comment]
something like this 
https://github.com/sipcapture/homer-app/blob/master/model/applications.go#L16

**Comment by ghmj2417** [comment]
Sure.  I can do a PR.  Do we have permissions to create and push branches?

**Comment by ghmj2417** [comment]
#259

**Comment by adubovikov** [comment]
@ghmj2417 thank you, but can you please sign https://cla-assistant.io/sipcapture/homer-app?pullRequest=259 ?

**Comment by ghmj2417** [comment]
Deleted #259 and created #262
