### ISSUE TITLE
homer URL based search

### ISSUE THREAD

**Issue by kpribic** [sipcapture/homer-app#260]
Is it possible to invoke a search via URL on Homer7?
Couldn't find any documentation except a rather empty ticket about passing time via URL.

Idea is to have an external system generate a URL that a user can click and open Homer with specific time and search parameters.

**Comment by lmangani** [comment]
Yes. The "Share Link" functionality will show you an example of URL parameter mapping. Please give it a shot and let us know if this is what you're after - we definitely need help documenting this in the wiki once time allows.

**Comment by kpribic** [comment]
OK, it looks like escaped json. How do I generate the id value? Can't figure out where that came from...

Example (unescaped :-) ):
```
{
  "param": {
    "id": {},
    "location": {},
    "search": {
      "1_call": {
        "callid": [
          "720c53a0319aeb155569be822c967cb8@5.5.5.5:5060"
        ],
        "id": 124685641,
        "uuid": []
      }
    },
    "timezone": {
      "name": "Local",
      "value": -60
    },
    "transaction": {
      "call": true,
      "registration": false,
      "rest": false
    }
  },
  "timestamp": {
    "from": 1580200739039,
    "to": 1580201639039
  }
}
```

**Comment by kpribic** [comment]
Anyways doesn't work now, I get {"message":"Not Found"}, same as https://github.com/sipcapture/homer-app/issues/254
I presume fix isn't included in 1.1.12. I'll test when the new release gets out.

**Comment by adubovikov** [comment]
does the share link work?
can you please share your json request ?

**Comment by AlexeyOplachko** [comment]
Can confirm, on 7.7.012 share link does not work. Seems like fix is not yet merged to master

**Comment by kpribic** [comment]
URL as generated by Homer7 share link (I just masked host IP, no changes to the content)
`http://6.6.6.6:9080/call/result/?%7B%22timestamp%22%3A%7B%22from%22%3A1580214648301%2C%22to%22%3A1580215548301%7D%2C%22param%22%3A%7B%22search%22%3A%7B%221_call%22%3A%7B%22id%22%3A127108517%2C%22callid%22%3A%5B%221736420641-1543517928-1702904996%22%5D%2C%22uuid%22%3A%5B%5D%7D%7D%2C%22location%22%3A%7B%7D%2C%22transaction%22%3A%7B%22call%22%3Atrue%2C%22registration%22%3Afalse%2C%22rest%22%3Afalse%7D%2C%22id%22%3A%7B%7D%2C%22timezone%22%3A%7B%22value%22%3A-60%2C%22name%22%3A%22Local%22%7D%7D%7D=`

Decoded and formatted json from that request (payload between "?" and "= at the end):
```
{
  "timestamp": {
    "from": 1580214648301,
    "to": 1580215548301
  },
  "param": {
    "search": {
      "1_call": {
        "id": 127108517,
        "callid": [
          "1736420641-1543517928-1702904996"
        ],
        "uuid": []
      }
    },
    "location": {},
    "transaction": {
      "call": true,
      "registration": false,
      "rest": false
    },
    "id": {},
    "timezone": {
      "value": -60,
      "name": "Local"
    }
  }
}
```

As a response I get:
`{"message":"Not Found"}`

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.15

**Comment by adubovikov** [comment]
please let us know if you issue has been fixed

**Comment by kpribic** [comment]
Still doesn't work, when I open url I still get {"message":"Not Found"}

Decoded url:
```http://5.5.5.5:9080/call/result/?{"timestamp":{"from":1580285777186,"to":1580286677186},"param":{"search":{"1_call":{"id":133840786,"callid":["237d3a9b-e06e-420d-8d1d-dba267f6bb9b"],"uuid":[]}},"location":{},"transaction":{"call":true,"registration":false,"rest":false},"id":{},"timezone":{"value":-60,"name":"Local"}}}=```

Additionally now when I correlate a call I get a popup in the lower left corner, this didn't happen with previous release.

![image](https://user-images.githubusercontent.com/50572561/73340302-c6faf400-427a-11ea-83a0-da34ee9b3c5b.png)


Versions:
 homer-app 1.1.15
 homer-ui 7.7.014(prod)

**Comment by adubovikov** [comment]
yes, sorry, this is response in case you don't have any agents registered. Can you please take this binary and retest it ? It should hide this error
https://github.com/sipcapture/homer-app/raw/master/homer-app

**Comment by adubovikov** [comment]
You url looks good - just compared to my. If you go to any session and press the share link button, do you get any result ?

**Comment by adubovikov** [comment]
@kpribic any update ?

**Comment by kpribic** [comment]
```
/usr/local/bin/homer-app --version
VERSION: 1.1.16
```

Same:
![image](https://user-images.githubusercontent.com/50572561/73355056-82318600-4297-11ea-8cf5-4207c91409cc.png)

**Comment by adubovikov** [comment]
you are absolutely right. This is issue with / at the end. Can you please take this binary and re-test ?
https://github.com/sipcapture/homer-app/raw/master/homer-app

**Comment by kpribic** [comment]
@adubovikov it works great with the new binary!

One question before this ticket is closed: you mentioned controlling selection of multiple databases using existing widgets (https://github.com/sipcapture/homer-app/issues/222#issuecomment-574879085).

Can DB be selected via URL when doing a search or is this something that is yet to be implemented?

**Comment by adubovikov** [comment]
yes, using param.localtion.node . Please check the POST body and you will see

**Comment by kpribic** [comment]
Got it, thanks!
