### ISSUE TITLE
Wrong protocol displayed

### ISSUE THREAD

**Issue by ghmj2417** [sipcapture/homer-app#266]
When I click on a message and it shows the message for a SIP call, if the protocol used is TCP (6) it will still show UDP in the Proto column.  When I look at the message's details, I see the protocol as 6, TCP.

![homer_wrong_protocol](https://user-images.githubusercontent.com/18738647/73373613-eb5ccd80-4286-11ea-9719-0236ba7f23cf.jpg)

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-ui/commit/0fc93e14a6f266290b288a72975a8f247940cf68

fixed
