### ISSUE TITLE
LDAP auth not executing

### ISSUE THREAD

**Issue by ccmsi** [sipcapture/homer-app#267]
We were using LDAP auth in previous node edition so we do not have a fundamental LDAP issue.

With new go edition / webapp_config.json we have:
- adapted "ldap_config" to match our environment
- changed "auth_settings" to "type": "ldap"
however on login we get "OK" message in web interface but no login is executed, display stays on login page. Using packet capture / tcpdump we do not observe traffic from homer-app to ldap server.

  "ldap_config": {
    "attributes": [
      "givenName",
      "sn",
      "mail",
      "uid"
    ],
    "base": "ou=Users,...",
    "binddn": "cn=homer,...",
    "bindpassword": "ourbindpwd",
    "groupfilter": "(memberUid=%s)",
    "host": "192.168.215.48",
    "port": 389,
    "userfilter": "(uid=%s)",
    "usessl": false
  }

We see there is a groupfilter which suggests a group may have to exist, however we did not find such in the sourcecode and without traffic, it appears such a stage has not been reached yet.

Please advice.
Thanks and best regards.

**Comment by ccmsi** [comment]
just upgraded to 1.1.16 which has different behaviour... working on clarifying specifics of that.

**Comment by ccmsi** [comment]
seems it doesnt contact LDAP server either, just now responds with 401 / "incorrect password" in all cases

**Comment by adubovikov** [comment]
we are checking it

**Comment by adubovikov** [comment]
can you please download this binary and retest ? 
https://github.com/sipcapture/homer-app/raw/master/homer-app

the config has been changed a bit:
```
"ldap_config": {
    "base":  "dc=example,dc=com",
		"host":  "ldap.example.com",
		"port":   389,
    "usessl": false,
    "skiptls": true,
		"binddn": "uid=readonlysuer,ou=People,dc=example,dc=com",
		"bindpassword": "readonlypassword",
		"userfilter": "(uid=%s)",
    "groupfilter": "(memberUid=%s)",
    "admingroup": "admin",
    "adminmode": true,
    "attributes": ["givenName", "sn", "mail", "uid"]
  },
```

**Comment by adubovikov** [comment]
any updates?  :)

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.17

**Comment by ccmsi** [comment]
Login using LDAP works, going to check admin group membership.
Thanks for this superquick response.
Best regards.

Am 30. Januar 2020 20:57:28 MEZ schrieb Alexandr Dubovikov <notifications@github.com>:
>https://github.com/sipcapture/homer-app/releases/tag/1.1.17
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/sipcapture/homer-app/issues/267#issuecomment-580427340

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by ccmsi** [comment]
Works. Issue can be closed.
Best regards.

**Comment by adubovikov** [comment]
thank you for the report
