### ISSUE TITLE
/call/result display widget mappings

### ISSUE THREAD

**Issue by ghmj2417** [sipcapture/homer-app#269]
From my dashboard I create a SIP Call search widget that has a Result Container to Default.  When I search a call it takes me to the /call/result URI and displays the search results widget.  However, I noticed the columns do not associate with my mappings that I created.  For example, in my SIP call and default mappings, I hide protocol_header.protocol, protocol_header.protocolFamily, and data_header.protocol, but the display results widget shows them.

When I create a display search widget on my dashboard, it shows my correct mappings.  It's only when it uses Default that it's not using my settings.

Should the Default search widget use our mappings? Or is there a different location in the database that I can update so I don't have to manually edit the widget?

**Comment by adubovikov** [comment]
No, it uses same mapping, but once the result has been displayed - this settings became be your local settings (stored in the localstorage) and you can do any manipulation with columns as you wish (hide/display columns in the grid settings) and all will be stored locally. Just try to remove your localstorage and you will see the result that you want

**Comment by ghmj2417** [comment]
Awesome. Thank you for the explanation.
