### ISSUE TITLE
RTCP not visible in latest Homer 7.7

### ISSUE THREAD

**Issue by s-schumann** [sipcapture/homer-app#270]
Hi

I don't see RTCP stats in Homer. I use a Kamailio/rtpengine combo and both send data.

SIP is decoded properly, RTCP isn't.

It looks as follows, RTCP decoded as LOG (red) in the messages of a session:
<img width="300" alt="Screenshot 2020-01-31 at 02 16 43" src="https://user-images.githubusercontent.com/428710/73504489-dfc8ee00-43cf-11ea-8d9d-3c9c775fe24a.png">

When opening the message it looks as follows:
<img width="504" alt="Screenshot 2020-01-31 at 02 16 53" src="https://user-images.githubusercontent.com/428710/73504507-ea838300-43cf-11ea-85be-a06da209acf2.png">

In the flow it is visibly decoded as RTCP:
<img width="356" alt="Screenshot 2020-01-31 at 02 17 04" src="https://user-images.githubusercontent.com/428710/73504518-f2dbbe00-43cf-11ea-8862-493d24b70bda.png">

But nothing in the QoS tab (which I'm after):
<img width="500" alt="Screenshot 2020-01-31 at 02 17 09" src="https://user-images.githubusercontent.com/428710/73504531-fbcc8f80-43cf-11ea-943d-47752be31a70.png">

To me it seems it just needs to be decoded somewhere. Maybe a mapping is needed? 

Any pointers or hints what I'm doing wrong? Homer runs on a single machine with the latest heplify-server.

Thanks!

Best regards
Sebastian

**Comment by adubovikov** [comment]
@s-schumann can you please share the reply from /qos API ?

**Comment by adubovikov** [comment]
colros for LOG/RTCP and SIP has been fixed here:
https://github.com/sipcapture/homer-ui/commit/f53a2593f80e44b7c439ff4cc2219da9a615b74b
it will be move to master and released tonight

**Comment by s-schumann** [comment]
Hi Alexandr

The response for a successful call is here: [response.txt](https://github.com/sipcapture/homer-app/files/4143249/response.txt)

I will try it once it is released. Thanks for now!

Sebastian

**Comment by adubovikov** [comment]
@s-schumann thank you, 
looks like some limiation in the parsing of big response. We will check it tomorrow. 
Just can you check if this error you have in long calls ? If you do short one < 3 minutes, will you get same error ?

**Comment by s-schumann** [comment]
@adubovikov Yes, same error for a short call: [short_response.txt](https://github.com/sipcapture/homer-app/files/4144614/short_response.txt)

It does also not matter if the other end is a phone or a gateway - always same result.

Thx, Sebastian

**Comment by adubovikov** [comment]
the issue has been found. Fixing and will be pushed soon

**Comment by RFbkak37y3kIY** [comment]
fixed into devel branch, waiting merge to master
https://github.com/sipcapture/homer-ui/commit/e16aa315beb029874c9d22a533b2c86af5f9d503

**Comment by s-schumann** [comment]
Hi 

Thank you. It's better but not fully working yet when testing.

I see this now in the list:
<img width="384" alt="Screenshot 2020-02-03 at 16 37 13" src="https://user-images.githubusercontent.com/428710/73693047-cd9fc600-46d5-11ea-9277-1728e81f4d84.png">

And this in the QoS tab:
<img width="1078" alt="Screenshot 2020-02-03 at 16 37 21" src="https://user-images.githubusercontent.com/428710/73693058-d1cbe380-46d5-11ea-8dc9-cc768022903e.png">

However QoS tab is empty and when selecting packet in the list view I no longer see the JSON but a spinning wheel.

The console shows this error:
[error.txt](https://github.com/sipcapture/homer-app/files/4150343/error.txt)

Thanks for checking.

Sebastian

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.20

**Comment by s-schumann** [comment]
All seems to work now. Thank you very much!

**Comment by adubovikov** [comment]
Perfect. Did you install it from package ?

**Comment by s-schumann** [comment]
Last time I compiled it from homer-ui and updated dist manually, but for verification now I installed it [freshly from the master of homer-app](https://gist.github.com/s-schumann/eaa221c938795d1d3495139ecc6a54b4) and it worked.

**Comment by adubovikov** [comment]
does it now include .gz files only ?

**Comment by s-schumann** [comment]
Yes, all .js files are .gz only.

```bash
admin@ip-172-31-42-57:~$ ls /usr/local/homer/dist/
3rdpartylicenses.txt  favicon.ico  main.27650fc9196cfe522e61.js.gz           polyfills.80273fb0fd77f19997e1.js.gz  scripts.a9cbc0c927d8887e906b.js.gz
assets                index.html   polyfills-es5.1f216a5b81ce3a04172c.js.gz  runtime.a8ef3a8272419c2e2c66.js.gz    styles.854a2e365ddb131f659e.css
```

**Comment by adubovikov** [comment]
great, in this case it should load and work couple times quicker :-)

**Comment by s-schumann** [comment]
Indeed the time until I'm logged into the first screen already with the search widget is notably faster! Really good job. I used to use Homer 5 in a previous project and after some initial obstacles I really like the new version a lot.

**Comment by adubovikov** [comment]
thank you! Very glad that you like it!
