### ISSUE TITLE
Protosearch LOG-default no filters

### ISSUE THREAD

**Issue by AlexeyOplachko** [sipcapture/homer-app#272]
If you select "LOG - default" as search type in protosearch it shows two default filters(Result container and query size) and two empty filters. ![chrome_2020-02-04_14-49-13](https://user-images.githubusercontent.com/45398541/73746309-94129d80-475d-11ea-8a78-c4aaf6c89f78.png)
![chrome_2020-02-04_14-49-55](https://user-images.githubusercontent.com/45398541/73746328-9ecd3280-475d-11ea-91ce-b023ef094dc7.png)

**Comment by adubovikov** [comment]
fixed https://github.com/sipcapture/homer-app/commit/a89794421ae8371d1cb205ebd55cd4a32cb5b8c1
