### ISSUE TITLE
loki, grafana, prometheus settings

### ISSUE THREAD

**Issue by ghmj2417** [sipcapture/homer-app#273]
I see two different places where loki, grafana, and prometheus settings are stored.  First, when populating homer_config, I see a table `global_settings` which gets populated with static data by `migration/migration.go`.  Second, the webapp_config.json file has settings for each of those items (except grafana). 

Which location is used when homer-app needs to reference those services?  If it's the Db, are you going to provide a way for us to push customized values when initializing the database/tables?

**Comment by adubovikov** [comment]
@ghmj2417 these are different settings:
settings for Loki, Influx, Promethues are in webapp_config.json
You can override settings for Prometheues and Influx using Advanced Settings - in this case in the request UI will send a "contact host"
settings for Grafana - in the Advanced settings and it has been inserted by init and migration

**Comment by ghmj2417** [comment]
I'm confused.

Loki is in both and the db and webapp_config have the host parameter.  So which one is used?
What's the purpose of storing it in the Db, if the webapp_config (which I can customize) is available?

Db - global_settings table
UI / Settings / Advanced:
Data: `{"host":"http://loki:3100"}`

webapp_config.json:
```
"loki_config": {
  "help": "Settings for LOKI Database (optional)",
  "user": "admin",
  "pass": "admin",
  "host": "http://127.0.0.1:3100",
  "api": "api/prom"
}
```

**Comment by lmangani** [comment]
This should allow for using db settings in simple setups as well as overriding or extending them via the `homer-app` api settings for specific purposes or to distribute configurations to a cluster formation. We should document the priority and or requirement of each in more detail to make this transparent in the settings page.

**Comment by ghmj2417** [comment]
What I am gathering is that you would like to use the Db as the preferred location for storing that info which makes sense.  But for a user to customize the settings upon database initialization, they have to update the Db record after initialization, or go into the UI and update it.  That correct?

I just need to know which one takes precedent so I can update my build scripts appropriately.  Right now, I am confused why both exist and the purposes they serve.

**Comment by ghmj2417** [comment]
I'll go ahead and close this.
