### ISSUE TITLE
AG-Grid "Select all" button

### ISSUE THREAD

**Issue by AlexeyOplachko** [sipcapture/homer-app#276]
"Select all" button should behave like in [AG-Grid example. ](https://www.ag-grid.com/example-runner/angular.php?section=javascript-grid-selection&example=header-checkbox-entire-set&generated=1&grid=%7B%22noStyle%22%3A0%2C%22height%22%3A%22100%25%22%2C%22width%22%3A%22100%25%22%2C%22enterprise%22%3Anull%7D)
So, same checkmark as individual rows, and `indeterminate_check_box` Material icon when only some of the rows are selected

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-ui/commit/5fd21be297bfc2f5e254594a60cf2e20a114bf10
