### ISSUE TITLE
Alias port can't be 0

### ISSUE THREAD

**Issue by kpribic** [sipcapture/homer-app#277]
When I try to configure Alias port via webGUI to value 0, expecting it to ignore port, it fails with error:
![image](https://user-images.githubusercontent.com/50572561/74023156-3d94a180-499f-11ea-91ea-7e4c91a0b711.png)

Ignoring port value is required if aliases are to work for TCP as SIP transport due to ephemeral port usage.

homer-app 1.1.21
UI 7.7.021(prod)

**Comment by kpribic** [comment]
Also tried with empty port field, throws a different error but still doesn't work.

**Comment by adubovikov** [comment]
working on it. As a temporaly solution - delete the record and create a new one with port 0. The issue only in editing

**Comment by adubovikov** [comment]
fixed in 1.1.22
