### ISSUE TITLE
How do mappings work?

### ISSUE THREAD

**Issue by kpribic** [sipcapture/homer-app#278]
I've been playing around with correlation mappings and I have a couple of questions.
For start let's assume this topology:

![image](https://user-images.githubusercontent.com/50572561/74034756-35e1f680-49b9-11ea-85b1-2f9dfd747354.png)

**1. Correlation attempt # 1** - to connect all following dialogs with the first dialog I need to check if X-CID field in some dialog match my selected call-ID 1.
This would be something like:
```
    {
        "source_field": "data_header.callid",
        "lookup_id": 1,
        "lookup_profile": "call",
        "lookup_field": "data_header->>'X-CID'",
        "lookup_range": [
            -300,
            200
        ]
    }
```
This works over one B2B didn't try across multiple B2Bs.

**2. Correlation attempt # 2** - in order to look back based on X-CID i need a rule to find dialogs with the same X-CID and add the first dialog that has Call-ID same as X-CID 

```
   {
        "source_field": "data_header.X-CID",
        "lookup_id": 1,
        "lookup_profile": "call",
        "lookup_field": "data_header->>'callid'",
        "lookup_range": [
            -300,
            200
        ]
    }
```
This will find first dialog. However to find all **other** dialogs that have same X-CID i would need a separate rule to connect them first:

```
    {
        "source_field": "data_header.X-CID",
        "lookup_id": 1,
        "lookup_profile": "call",
        "lookup_field": "data_header->>'X-CID'",
        "lookup_range": [
            -300,
            200
        ]
    }
```

This doesn't work well. I do get INVITE messages from all dialogs, but ONLY INVITEs -  I'm missing other messages in those dialogs. Only dialog that is complete is the one I clicked on to start correlating. Probably I'm missing a step where all Call-IDs are collected from found INVITE messages based on a given X-CID and second round of searching is done based on that.

If I select all the relevant INVITE messages in the Search widget manually then I get all the messages for all dialogs in flow.

**Questions:**
1. Is this the right way to think about this problem at all? 
2. Is there some way to tell the correlating engine to do the second round of Call-ID collecting?
3. Does the order of mapping rules in the config file matter?

**Comment by lmangani** [comment]
Hi @kpribic 

I would actually start by configuring `heplify-server` to extract the value for correlation:
```
# AlegIDs         = ["X-CID"]
```
This should progress the situation forward most likely requiring no other changes - if that's not the case, let us know and we'll drill into the mapping aspect.

**Comment by kpribic** [comment]
Do Correlation ID and Session ID have some special status compared to other fields?

OK, I'll remap CorrelationID and try again. Currently it's not stable: sometimes it's icid-value and sometimes x-cid, depending where in the flow you click.
Of course I wanted to make it work both ways :imp:

**Comment by lmangani** [comment]
perhaps you can try configure multiple correlation headers in order of priority?
```
# AlegIDs         = ["X-CID", "X-ICID-WHATEVER"]
```

**Comment by adubovikov** [comment]
in worse case, just make a multiple step for same HEP ID: first for
correlation_id, second for a custom header. At the end it will collect all
"callid" and do big query.

Wbr,
Alexandr

**Comment by kpribic** [comment]
> in worse case, just make a multiple step for same HEP ID: first for
> correlation_id, second for a custom header. At the end it will collect all
> "callid" and do big query.

That's exactly what I tried and it didn't work. Custom rule for correlation collected all the right INVITEs in the topology shown in the first post but didn't collect all the other messages in those dialogs.

I'll try to figure out a way to generate those scenarios in pcap with dummy numbers

**Comment by adubovikov** [comment]
Here the block that does the correlation:
https://github.com/sipcapture/homer-app/blob/master/data/service/search.go#L558-L627
if you can find the issue - please let us know.

**Comment by kpribic** [comment]
@adubovikov sorry for the delay, my postgres crashed and I spent a whole day trying to figure out what is a "systems" database before I looked at your latest commits.

OK, back to correlation - it appears to me that there is no "last" call id query for all found dialogs.
I think this test proves it:
I clicked on a message that has:
- callid = 195314e32b1f45a4277a505873c1d189
- X-CID = SDcs48b01-390a50c9ce728c88ee162fd69ebb07c9-ctvvfv3

This resulted in queries:

```
2020-02-11 09:28:44.682 UTC [44496] LOG:  statement: SELECT * FROM "global_settings"  
2020-02-11 09:28:44.682 UTC [44495] LOG:  execute <unnamed>: SELECT * FROM "mapping_schema"  WHERE (hepid = $1 and profile = $2)
2020-02-11 09:28:44.682 UTC [44495] DETAIL:  parameters: $1 = '1', $2 = 'call'
2020-02-11 09:28:44.683 UTC [44496] LOG:  statement: SELECT * FROM "alias"  WHERE (status = true)

################ this is query based on callid of the message I clicked on
2020-02-11 09:28:44.684 UTC [44915] LOG:  execute <unnamed>: SELECT * FROM "hep_proto_1_call"  WHERE (sid in ($1) and create_date between $2 and $3)
2020-02-11 09:28:44.684 UTC [44915] DETAIL:  parameters: $1 = '195314e32b1f45a4277a505873c1d189', $2 = '2020-02-11 09:10:56+00', $3 = '2020-02-11 09:25:56+00'

################ this is query based on mapping, searching for messages with same x-cid
2020-02-11 09:28:44.685 UTC [44497] LOG:  execute <unnamed>: SELECT * FROM "hep_proto_1_call"  WHERE (data_header->>'X-CID' in ($1) and create_date between $2 and $3)
2020-02-11 09:28:44.685 UTC [44497] DETAIL:  parameters: $1 = 'SDcs48b01-390a50c9ce728c88ee162fd69ebb07c9-ctvvfv3', $2 = '2020-02-11 09:05:56+00', $3 = '2020-02-11 09:29:16+00'

############# missing query for all call-ids in all found dialogs at the end

```


Only mapping configured is:
```
[
    {
        "source_field": "data_header.X-CID",
        "lookup_id": 1,
        "lookup_profile": "call",
        "lookup_field": "data_header->>'X-CID'",
        "lookup_range": [
            -300,
            200
        ]
    }
]
```

**Comment by adubovikov** [comment]
just do this way
```
[
 {
        "source_field": "data_header.callid",
        "lookup_id": 1,
        "lookup_profile": "call",
        "lookup_field": "data_header->>'X-CID'",
        "lookup_range": [
            -300,
            200
        ]
},
{
        "source_field": "data_header.X-CID",
        "lookup_id": 1,
        "lookup_profile": "call",
        "lookup_field": "data_header->>'callid'",
        "lookup_range": [
            -300,
            200
        ]
    },
   {
        "source_field": "data_header.X-CID",
        "lookup_id": 1,
        "lookup_profile": "call",
        "lookup_field": "data_header->>'X-CID'",
        "lookup_range": [
            -300,
            200
        ]
    }
  ]
```

**Comment by adubovikov** [comment]
anyhow if you do this select:
```
SELECT sid FROM "hep_proto_1_call"  WHERE (data_header->>'X-CID' in ('SDcs48b01-390a50c9ce728c88ee162fd69ebb07c9-ctvvfv3') and create_date between '2020-02-11 09:05:56+00' AND '2020-02-11 09:29:16+00');
```

do you see all callids ?

**Comment by kpribic** [comment]
> ```
> SELECT sid FROM "hep_proto_1_call"  WHERE (data_header->>'X-CID' in ('SDcs48b01-390a50c9ce728c88ee162fd69ebb07c9-ctvvfv3') and create_date between '2020-02-11 09:05:56+00' AND '2020-02-11 09:29:16+00');
> ```
Yes, I get call IDs from those INVITEs that are correlated without other messages in those dialogs (shown twice because they go through proxy):
195314e32b1f45a4277a505873c1d189
195314e32b1f45a4277a505873c1d189
**6cb9716a1c7c77c56df82cd0725ce525**
**6cb9716a1c7c77c56df82cd0725ce525**

Regarding your proposal with additional mapping (callid->xcid and xcid->callid), that is exactly what I did in the first post of this thread. That won't work because there are calls that have callid that doesn't correspond to any xcid (as shown in picture in the first post). They need to be found via x-cid. 
This is what DB queries look like with the mapping you proposed:

```
2020-02-11 11:36:56.353 UTC [44496] LOG:  execute <unnamed>: SELECT * FROM "mapping_schema"  WHERE (hepid = $1 and profile = $2)
2020-02-11 11:36:56.353 UTC [44496] DETAIL:  parameters: $1 = '1', $2 = 'call'

2020-02-11 11:36:56.356 UTC [44495] LOG:  statement: SELECT * FROM "alias"  WHERE (status = true)
2020-02-11 11:36:56.357 UTC [44497] LOG:  execute <unnamed>: SELECT * FROM "hep_proto_1_call"  WHERE (sid in ($1) and create_date between $2 and $3)
2020-02-11 11:36:56.357 UTC [44497] DETAIL:  parameters: $1 = '195314e32b1f45a4277a505873c1d189', $2 = '2020-02-11 09:10:56+00', $3 = '2020-02-11 09:25:56+00'
2020-02-11 11:36:56.358 UTC [44490] LOG:  statement: COMMIT

2020-02-11 11:36:56.359 UTC [44915] LOG:  execute <unnamed>: SELECT * FROM "hep_proto_1_call"  WHERE (data_header->>'X-CID' in ($1) and create_date between $2 and $3)
2020-02-11 11:36:56.359 UTC [44915] DETAIL:  parameters: $1 = '195314e32b1f45a4277a505873c1d189', $2 = '2020-02-11 09:05:56+00', $3 = '2020-02-11 09:29:16+00'

2020-02-11 11:36:56.676 UTC [44497] LOG:  execute <unnamed>: SELECT * FROM "hep_proto_1_call"  WHERE (data_header->>'callid' in ($1) and create_date between $2 and $3)
2020-02-11 11:36:56.676 UTC [44497] DETAIL:  parameters: $1 = 'SDcs48b01-390a50c9ce728c88ee162fd69ebb07c9-ctvvfv3', $2 = '2020-02-11 09:05:56+00', $3 = '2020-02-11 09:29:16+00'

2020-02-11 11:36:56.678 UTC [44915] LOG:  execute <unnamed>: SELECT * FROM "hep_proto_1_call"  WHERE (data_header->>'X-CID' in ($1) and create_date between $2 and $3)
2020-02-11 11:36:56.678 UTC [44915] DETAIL:  parameters: $1 = 'SDcs48b01-390a50c9ce728c88ee162fd69ebb07c9-ctvvfv3', $2 = '2020-02-11 09:05:56+00', $3 = '2020-02-11 09:29:16+00'
```

Homer never actually asks for all messages with call-ID **6cb9716a1c7c77c56df82cd0725ce525**

**Comment by adubovikov** [comment]
but this means, the X-CID exist ONLY in the INVITES. Did I understand you correct ?

**Comment by kpribic** [comment]
Yes, exists only in INVITEs. Isn't this usual way to do it?

I don't think it's even possible to add headers to other messages on BTBUAs like Asterisk.

**Comment by adubovikov** [comment]
so, these are the old callids that you have to get by "correlation":
```
195314e32b1f45a4277a505873c1d189
195314e32b1f45a4277a505873c1d189
6cb9716a1c7c77c56df82cd0725ce525
6cb9716a1c7c77c56df82cd0725ce525
```
and you have them by executing SELECT manualy ?

**Comment by kpribic** [comment]
Yes this is what I got when I executed your query without changes.

Just to be clear, everything works if I search in homer by x-cid for all the invites, manually select all call-IDs by clicking the checkboxes and then correlating by clicking on one SID. I get all dialogs and all messages. Data is there, issue is just that only thing connecting all those dialogs is xcid in INVITEs.

**Comment by adubovikov** [comment]
so, take the latest binary (just uploaded to master)

and in the correlation mapping:
```
[
{
        "source_field": "data_header.X-CID",
        "lookup_id": 1,
        "lookup_profile": "call",
        "append_sid": true,
        "lookup_field": "data_header->>'callid'",
        "lookup_range": [
            -300,
            200
        ]
    },
   {
        "source_field": "data_header.callid",
        "lookup_id": 1,
        "lookup_profile": "call",
        "lookup_field": "sid",
        "lookup_range": [
            -300,
            200
        ]
    }
  ]
```
the param 
```
 "append_sid": true,
```

will add the all callid (sid) from the first lookup to an array and this array will be added to any next correlation lookups:

1. i.e. in the first lookup you will do X-CID match and will receive callid 12345. The param will activate trigger to add the callid to an array.
2. second lookup you will do by callid and the array will be concatinate to the lookup params and in this case you do search by sid and you will get ALL messages with same sid (callid = 12345) 

so, please download the binary and let us know

**Comment by kpribic** [comment]
It works! (I changed the first maping to X-CID -> X-CID in your config example, because that's the main correlating ID across dialogs)

So, if I understand you correctly, ordering of rules is really important now because call-ID discovered in one rule will be available only to mapping rules below and not rules above?

**Comment by adubovikov** [comment]
Super. Yes it goes to the chain steps: 1->2->3 and in each step you can calll append_sid to apply "sid"   of response to session correaltion array. If the array is not empty it will apply to each next lookup.

**Comment by kpribic** [comment]
OK I'll experiment with this a bit to make sure I'm not closing the ticket prematurely :)

**Comment by adubovikov** [comment]
just do it :-)

**Comment by kpribic** [comment]
I think that's it as far as I can test at the moment.
I settled at this config to cover every possible case (depending on which dialog is clicked on).

```
[
    {
       "source_field": "data_header.callid",
        "lookup_id": 1,
        "lookup_profile": "call",
        "append_sid": true,
        "lookup_field": "data_header->>'X-CID'",
        "lookup_range": [
            -300,
            200
        ]
    },
    {
        "source_field": "data_header.X-CID",
        "lookup_id": 1,
        "lookup_profile": "call",
        "append_sid": true,
        "lookup_field": "data_header->>'X-CID'",
        "lookup_range": [
            -300,
            200
        ]
    },
    {
        "source_field": "data_header.X-CID",
        "lookup_id": 1,
        "lookup_profile": "call",
        "append_sid": true,
        "lookup_field": "data_header->>'callid'",
        "lookup_range": [
            -300,
            200
        ]
    },
    {
        "source_field": "data_header.callid",
        "lookup_id": 1,
        "lookup_profile": "call",
        "lookup_field": "sid",
        "lookup_range": [
            -300,
            200
        ]
    }
]
```

**Comment by adubovikov** [comment]
@kpribic great! Thank you. @lmangani IMHO need to document it right way :)
