### ISSUE TITLE
Loki api/prom uri deprecated

### ISSUE THREAD

**Issue by ghmj2417** [sipcapture/homer-app#284]
When updating the webapp_config.json and loki param in the Db to `loki/api/v1` I get the following error message:
```
{"level":"error","msg":"Couldn't  query:http://127.0.0.1:3100/loki/api/v1/query?end=1581368140000000000\u0026limit=100\u0026query=%7Bjob%3D%22heplify-server%22%7D\u0026regexp=\u0026start=1581367840000000000","time":"2020-02-10T20:55:43Z"}
```
Per their site, [here](https://github.com/grafana/loki/blob/master/docs/api.md#get-apipromquery),
`WARNING: /api/prom/query is DEPRECATED; use /loki/api/v1/query_range instead.`

Should your query arg be changed to query_range?  Or would this break other people's Loki implementations?

**Comment by lmangani** [comment]
What version of Loki are you using?

**Comment by adubovikov** [comment]
```
{"level":"error","msg":"Couldn't  query:http://127.0.0.1:3100/loki/api/v1/query?end=1581368140000000000\u0026limit=100\u0026query=%7Bjob%3D%22heplify-server%22%7D\u0026regexp=\u0026start=1581367840000000000","time":"2020-02-10T20:55:43Z"}
```
has been fixed already - this was just debug. Please update  to 1.1.23

**Comment by ghmj2417** [comment]
Whoomp whoomp, I am running 1.1.22.  Ugh, sorry about that.  I should have searched closed issues.  I'll change to 1.1.23 and check.

**Comment by adubovikov** [comment]
but the depricated api was not fixed there

**Comment by lmangani** [comment]
I guess we need to allow further configuration to deal with the multiple versions of the LOKI API now. We'll come up with a plan in the coming days hopefully through configuration only.

**Comment by adubovikov** [comment]
let me check, i think it was allowed

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/blob/master/etc/webapp_config.json#L41

**Comment by adubovikov** [comment]
ok, this change only prefix, but looks like they change some another params. Update is comming

**Comment by lmangani** [comment]
the issue is with the `query` part preceding the parameters which becomes `query_range`

**Comment by ghmj2417** [comment]
I was using latest Loki dev build, aka using master. We can define the uri but not the query part. You are appending query whenever we search, however the new uri requires query_range instead of query. I think you guys already know this now.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/commit/448311d24da477292f66957334d1220903a15280
fixed
