### ISSUE TITLE
Protosearch: Fields changing order

### ISSUE THREAD

**Issue by AlexeyOplachko** [sipcapture/homer-app#292]
Saving settings for protosearch without changing anything reorders all selected fields in the same way as they sorted in list of inactive fields.
![2020-02-14_18-49-16](https://user-images.githubusercontent.com/45398541/74551026-1b7cbf80-4f5b-11ea-9611-9d0854dd1c3d.gif)

**Comment by adubovikov** [comment]
@RFbkak37y3kIY any updates here ?
