### ISSUE TITLE
v 1.1.27 displays v 7.7.021 in browser tab /header

### ISSUE THREAD

**Issue by ccmsi** [sipcapture/homer-app#298]

**Comment by adubovikov** [comment]
sorry ? What is your question ?

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer/wiki/Troubleshooting-Homer-7.7

**Comment by adubovikov** [comment]
Set the issue a proper way. As we wrote thousands times we couldn't read your mind!

**Comment by ccmsi** [comment]
v 1.1.27 displays v 7.7.021 in browser tab /header

nothing else there to say

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer/wiki/Troubleshooting-Homer-7.7#submit-a-bug-report

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer/wiki/Troubleshooting-Homer-7.7#version-desync--homer-app-vs-homer-ui

**Comment by ccmsi** [comment]
/opt/homer-app/dist# md5sum main.27650fc9196cfe522e61.js.gz
c28106cbebcdd65329d6f08c87caa3d9  main.27650fc9196cfe522e61.js.gz

**Comment by adubovikov** [comment]
Great! 
```
md5sum main.9b8e311ae067e85ac7cc.js.gz
09426366e9b628356c8b110ebb00e3c8  main.9b8e311ae067e85ac7cc.js.gz
```
I won!

**Comment by ccmsi** [comment]
this is v1.1.27:
https://github.com/sipcapture/homer-app/tree/be0853f3fccf4b52a8e3d38699f03c5e98b13e8b/dist which the report is about, there is no main.9b8e311ae067e85ac7cc.js.gz
i will go and check your just released v1.1.31

**Comment by adubovikov** [comment]
wait, wait,. we don't update local dist! Normaly the directory should be removed!

**Comment by ccmsi** [comment]
each version necessarily comes with its matching dist. while at it your main.9b8e311ae067e85ac7cc.js.gz also does not relate to v1.1.31 which is your current release. so atm i dont know what you are comparing with. is it a relase at all ?

**Comment by adubovikov** [comment]
the release of homer-app - and the packaging system takes homer-ui and homer-app and make a package base on the version of homer-app. The directory dist was only for tests and have to be removed. If you do manual install use always the repo homer-ui and compile the UI manualy. Read the documenation.

**Comment by ccmsi** [comment]
packaging crates a tar.gz which is published as a release and contains said components preumably  built the same way from matching versions. would there be an expectation of a different result ? if said files do not match /w ork, why are they published as a release ?

**Comment by adubovikov** [comment]
you mix two different cases. The homer-app release is a release ONLY of the homer-app and it has nothing todo with rpm/deb packages except a release tag. As I wrote above, the package will always contain the actual release of the homer-ui. If you want to install UI/APP manualy you have to build it manualy. In worse case copy the latest compiled dist from :  https://github.com/sipcapture/homer-ui/tree/master/dist/homer-ui

**Comment by adubovikov** [comment]
just updated it for you: https://github.com/sipcapture/homer-app/blob/master/README.md#manual-dist

**Comment by lmangani** [comment]
@ccmsi I'm not sure where we're going with this - the current builders for published versions use docker to compile the frontend and backend compoments and assemble them into a release derived from `homer-app` regardless of the dist contents in git.

If you do see a better way or any improvement, feel free to submit a PR or change proposal and we'll gladly consider it. Thanks for sharing your time and thoughts, its much appreciated.

**Comment by ccmsi** [comment]
i'm currently not quite sure if i understand correctly.
Whatever the correct way of creating the build, it should either match / work or not be contained in the release file.
If the dist folder in homer-app repo is a "random" instance of "homer-ui" then IMO it should be part of the homer-app repo. Actually i think in that case, it should be part stored in the homer-app repo at all and blended out with gitignore.
Maybe reference with git remote add.
I do think though that providing a release in homer-app that contains a matching dist folder is a good thing to do. ie by pulling in latest release of homer-ui in the build script.
In the end, still not quite sure i got your description correctly.
go compile it i dont think is the right advice for pulling odwn a realease. and no i'm not mixing it with an rpm or deb module.
i

**Comment by adubovikov** [comment]
@ccmsi I appologies, but did you read the link that I paste before?

https://github.com/sipcapture/homer-app/blob/master/README.md#manual-dist

**Comment by lmangani** [comment]
@ccmsi the `dist` folder is a snapshot since its built from another repository, we're not making the assumption the user will or should have all the requirements to build one necessarily, neither we do take for granted they have `docker` available to do so. It's a commodity and it gets updated as we release to lower the entry bar into custom builds for the `homer-app` components.

The problem is there is no such thing as a `matching release` as the UI and API are developed separately, and patched at different rate and intervals depending on the case. Usually the UI part gets the most updates, so we have decided to aggregate those by `homer-app` releases for now to avoid having thousands of versions online, and retaining the ability manually if/when needed.

The ultimate goal is to create a smooth process to use both so any actionable suggestions are always welcome :)

**Comment by ccmsi** [comment]
yes i did but situation remains.
there is a dist folder contained in what is *designated* as homer-app release. IMO if it is, it must be a *release*.
looking closer at homer-ui it appears to me, there are release tags, but there is no *release" asset, just source.
a git clone IMO is no release operation and nor is a build.

**Comment by ccmsi** [comment]
> The problem is there is no such thing as a matching release as the UI and API are developed separately, and patched at different rate and intervals depending on the case.

That to me reads like the opposite. Matching releases must be chosen as otherwise it wont work.

**Comment by adubovikov** [comment]
ok, looks like a valid point. We will recheck

**Comment by ccmsi** [comment]
the dist folder was added to homer-ui repo. would that not be the build result ? (cant verify atm as the build of homer-ui doesnt complete for me atm)

**Comment by adubovikov** [comment]
so, there is two ways for now: 
- we will update the dist in /homer-app during package/release of homer-app.
- we will release dist asset in /homer-ui

**Comment by ccmsi** [comment]
so yes, dist folder is produced by homer-ui build therefore should not be part of the repo and be gitignored. meaning i'd propose to undo commit 62d58a5b934ba9bace69b87b6fa8b21e1b447eb3

**Comment by ccmsi** [comment]
for homer-ui, is there consistency in the usage of branches? iE master = release,  latest= devel_release_candidate ?

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.32
homer-ui now there as a an asset. I think it will solve your issue

**Comment by ccmsi** [comment]
sort of.
i'm currently considering running a Jenkins instance for homer-ui / homer-app . the question about branch usage/mapping ie for dev/staging/prod is for that.

**Comment by lmangani** [comment]
@ccmsi if you plan on contributing back something all users can benefit, we'll be glad to help you. If this is for your exclusive usage, its a lower priority. Feel free to open a dedicated ticket for this.

**Comment by ccmsi** [comment]
plan to me is such a string word. atm i'm in the state where i believe i know what needs to be done and am willing to give it a shot. if it works out, fine. we'll probably serve back the jenkinsfiles and could feed the builds. promising something will be completed before it is i practically never do. however i did verifiably complete a couple things.
independent of that, any user or potetnial contrubutot should be able to read up the meaning of your bracnhes somewhere in your docs.

**Comment by lmangani** [comment]
@ccmsi much appreciated minus the extensive use of conditional. This is a community project, including the documentation, etc. When you get somewhere with this and if you think we can help, let us know and we'll be happy to.

**Comment by ccmsi** [comment]
great.
then let me know if there's a matching between branch names and dev/staging/prod paths

> minus the extensive use of conditional. This is a community project, including the documentation, etc
great, then evidently we understand each other although we are not always consistent in our statements
