### ISSUE TITLE
Can not login to Homer 7 beta instance

### ISSUE THREAD

**Issue by ivlovric** [sipcapture/homer-app#3]
I am unable to login using any known homer 7 frontend password combination with user "admin". 
I am getting this in browser debug/developer tools: "[ "RequestResponseInterceptor" ]
 Array [ "reponseError" ]
 Unauthorized incorrect password"

I see users in homer_config database:
id | username | partid |     email      | firstname | lastname | department | usergroup |                             hash                             |                 guid                 |          created_at           
----+----------+--------+----------------+-----------+----------+------------+-----------+--------------------------------------------------------------+--------------------------------------+-------------------------------
  1 | admin    |     10 | root@localhost | Homer     | Admin    | NOC        | admin     | $2a$10$ae6Ljlb7nEsqUdQeN.Uztu1iAbx2VeEfgZQhVQgmIpdFA38OpbYui | 11111111-1111-1111-1111-111111111111 | 2018-08-15 18:54:47.721678+02
  2 | support  |     10 | root@localhost | Homer     | Support  | NOC        | admin     | $2a$10$ae6Ljlb7nEsqUdQeN.Uztu1iAbx2VeEfgZQhVQgmIpdFA38OpbYui | 22222222-2222-2222-2222-222222222222 | 2018-08-15 18:54:47.721678+02
(2 rows)

What am I missing and what is default admin password?

Thanks and kind regards,
Ivica

**Comment by lmangani** [comment]
Hi @ivlovric ,

The default login for seven is `admin/sipcapture`
Have you installed homer-app as part of a stack or stand-alone?

**Comment by ivlovric** [comment]
Hi, @lmangani!

Thanks for your quick response.
Perfect, these credentials  work. I was following installation procedure for stack version but was unable to find default credentials anywhere so I was combining every previous homer versions passwords.

Maybe it would be convenient to include this info in installation procedure.

**Comment by lmangani** [comment]
@ivlovric glad you got around this. There's actually no real installation procedure, this is in alpha so welcome to the team and feel free to report issues you will SURE find.
