### ISSUE TITLE
Building swagger throws error

### ISSUE THREAD

**Issue by ghmj2417** [sipcapture/homer-app#301]
It was building fine with release 1.1.27 but now it's throwing an error when trying to build swagger

`operation (search): invalid route/operation schema provided`

I noticed there was a recent commit (2 days ago) to models.  Do you think this broke the build?

**Comment by aqsyonas** [comment]
@ghmj2417 should be fixed in below pull request. 

https://github.com/sipcapture/homer-app/pull/302

**Comment by adubovikov** [comment]
please reopen if needed
