### ISSUE TITLE
loki - Labels not loading, searching returns all results

### ISSUE THREAD

**Issue by ghmj2417** [sipcapture/homer-app#305]
Using homer-app 1.1.32 and homer-ui 7.7.025.

When using the Loki search widget, when typing `{` the Labels box pops up and just says loading.  It doesn't show which labels are available.  Also, when I type in `job="`, I get the `Label value for "job"` box, but doesn't show the job names.  I have tried this using Firefox 73.0.1 and Chrome 80.0.3987.116.  Both show the same symptom.

When using the Loki search widget or selecting Loki search from the call message box, if you add search parameters beyond `{job="heplify-server"}` the expected results aren't returned.  From what I can gather it is retrieving all messages.

Example: if I use the query `{job="heplify-server"} 123456` (where 123456 is the call id) I am getting a bunch of additional messages.  I took the same query `{job="heplify-server"} 123456` and put it into Grafana, I received the expected results for only that call id.

**Comment by ghmj2417** [comment]
I take that back about the query being the same for Grafana.  I used an actual Loki search expression `{job="heplify-server"} |= "123456"`.  I tried doing the same using the widget, but still didn't get the expected results.  It looks as though Loki parameter searching via homer-app isn't working.

**Comment by lmangani** [comment]
There's currently a bit of desync due to the Loki API changes. If you're running the latest version of Loki, you most likely are suffering due to this. Please standby for a fix to re-test with.

**Comment by ghmj2417** [comment]
Sounds good, thank you @lmangani

**Comment by adubovikov** [comment]
@ghmj2417 can you please update homer-app and homer-ui to the latest version. 

https://github.com/sipcapture/homer-app/releases/tag/1.1.35

**Comment by ghmj2417** [comment]
Updated.  Still the same issues.

**Comment by adubovikov** [comment]
Can you please tell your Loki's version?

**Comment by ghmj2417** [comment]
1.3.0

**Comment by alan-mc** [comment]
I have found the same issue - In Grafana Nodeexplorer - the search works.  I see in the logs filtered correctly.  Homer 7 no such luck.. :(

Nodeexplorer -  ....query="{job=\"west-01\"} |= \"1589395010.3732808\"" query_type=filter range_type=range  
Homer7 - .... query="{job=\"west-01\"}" query_type=limited range_type=range    and it does not show my filter info. 

loki - 1.4.1
homer7 - 7.7.032

Thanks for any help.

**Comment by alan-mc** [comment]
I figured out that the query will work if you remove all spaces.   example  -
{job="west-01"}|="1589490090.3762850"    - returns the filtered data...  if you have any space it fails to return as filtered and just returns all the entries in the log.

**Comment by adubovikov** [comment]
the version 1.3.0 has been released. Please install it and retest it.

**Comment by adubovikov** [comment]
Please install homer-app-1.4.0 and test again
