### ISSUE TITLE
Any chance to add expire time on returned token result.

### ISSUE THREAD

**Issue by bibace** [sipcapture/homer-app#307]
Happy with homer 7 apis so far.

However when I get token from auth endpoint,

it doesnt contain expire time. Really need it for storing the token in a caching service.

Furthermore, I still havent found any documentations about how to use Auth-Token from Homer setting.

I tried to put the token I generated to parameter Auth-Token in header, but always get

wrong JWT format error.

**Comment by adubovikov** [comment]
![Screenshot from 2020-02-24 02-09-08](https://user-images.githubusercontent.com/4513061/75123754-ade33880-56aa-11ea-95b6-277a12f609a1.png)

Auth-Token you can use for HEPSUB for an external agent
