### ISSUE TITLE
A/B leg call association seems to be broken with default settings

### ISSUE THREAD

**Issue by gedia** [sipcapture/homer-app#308]
I believe the JSON dict that is meant to allow for a-leg and b-leg association is wrong in the default installation. Here's the original:

```
    {
        "source_field": "data_header.correlation_id",
        "lookup_id": 1,
        "lookup_profile": "default",
        "lookup_field": "sid",
        "lookup_range": [
            -300,
            200
        ]
    }
```
whereas what works for me is the following:
```
    {
        "source_field": "protocol_header.correlation_id",
        "lookup_id": 1,
        "lookup_profile": "call",
        "lookup_field": "sid",
        "lookup_range": [
            -300,
            200
        ]
    }
```

Am I missing something here? Is this stanza meant for some other functionality?

**Comment by adubovikov** [comment]
thank you. Just fixed in the master

**Comment by gedia** [comment]
Looking at the diff, it still reads: data_header.correlation_id

I believe the correlation_id is located in the protocol_header column in PostgreSQL, not in the data_header column, at least in the latest schema. Am i mistaken?

**Comment by adubovikov** [comment]
:-) you are absoultely right! 
fixed
