### ISSUE TITLE
how to set data_header->method property

### ISSUE THREAD

**Issue by kpribic** [sipcapture/homer-app#314]
How can I propagate some nice title for a message so that it shows in data_header->method property that homer-ui so nicely renders in flow?

Random example would be:
![image](https://user-images.githubusercontent.com/50572561/75992229-f6df8c00-5ef7-11ea-82f3-73ee056ce0ec.png)

With data_header value:
```
{
  "node": "mynode",
  "proto": "log",
  "method": "call response"
}

```

I'm pushing logs into homer DB via hepipe.js -> heplify-server -> postgresql -> hep_proto_100_default.

As far as I can tell there is no field in HEP3 protocol that would would map to "method". I guess that heplify-server parses SIP messages for SIP method and then inserts it into db.

I remember a picture from some conference showing Janus events with nice titles, presumably that worked via method property.  Was it direct write into db bypassing heplify-server or is there some Janus table specific logic somewhere?

**Comment by lmangani** [comment]
@kpribic that's correct, the equivalent of "method" changed between protocols. 
We can change how Janus-specific things are displayed depending on our shared preferences so feel free to make a proposal or some mock-up for consideration and I'll bring it forward.

**Comment by kpribic** [comment]
Heplify server currently parses SIP messages and generates data_header jsonb values via **hardcoded** logic. In order for homer7 to be truly multiprotocol correlation engine we would need some sort flexibility for non-sip messages in terms of extracting specific values to data_header.

First use case that I tried to cover here is bridging traffic from webrtc to SIP domain and webrtc (when isn't sip) is json.

I'd propose some sort of **config file** for heplify-server to define how parsing is done for custom (json) protocols. This way it is also _much easier to get community support_ because to edit a config file you don't have to be a go expert.

**Partial support for data_header**
This would just extract method header with a fallback value

```
proto: 1000
payload_type: json
condition: janus == "event" AND plugindata.plugin == "janus.plugin.sip"
value_method: plugindata.data.result.event + " " + plugindata.data.result.code
default_value_method: "sip plugin unknown event"
```

For janus message:
```
{
  "janus": "event",
  "session_id": 5280921641799553,
  "sender": 8936267095561071,
  "plugindata": {
    "plugin": "janus.plugin.sip",
    "data": {
      "sip": "event",
      "result": {
        "event": "hangup",
        "code": 200,
        "reason": "Session Terminated",
        "reason_header": "Normal call clearing"
      },
      "call_id": "fc340d55-9d10-4ed1-85ea-961537522aa1"
    }
  }
}
```

This example includes two complications: _concatenation and boolean logic_ in selection. Not sure how complicated is that to implement. I mean it's probably possible to make a basic version without this however it would be very limiting in terms of supporting any custom protocols. Concatenation is proably optional but boolean logic most likely isn't.

Some conditions to make this work:
If any field is empty (doesn't exist) in metod part then just send empty string for that value. If whole method part is empty (or just a space in this case) after parsing - use default_method.

**Full support for data_header (proper solution)**
If we have support for method parsing then generic value parsing is not far away.
Lets say that for some reason it's also interesting to search for reason code in webrtc messages, to avoid substing matching in RAW it would be useful to have "code" value separately in data_header.

Example:

```
proto: 1000
payload_type: json
condition: janus == "event" AND plugindata.plugin == "janus.plugin.sip"
value_method: plugindata.data.result.event + " " + plugindata.data.result.code
value_code: plugindata.data.result.code
value_static_string: "my favorite janus message"
default_value_method: "sip plugin event"
```

this should result in data_header:
```
{
 "proto":"json"
 "method":"hangup 200"
 "code": "200"
 "static_string": "my favorite janus message"
}
```
As before, if value returned is empty (element doesn't exits) then it should be silently dropped from data_header.

@lmangani If we put aside this specific format of config file  (I'm sure you can think of a better one), does this external config file concept in general make sense to you?

**Comment by kpribic** [comment]
I just realized that this is the same problem as mentioned in https://github.com/sipcapture/heplify-server/issues/310#issuecomment-579185588 , meanin pipelining. For some reason I didn't connect these two issues  :-/

Now that I re-read your answer it feels like you meant a hardcoded mapping for janus as interim solution. @lmangani can you confirm if this is true? If so I could try to catch some janus messages and do a draft mapping.

**Comment by negbie** [comment]
@kpribic you could now do something like this. Run or set following flags:

./heplify-server -scriptenable -scriptengine expr -scriptfolder scripts/

Place in the scripts (or what ever folder you set as scriptfolder) a file like setmethod.expr with something like this:

GetHEPProtoType()==100 ? SetSIPHeader("Method", "your_method") : ""

This checks if HEP Prototype is 100 and if so it set's the method. Otherwise it does nothing.

**Comment by kpribic** [comment]
@negbie I was waiting for some hints/docs on how to use all these new features :-)
Is there any way to set some sort of regex that looks at some values in the packet and sets a different method depending on regex match?
For example in this Janus message I'd like to set the method to "call" while for some other message something else makes sense.
```
janus: "message"
body:
request: "call"
uri: "sip:XXX@YYYYY.com"
call_id: "dd95f6e2-924b-49ad-b2ec-9595595ed446"
autoack: false
autoaccept_reinvites: false
headers:
...
```

**Comment by adubovikov** [comment]
the version 1.3.0 has been released. Please install it and retest it.
