### ISSUE TITLE
Homer7 (7.7.031 prod) cannot handle IPv6 addresses (in flows) after first colon

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/homer-app#315]
Homer's treatment of IPv6 should not make them very long either. Perhaps most relevant is the 1st and last 16bits.

![Screenshot 2020-03-09 at 18 59 28](https://user-images.githubusercontent.com/647633/76243368-8195f300-6238-11ea-82bb-22a51fcbb92d.png)

**Comment by systemcrash** [comment]
Tried rolling back in docker to image: sipcapture/homer-app:1.1.2, without cleaning up DB or on disk files, and IPv6 labels displayed OK (though flow was a bit broken).

**Comment by adubovikov** [comment]
7.7.004 - very old. Please upgrade to the latest version

**Comment by adubovikov** [comment]
sorry, this means in the 7.7.004 - the labels are ok and in the current have broken ?

**Comment by systemcrash** [comment]
> sorry, this means in the 7.7.004 - the labels are ok and in the current have broken ?

Effectively, yes (short of nuking all data on disk to verify this, I'm sure this is the case)

**Comment by adubovikov** [comment]
please provide your ipv6 dumps

**Comment by systemcrash** [comment]
Have you a private email to which I can send?

**Comment by systemcrash** [comment]
Or a https://www.guerrillamail.com/

**Comment by adubovikov** [comment]
alexandr.dubovikov@gmail.com

**Comment by systemcrash** [comment]
OK, msg sent. You may need to check spam folder :)

**Comment by systemcrash** [comment]
Well, [this](https://github.com/sipcapture/homer-view/blob/9905979d612370790670e3864599944d4081bc64/src/app/components/detail-dialog/tab-flow/tab-flow.component.ts#L114) explains why IPv6 in the address graph is shanked.

**Comment by systemcrash** [comment]
Pushed attempted fixes to homer-ui https://github.com/sipcapture/homer-ui/pull/227

It's a damn rabbit-warren trying to find where bugs are since code is spread all over the place.....

**Comment by lmangani** [comment]
@systemcrash Thanks first and foremost for dedicating your time and helping us! You're new to the platform, and I reckon the documentation is not there, but code is not all over the place - it just takes time to get into other people's design particularly with a self-contained project like ours. HOMER is not Kubernetes or something for the masses, but rather an expression of our humble expertise we're sharing our of passion (Homer makes no income). Give it some time and hopefully things will become familiar when paired with the logic or the legacy/compatibility of our project driving certain decisions. And again thanks for your time and patch contribution, they're much appreciated - if we had more of these we'd leap ahead years at once and perhaps would have time for docs, too :)

**Comment by systemcrash** [comment]
Things are moving in the a forward direction!

I'm grateful for your continuous interaction to keep things moving forward. But I will say this: something this whole project lacks is an overall hierarchy or structural document. Perhaps even some kind of design document. A bit like the HEP PDF which is a bit out of date but for how all the data/db formats are. Another day.....

**Comment by systemcrash** [comment]
Latest homer-ui PR sipcapture/homer-ui/pull/230 also cleans up IPv4 and v6 graphs nicely, with the exception of sipcapture/homer-ui/issues/231
