### ISSUE TITLE
Homer7 (7.7.031 prod) cannot export PCAP

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/homer-app#316]
Current pcap sizes are 24 bytes. i.e. effectively empty. 

Any suggestions?

Currently viewing any flow, shows similar to this in the logs:

```
homer-webapp      | {"level":"error","msg":"GetTransactionData: We have got error:  pq: relation \"hep_proto_100_call\" does not exist","time":"2020-03-10T15:23:32Z"}
homer-webapp      | {"level":"error","msg":"GetTransactionData: We have got error:  pq: relation \"hep_proto_5_call\" does not exist","time":"2020-03-10T15:23:32Z"}
homer-webapp      | {"level":"error","msg":"GetTransactionData: We have got error:  pq: relation \"hep_proto_100_call\" does not exist","time":"2020-03-10T15:23:53Z"}
homer-webapp      | {"level":"error","msg":"GetTransactionData: We have got error:  pq: relation \"hep_proto_5_call\" does not exist","time":"2020-03-10T15:23:53Z"}
```

**Comment by systemcrash** [comment]
Showing export TXT also results in 0 byte files.

**Comment by lmangani** [comment]
Please check what the browser console is posting in the query to the API please

**Comment by lmangani** [comment]
@systemcrash i just tested on the latest build and I can export a PCAP just fine. Are you exporting a Call related session or some other transaction type perhaps?

**Comment by systemcrash** [comment]
Call (session).

**Comment by lmangani** [comment]
Cannot reproduce it. Are you using a container or system installed version of homer-app?

**Comment by systemcrash** [comment]
First displaying the flow, I get:

ERROR TypeError: "Argument 1 of Selection.setBaseAndExtent is not an object."

and then

{
  "data": "",
  "message": "no agent subscription object found for type [cdr]"
}

Everything is docker.

**Comment by systemcrash** [comment]
Export flow as PNG is OK, however.

**Comment by adubovikov** [comment]
need to know the version of homer-app and UI

**Comment by adubovikov** [comment]
IMHO you have to allow popup in your browser. This can be an issue

**Comment by systemcrash** [comment]
> IMHO you have to allow popup in your browser. This can be an issue

Thanks - definitely not the issue here. Disabled all ad-blockers. 

homer-webapp      |  Version: homer-app 1.1.35

UI: 7.7.031 - same as subject

**Comment by adubovikov** [comment]
and you have all messages in the popup ?

**Comment by systemcrash** [comment]
Yes - poking into individual messages shows each content correctly

**Comment by systemcrash** [comment]
The "Share link" opens a new window, which shows zero results...

**Comment by adubovikov** [comment]
@systemcrash can you provide an access to check ?

**Comment by systemcrash** [comment]
From what subnet?

**Comment by adubovikov** [comment]
212.60.251.0/24

**Comment by systemcrash** [comment]
http://193.180.23.2

**Comment by adubovikov** [comment]
works without any issues :-)

**Comment by adubovikov** [comment]
![Screenshot from 2020-03-10 19-10-15](https://user-images.githubusercontent.com/4513061/76344985-d00fc400-6302-11ea-95eb-ec3fd183f712.png)

**Comment by adubovikov** [comment]
and share link works as well :-)
![Screenshot from 2020-03-10 19-11-05](https://user-images.githubusercontent.com/4513061/76345051-f5043700-6302-11ea-98b9-e6aed17b974a.png)

**Comment by adubovikov** [comment]
maybe you have some cache or proxy or something else... ? Can you go to F12 -> Application and clean up the local storage ?

**Comment by systemcrash** [comment]
Bizarre. When accessed via IP or a different domain name, things work.....

**Comment by adubovikov** [comment]
:-) check your network topology. IMHO the ticket can be closed

**Comment by systemcrash** [comment]
Yeah, I think for now..... gremlins :(
