### ISSUE TITLE
Feature request: import PCAP

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/homer-app#318]
Import an on-disk PCAP into Homer, from the GUI

Process SIP, RTP and RTCP. 

(without having to utilise command-line utilities)

**Comment by adubovikov** [comment]
sorry, can you be more concrete ?

**Comment by systemcrash** [comment]
Instead of relying on heplify to ingest stuff, can we have the possibility to just upload a PCAP (of a call with SIP+RTP etc) into Homer

**Comment by adubovikov** [comment]
you can use heplify to upload HEP json/sip to Homer

**Comment by systemcrash** [comment]
from the Homer GUI? *click*?

**Comment by adubovikov** [comment]
We love CLI - unix shell :-) mouse is for loser ;-)

**Comment by systemcrash** [comment]
Me too :) But there are some knuckle-draggers who will need a 'quick and dirty' to get things going.

**Comment by lmangani** [comment]
If this needs to be done:

- PRs are welcome 
- Donations are welcome

Alternatively, you can purchase our professional services to get this developed or consider HEPIC which already does all of the above out of the box (and sponsors the development of HOMER)
