### ISSUE TITLE
Using a subpath in the URL

### ISSUE THREAD

**Issue by ghmj2417** [sipcapture/homer-app#321]
Is there a way to tell homer-app that it will be using a subpath?  Example; my URL would look like https://homer.local/v7/ where /v7 is the subpath.

While testing using a subpath, homer-app responds with everything as root which will return a 404.

Examples:
https://homer.local/main.1da17dcb9456b1d22073.js
https://homer.local/runtime.458556a34b891ea32398.js

It should be:
https://homer.local/v7/main.1da17dcb9456b1d22073.js
https://homer.local/v7/runtime.458556a34b891ea32398.js

**Comment by adubovikov** [comment]
Use nginx or change the  path in index.html

**Comment by ghmj2417** [comment]
I am using Apache.  That's how I am proxying all /v7 requests to the homer-app. The problem being homer-app isn't aware there is a subpath and is responding to all requests as if it's using root.

I ask about this because apps like grafana and prometheus allow you to specify a subpath or url if the application is being reverse proxied.

Are you saying that I need to be responsible for modifying the response through apache? Or the other option is to alter the index.html and prepend every anchor with /v7?  Although I could probably do something clever, wouldn't it be best if this was configurable via homer settings?

I assume I am not the only one that will want to use a subpath with homer version 7.  Especially when we need to run v5 and v7 side be side on the same server.

**Comment by adubovikov** [comment]
ok, we can add subpath in the homer-app, but anyway you have to change the index.html and point all scripts and css to /v7 or as I wrote above - nginx that will point to html/js/css and API calls go to proxy_pass to the homer-app in worse case -> https://httpd.apache.org/docs/2.4/mod/mod_proxy.html

**Comment by ghmj2417** [comment]
Thank you @adubovikov. I am using ProxyPass and ProxyPassReverse to redirect requests for /v7 to homer-app.  I am going to fiddle around with it more to come up with a workaround until you guys support it.  I'll do as you suggested and review making the changes to index.html.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/commit/2fc1a4e6c8fca268e79b09521b5ee44d95554f29

--webapp-api-prefix

**Comment by adubovikov** [comment]
5b1dd12..cb4bd9f
http_settings.api_prefix

**Comment by ghmj2417** [comment]
That was fast!  Thank you!  I will test it and let you know.

**Comment by ghmj2417** [comment]
For this to work as expected it appears homer-ui has to be aware that a prefix is also being used.  When testing this, I see connections to root instead of my prefix.

At the login screen (https://homer.local/v7/(system:login)?returnUrl=%2Fdashboard%2Fhome)
https://homer.local/assets/images/homerseven.png is being returned by https://homer.local/v7/main.1da17dcb9456b1d22073.js

When trying to login by clicking Login, the UI is trying to post to /api/v3/auth instead of /v7/api/v3/auth.  The initiator for the URI is https://homer.local/v7/polyfills.635d703039731e52383d.js and https://homer.local/v7/main.1da17dcb9456b1d22073.js.

Based off of what I have seen the .js files and index.html need to be aware that a subpath (or prefix) is being used.  I don't know the best approach to this since homer-ui and homer-app are decoupled.  Maybe using relative links or references?  Or maybe for the users that clone and build homer-ui, check for a variable that will add the prefix to links within js files and index.html?

I know this is a big ask, but I can see where supporting this will help users like myself that must run v5 and v7 on the same server.  I have limited administration of the server and the DNS record associated with my HOMER instance.  My only solution is to use subpaths and reverse proxy v5 and v7 requests.

As a workaround I can search and replace within the .js files and index.html.  index.html is easy.  However the js files are compressed.  If I decompress the js files, can homer-app support decompressed js files?  I see that http_settings.gzip and http_settings.gzip_static are configurable vars.  What do these settings do?

**Comment by lmangani** [comment]
@ghmj2417 just use a proxy such as NGINX and run both locally. It's the easiest path to your destination.

**Comment by ghmj2417** [comment]
Why is this closed?  I have already stated I am using a proxy.  I can make most of this work except when it comes to the js files. It would have been nice if you reviewed the last paragraph of my last comment.  I specifically said I can search and replace the files but I have questions about the files being compressed.  I'll ask again

As a workaround I can search and replace within the .js files and index.html. index.html is easy. However the js files are compressed. If I decompress the js files, can homer-app support decompressed js files? I see that http_settings.gzip and http_settings.gzip_static are configurable vars. What do these settings do?

**Comment by lmangani** [comment]
@ghmj2417 your type of challenge should be handled in front the app, if needed and when needed just like HTTPS, etc. I'm also not for expecting people to search and replace file content manually - those are updated daily, what are you going to do with that? So - either we support it well, or we don't support something - that's my view. The provided parameter should be used in conjuinction with the proxy to adjust the path of the accepted requests.

The thread stays open as you can see. If you want us to help you troubleshoot, please do show us the proxy config and every piece of the puzzle not just the problem. 

Thanks

**Comment by adubovikov** [comment]
ok, my 5 cents about this scenario. You just need  to change this file:
https://github.com/sipcapture/homer-ui/blob/master/src/environments/environment.prod.ts#L13
and compile the application. To replace the it in js files make no sense.

**Comment by ghmj2417** [comment]
When I do perform updates, I will use Ansible or a bash script to search and replace what I need.  I am not worried about this method, unless something is added or changed.  In that case, we will update the script accordingly.  This is merely a workaround and is not the final solution.

My ask can be handled in two places, first of which is what you stated, front end it with a proxy and don't do anything to the application.  I have done this.  The second is use a proxy and tell the application that it will be using a subpath.  This is exactly how Prometheus and Grafana work.  I don't care which method to take as long as one works.  Since the latter is not entirely supported at this time, I am trying to make the proxy work.

The problem is with the .js files and the links within them.  The links within the index.html file are being rewritten properly.  I provided the examples of when the .js files are referencing paths that are not being rewritten.  I am still investigating how this can be handled through the proxy.  This is why I asked about the http_settings.gzip and http_settings.gzip_static.  Maybe the proxy doesn't like the fact that the files are compressed.  I don't know.


Here is the partial proxy config:
```
ProxyHTMLLinks  a               href
ProxyHTMLLinks  area            href
ProxyHTMLLinks  link            href
ProxyHTMLLinks  img             src longdesc usemap
ProxyHTMLLinks  object          classid codebase data usemap
ProxyHTMLLinks  q               cite
ProxyHTMLLinks  blockquote      cite
ProxyHTMLLinks  ins             cite
ProxyHTMLLinks  del             cite
ProxyHTMLLinks  form            action
ProxyHTMLLinks  input           src usemap
ProxyHTMLLinks  head            profile
ProxyHTMLLinks  base            href
ProxyHTMLLinks  script          src for

ProxyHTMLEvents	onclick ondblclick onmousedown onmouseup \
		onmouseover onmousemove onmouseout onkeypress \
		onkeydown onkeyup onfocus onblur onload \
		onunload onsubmit onreset onselect onchange

Listen 443 https
<VirtualHost *:443>
    ....
    ProxyPass /grafana/ http://127.0.0.1:3000/
    ProxyPassReverse /grafana/ http://127.0.0.1:3000/
    ProxyPass /prometheus/ http://127.0.0.1:9090/prometheus/
    ProxyPassReverse /prometheus/ http://127.0.0.1:9090/prometheus/
    ProxyPass /v7/ http://127.0.0.1:8080/
    <Location /v7/>
        ProxyPassReverse /
        ProxyHTMLEnable On
        ProxyHTMLExtended On
        ProxyHTMLURLMap http://127.0.0.1:8080/ /v7/
        ProxyHTMLURLMap / /v7/
    </Location>
    ProxyPass / http://127.0.0.1:8081/
    ProxyPassReverse / http://127.0.0.1:8081/
    ....
</VirtualHost>
```
@adubovikov You say adding the prefix to the js files doesn't make sense.  Then what does make sense?  Do you want us to replace or update the environments file with our own?  As mentioned above, what happens if you change the file structure?  Also, that suggestion fixes the /api/v3 reference but not the /assets reference that occurs in the js files.

Just to provide an example of how I did this in Grafana and Prometheus:

Grafana:
# The full public facing url
root_url = https://homer.local/grafana/

# Serve Grafana from subpath specified in `root_url` setting. By default it is set to `false` for compatibility reasons.
serve_from_sub_path = true

Prometheus:
(Add this arg when starting Prometheus) --web.external-url=http://127.0.0.1:9090/prometheus

**Comment by ghmj2417** [comment]
I am in the process of testing the use of relative links.  The goal is to support users like myself but also support the users that are able to use root.  This would require minimal change to homer-ui.  Hopefully this works.

I have found absolute references in js files and will post them here if I deem they need to be changed.  I will update this issue once I find out more.

**Comment by adubovikov** [comment]
not sure I have understood, if you change the path in the file and compile the app you will get exactly that you asked for. The params that you change for prometheus/grafana are ONLY for API calls, but nor for UI.

**Comment by ghmj2417** [comment]
It definitely changes something within the UI because when I don't use those settings, the UI won't load.  Of course it's possible I am overlooking something.  I am also using swagger-ui and checked to see how its files are setup because I am using a subpath for that too.  I noticed all refs or srcs use relative paths starting with `./`  That's what lead me to believe my request could be achieved by making sure relative paths are used with `./`.  This is why I am testing homer-ui with prepending all relative paths with `./`.  So far I have been able to make this work without any significant changes to homer-ui.

Yes, I know if I change the necessary files and then compile it will work.  But I think this goes against Lorenzo's thinking.  I shouldn't have to search and replace parts of a file.  I don't mind doing as you suggested.  I just want to make sure that is the agreed upon approach.

**Comment by lmangani** [comment]
@ghmj2417 I just want to make sure we can have a solution where you don't have to hack the code, so when we release a security fix or improvement, you can immediately enjoy rather than have a hybrid which easily gets hard to maintain. Let's identify those changes and see if they can be assigned to a variable or something instead?

**Comment by ghmj2417** [comment]
Thanks @lmangani.  I agree 100%.  My goal with this testing is to have a configuration in place that can support my needs as well as others that don't require the use of a subpath.  So far prepending `./` to all of the hrefs or srcs has worked.  The only piece I can see that needs knowledge of the prefix is the apiUrl in homer-ui.  As @adubovikov has mentioned, I can update the variable in the file, or I can replace the file with my own.  In either instance, if you were to make changes to those files, I would have to update my changes as well.  That would be a downside to going down that path.  I haven't actually tested this suggestion yet.

My changes so far include:
index.html
Prefix all href or src values with `./`

main.*.js
poly.*.js
Found all /assets/images/homerseven.png references and prefixed it with `./`
Found all /api/v3 references and changed it to /v7/api/v3 (/v7 being my subpath)

I'm going to continue tinkering with my Apache setup and finding if anymore homer-ui items need to be changed.

**Comment by ghmj2417** [comment]
I think I have identified everything that needs to be changed.  That was a lot of testing.  Quite a bit of tinkering.  I've learned more than I wanted to know about Angular.

Here is what I have found:

When building homer-ui:

Add `--base-href` param to npm build fixes the main problem.
`npm run ng -- build --prod --base-href=/v7/ && gzip -9 ./dist/homer-ui/*.js`

As @adubovikov pointed out, I must do something with environments.prod.ts.  Either create my own or modify the existing.  This begs the question, would there be a way to pass a variable during build that could prepend a prefix to '/api/v3' or set an environment variable that can be referenced?  Example: apiUrl: $ENV.apiUrl || window.location.protocol + '//' + (window.location.host) + api_prefix + '/api/v3',

This is a must as using /assets/images/homerseven.png will never work.
All references to /assets/images/homerseven.png must be changed to assets/images/homerseven.png or ./assets/images/homerseven.png.
I found references in the following files
src/index.html
src/app/components/login/login.component.html
src/app/components/menu/menu.component.html

This makes sure your favicon.ico works properly.
add <link rel="icon" type="image/x-icon" href="favicon.ico"> to index.html under <base />

When using a prefix in the homer-app, I have noticed failures when trying to reload pages that have the URIs, /$prefix/dashboard/home and /$prefix/(system:login).  When I remove the prefix from homer-app, these reloads work properly.  For my testing I have not added the prefix to homer-app.

This is the apache config that is working.  The final ProxyPass/ProxyPassReverse point to v5.
```
Listen 4443 https
<VirtualHost *:4443>
    SSLEngine on
    SSLCertificateFile "cert.crt"
    SSLCertificateKeyFile "key.key"

    RewriteEngine on
    RewriteRule "^/swagger$" "%{REQUEST_SCHEME}://%{HTTP_HOST}/swagger/"
    RewriteRule "^/grafana$" "%{REQUEST_SCHEME}://%{HTTP_HOST}/grafana/"
    RewriteRule "^/prometheus$" "%{REQUEST_SCHEME}://%{HTTP_HOST}/prometheus/"
    RewriteRule "^/v7$" "%{REQUEST_SCHEME}://%{HTTP_HOST}/v7/"

    ProxyPass /swagger !
    Alias "/swagger" "/opt/swagger-api/swagger-ui/dist"
    <Directory "/opt/swagger-api/swagger-ui/dist">
        Require all granted
    </Directory>

    ProxyPass /grafana/ http://127.0.0.1:3000/
    ProxyPassReverse /grafana/ http://127.0.0.1:3000/
    ProxyPass /prometheus/ http://127.0.0.1:9090/prometheus/
    ProxyPassReverse /prometheus/ http://127.0.0.1:9090/prometheus/
    ProxyPass /v7/api/v3/ http://127.0.0.1:8080/api/v3/
    ProxyPassReverse /v7/api/v3/ http://127.0.0.1:8080/api/v3/
    ProxyPass /v7/ http://127.0.0.1:8080/
    ProxyPassReverse /v7/ http://127.0.0.1:8080/
    ProxyPass / http://127.0.0.1:8081/
    ProxyPassReverse / http://127.0.0.1:8081/
</VirtualHost>
```

If you would like I can create a pull request for the /assets and favicon changes.  Please let me know if you want me to do that.

**Comment by ghmj2417** [comment]
Put in a PR for homer-ui, https://github.com/sipcapture/homer-ui/pull/186

If you guys can comment on this:
As @adubovikov pointed out, I must do something with environments.prod.ts. Either create my own or modify the existing. This begs the question, would there be a way to pass a variable during build that could prepend a prefix to '/api/v3' or set an environment variable that can be referenced? Example: apiUrl: $ENV.apiUrl || window.location.protocol + '//' + (window.location.host) + api_prefix + '/api/v3',

**Comment by adubovikov** [comment]
done
