### ISSUE TITLE
After refresh last search operations applies to all Display Results widgets

### ISSUE THREAD

**Issue by runelucica** [sipcapture/homer-app#322]
As agreed on [Issue 320](https://github.com/sipcapture/homer-app/issues/320) I am opening additional issues for the other topics discovered while testing.

After a refresh of the page, it seems that the last search button pressed applies to all Display results widgets.
You have to click Search again on each Proto Search widget to apply the correct filters to each Display Results widget. Is this normal?

This is what the dashboard look like after pressing the Search button on the second Proto Search and refreshing the page:

![Search2](https://user-images.githubusercontent.com/41921868/76742962-3157ed00-6772-11ea-8d17-302b2427a34a.PNG)

**Comment by RFbkak37y3kIY** [comment]
fixed on devel branch, waiting marge to master
