### ISSUE TITLE
Display Results widget built-in Search option question

### ISSUE THREAD

**Issue by runelucica** [sipcapture/homer-app#323]
As agreed on [Issue 320](https://github.com/sipcapture/homer-app/issues/320) I am opening additional issues for the other topics discovered while testing.

While working on building pre-populated Search Dashboards I initially tried using the search option built directly into Display Results widget.
I added 2 Display Results widgets to the same dashboard. I tried configuring different search filters for the 2 Display Results widgets.
It seems that the widget built in search option references the same Search widget regardless of how many dashboards and Display Result widgets I have. If you configure a search in one of the widgets, after you refresh the page or switch between the dashboard it applies the search on all Display Results dashboards.
I have 2 questions here:

Does this work as per design?
Can I use the built in search function from a Display Result widget or do you recommend I always use a Proto Search (with Results Container selection) + Display Results widget?

**Comment by RFbkak37y3kIY** [comment]
fixed on devel branch, waiting marge to master
