### ISSUE TITLE
No packet loss label in QoS Tab

### ISSUE THREAD

**Issue by Sp0rN** [sipcapture/homer-app#326]
Hi Guys,

I have a homer 7 stack that I installed using the quick install script, alongside prometheus,grafana, loki, promtail etc, which all work perfectly.

However, in a previous homer implementation, there used to be a packets lost label in the QoS tab of a call, but Im not seeing it:

![image](https://user-images.githubusercontent.com/31306657/77068133-c5ce8380-69ee-11ea-8d2c-45c799db3f11.png)

Looking through the hep logs, there is atleast 1 lost packet, which should pull through to the QoS graph, but theres nothing there:

![image](https://user-images.githubusercontent.com/31306657/77067675-0b3e8100-69ee-11ea-8c97-82b4c8f43ea4.png)

Im sure the data is in psql/prometheus as the panel in grafana is picking up on packet loss:

![image](https://user-images.githubusercontent.com/31306657/77067736-27422280-69ee-11ea-964b-66bb470cf821.png)

This might be due to versions, however I'm not sure how to properly update a system provisioned by the install script.

**Comment by adubovikov** [comment]
you didn't install the latest version

**Comment by Sp0rN** [comment]
Thanks @adubovikov

What would be the process of upgrading? As I installed using the installation script, could I re run that?

**Comment by adubovikov** [comment]
if you have installed packages - just upgrade it

**Comment by Sp0rN** [comment]
I have upgraded homer-app to 1.1.36 and heplify-server to 1.26, afaik these are the latest versions?

**Comment by adubovikov** [comment]
Do you use UI from the package ? Show me the version from the browser's title

**Comment by Sp0rN** [comment]
UI on browser title is 7.7.030, im assuming its meant to be 7.7.0.31, what package is this version refering to?

**Comment by adubovikov** [comment]
7.7.0.31 has it, and this UI in the latest homer-app package. If you compiled the UI manualy - please fetch the latest master and do it again.

**Comment by Sp0rN** [comment]
Thanks @adubovikov managed to come right and everything is working perfectly.

Thanks again for the help.
