### ISSUE TITLE
LDAP - two types of groups

### ISSUE THREAD

**Issue by kpribic** [sipcapture/homer-app#328]
Is it possible to differentiate two types of Homer users based on LDAP groups?

Specifically that a user is logged in as admin if he is member of eg. HOMER_admin group on AD, and as supporter if he is member of HOMER_support group on AD? 
It would be important this works with recursive group search for AD.

Something like:
1. Search sAMAccountName:jblack
2. Response from AD--> CN=Joe Black, OU=Users, OU= Networking, DC=mycompany, DC=com
3. Bind CN=Joe Black, OU=Users, OU= Networking, DC=mycompany, DC=com
4. Recursive search of all groups on AD:
```
 (&
(objectClass=group)
(member:1.2.840.113556.1.4.1941:=CN=Joe Black, OU=Users, OU= Networking, DC=mycompany, DC=com)
 )
```
8. Check if HOMER_admin group is in list. If so login as admin.
9. Check if HOMER_support group is in list. If so login as supporter.

**Comment by lmangani** [comment]
This feature is as "corporate" as it gets, so I think it should be sponsored - we'll welcome a PR or Bounty Donation :)

**Comment by kpribic** [comment]
@lmangani  does this look ok to you?

- user DN change for AD recursive group query + TCP connection fix: https://github.com/kpribic/homer-app/commit/3570f2ef91c59488657ffc8ea233a0d4f048f0f9
- Two groups feature: https://github.com/kpribic/homer-app/commit/a45ffca01fe848e4743907e7e543e71ae67c737f

I was trying to do minimum changes to the code, so two new parameters are added to config: 
- usergroup --> LDAP group that user needs to be in to match
- usermode --> boolean that works same as adminmode just for restricted users (adminmode has precedence)

If adminmode and usermode are both false then login is possible only with group match.

There is one caveat, like I mentioned here https://github.com/sipcapture/homer-app/issues/324#issuecomment-605902531 . I had to change the variable used to query groups to DN (from username) because apparently member:1.2.840.113556.1.4.1941 takes only DN format (https://ldapwiki.com/wiki/LDAP_MATCHING_RULE_IN_CHAIN).

Final config looks like this for my desired scenario (login only with group match):

```
  "ldap_config": {
    "admingroup": "HOMER_administrators",
    "adminmode": false,
    "anonymous": false,
    "usermode": false,
    "usergroup": "HOMER_users",
    "attributes": [
      "dn",
      "givenName",
      "sn",
      "mail",
      "uid"
    ],
```

**Comment by Majongman** [comment]
@kpribic  Hello, i'm trying to differentiate two types of Homer users too. But users have admin access or limited access depending on the variable "adminmode" only. Can you tell me what is wrong with my configuration?
  "ldap_config": {
    "base": "dc=example,dc=local",
    "host": "example.local",
    "port": 636,
    "usessl": true,
    "skiptls": false,
    "binddn": "CN=homer-svc,OU=ENTERPRISE,DC=example,DC=local",
    "bindpassword": "PASSWORD",
    "userfilter": "(&(sAMAccountName=%s)(|(memberof:1.2.840.113556.1.4.1941:=CN=homer_user,OU=ENTERPRISE,DC=example,DC=local)(memberof:1.2.840.113556.1.4.1941:=CN=homer_admin,OU=ENTERPRISE,DC=example,DC=local)))",
    "groupfilter": "(member:1.2.840.113556.1.4.1941:=%s)",
    "groupattribute": "cn",
    "admingroup": "homer_admin",
    "adminmode": false,
    "usergroup": "homer_user",
    "usermode": false,
    "attributes": ["dn", "givenName", "sn", "mail", "sAMAccountName"],
    "skipverify": false,
    "anonymous": false,
    "userdn": "CN=%s,OU=MYGROUP,DC=example,DC=local"
  },

**Comment by kpribic** [comment]
Just to be sure we are talking about the same thing:

1. This feature is **not included in standard homer-app release**, it's currently only in this fork https://github.com/kpribic/homer-app. You will need to compile it from there if you want to try it.
2. I tested this on Microsoft AD, as far as I can tell this recursive query is not really supported. I think it **should** work with only `"groupfilter": "(memberUid=%s)" `if you want to test for direct membership, and not recursive.
3. Fork is currently based on 1.1.37. I do plan to update it to the newest one next week.

Assuming above is understood:

- My user filter is much simpler "userfilter": "(sAMAccountName=%s)", but if you're managing to login I guess your works as well. At first glance your config looks ok.
- If you're managing to log in but `adminmode` regulates what is going on that means you didn't match groups listed in admin group or user group.That is checked first

One way to troubleshoot is to set encryption to false, trace the LDAP singnalling and see if the correct list of groups is returned. I don't remember if debug mode lists this information, probably not.

**Comment by kpribic** [comment]
@Majongman pull request has been merged, so I propose you try again with compiling from sipcapture homer-app master.
