### ISSUE TITLE
Swagger calls referencing wrong URIs and use wrong methods

### ISSUE THREAD

**Issue by ghmj2417** [sipcapture/homer-app#329]
I created a swagger page based off of the instructions on the README.  The swagger.json file gets created without any issues but I have noticed quite a few of the calls aren't using the correct URIs or don't support the method on the swagger page.

When reviewing the URIs and methods in `router/v1` I noticed the following.  I think a review of the swagger definitions needs to be updated with what is in `router/v1` modules.

All references using `/api` or `/api/v3` appear to be invalid and those prefixes should be removed.  Example, `/api/search/call/message` should actually be `/search/call/message`.  Another example, `/api/v3/proxy/grafana/url` should be `/proxy/grafana/url`.

I found at least one method that is in swagger that doesn't match with a route.  Example, `/search/call/data` is using a GET on swagger, but the actual call must use a POST.

I can try to help out with this if you guys want by creating a PR, but if you guys prefer to do it yourselves that works too.

**Comment by ghmj2417** [comment]
I'm going to go ahead and create a PR.

**Comment by ghmj2417** [comment]
PR: https://github.com/sipcapture/homer-app/pull/331

**Comment by adubovikov** [comment]
merged. Thank you!
