### ISSUE TITLE
Timespan seems stuck when looking at flow data

### ISSUE THREAD

**Issue by nakchak** [sipcapture/homer-app#332]
Appologies for posting the issue in probably the [wrong repo before](https://github.com/sipcapture/homer/issues/399), could really do with some concerted effort on signposting to direct users issues to the appropriate repo.

Im running a docker-compose based setup using the hom7-prom-all script, everything seems to have gone without a hitch and have updated to the latest release (7.7.032), in an effort to resolve this issue. but it persists.

The issue is that when i try and examine the call flow of a call > 15 mins the sip flow is truncated at the 15 mark.  Went through the trouble shooting doc, (needs a docker version of that doc as a lot is not directly applicable) debugging the ajax requests when opening the flow found something interesting. the qos query is settings its time span to a range that matches the timespan filter, the transactions query however is ignoring the time span filter and regardless of what i set the range to sticks to a delta of 900 (15mins) between start and end times.

**Comment by lmangani** [comment]
@nakchak could you attach a step-by-step procedure to reproduce this accurately?

**Comment by nakchak** [comment]
@lmangani Sure

![image](https://user-images.githubusercontent.com/610677/78357059-a451c800-75a8-11ea-903a-af26dd07864a.png) Set timeframe to last 5 mins, would expect the delta between upper and lower timestamps to be 300 (for simplicity im ignoring the ms value used)
Click the session id to open call flow.
![image](https://user-images.githubusercontent.com/610677/78357302-1e824c80-75a9-11ea-8ddb-440c9969fcd3.png) delta 300 on qos request
![image](https://user-images.githubusercontent.com/610677/78357513-82a51080-75a9-11ea-984f-296fd1907178.png) delta 900 on transaction request

Now i set the timeframe to last hour
![image](https://user-images.githubusercontent.com/610677/78357720-d6175e80-75a9-11ea-9599-8752a47ee6f8.png) expecting a timestamp delta of 3600
Click session id again
![image](https://user-images.githubusercontent.com/610677/78357879-25f62580-75aa-11ea-8d76-5d6c6624d1db.png) delta between values is 3600 as expected.
![image](https://user-images.githubusercontent.com/610677/78357958-4b832f00-75aa-11ea-8dc1-ae415fc9ebf8.png)
![image](https://user-images.githubusercontent.com/610677/78358129-9604ab80-75aa-11ea-9294-22c204180e0d.png) delta between values is 900.

I dont believe either that its a local caching/cookie/storage issue as the same behavior occurs when in private browsing mode, and i get the same behavior in firefox and chrome.

My gut is telling me a debug or test value was left in prod code, or a there is a variable name mismatch somewhere and a default is being used, as that's the sort of thing i have done too many times to count!

**Comment by lmangani** [comment]
Thanks @nakchak for the clear example! we'll take a deep look and surely find the glitch

**Comment by AlexeyOplachko** [comment]
Fixed with https://github.com/sipcapture/homer-ui/commit/099efff51097a465b378cfbcc8682d08064f19fb
