### ISSUE TITLE
Doubt regarding "Retention" setting

### ISSUE THREAD

**Issue by lsadehaan** [sipcapture/homer-app#337]
Hi, where can I find more details about the Homer settings.
I'd specifically like to understand all the settings under the Mapping settings.
To start off - what are the Partition ID, Partition Step and Retention values for?
If you can point me in the direction of some documentation explaining the rest of it, that would be great!
![image](https://user-images.githubusercontent.com/4754900/78922804-8cc58400-7a6d-11ea-8a10-4e863b2137c6.png)

**Comment by lmangani** [comment]
This feature is in development. You can start with the wiki article: 
https://github.com/sipcapture/homer-app/wiki/Examples:-Correlation-MAPPING

The `Partition` fields are reserved for developer usage and can be ignored, they will be hidden as soon as this is stable. `Profile` matters for the purpose of correlation mapping.

I hope this helps!
