### ISSUE TITLE
QoS tab data needs ordering

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/homer-app#345]
I recommend a sort at the DB (so API works cleanly), or sort on the returned JSON. 

Is there a way to prevent stuff like this?:

![Screenshot 2020-05-14 at 17 49 47](https://user-images.githubusercontent.com/647633/81956453-9d888d00-960b-11ea-9d38-5bab957a975f.png)

In our testing, we see this occasionally.

**Comment by systemcrash** [comment]
This seems to be fine now. Will re-open if necessary.

**Comment by systemcrash** [comment]
This fix appears to be broken in current master. When I view the QoS tab for any call, all data types appear to be sorted in reverse order (and not forward, as expected).

e.g. for packets:

![Screenshot 2020-10-02 at 17 54 37](https://user-images.githubusercontent.com/647633/94943819-97228100-04d8-11eb-98f9-3f6ac7fc5af1.png)


The returned JSON data from the qos endpoint shows packet and octet count correctly increasing for consecutive entries. So this is exclusively a sort problem somewhere.

**Comment by systemcrash** [comment]
Time tags are listed in chronological order. Corresponding values are displayed in reverse.

**Comment by adubovikov** [comment]
@AlexeyOplachko can you please recheck ?

**Comment by systemcrash** [comment]
Isn't it trivial to verify this bug in current master?

**Comment by adubovikov** [comment]
@systemcrash it's not complex, but we are also busy with another tasks, don't worry this one is next

**Comment by adubovikov** [comment]
@AlexeyOplachko fixed it in the last devel branch (homer-ui). Please take it and retest

**Comment by systemcrash** [comment]
Nope - still showing backwards in master. This will land tomorrow in homer-app?

How would I test with the homer-ui devel branch, should I want/need to?

**Comment by adubovikov** [comment]
1. git clone -b devel http://github.com/sipcapture/homer-ui
2. cd homer-ui
3. npm install
4. npm run build
5. cp dist to your homer-app directory

test it

**Comment by adubovikov** [comment]
sorry, but I have cleary wrote - devel branch. Not master

**Comment by systemcrash** [comment]
> 1. git clone -b devel http://github.com/sipcapture/homer-ui 2. cd homer-ui 3. npm install 4. npm run build 5. cp dist to your homer-app directory test it

Ok - thank you. This would be good in the wiki. But since I docker-compose, and only have images.....

**Comment by adubovikov** [comment]
in this case you have to wait until our dev-team will not finish all tests
and only after push everything to the master.

**Comment by systemcrash** [comment]
Pulled current master. Appears as though this commit has fixed sort order, once again. 

https://github.com/sipcapture/homer-ui/commit/b1f77fa53c4a720ea3e0a48ad036153c492566d3

**Comment by adubovikov** [comment]
you are welcome. Don't forget to star our project: https://github.com/sipcapture/homer/stargazers

**Comment by adubovikov** [comment]
thank you, but better to star homer project  - this is out front page :-)

**Comment by systemcrash** [comment]
Stalker 😉
