### ISSUE TITLE
Help to make a wiki page. 

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/homer-app#346]
In light of #342 - I'd like to make a wiki page which lays out how to put things together. Something which gives people a better idea of how the correlation inputs work. 

[This example](https://github.com/sipcapture/homer-app/wiki/Examples:-Correlation-MAPPING) when used, makes all RTCP packets appear in the call graph. Not bad. But how to make them appear in the QoS tab? Or does it not work like that?

Let's say I have this abstract scenario:

```
Leg A --> b2bua --> Leg B
Call-ID:            Call-ID:
abc                 abc@b2bua
corrrelation-id: abc
RTP A --> b2bua --> RTP B
corrrelation-id: abc
```

So the HEP agent at `b2bua` sends to heplify-server all legs and RTCP for both legs with `corrrelation-id: abc`.

Graph Call Leg A `Call-ID: abc`. QoS tab is there. ( RTCP was stored with `corrrelation-id: abc`)
Graph Call Leg B. `Call-ID: abc@b2bua` QoS tab disappears on current homer build (it thinks there is no RTCP - there is no RTCP stored under `corrrelation-id: abc@b2bua`). 

It seems that the QoS tab does its own query and always uses the `call-id` of the current SIP call Leg. So the QoS query for Leg B becomes `abc@b2bua` e.g. :

```javascript
{"timestamp":{"from":1589571021000,"to":1589581821000},"param":{"search":{"1_call":{"id":3749,"callid":["Vxbd2l0bAFG80Se4QR@192.0.2.2"],"uuid":[]}},"location":{},"transaction":{"call":true,"registration":false,"rest":false},"id":{},"timezone":{"value":-120,"name":"Local"}}}
```

 which was earlier captured and stored under `corrrelation-id: abc`, so, in effect stored under `abc`.  Currently Homer assumes that RT(C)P for the QoS is found under the query `corrrelation-id = call-id` i.e. for Leg B: `call-id: abc@b2bua` when in fact it is under `abc` so QoS currently returns nothing for those legs:

```javascript
{"rtcp":{"data":[],"total":0},"rtp":{"data":[],"total":0}}
```

There is the potential that we are sending the correlation-id for both RTP legs in the HEP, instead of the individual call-id. We can later fix the HEP agent to send the correlation-id in the HEP packet as the SIP Call-ID for the RTP stream. 

But I wonder if there is a way to work around this via correlation scripts in the GUI? 

I use e.g.

```json
[  
  {
    "source_field": "data_header.callid",
    "lookup_id": 5,
    "lookup_profile": "default",
    "lookup_field": "sid",
    "lookup_range": [
      -300,
      200
    ]
  }
]
```

I get RTCP in the call graph only:

![Screenshot 2020-05-16 at 01 02 33](https://user-images.githubusercontent.com/647633/82102826-0e659d00-9711-11ea-85eb-58a11483d332.png)

And under the Logs -> HEP Logs tab as the JSON packets. Like
```javascript
payload: Object {"message":{"report_count":1,"type":200,"ssrc":1251574919,"sender_information":{"ntp_timestamp_sec":23930,"ntp_timestamp_usec":996409344,"rtp_timestamp":2732685996,"packets":242,"octets":38720},"report_blocks":[{"source_ssrc":33338885,"fraction_lost":0,"packets_lost":0,"highest_seq_no":367,"ia_jitter":10,"lsr":0,"dlsr":0}]},"timestamp":"2020-05-15T21:07:40.127Z","raw":{"captureId":"1","correlation_id":"Vxbd2l0bAFG80Se4QR","create_date":1589576860127,"dbnode":"local","dstIp":"192.0.2.2","dstPort":58445,"id":323,"node":["local","1"],"payloadType":5,"profile":"5_default","proto":"rtcp","protocol":17,"protocolFamily":2,"sid":"Vxbd2l0bAFG80Se4QR","srcIp":"192.0.2.1","srcPort":54835,"timeSeconds":1589576860,"timeUseconds":127810}}
```

These seem to dispatch via the
```
http://homer-uri/api/v3/search/call/message
```

but not get dispatched via the 
```
http://homer-uri/api/v3/call/report/qos
```

Help?

**Comment by systemcrash** [comment]
If I use the following e.g.

```javascript
[
    {
        "source_field": "protocol_header.correlation_id",
        "lookup_id": 5,
        "lookup_profile": "default",
        "lookup_field": "sid",
        "lookup_range": [
            -300,
            200
        ],
        "input_function_js": "var returnData=[]; for (var i = 0; i < data.length; i++) { returnData.push(data[i]+'@%'); }; returnData;"
    }
]
```

this finds RTCP for all call legs `abc` and `abc@b2bua` with the `@%` extra search param. But graphs it in the call-graph...

**Comment by systemcrash** [comment]
I'm still in the dark what the following are:

input_function_js
returnData
data

**Comment by systemcrash** [comment]
Is a mapping necessary for the QoS tab ( which calls the qos endpoint )?

alias: qos - id: 1 - profile: call
?

I tried this and it didn't give expected results.

**Comment by systemcrash** [comment]
It seems I cannot get past this, where the call-id is used:

https://github.com/sipcapture/homer-ui/blob/8f179c4e602020fd603b38e47d1a16f192d90d0e/src/app/components/search-grid-call/search-grid-call.component.ts#L776

Perhaps it is meant to be this way... that call-id is used for RT(C)P instead of correlation-id. Yes?

**Comment by adubovikov** [comment]
the answer is heplify-server. It forces to use callid if no correllation-id in HEP header. We have fixed it already

**Comment by adubovikov** [comment]
I am closing the ticket. Please also install homer-app-1.4.0
