### ISSUE TITLE
Add git 2+ to list of dependencies

### ISSUE THREAD

**Issue by nfantone** [sipcapture/homer-app#354]
Currently, the [requirements](https://github.com/sipcapture/homer-app#requirements) list `golang` and `postgresql` as mandatory dependencies. However, `make` commands, when installing on local systems, won't work if `git` is either not installed or older than `2.1.4` - which is, unfortunately, still the case of many default distributions, such as CentOS 7 even after installing `golang`.

```sh
[root@homer0 homer-app]# make modules
go get ./...
go: github.com/labstack/echo/v4@v4.0.0 requires
        github.com/valyala/fasttemplate@v0.0.0-20170224212429-dcecefd839c4: invalid version: git fetch --unshallow -f origin in /root/go/pkg/mod/cache/vcs/5d1526a6d3ead7298c1cdcdbdf7fcfcccc86964868f468b9900d9e4b0c3c0ba6: exit status 128:
        fatal: git fetch-pack: expected shallow list
```

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/commit/6e4eee26bb3112073fdf1821502703a5ec9d6878

thank you
