### ISSUE TITLE
Building from master receiving build errors

### ISSUE THREAD

**Issue by ghmj2417** [sipcapture/homer-app#359]
I think this commit (https://github.com/sipcapture/homer-app/commit/62f5f6212146fb55ddbddd01972e8f5e3d189aee) has introduced some type of issue when building homer-app.

I am building from master, using `make modules` and `make all`.  I am receiving the following error.
`# github.com/sipcapture/homer-app/utils/ldap utils/ldap/ldap.go:152:23: logrus.Error(\"No username/password provided\") used as value make: *** [all] Error 2`

I want to say it doesn't like the syntax or assignment but I have no idea.

Any suggestions?

**Comment by adubovikov** [comment]
Thank you. Fixed!
