### ISSUE TITLE
Export to PNG lacks address header row (no IPs/FQDNs)

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/homer-app#361]
From the top of the image, they look like this currently

![f40c21c-781d254975f-2ab22adf@sipgt-59ca6316](https://user-images.githubusercontent.com/647633/84390017-41f3f400-abf7-11ea-98fa-45214ec9de9a.png)

Homer 7.7.034

**Comment by systemcrash** [comment]
No errors from browser console.

**Comment by mikegoodstadt** [comment]
Error not detected in version 7.8.1
