### ISSUE TITLE
Smart-input single quotes

### ISSUE THREAD

**Issue by AlexeyOplachko** [sipcapture/homer-app#362]
When searching with smart-input and using single-quotes instead of double-quotes in it, request is sent successfully to server, but it receives empty response. 
I see two possible solutions

1. Allow single-quotes for a query
2. Auto-replace single-quotes with double-quotes in UI.

**Comment by lmangani** [comment]
@AlexeyOplachko why me? Perhaps @adubovikov can help best ;)

**Comment by adubovikov** [comment]
I will take

**Comment by adubovikov** [comment]
was fixed
