### ISSUE TITLE
Export PCAP/TEXT not working

### ISSUE THREAD

**Issue by mneuhauser** [sipcapture/homer-app#363]
homer-app 1.1.39 from https://packagecloud.io/qxip/sipcapture/el/8/ repo
Exporting a flow as PCAP or TEXT always creates an empty file (tested with up-to-date Chrome and Firefox). Exporting PNG does work.

**Comment by adubovikov** [comment]
any exception in the log file of webapp ?

**Comment by mneuhauser** [comment]
No. Unrelated(?) messages:

Jun 16 08:33:39 server homer-app[1309]: {"level":"error","msg":"GetTransactionData: We have got error:  pq: relation \"hep_proto_100_call\" does not exist","time":"2020-06-16T08:33:39+02:00"}
Jun 16 08:33:39 server homer-app[1309]: {"level":"error","msg":"GetTransactionData: We have got error:  pq: relation \"hep_proto_5_call\" does not exist","time":"2020-06-16T08:33:39+02:00"}
Jun 16 09:12:36 server homer-app[1309]: {"level":"error","msg":"GetTransactionData: We have got error:  pq: relation \"hep_proto_100_call\" does not exist","time":"2020-06-16T09:12:36+02:00"}
Jun 16 09:12:36 server homer-app[1309]: {"level":"error","msg":"GetTransactionData: We have got error:  pq: relation \"hep_proto_5_call\" does not exist","time":"2020-06-16T09:12:36+02:00"}
Jun 16 09:49:01 server homer-app[1309]: {"level":"error","msg":"GetTransactionData: We have got error:  pq: relation \"hep_proto_100_call\" does not exist","time":"2020-06-16T09:49:01+02:00"}
Jun 16 09:49:01 server homer-app[1309]: {"level":"error","msg":"GetTransactionData: We have got error:  pq: relation \"hep_proto_5_call\" does not exist","time":"2020-06-16T09:49:01+02:00"}
Jun 16 10:09:16 server homer-app[1309]: {"level":"error","msg":"GetTransactionData: We have got error:  pq: relation \"hep_proto_100_call\" does not exist","time":"2020-06-16T10:09:16+02:00"}
Jun 16 10:09:16 server homer-app[1309]: {"level":"error","msg":"GetTransactionData: We have got error:  pq: relation \"hep_proto_5_call\" does not exist","time":"2020-06-16T10:09:16+02:00"}

**Comment by adubovikov** [comment]
please enable debug  and check again.

**Comment by mneuhauser** [comment]
Jun 19 11:36:34 server homer-app[10902]: {"level":"info","msg":"Claims","time":"2020-06-19T11:36:34+02:00"}
Jun 19 11:36:34 server homer-app[10902]: {"level":"info","msg":"\u0026{admin true false { 1592573634  0  0 }}","time":"2020-06-19T11:36:34+02:00"}
Jun 19 11:36:34 server homer-app[10902]: {"level":"info","module":"gorm","msg":"SELECT * FROM \"mapping_schema\"  WHERE (hepid = $1 and profile = $2)","time":"2020-06-19T11:36:34+02:00","type":"sql"}
Jun 19 11:36:34 server homer-app[10902]: {"level":"info","module":"gorm","msg":"SELECT * FROM \"alias\"  WHERE (status = true)","time":"2020-06-19T11:36:34+02:00","type":"sql"}
Jun 19 11:36:34 server homer-app[10902]: {"level":"info","module":"gorm","msg":"SELECT * FROM \"hep_proto_1_default\"  WHERE (sid in ($1) and create_date between $2 and $3)","time":"2020-06-19T11:36:34+02:00","type":"sql"}
Jun 19 11:36:34 server homer-app[10902]: {"level":"debug","msg":"GetTransactionData: Len: 0","time":"2020-06-19T11:36:34+02:00"}

**Comment by mneuhauser** [comment]
Just found out that export of flow found via default SIP search **does** work (see debug log below)! Export does **not** work for call (debug log in prevous comment) and registration (see debug log at end) SIP search.

export of flow from default SIP search result:
Jun 21 12:51:24 server homer-app[12356]: {"level":"info","msg":"Claims","time":"2020-06-21T12:51:24+02:00"}
Jun 21 12:51:24 server homer-app[12356]: {"level":"info","msg":"\u0026{admin true false { 1592808376  0  0 }}","time":"2020-06-21T12:51:24+02:00"}
Jun 21 12:51:24 server homer-app[12356]: {"level":"info","module":"gorm","msg":"SELECT * FROM \"mapping_schema\"  WHERE (hepid = $1 and profile = $2)","time":"2020-06-21T12:51:24+02:00","type":"sql"}
Jun 21 12:51:24 server homer-app[12356]: {"level":"info","module":"gorm","msg":"SELECT * FROM \"alias\"  WHERE (status = true)","time":"2020-06-21T12:51:24+02:00","type":"sql"}
Jun 21 12:51:25 server homer-app[12356]: {"level":"info","module":"gorm","msg":"SELECT * FROM \"hep_proto_1_default\"  WHERE (sid in ($1) and create_date between $2 and $3)","time":"2020-06-21T12:51:25+02:00","type":"sql"}
Jun 21 12:51:25 server homer-app[12356]: {"level":"debug","msg":"GetTransactionData: Len: 4","time":"2020-06-21T12:51:25+02:00"}
Jun 21 12:51:25 server homer-app[12356]: {"level":"debug","msg":"default","time":"2020-06-21T12:51:25+02:00"}
Jun 21 12:51:25 server homer-app[12356]: {"level":"debug","msg":"sid","time":"2020-06-21T12:51:25+02:00"}
Jun 21 12:51:25 server homer-app[12356]: {"level":"info","module":"gorm","msg":"SELECT * FROM \"hep_proto_100_default\"  WHERE (sid in ($1) and create_date between $2 and $3)","time":"2020-06-21T12:51:25+02:00","type":"sql"}
Jun 21 12:51:25 server homer-app[12356]: {"level":"debug","msg":"GetTransactionData: Len: 0","time":"2020-06-21T12:51:25+02:00"}
Jun 21 12:51:25 server homer-app[12356]: {"level":"debug","msg":"Correlation data len:4","time":"2020-06-21T12:51:25+02:00"}
Jun 21 12:51:25 server homer-app[12356]: {"level":"debug","msg":"default","time":"2020-06-21T12:51:25+02:00"}
Jun 21 12:51:25 server homer-app[12356]: {"level":"debug","msg":"sid","time":"2020-06-21T12:51:25+02:00"}
Jun 21 12:51:25 server homer-app[12356]: {"level":"info","module":"gorm","msg":"SELECT * FROM \"hep_proto_5_default\"  WHERE (sid in ($1) and create_date between $2 and $3)","time":"2020-06-21T12:51:25+02:00","type":"sql"}
Jun 21 12:51:25 server homer-app[12356]: {"level":"debug","msg":"GetTransactionData: Len: 0","time":"2020-06-21T12:51:25+02:00"}
Jun 21 12:51:25 server homer-app[12356]: {"level":"debug","msg":"Correlation data len:4","time":"2020-06-21T12:51:25+02:00"}
Jun 21 12:51:25 server homer-app[12356]: {"level":"info","module":"gorm","msg":"SELECT * FROM \"hep_proto_1_default\"  WHERE (sid in ($1) and create_date between $2 and $3)","time":"2020-06-21T12:51:25+02:00","type":"sql"}
Jun 21 12:51:25 server homer-app[12356]: {"level":"debug","msg":"GetTransactionData: Len: 4","time":"2020-06-21T12:51:25+02:00"}
Jun 21 12:51:25 server homer-app[12356]: {"level":"debug","msg":"Correlation data len:8","time":"2020-06-21T12:51:25+02:00"}

export of flow from registration SIP search result:
Jun 21 13:01:14 server homer-app[12356]: {"level":"info","msg":"Claims","time":"2020-06-21T13:01:14+02:00"}
Jun 21 13:01:14 server homer-app[12356]: {"level":"info","msg":"\u0026{admin true false { 1592808376  0  0 }}","time":"2020-06-21T13:01:14+02:00"}
Jun 21 13:01:14 server homer-app[12356]: {"level":"info","module":"gorm","msg":"SELECT * FROM \"mapping_schema\"  WHERE (hepid = $1 and profile = $2)","time":"2020-06-21T13:01:14+02:00","type":"sql"}
Jun 21 13:01:14 server homer-app[12356]: {"level":"info","module":"gorm","msg":"SELECT * FROM \"alias\"  WHERE (status = true)","time":"2020-06-21T13:01:14+02:00","type":"sql"}
Jun 21 13:01:15 server homer-app[12356]: {"level":"info","module":"gorm","msg":"SELECT * FROM \"hep_proto_1_default\"  WHERE (sid in ($1) and create_date between $2 and $3)","time":"2020-06-21T13:01:15+02:00","type":"sql"}
Jun 21 13:01:15 server homer-app[12356]: {"level":"debug","msg":"GetTransactionData: Len: 0","time":"2020-06-21T13:01:15+02:00"}

**Comment by mikegoodstadt** [comment]
[Fixed](https://github.com/sipcapture/homer-ui/commit/f50b495f0f3894bae9e93cf7b19698bf7fe8a18c) on devel branch of homer-ui, for release on master shortly.
