### ISSUE TITLE
HTTP_PORT variable is not effective in docker-entrypoint.d/1 startup script

### ISSUE THREAD

**Issue by eill** [sipcapture/homer-app#365]
https://github.com/sipcapture/homer-app/blob/d2f69b8a7ddfe23c906e3736bc93e932fcb7b7b2/docker/webapp_config.json#L40

https://github.com/sipcapture/homer-app/blob/d2f69b8a7ddfe23c906e3736bc93e932fcb7b7b2/docker/docker-entrypoint.d/1#L37

docker/docker-entrypoint.d/1 script replaces port 9080 to the port specified in the $HTTP_PORT variable, but changing the default port from 9080 to 80 broke the logic, so sed -i will never change the requested parameter.

Consider change the default http port back to 9080 or change the parameter name so the sed will be able to distinguish it among others.

Another solution is to provide jq, but this will definitely increase image size.

**Comment by systemcrash** [comment]
@lmangani

**Comment by systemcrash** [comment]
Fix merged. Should be in tomorrows build. Let us know how you get on with it @eill

**Comment by adubovikov** [comment]
@systemcrash does it work now ?

**Comment by systemcrash** [comment]
@eill did you try a newer build?

**Comment by adubovikov** [comment]
ok, i will close the ticket. Please reopen if needed.
