### ISSUE TITLE
Authentication to Grafana in Panel Widget

### ISSUE THREAD

**Issue by flantel** [sipcapture/homer-app#372]
Hi,
I have both the user, pass and key set under Advanced for Grafana search, but these do not appear to be used when defining a grafana widget.

What is the method of authenticating widgets so the graphs do not bring up the login screen?
Thanks

**Comment by flantel** [comment]
Sorry, for whatever reason it is working now!

**Comment by flantel** [comment]
Re-opening this as I am still having issues. Grafana graphs only show up if I am already logged in to Grafana. In Advanced -> grafana search settings I have

```
{
    "host": "http://grafana:3000",
    "password": "XXXXXX",
    "token": "XXXXXXXXXXXsdGtWeDlKMlBQQUtiT3RaT1E3akwiLCJuIjoiaG9tZXIiLCJpZCI6MX0=",
    "user": "homer"
}
```
Should this work to authenticate these graph requests with Grafana?
Thanks

**Comment by lmangani** [comment]
Hi @flantel yes it should. Could you grab some logs for when this action fails?

**Comment by flantel** [comment]
Hi
There are no logs pointing to any problem. Howeve,r when Homer makes the request, I see no token in the headers, which I would expect. Grafana simply reirects to the login page.
Here are the Request Headers:
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Connection: keep-alive
Cookie: redirect_to=%2Fd-solo%2FSj2saAbez%2FConcurrent%2520Sessions%3Ffrom%3D1606867200000%26orgId%3D1%26panelId%3D21%26rand%3D387386%26refresh%3D%26theme%3Dlight%26to%3D1606953599000
DNT: 1
Host: grafana.domain.com
Referer: https://homer.domain.com/
Sec-Fetch-Dest: iframe
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-site
sec-gpc: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
``` 
The strange thing is, when I am defining a Grafana widget, the drop-downs get filled with the data from Grafana OK, and I can choose the dashboard. 

Homer logs attached. 
[homer.log](https://github.com/sipcapture/homer-app/files/5629549/homer.log)

**Comment by lmangani** [comment]
Thanks! @AlexeyOplachko could you check this next in your queue based on @flantel 's input?

**Comment by adubovikov** [comment]
it was fixed using proxy mode in homer-app. Please retest!

**Comment by adubovikov** [comment]
Please install homer-app-1.4.0 and test again
