### ISSUE TITLE
Example API Usage?

### ISSUE THREAD

**Issue by flantel** [sipcapture/homer-app#374]
Hi

I am trying to post data to create Aliases via the API. I keep getting validation errors such as 
```
Error:Field validation for 'Alias' failed on the 'required' tag
```

I am POSTing to /api/v3/alias and my json payload looks like this:

```
{"data":[{"alias":"my_alias_name","ip":"127.0.0.1","port":5060,"mask":32,"captureID":"CAP101","status":true}]}
```

I am guessing that my json post is slightly wrong, but it appears to be the same as the output of `GET /api/v3/alias` 

Can someone share a sample json payload so I can see where I might be going wrong?

Many thanks

**Comment by adubovikov** [comment]
here you can find the description of required fields:

https://github.com/sipcapture/homer-app/blob/0b19c668628860302947fe1ec9f7b990c2d2278f/model/alias.go#L13-L33

**Comment by adubovikov** [comment]
Request Method: POST

```
{"alias":"localhost34","ip":"127.0.0.1","port":5060,"mask":32,"captureID":"CAP101","status":true}
```

**Comment by flantel** [comment]
OK, that worked! 

Thanks again @adubovikov
