### ISSUE TITLE
SIP flow visualization is not working when changing web application port to some other port

### ISSUE THREAD

**Issue by ishvaram** [sipcapture/homer-app#381]
I've encountered with strange issue when I changed with the new port for the web application its everything else is working. But not sip flow visualization when I click it. its keep on loading and visualization is not coming for selected Call-ID
![captured (1)](https://user-images.githubusercontent.com/4301774/92309472-69264b80-efc3-11ea-8838-44947991a36e.gif)

I've checked this with both Chrome and Mozilla to double-check its not an browser issue

below is the error that I see in the console. 

```
main.1adcddffcc54c3672a03.js:75516 ERROR TypeError: Cannot read property 'protocol_id' of null
    at SearchGridCallComponent.push../src/app/components/search-grid-call/search-grid-call.component.ts.SearchGridCallComponent.queryBuilderQOS (main.1adcddffcc54c3672a03.js:321570)
    at SearchGridCallComponent.push../src/app/components/search-grid-call/search-grid-call.component.ts.SearchGridCallCompon
![captured (1)](https://user-images.githubusercontent.com/4301774/92309460-4c8a1380-efc3-11ea-8998-6a459da0ff36.gif)
ent.openTransactionDialog (main.1adcddffcc54c3672a03.js:321886)
    at SearchGridCallComponent.push../src/app/components/search-grid-call/search-grid-call.component.ts.SearchGridCallComponent.openTransactionForSelectedRows (main.1adcddffcc54c3672a03.js:321828)
    at ColumnCallidRenderer.push../src/app/components/search-grid-call/renderer/column-callid-renderer.component.ts.ColumnCallidRenderer.openTransactionPopup (main.1adcddffcc54c3672a03.js:321183)
    at ColumnCallidRenderer_Template_a_click_0_listener (ng:///ColumnCallidRenderer.js:12)
    at executeListenerWithErrorHandling (main.1adcddffcc54c3672a03.js:86868)
    at wrapListenerIn_markDirtyAndPreventDefault (main.1adcddffcc54c3672a03.js:86896)
    at HTMLAnchorElement.<anonymous> (main.1adcddffcc54c3672a03.js:160133)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (polyfills.72ffcb9be5231183c7c3.js:3271)
    at Object.onInvokeTask (main.1adcddffcc54c3672a03.js:97771)

```

Using Homer 7.7 golang app.

**Comment by adubovikov** [comment]
sorry, can you please be more concrete ? What did you change ? Where and why ?

**Comment by ishvaram** [comment]
@adubovikov I've changed the http_settings
```
  "http_settings": {
    "help": "Settings for the HOMER Webapp Server",
    "host": "0.0.0.0",
    "port" : 80,
    "root" : "/usr/local/homer/dist",
    "gzip" : true,
    "debug" : false
  },

```


the default port is 8080, I want to run the application on port 80. So changed it.

with the port being 8080 all the functionalities are working, but if I change the port to 80 or some other port then SIP flow visualization alone not working

**Comment by adubovikov** [comment]
please check if your API has been sent to the correct port.
In the browser -> F12 -> network tab

**Comment by ishvaram** [comment]
@adubovikov Yes it is going to the correct port.

**Comment by ishvaram** [comment]
@adubovikov Also i wanted to know is there a way where i can show only one transaction for a given call-ID. currently we're showing all the INVITE,100, 180, 183, ACK , BYE events as rows in the widget for a given call-ID. Instead of that can we show only transaction per call-ID

**Comment by lmangani** [comment]
Hi Kovalan,

Transaction tracking feature is currently only available in HEPIC (hepic.tel).
Lets keep this issue relevant to the report to avoid confusion.

**Comment by ishvaram** [comment]
@lmangani Ok I understand and inline that we should keep this in separate. But I didn't get why this needs to be raised hepic.
What exactly you mean by Transaction tracking feature? What i need is just one row per call ID instead of showing all events in Homer UI.

@adubovikov Do you have any suggestions?

**Comment by adubovikov** [comment]
if it goes to correct port, check if you have received any data in this API call. Some examples will be not bad.
Also, please provide the topology, because  we have tested homer-app on port 80 and we don't have any issues so far

**Comment by ishvaram** [comment]
@adubovikov I just re-build homer-app again and now its working fine.

**One last question:**
is it possible to show one record per call instead of showing all the rows in homer-app?

**Comment by adubovikov** [comment]
@ishvaram as @lmangani already wrote, if you don't have CDR and want to generate it base on your SIP messages, this feature is availble in HEPIC platform (hepic.tel)

and we glad that you solved your issue. Don't forget star our project:

https://github.com/sipcapture/homer/stargazers

**Comment by ishvaram** [comment]
@adubovikov my question is slightly different, I don't want to generate a CDR from this sip trace. I just need a different visualization

Currently, for one call I've traces like below showing all the transactions in the UI for one call.
![alltraces](https://user-images.githubusercontent.com/4301774/92443432-20db7900-f1cf-11ea-92f3-3dba0e1a2d7b.png)

But instead, I need only one trace per call to be shown on the dashboard of homer. like below
![whatwenned](https://user-images.githubusercontent.com/4301774/92443525-3baded80-f1cf-11ea-89bc-628711048e26.png)

**Comment by adubovikov** [comment]
@ishvaram this is CDR/TDR view  - Call Detail Record ;-) 
you can isolate your trace filtering by method INVITE

**Comment by ishvaram** [comment]
@adubovikov is possible to apply the filter by default when i open the widget, instead we manually applying filter?

**Comment by adubovikov** [comment]
@ishvaram you can implement it using your local storage.  The project is open for contribution :-)

**Comment by ishvaram** [comment]
@adubovikov Can you give some more insights. Ready to take this up and contribute :)

**Comment by adubovikov** [comment]
you have to read/write the settings from/to your local storage. You can check how it has been implemented in the proto search widget.
