### ISSUE TITLE
Search results and time+date must correlate to display graphs correctly

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/homer-app#389]
(Homer 7.7.034)
e.g.

call search -> session ID -> specified

Search results show only that call. OK - expected.

But to correctly display all of the call graph, the date+time must be correctly specified: only packets whose timestamp falls between the start date+time and the end date+time will appear on the graph. 

e.g. if I have calls "from the last five minutes" specified, but a call-ID is already an hour old, I see the search results, but the graph is empty etc....

😢

**Comment by systemcrash** [comment]
Homer could/should auto adjust date+time ranges which encompass displayed search results, so call graphs render correctly.

**Comment by systemcrash** [comment]
This problem mainly manifests when I performed a search and the result was actually e.g. 'within the last 5 minutes' (go away, do something else, return 15 minutes later) and clicking to view the graph. Perhaps clicking on the graph can pass parameters to modify date+time.....

**Comment by adubovikov** [comment]
did you test with the latest devel branch ?

**Comment by adubovikov** [comment]
the version 1.3.0 has been released. Please install it and retest it.

**Comment by adubovikov** [comment]
Please install homer-app-1.4.0 and test again
