### ISSUE TITLE
Wrong time interval selection in the search menu

### ISSUE THREAD

**Issue by uazham** [sipcapture/homer-app#391]
I have a server with Centos 7 and with UTC timezone
Homer-app was installed using homer_installer.sh according to
https://github.com/sipcapture/homer-installer
My current version is 7.8.2
Last updates were installed using yum 

SIP server configured with UTC timezone is sending packets to Homer 7. Packets saved in DB are in UTC

In the Search menu I can select timezone to display packets in the result table BUT the time for search I should enter in my local timezone and this is not correct (uncomfortably/confuses)
In my opinion if I have selected timezone UTC in the search menu then I should enter the time interval for search in UTC

And the second question is how can I change default timezone in the search menu?

**Comment by lmangani** [comment]
You can choose the timezone you want you client to use to perform queries. 
Not all users are the same, the only option is to provide flexibility :)

![image](https://user-images.githubusercontent.com/1423657/95436687-687f2d00-0954-11eb-9b79-1fdf59c54b3f.png)

**Comment by uazham** [comment]
>>You can choose the timezone you want you client to use to perform queries.
This selection is not saved after logout/login

But the main problem is in time selection:
For example my call was started at 08:01 UTC and finished at 08:02 UTC (SIP server timezone and Homer server timezone is in UTC)
My local timezone is GMT+3. If I will fill the time fields with 08:00:00 and 08:03:00 Etc/UTC) then the call will not be displayed
Currently I should fill time to search in my local timezone  starting from 11:00:00 till 11:03:00 to find the call or use default time from 00:00:00 till 23:59:59
BUT usage of such big interval causing a high load on server due to big data in DB

**Comment by lmangani** [comment]
Just select UTC as your timezone? About the load, that's a completely unrelated issue related to capacity planning.

**Comment by adubovikov** [comment]
about save param - we will check

**Comment by uazham** [comment]
>Just select UTC as your timezone? About the load, that's a completely unrelated issue related to capacity planning.

Just tell me why I cannot find the call using more accurate interval? This question is not related to capacity planning
![gmt3-found](https://user-images.githubusercontent.com/33671443/95440959-3b397b80-0962-11eb-9110-3c1405450601.PNG)
![utc-empty](https://user-images.githubusercontent.com/33671443/95440991-442a4d00-0962-11eb-8842-21c86108d367.PNG)

**Comment by lmangani** [comment]
> BUT usage of such big interval causing a high load on server due to big data in DB
I was referring to this part

**Comment by adubovikov** [comment]
@uazham can you please show the params that have been sent in the API ? (F12 -> network console) 
I am more interesting for time: {from/to}

**Comment by adubovikov** [comment]
so, Just did a test:
![Screenshot from 2020-10-08 12-39-25](https://user-images.githubusercontent.com/4513061/95448292-64a6d700-0963-11eb-9383-4f1dca916484.png)

and it sends:

```
param: {transaction: {}, limit: 200, search: {1_call: []}, location: {},…}
timestamp: {from: 1602108000000, to: 1602194399000}
from: 1602108000000
to: 1602194399000
```

1602108000000  - 10/07/2020 @ 10:00pm (UTC)

![Screenshot from 2020-10-08 12-39-47](https://user-images.githubusercontent.com/4513061/95448377-8dc76780-0963-11eb-9dc5-31ce05cd7fe6.png)

```
timestamp: {from: 1602115200000, to: 1602201599000}
from: 1602115200000
to: 1602201599000
```

1602115200000 - 10/08/2020 @ 12:00am (UTC)

Please be sure, you first selected a time zone -> press apply and after select the time range again.

**Comment by uazham** [comment]
>Please be sure, you first selected a time zone -> press apply and after select the time range again.
I have tried it.
You may check result on the picture.
![gmt3-timestamp](https://user-images.githubusercontent.com/33671443/95455437-8cec0100-0976-11eb-8435-997e54cb4899.PNG)

**Comment by adubovikov** [comment]
confirmed. It's not working for custom zone, only for predefined. Let us check! Thanks for report

**Comment by adubovikov** [comment]
we have implemented the local storage for timezones, fixed restore pararameters for the datetime picker, added timezones in the result. Version 7.8.3 in the develop branch. Please test it and let us know if it solve your issues and after we will push it to the master branch. Thank you!


![Screenshot from 2020-10-11 12-04-18](https://user-images.githubusercontent.com/4513061/95676244-e2195400-0bbc-11eb-9643-c70fc767e48b.png)


![Screenshot from 2020-10-11 12-20-53](https://user-images.githubusercontent.com/4513061/95676249-e3e31780-0bbc-11eb-8135-73844e647770.png)

**Comment by uazham** [comment]
Unfortunately I cannot find "devel" branch of homer-app
Could you please clarify should I clone "devel" branch of Homer-UI https://github.com/sipcapture/homer-ui/tree/devel and somehow integrate it in my current installation (https://github.com/sipcapture/homer-installer + yum) or clone master branch of homer-app and somehow change it to use devel branch of homer-ui during make process?
Thank you in advance.

**Comment by adubovikov** [comment]
ah, sorry, yes, this is homer-ui. You have to compile new dist and test it

git clone -b devel http://github.com/sipcapture/homer-ui
cd homer-ui
npm install
npm run build

and after copy dist to your homer-app's dist directory

**Comment by uazham** [comment]
After "npm run build" and moving contents of "dist" to /usr/local/homer/dist
I can see an infinite try to show me a login screen (cookies and cache were cleared)
![image](https://user-images.githubusercontent.com/33671443/95730272-b4004680-0c86-11eb-8be9-146cfa8d8aef.png)

**Comment by adubovikov** [comment]
It doesn't say too much. Please show your Web devel console (F12)

**Comment by uazham** [comment]
Cold you tell me what what tab of console I need to show?
"Console" tab show me the following errors:
![image](https://user-images.githubusercontent.com/33671443/95731420-2e7d9600-0c88-11eb-9a69-71e1641f2f69.png)

**Comment by adubovikov** [comment]
can you show me the result of ls -l in your /usr/local/homer/dist ?

**Comment by adubovikov** [comment]
lets do this way:

run not "npm run build", but "ng build --prod" and copy the files one
more time

**Comment by adubovikov** [comment]
or you can run:

npm run build-keep-js

**Comment by uazham** [comment]
[root@homer7 dist]# ls -la
total 2396
drwxr-xr-x 3 root root   4096 Oct 12 09:44 .
drwxr-xr-x 7 root root   4096 Oct 12 09:42 ..
-rw-r--r-- 1 root root  54026 Oct 11 19:49 3rdpartylicenses.txt
drwxr-xr-x 4 root root   4096 Oct 11 19:49 assets
-rw-r--r-- 1 root root   1150 Oct 11 19:49 favicon.ico
-rw-r--r-- 1 root root   4891 Oct 11 19:49 index.html
-rw-r--r-- 1 root root 991042 Oct 11 19:49 main.9ef1d42436b3e37731d4.js.gz
-rw-r--r-- 1 root root 143258 Oct 11 19:49 MaterialIcons-Regular.4674f8ded773cb03e824.eot
-rw-r--r-- 1 root root 128180 Oct 11 19:49 MaterialIcons-Regular.5e7382c63da0098d634a.ttf
-rw-r--r-- 1 root root  57620 Oct 11 19:49 MaterialIcons-Regular.83bebaf37c09c7e1c3ee.woff
-rw-r--r-- 1 root root  44300 Oct 11 19:49 MaterialIcons-Regular.cff684e59ffb052d72cb.woff2
-rw-r--r-- 1 root root  12440 Oct 11 19:49 polyfills.a56ce1af579b5175dbe7.js.gz
-rw-r--r-- 1 root root  44411 Sep 14 10:24 polyfills-es5.5c18e42a12971a582433.js.gz
-rw-r--r-- 1 root root 171272 Oct 11 19:49 Roboto-Regular.03523cf578d69fa92322.ttf
-rw-r--r-- 1 root root    751 Oct 11 19:49 runtime.acf0dec4155e77772545.js.gz
-rw-r--r-- 1 root root 397300 Oct 11 19:49 scripts.ff754b2dda50d6e94971.js.gz
-rw-r--r-- 1 root root 355015 Oct 11 19:49 styles.8ce088cff68721a3d641.css
-rw-r--r-- 1 root root   7180 Oct 11 19:49 worker-json.js.gz


Let me try suggested commands...

**Comment by uazham** [comment]
result of  "npm run build-keep-js"

WARNING in /root/homer-ui-update/homer-ui/src/karma.conf.js is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
WARNING in /root/homer-ui-update/homer-ui/src/app/components/widgets/pcap-widget-component/modules/hep-js/test/index.js is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
WARNING in /root/homer-ui-update/homer-ui/src/environments/environment.dev.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
WARNING in /root/homer-ui-update/homer-ui/src/environments/environment.prod.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
WARNING in /root/homer-ui-update/homer-ui/src/environments/environment.webapp.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
WARNING in /root/homer-ui-update/homer-ui/src/main.ts depends on 'hammerjs'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
WARNING in /root/homer-ui-update/homer-ui/node_modules/ngx-daterangepicker-material/__ivy_ngcc__/fesm2015/ngx-daterangepicker-material.js depends on 'moment-timezone'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
WARNING in /root/homer-ui-update/homer-ui/node_modules/ng2-charts/__ivy_ngcc__/fesm2015/ng2-charts.js depends on 'chart.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

gzip: invalid option -- 'k'
Try `gzip --help' for more information.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! homer-ui@7.8.1 build-keep-js: `ng build --prod && gzip -9 -k ./dist/homer-ui/*.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the homer-ui@7.8.1 build-keep-js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-12T09_50_09_000Z-debug.log

Unfortunately I'm not familiar well with nodejs. Should I install some specific packages (yarn, ng, etc)?

**Comment by adubovikov** [comment]
looks like you have very specific linux. Normally gzip should have option
-k (--keep)

anyway, run:

ng build --prod

and after copy the files to the dist

**Comment by uazham** [comment]
Unfortunately still show errors after "ng build --prod"
[build-output.txt](https://github.com/sipcapture/homer-app/files/5364661/build-output.txt)

![image](https://user-images.githubusercontent.com/33671443/95738524-10b52e80-0c92-11eb-9c7c-a2f0c5c49356.png)

And gzip on Centos 7 do not have -k option

**Comment by adubovikov** [comment]
please pull the last devel branch and after:

npm run build-noenv

and copy dist and retest it

**Comment by uazham** [comment]
Now both options are working fine:
1. Search with timezone for the custom interval
2. Saving timezone settings after logout/login
Thank you!

**Comment by adubovikov** [comment]
ok, we will push the changes to the master. 

You know that to do here:  https://github.com/sipcapture/homer/stargazers
