### ISSUE TITLE
How to add sip headers to data_header 

### ISSUE THREAD

**Issue by duarterocha91** [sipcapture/homer-app#393]
Hello all, 

I need to add the Cseq header contained in the "raw" column to the data_header column. Is this possible?

What's the best method?

Cheers

**Comment by adubovikov** [comment]
Please follow these discussions:

https://github.com/sipcapture/homer-app/issues/278

https://github.com/sipcapture/heplify-server/issues/310#issuecomment-627228725

**Comment by adubovikov** [comment]
did we answer on your question ?
