### ISSUE TITLE
SIP flow visualization and Export Pcap is not working

### ISSUE THREAD

**Issue by ishvaram** [sipcapture/homer-app#394]
@lmangani  @adubovikov 
I've encountered with weird issue 

**issue 1:** SIP flow visualization of a call is not working. not working meaning the popup is keep on loading forever. it doesn't render the tabs where we see Messages, Flow, QoS, Loki, Export.

**issue 1:** Export pcap file is empty after downloading. I see below error

![export_pcap](https://user-images.githubusercontent.com/4301774/96680085-78563280-1392-11eb-9fb8-fdff8b8bc92a.png)

I'm using the source from git tag 1.1.8. I see both of these issues are fixed and I don't find a branch where all these fixes are available? Can you guys please point me to the correct git branch or git tag?

**Comment by adubovikov** [comment]
if you can take master's branch of homer-ui and homer-app it will be great

**Comment by ishvaram** [comment]
@adubovikov master branch doesn't have a dist folder and I believe dist folder is needed for the UI.

I'm just running the homer-app. if i run with homer-app master branch it doesn't show any UI, its acting as a API only

Currently i'm running homer-app from the tag 1.1.8 only i'm able to see the dashboard.

```
if you can take the master's branch of homer-ui and homer-app it will be great
```
by above comment you mean to say i've to build both the binaries and run it in the machine

Please correct if i'm doing something wrong

**Comment by jacovinus** [comment]
@ishvaram, please try with the homer-app [Last Release: 1.2.5](https://github.com/sipcapture/homer-app/releases/tag/1.2.5)

**Comment by adubovikov** [comment]
we will release a new release today

**Comment by ishvaram** [comment]
@adubovikov Should i take the new release then or the one which is pointed by @jacovinus ?

**Comment by adubovikov** [comment]
if you don't want wait, you can take that @jacovinus said.

**Comment by ishvaram** [comment]
is Last Release: 1.2.5 and new release thats gonna come up, both are same ? @adubovikov

**Comment by adubovikov** [comment]
@ishvaram no

**Comment by ishvaram** [comment]
@adubovikov which one do you recommend? 1.2.5 or latest release (if it has additional features)

**Comment by adubovikov** [comment]
I wrote you already. If you don't want to wait, take 1.2.5. More I couldn't tell you

**Comment by ishvaram** [comment]
@adubovikov I will wait, where can I get the latest-stable release details? do we post anywhere?

**Comment by adubovikov** [comment]
we release packages and we do also tags here https://github.com/sipcapture/homer-app/releases

**Comment by ishvaram** [comment]
@adubovikov and @jacovinus I've to download the binary from the release and deployed. It's still the same with the SIP flow loading and pcap download part.

![pcapnotloading](https://user-images.githubusercontent.com/4301774/96717628-68574680-13c4-11eb-8cb9-ddce6f80b4b1.png)

**Comment by adubovikov** [comment]
it's great that you donwload the binary, but did you upgrade the UI ? Whats version do you have in the title ?

**Comment by ishvaram** [comment]
I haven't upgraded the UI? how to do that? 

```
Whats version do you have in the title ?
```
HOMER 7.7.010(prod) this is what i see in the title

**Comment by adubovikov** [comment]
if you will be read my replies and not make assumptions you would finished it couple steps before.
two ways as I said:

1. install packagecloud : https://github.com/sipcapture/homer/wiki/Quick-Install#debian

or
2. take the release files from here: https://github.com/sipcapture/homer-app/releases/tag/1.2.6  
specialy: https://github.com/sipcapture/homer-app/releases/download/1.2.6/homer-ui-7.8.5.tgz and push to your /usr/local/homer/dist

so, again: Please follow the instructions. Otherwise nobody couldn't help you

**Comment by ishvaram** [comment]
@adubovikov To be honest, The steps not documented well. right from the beginning. I understand that this is open source. 
Download tar ball of homer-ui and updating with dist directory is something internal to this project which is not documented anywhere?

If this would've communicated earlier clearly, Yes this thread wouldn't be gone this long. 

Having said that, Thanks a ton though! I've followed your clearly written instruction of above one and all my issues are fixed now. thanks once again.

**Comment by lmangani** [comment]
@ishvaram you're welcome - the extra procedure is just a manual override in case you wanted to know how to do so, while a normal user should just install the packages and we worked quite hard to make this even possible. If you think the docs are inaccurate or can be improved, please help by submitting a PR with your changes - that's how a community should operate after all.

Thanks for your report!

**Comment by adubovikov** [comment]
great that this has been fixed, but I wanna point your attention to the "To be honest, The steps are not documented well". We spend our time to help you to solve your issue and honestly we don't need "Thanks a ton though!", but a some help to inprove the documentation will be more than welcome.

**Comment by ishvaram** [comment]
@adubovikov Surely,  Will be updating the wiki page over the weekend. Appreciate the prompt reply :)

**Comment by adubovikov** [comment]
thanks in advice!
