### ISSUE TITLE
How does one update the Call search -> Logs -> Loki strings?

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/homer-app#397]
LogQL field is pre-filled with: `{job="heplify-server"}` - how does one change this?

Could not find it ...

**Comment by lmangani** [comment]
Hi Paul, are you referring to the Session Logs tab query (which is editable) or to the Loki search widget here?

**Comment by systemcrash** [comment]
Tab. 

It seems like this label is [hard-coded](https://github.com/sipcapture/homer-ui/blob/420f257183ad85007432e90a5bcac9d43dd01dd7/src/app/components/search-grid-call/detail-dialog/tab-loki/tab-loki.component.ts#L43): this should be made configurable. 

Loki 2 just arrived, and the label formatting has been improved, esp for people who use `syslog` like me:

e.g.

This does not work:
`{job="heplify-server"} b8be56f-1219057c747-7be12060@sipgt-0cb09c9b`
but this does
`{job="heplify-server"}|="b8be56f-1219057c747-7be12060@sipgt-0cb09c9b"`

So how can I tweak this in Homer? Possible today?

**Comment by systemcrash** [comment]
https://grafana.com/blog/2020/10/28/loki-2.0-released-transform-logs-as-youre-querying-them-and-set-up-alerts-within-loki

**Comment by lmangani** [comment]
Tab query is editable and user is expected to change it to their likes. This said, we can't assume everyone is immediately using loki v2 API (which we support also in other elements) so to be sure we need to move this into an advanced variable to be made configurable.

**Comment by systemcrash** [comment]
Is there some javascript magic that can be run to wrap the call-id in e.g.
`|="call-id"`

For multiple call-ids, something slightly more complex is required.

**Comment by lmangani** [comment]
yes we can consider adding it in the coming day, but right now, this is more supposed to be a "ready to use" search window into Loki rather than a preset or query builder per se. That's more of a starting point. 
![ezgif com-optimize (76)](https://user-images.githubusercontent.com/1423657/97627731-13eb4100-1a2c-11eb-8366-7f825895a3ed.gif)

**Comment by lmangani** [comment]
We need to map [this template](https://github.com/sipcapture/homer-ui/blob/407f7e4a26a51983502c35a85aebef1a9c9cdc42/src/app/components/search-grid-call/detail-dialog/tab-loki/tab-loki.component.ts#L43) to an advanced variable to make it flexible enough.

**Comment by systemcrash** [comment]
Ah, OK. Understood - just that the TS source has:

`${labels}` - and I was wondering whether the user can mutate this before it goes to the Loki LogQL field

**Comment by lmangani** [comment]
```
{job="heplify-server"}|="${labels}"
`` ``

**Comment by lmangani** [comment]
Might have to change the current `|` separators too if you expect multiple ids otherwise, but we don't want to assume the backend version or build anything more than a simple template here, so it should be kept template-friendly to be useful to everyone.

**Comment by systemcrash** [comment]
It seems to me that the `heplify-server` part, is an assumption that heplify-server handles ingress logs also. 

But we're just bringing logs in via syslog, so *nothing* is tagged, and searching for the call-id with the label as is produces only:

```
2020-10-29 21:02:19.019
i: zx6ivNkCBwHEjak4QF@sipgt-49c52a68
2020-10-29 21:02:19.018
i: zx6ivNkCBwHEjak4QF@sipgt-49c52a68
2020-10-29 21:02:19.018
i: zx6ivNkCBwHEjak4QF@sipgt-49c52a68
2020-10-29 21:02:19.015
i: zx6ivNkCBwHEjak4QF@sipgt-49c52a68
2020-10-29 21:02:19.014
i: zx6ivNkCBwHEjak4QF@sipgt-49c52a68
2020-10-29 21:02:19.012
i: zx6ivNkCBwHEjak4QF@sipgt-49c52a68
2020-10-29 21:02:09.899
Call-ID: zx6ivNkCBwHEjak4QF@sipgt-49c52a68
2020-10-29 21:02:09.899
Call-ID: zx6ivNkCBwHEjak4QF@sipgt-49c52a68
```

and not the rest of the desired message parts..... ;)

**Comment by systemcrash** [comment]
> ```
> {job="heplify-server"}|="${labels}"
> `` ``
> ```

I point out [here](https://grafana.com/blog/2020/10/28/loki-2.0-released-transform-logs-as-youre-querying-them-and-set-up-alerts-within-loki/) that:
```Things in orange you should already be familiar with. Filtering on log content with |= != |~ and !~, and converting your logs into metrics with rate and count_over_time were available in Loki 1.x. Everything else in white is new in 2.0...```

**Comment by lmangani** [comment]
@AlexeyOplachko could we make [this template](https://github.com/sipcapture/homer-ui/blob/407f7e4a26a51983502c35a85aebef1a9c9cdc42/src/app/components/search-grid-call/detail-dialog/tab-loki/tab-loki.component.ts#L43) a Loki object variable via advanced settngs?

Example: 
![image](https://user-images.githubusercontent.com/1423657/97704036-f19c0680-1ab1-11eb-93a7-521dc45fcb43.png)

Potential tasks: 
* define and discuss variable naming
* change static template to use variable
* change default loki advanced settings defaults to include a template

**Comment by systemcrash** [comment]
To be immediately helpful, I note that a `|~` i.e. regex match is more useful than `|=` literal string match. 

For calls with multiple legs, labels comprised of a or b form, e.g. `a|b` should be (must be):

`{job="heplify-server"}|~"a|b"` 

No extra white-space. As
`{job="heplify-server"}|~"a | b"` 
is not the same as
`{job="heplify-server"}|~"a|b"` 

Altho, if I modify the expression that pre-fills the field to the above 'regex or' format, I get everything back:
`{job="heplify-server"} |~"UVdJEhSH7IHYgB56Ql@ip|UVdJEhSH7IHYgB56Ql@asdf"`


buuuut....


if I remove the trailing space after the braces, I get only the desired results (good thing):
`{job="heplify-server"}|~"UVdJEhSH7IHYgB56Ql@ip|UVdJEhSH7IHYgB56Ql@asdf"`

**Comment by systemcrash** [comment]
Also, all Log results in this window get hacked up for HTML display:

`To: &lt;sip:+567...`
instead of 
`To: <sip:+567...`

The JSON returned shows all angle brackets in the headers are intact, however.

**Comment by systemcrash** [comment]
The HTML returned in the LogQL results is not even used (bloat):

`<div class="item-tex-loki hover loki-highlight lokimessage"><span></span>C<span></span>A<span></span>N<span></span>C<span></span>E<span></span>L<span></span> <span></span>s<span></span>i<span></span>p<span></span>:<span></span>s<span></span>t<span></span>p<span></span>k<span></span>v<span></span>r<span></span>t<span></span>@<span></span>1<span></span>0<span></span>.<span></span>4<span></span>8<span></span>.<span></span>8<span></span>.<span></span>2<span></span>0<span></span>:<span></span>3<span></span>2<span></span>7<span></span>6<span></span>8<span></span>;<span></span>l<span></span>i<span></span>n<span></span>e<span></span>=<span></span>i<span></span>7<span></span>x<span></span>e<span></span>2<span></span>k<span></span>g<span></span>x<span></span> <span></span>S<span></span>I<span></span>P<span></span>/<span></span>2<span></span>.<span></span>0<span></span>
<span></span>`

Plz fix ☹️

**Comment by AlexeyOplachko** [comment]
> The HTML returned in the LogQL results is not even used (bloat):
> 
> `<div class="item-tex-loki hover loki-highlight lokimessage"><span></span>C<span></span>A<span></span>N<span></span>C<span></span>E<span></span>L<span></span> <span></span>s<span></span>i<span></span>p<span></span>:<span></span>s<span></span>t<span></span>p<span></span>k<span></span>v<span></span>r<span></span>t<span></span>@<span></span>1<span></span>0<span></span>.<span></span>4<span></span>8<span></span>.<span></span>8<span></span>.<span></span>2<span></span>0<span></span>:<span></span>3<span></span>2<span></span>7<span></span>6<span></span>8<span></span>;<span></span>l<span></span>i<span></span>n<span></span>e<span></span>=<span></span>i<span></span>7<span></span>x<span></span>e<span></span>2<span></span>k<span></span>g<span></span>x<span></span> <span></span>S<span></span>I<span></span>P<span></span>/<span></span>2<span></span>.<span></span>0<span></span> <span></span>`
> 
> Plz fix ☹️

Can you please clarify where you're getting this? Because this doesn't seem to happen neither on Chrome nor on FF. I'm getting just text inside of <div class="item-tex-loki hover loki-highlight lokimessage">

**Comment by systemcrash** [comment]
Like this:
![bloatedhtml](https://user-images.githubusercontent.com/647633/98707662-92c37080-2380-11eb-8aec-3e9bb09f1589.png)

**Comment by systemcrash** [comment]
Span and formatting errors seem fixed in v1.3.0 🤩 
Default `{job="heplify-server"}|~"..."` is much better and works. 

Was this supposed to be in there also?:

> @AlexeyOplachko could we make [this template](https://github.com/sipcapture/homer-ui/blob/407f7e4a26a51983502c35a85aebef1a9c9cdc42/src/app/components/search-grid-call/detail-dialog/tab-loki/tab-loki.component.ts#L43) a Loki object variable via advanced settngs?

**Comment by AlexeyOplachko** [comment]
Yes, template should look like following: 
`    "template": {
        "lineFilterOperator": "|~",
        "logStreamSelector": "{job=\"heplify-server\"}"
    }`
In advanced setting `category: Search` `param: lokiserver`

**Comment by systemcrash** [comment]
> Yes, template should look like following:
> ` "template": { "lineFilterOperator": "|~", "logStreamSelector": "{job=\"heplify-server\"}" }`
> In advanced setting `category: Search` `param: lokiserver`

Hmm. No worky. ☹️ 

```javascript
{
    "host": "http://blah:3100"
    "template": { "lineFilterOperator": "|~", 
    "logStreamSelector": "{job=\"something\"}" }
}
```

**Comment by systemcrash** [comment]
In both of these LogQL cases, if I copy/paste the expression in Grafana explore, it returns the results perfectly. So the expressions are fine.

**Comment by AlexeyOplachko** [comment]
> > Yes, template should look like following:
> > ` "template": { "lineFilterOperator": "|~", "logStreamSelector": "{job=\"heplify-server\"}" }`
> > In advanced setting `category: Search` `param: lokiserver`
> 
> Hmm. No worky. ☹️
> 
> ```js
> {
>     "host": "http://blah:3100"
>     "template": { "lineFilterOperator": "|~", 
>     "logStreamSelector": "{job=\"something\"}" }
> }
> ```
> 
> Still displays `{job="heplify-server"}`

You missed a comma after host param ;)

**Comment by systemcrash** [comment]
Yup 🤦  fixed. Thank you.

**Comment by systemcrash** [comment]
> I also get a stackdump `t is null` error when I start to type `{` to trigger a label fetch.
> I think this is related to #305

Still get this though, for fetching labels, after I fixed the JSON typo.
