### ISSUE TITLE
Cannot close Settings -> User Settings prefs windows once open

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/homer-app#398]

**Comment by systemcrash** [comment]
![Screenshot 2020-10-29 at 21 13 36](https://user-images.githubusercontent.com/647633/97636004-a09bfc00-1a38-11eb-96ad-194174ac2aa6.png)
Nothing, close, save, cancel - nothing works.

**Comment by AlexeyOplachko** [comment]
Fixed on devel branch

**Comment by adubovikov** [comment]
the version 1.3.0 has been released. Please install it and retest it.

**Comment by systemcrash** [comment]
Seems fixed 🤩
