### ISSUE TITLE
Mouse-over the call search home page `pagination` panel at the bottom error

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/homer-app#399]
```
ERROR TypeError: i is undefined
    changeCurrent http://myhost/main.f88a1aa9c21097caf8a8.js:1
    gF http://myhost/main.f88a1aa9c21097caf8a8.js:1
    na http://myhost/main.f88a1aa9c21097caf8a8.js:1
    r http://myhost/main.f88a1aa9c21097caf8a8.js:1
    Kh http://myhost/main.f88a1aa9c21097caf8a8.js:1
    invokeTask http://myhost/polyfills.a56ce1af579b5175dbe7.js:1
    onInvokeTask http://myhost/main.f88a1aa9c21097caf8a8.js:1
    invokeTask http://myhost/polyfills.a56ce1af579b5175dbe7.js:1
    runTask http://myhost/polyfills.a56ce1af579b5175dbe7.js:1
    invokeTask http://myhost/polyfills.a56ce1af579b5175dbe7.js:1
    _ http://myhost/polyfills.a56ce1af579b5175dbe7.js:1
    k http://myhost/polyfills.a56ce1af579b5175dbe7.js:1
main.f88a1aa9c21097caf8a8.js:1:2360674
```

**Comment by systemcrash** [comment]
![Kapture 2020-10-29 at 22 42 49](https://user-images.githubusercontent.com/647633/97635827-4b5fea80-1a38-11eb-9db3-128b858e0342.gif)

**Comment by adubovikov** [comment]
We did a fix here, https://github.com/sipcapture/homer-ui/commit/de1c695aed2bdb62cfae099e2c82f6480ad991bc

but a bit more info how it happend will be more than welcome :-)

**Comment by systemcrash** [comment]
Your comment gives me an idea: if you're so sure you've fixed it, stick it in main (tho for some stuff that might be dangerous). Can you cook up a homer-webapp-dev which includes the latest dev branch merges? Then I can pull that docker image in and test exclusively that 'thing'. For things where community feedback is necessary to confirm a fix, this -dev image is a win, I think.

**Comment by systemcrash** [comment]
Is fix in master yet?

**Comment by adubovikov** [comment]
the version 1.3.0 has been released. Please install it and retest it.

**Comment by systemcrash** [comment]
Seems fixed 🤩
