### ISSUE TITLE
Visualize OPTIONS Method

### ISSUE THREAD

**Issue by Sp0rN** [sipcapture/homer-app#401]
Hi Guys, small issue...(or lack of understanding :P )

Im trying to view OPTIONS message flow in homer-app, but when searching for the OPTIONS method, I get no results in my search widget. I've confirmed these are in the DB, I'm just not able visualise them in the homer GUI. Im able to see all the standard SIP Invite traces, but no OPTIONS, or REGISTERS (not interested in register though).

I had a look at the mappings but I dont have a great understanding on how the mappings work...concerned I just break it.

**Comment by lmangani** [comment]
Hi @Sp0rN 
If we are talking about out-of-band options (not related to a call or registration) will be in the SIP - default protocol bucket. 
Try creating a new proto search widget for using the `SIP - default` profile and it should work.

NOTE: We're adding an option to the form itself to switch between profiles to make this more intuitive.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-ui/issues/330
the same way....

**Comment by adubovikov** [comment]
for now (current release) please create own widget for each profile (call, registration, search)

**Comment by Sp0rN** [comment]
Thanks guys, this worked, im now able to see all my OPTIONS :)

Thanks again!

**Comment by adubovikov** [comment]
you are welcome, let me close the ticket because we track the new feature in sipcapture/homer-ui#330
