### ISSUE TITLE
Hot suggestion plz: advanced setting for CSS stylesheet for message (colour) styling

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/homer-app#403]
So one can modify the rainbow here:

![Screenshot 2020-11-21 at 17 58 14](https://user-images.githubusercontent.com/647633/99882798-56ff9500-2c23-11eb-9cff-7d1fa24c8254.png)

Note also how msg details colours differ from [results panel/call graph] method colours.... - can they be synchronized?

Not criticism - colours are a good thing™ 😄

**Comment by adubovikov** [comment]
@jacovinus can you please sync it ?

**Comment by systemcrash** [comment]
(JSON also OK)

**Comment by adubovikov** [comment]
Release 1.3.6

**Comment by systemcrash** [comment]
What setting is necessary?

**Comment by adubovikov** [comment]
no settings - just default colors

**Comment by jacovinus** [comment]
closing, was already solved.
