### ISSUE TITLE
Loki Query and HEPSUB options not on all calls

### ISSUE THREAD

**Issue by thepacketlover** [sipcapture/homer-app#411]
Hello,
  I have been working with hepsub and it seems the only way on 1.3.13 I can get to the Loki query or hepsub tabs are that there has to be a record in the database for the correlation ID and HEP type 100 to enable the Logging tab.   Is that a correct assumption?

call generated with HEPGEN.js.  
![image](https://user-images.githubusercontent.com/78734572/107874725-84a65400-6e89-11eb-84fb-64c3c60b3f43.png)

If I just use heplify server and send in data and view the calls I do not get the "logs tab". that has the subtab for loki and registered hepsub endpoints.

call generated from heplify.    ./heplify -hs aaa.bbb.ccc.ddd:9060 -e
![image](https://user-images.githubusercontent.com/78734572/107874732-94259d00-6e89-11eb-8044-b52e6414dd0c.png)

The environment is hom7-prom-all on the homer7-docker project. 
Is there a way to "force" the logging tab to appear?   It seems normal to me that the tab should appear on all calls since there needs to be a query to loki or hepsub to see if data would be available.   I am relatively new here, so I hope I am not missing something obvious.

thanks

**Comment by lmangani** [comment]
Thanks @thepacketlover and indeed @adubovikov already confirmed he could replicate this undesirable condition. 
Expect a fresh fix early this week

**Comment by thepacketlover** [comment]
@lmangani   thanks for the quick response.

**Comment by jacovinus** [comment]
it should be fixed with https://github.com/sipcapture/homer-ui/pull/388

**Comment by thepacketlover** [comment]
@lmangani  @adubovikov @jacovinus   
  Looks like it is resolved.  Thank you for the quick help on this issue.

**Comment by thepacketlover** [comment]
thanks

**Comment by lmangani** [comment]
Thank you @thepacketlover

**Comment by adubovikov** [comment]
@thepacketlover thank you! Please star us also here: https://github.com/sipcapture/homer/stargazers

**Comment by jacovinus** [comment]
thanks @thepacketlover, we are pleased to help you!
