### ISSUE TITLE
Ldap or Active Directory Authentication

### ISSUE THREAD

**Issue by fabneto** [sipcapture/homer-app#412]
Hi!

I'd like to know if there is any way to configure LDAP auth and filter users by groups, by example:

user 1 - can login and is admin group (this user is part of Homer_Admins group)
user 2 - Can login and is a normal user (this user is part of Homer_Users group)
user 3 - Can't login because isn't part of any groups above

Thanks!

**Comment by adubovikov** [comment]
```
"ldap_config": {
  "admingroup": "Homer_Admins",
  "usergroup": "Homer_Users"
}

```
good luck
