### ISSUE TITLE
Support configuration reload via an API

### ISSUE THREAD

**Issue by mmerrill3** [sipcapture/homer-app#413]
Expose an API to allow readConfig() to be called again by outside processes, or sidecar containers.  This would be a POST for the homer-app to refresh it's configuration, including possible password changes to databases.

**Comment by adubovikov** [comment]
so, some params can be changed, this is not a problem, but server socket and binding can be changed only on restart.

**Comment by mmerrill3** [comment]
Thanks @adubovikov, I was interested in the database passwords.  I could see a solution where a configuration reload request is sent, and the readConfig() can be aware if the config was already read.  If so, then only look to update certain config settings, like the database passwords.

**Comment by mmerrill3** [comment]
I can try a first pass at this over the weekend.

**Comment by mmerrill3** [comment]
I believe we can just use viper to watch for changes to the file.  I am going to give the ability to turn on/off this feature via configuration.  Like this:

```
if *appFlags.WatchConfig {
		viper.WatchConfig()
	}
```

**Comment by adubovikov** [comment]
@mmerrill3 sorry - should we close the ticket ?
