### ISSUE TITLE
homer-app config file writes are switched for database_config and database_data sections.

### ISSUE THREAD

**Issue by pgopu** [sipcapture/homer-app#414]
https://github.com/sipcapture/homer-app/blob/473074c607656528d99eb01239c017d9f9a523a6/main.go#L234

appFlags.SaveHomerDbConfigToConfig calls applyDBDataParamToConfig() and
appFlags.SaveHomerDbDataToConfig calls applyDBConfigParamToConfig() 
should be switched.

**Comment by adubovikov** [comment]
Thank you. Fixed
https://github.com/sipcapture/homer-app/commit/a63bce1ccea0135a0836073ce37c6be70a1dd561

**Comment by pgopu** [comment]
Thank you @adubovikov

**Comment by adubovikov** [comment]
you are welcome and thank you as well :-)

**Comment by pgopu** [comment]
Hi Alexandr, I have a question - How do I configure Homerapp to read from
Multiple databases? Thank you!



Prameela Gopu

***@***.*** ***@***.***>

23 Main St.  • Holmdel, NJ  07733 • USA


<https://www.vonage.com/newera>Communications APIs  | Unified
Communications  | Contact Centers

NOTE: The information contained in this email message is considered
confidential and proprietary to the sender and is intended solely
for review and use by the named recipient.  Any unauthorized review, use or
distribution is strictly prohibited. If you have received this
message in error, please advise the sender by reply email and delete the
message.

**Comment by adubovikov** [comment]
Just add multiple databases in the json config and it will automatically
displayed in the drop down select menu

**Comment by pgopu** [comment]
Thanks a lot Alexandr!!!



Prameela Gopu

***@***.*** ***@***.***>

23 Main St.  • Holmdel, NJ  07733 • USA


<https://www.vonage.com/newera>Communications APIs  | Unified
Communications  | Contact Centers

NOTE: The information contained in this email message is considered
confidential and proprietary to the sender and is intended solely
for review and use by the named recipient.  Any unauthorized review, use or
distribution is strictly prohibited. If you have received this
message in error, please advise the sender by reply email and delete the
message.

**Comment by pgopu** [comment]
Hi Alexandr,

In regards to the issue #414, the problem still exists in the main.go file.
We are now calling correct function, but not sending correct parameters.
Please check the colored text.
/* now check if we do write to config */
if *appFlags.SaveHomerDbConfigToConfig {
    applyDBConfigParamToConfig(appFlags.DatabaseHomerUser,
appFlags.DatabaseHomerPassword,
            appFlags.DatabaseHomerData, appFlags.DatabaseHost,
appFlags.DatabaseSSLMode)
    os.Exit(0)
} else if *appFlags.SaveHomerDbDataToConfig {
    applyDBDataParamToConfig(appFlags.DatabaseHomerUser,
appFlags.DatabaseHomerPassword, appFlags.DatabaseHomerConfig,
            appFlags.DatabaseHost, appFlags.DatabaseHomerNode,
appFlags.DatabaseSSLMode)
    os.Exit(0)
}

Also, I have a couple of questions on how to use heplify-server and
homer-app.
Q1. I am able to search for calls by callID in homer-app. I would like to
search by a couple of sip headers. I have added them to my
heplify-server.toml file,
AlegIds                     = ["X-OpenTok-SessionId"]
DiscardMethod         = ["OPTIONS","NOTIFY"]
CustomHeader         = ["X-OpenTok-SessionId", "X-OpenTok-ConnectionId",
"X-OpenTok-StreamId"]
SIPHeader                =
["callid","callid_aleg","method","ruri_user","ruri_domain","from_user","from_domain","from_tag","to_user","to_domain","to_tag","via","contact_user"]
After adding this configuration, I sent these custom headers. But when I
search by the CorrelationID in Homer-app7, it did not return any records.
But those records were returned when I searched by Call-ID. What am I
missing? I thought once we add Custom Header, those are available for
search by correlation Id in Homerapp. Q2. How do I make heplify-server send
metrics to Prometheus? I see some docker example to install heplify-server,
homerapp5, prometheus, and Grafana Will the similar work with homer7? It
seems I need to add env variables - "HEPLIFYSERVER_PROMADDR=0.0.0.0:9096",
"HEPLIFYSERVER_PROMTARGETIP=", "HEPLIFYSERVER_PROMTARGETNAME=" to
heplify-server pod? Or do I need to add them to the config file? I have
already installed Prometheus on the same cluster.
Thanks a lot for your continuous support. I understand, I should not be
contacting you personally for my questions, but I do not know any other
way. Please let me know if there are any other channels where I can get
some help. I am searching issues on your git repositories to get
information.



Prameela Gopu

***@***.*** ***@***.***>

23 Main St.  • Holmdel, NJ  07733 • USA


<https://www.vonage.com/newera>Communications APIs  | Unified
Communications  | Contact Centers

NOTE: The information contained in this email message is considered
confidential and proprietary to the sender and is intended solely
for review and use by the named recipient.  Any unauthorized review, use or
distribution is strictly prohibited. If you have received this
message in error, please advise the sender by reply email and delete the
message.
