### ISSUE TITLE
bash: homer-app: command not found

### ISSUE THREAD

**Issue by JuanUnited** [sipcapture/homer-app#421]
Hi!
Guys, I'm having the following issue and may anyone can help me:

# homer-app -create-config-db -database-root-user=postgres -database-host="127.0.0.1" -database-root-password=postgres -database-homer-user=homer_user
bash: homer-app: command not found

![image](https://user-images.githubusercontent.com/71094708/111083144-f057fd00-84d9-11eb-8e2e-166430253ba7.png)

And when I use systemctl status homer-app.service I got this:

● homer-app.service - Homer API Server and UI Webapplication
   Loaded: loaded (/usr/lib/systemd/system/homer-app.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2021-03-14 15:27:35 -05; 2s ago
  Process: 11583 ExecStart=/usr/local/bin/homer-app (code=exited, status=2)
 Main PID: 11583 (code=exited, status=2)

.us-east-2.compute.internal systemd[1]: homer-app.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
.us-east-2.compute.internal systemd[1]: homer-app.service: Failed with result 'exit-code'.

![image](https://user-images.githubusercontent.com/71094708/111083148-f817a180-84d9-11eb-92ef-0e204a329a30.png)

Any idea?

**Comment by adubovikov** [comment]
/usr/local/homer/bin/homer-app

**Comment by JuanUnited** [comment]
> /usr/local/homer/bin/homer-app

That directory isn't created yet

**Comment by adubovikov** [comment]
so, you didn't install homer-app ?

**Comment by JuanUnited** [comment]
> so, you didn't install homer-app ?

![image](https://user-images.githubusercontent.com/71094708/111083422-87718480-84db-11eb-98b3-c3b1e57c3f81.png)
 I have that

**Comment by JuanUnited** [comment]
> so, you didn't install homer-app ?

![image](https://user-images.githubusercontent.com/71094708/111083730-f4394e80-84dc-11eb-800c-de45b4f3adfd.png)

**Comment by adubovikov** [comment]
-webapp-config-path

**Comment by adubovikov** [comment]
and 
```
find / -name webapp_config.json

**Comment by JuanUnited** [comment]
> and
> 
> ```
> find / -name webapp_config.json
> ```

![image](https://user-images.githubusercontent.com/71094708/111359260-499a6a80-8659-11eb-8ad8-116617fc2894.png)

**Comment by adubovikov** [comment]
you didn't create DB, please follow the HOWTO:

https://github.com/sipcapture/homer-app#create-table--migration---connection-data-will-be-read-from-webapp_configjson
