### ISSUE TITLE
DB Limit

### ISSUE THREAD

**Issue by JuanUnited** [sipcapture/homer-app#423]
Hi there, me again.

I'm looking for a way to put a limit in the database, for example 2 or 3 days. Any idea?

**Comment by adubovikov** [comment]
https://github.com/sipcapture/heplify-server/blob/master/example/homer7_config/heplify-server.toml#L31

**Comment by JuanUnited** [comment]
> https://github.com/sipcapture/heplify-server/blob/master/example/homer7_config/heplify-server.toml#L31

But I use captagent

**Comment by lmangani** [comment]
@JuanUnited the agents are not responsible for rotation, they only send data. the capture server receiving them is responsible for the database storage and rotation, so what you're looking for is built in on the other side of the circuit. Just read through the link and apply to your usecase.

**Comment by JuanUnited** [comment]
> @JuanUnited the agents are not responsible for rotation, they only send data. the capture server receiving them is responsible for the database storage and rotation, so what you're looking for is built in on the other side of the circuit. Just read through the link and apply to your usecase.

Understood, thank you
