### ISSUE TITLE
TypeError: Cannot read property 'protocol_id' of null

### ISSUE THREAD

**Issue by emmceemoore** [sipcapture/homer-app#424]
I've noticed an issue where some users aren't able to see the modal produced by clicking on the "Session ID" when they first use the homer-app. (They click on the "Session ID" link and nothing happens.)

In the browser console, I see the following errors:
![image (3)](https://user-images.githubusercontent.com/484429/114591611-52299500-9c47-11eb-88c5-695e2f236938.png)

These are first-time visitors to the homer-app and I've found that if they first navigate to the home page and click on some of the records there (i.e. - "Session ID" to produce a modal) that the error goes away and the modals then work on the pre-generated "search" links that we send them to.

Perhaps there's some JavaScript or data dependency that doesn't get initialized in the path that they're taking? Just a guess.

Anyway, I've got a workaround but I thought you might like to know about this issue.

Thanks for all the work you've done on Homer! It's looking like it's going to be a really helpful tool for us.

**Comment by lmangani** [comment]
Thanks for the report @emmceemoore this is a very good pointer. We'll investigate this further.

**Comment by adubovikov** [comment]
Please install homer-app-1.4.0 and test again
