### ISSUE TITLE
Same IP alias for multiple ports

### ISSUE THREAD

**Issue by bmgante** [sipcapture/homer-app#431]
Hello,
Is it possible to configure on alias entry for multiple ports? Wondering if there´s any allowed wildcard (*) that could be used.
I´d like to enrich an IP which may have random ports.

Thanks

**Comment by lmangani** [comment]
Yes. Setting the port to 0 will match any for the set IP/Range.

**Comment by bmgante** [comment]
Thanks @lmangani
