### ISSUE TITLE
Unable to select remote nodes from GUI

### ISSUE THREAD

**Issue by jvb187** [sipcapture/homer-app#432]
I have followed the instructions for multi node setup, and I see the remote connection is successful in the docker logs, however the only node I am ever able to select is the LocalNode in the GUI.

Here is the relevant section of my config:

```
 "database_data": {
    "LocalNode": {
      "help": "Database settings",
      "host": "db",
      "name": "homer_data",
      "node": "LocalNode",
      "pass": "homerSeven",
      "user": "root"
    },
    "RemoteNode": {
      "help": "Remote database settings",
      "host": "192.168.240.59",
      "name": "homer_data",
      "node": "RemoteNode",
      "user": "root",
      "pass": "homerSeven"
    }
```

Here are the logs showing that the RemoteNode was successfully connected:

```
homer-webapp      | Database provisioning completed!
homer-webapp      | Successful ping: db, Type: data, Node: LocalNode 
homer-webapp      | PostgreSQL version: 11.12
homer-webapp      |  
homer-webapp      | Successful ping: 192.168.240.59, Type: data, Node: RemoteNode 
homer-webapp      |          ___              
homer-webapp      |         /__/\             
homer-webapp      |         \  \:\           
homer-webapp      |          \__\:\  
homer-webapp      |      ___ /  /::\     
homer-webapp      |     /__/\  /:/\:\     _____ _____    
homer-webapp      |     \  \:\/:/__\/    |___  |___  |   
homer-webapp      |      \  \::/            / /   / / 
homer-webapp      |       \  \:\           / /   / /          
homer-webapp      |        \  \:\         /_(_) /_/               
homer-webapp      |         \__\/         
homer-webapp      | 
homer-webapp      |  
homer-webapp      |  Version: homer-app 1.3.23 
homer-webapp      | ⇨ http server started on [::]:80
```
I then added Nodes to my search proto, but I am only ever able to see and choose LocalNode.  Is there some other step that I am missing to have the remote nodes appear in the GUI?  I am using the latest docker build (just set this up today for testing).

Thanks,
Jeremy

**Comment by adubovikov** [comment]
can you please share your mapping for SIP call ?

**Comment by adubovikov** [comment]
look at this:
https://github.com/sipcapture/homer-app/blob/master/migration/jsonschema/jsonschema.go#L319-L323

and activate _from_api, to retrieve the list automaticaly:

```
    "form_api": "/database/node/list",
```

**Comment by jvb187** [comment]
I updated my mapping to the following:

```
{
        "id": "node",
        "name": "Node",
        "type": "string",
        "index": "none",
        "form_type": "multiselect",
        "form_default": [
            {
                "value": "localnode",
                "name": "Local node"
            }
        ],
        "form_api": "/database/node/list",
        "system_param": true,
        "mapping": "param.location.node",
        "position": 23,
        "skip": false,
        "hide": false
    },
```

I am still only seeing LocalNode in the Node selection drop down though.  Is there something else I have to do to enable the node list api?  When I try /api/database/node/list, I get {"message":"Not Found"}.

Thanks,
Jeremy

**Comment by adubovikov** [comment]
rename form_default to -> "_form_default"

**Comment by jvb187** [comment]
That did it.. thank you!

**Comment by adubovikov** [comment]
you are welcome

**Comment by adubovikov** [comment]
please star the main homer project as well :-)

https://github.com/sipcapture/homer/stargazers

**Comment by mcebey1891** [comment]
Hi,
I have a problem related to this.
I followed this thread and I have the Node field with its options visible, but they appear in gray and cannot be chosen.
The Node field appears in the results with the correct node names.
I am using the latest Docker version of Homer7.
My mapping:
    {
        "id": "node",
        "name": "Node",
        "type": "string",
        "index": "none",
        "form_type": "multiselect",
        "form_default": [
            {
                "value": "ims",
                "name": "IMS"
            }
        ],
        "form_api": "/database/node/list",
        "system_param": true,
        "mapping": "param.location.node",
        "position": 23,
        "skip": false,
        "hide": false
    }

Thanks,
Mariano
