### ISSUE TITLE
Date/time picker appears to be buggy.

### ISSUE THREAD

**Issue by emmceemoore** [sipcapture/homer-app#433]
When entering custom values in the date/time range data picker I notice weird behavior.
- Input values don't "stick".
- Other values unexpectedly change.

This is the "picker" I'm referring to:
![image](https://user-images.githubusercontent.com/484429/128776698-691a4b0d-988a-4c4d-b47f-e7e7ccacaf6e.png)

In this ☝️ screenshot I have the hour (`07`) selected. If I type `11`, then I get this:
![image](https://user-images.githubusercontent.com/484429/128776800-965c85d6-cc8a-4164-af2c-e1883d490a1a.png)

The hour doesn't change but the dates change to an impossible looking range. I've seen other weirdness as well when trying to input the desired values.

* * *

Versions/Configuration:
- homer-app version `7.9.18`
- Latest version of Brave Browser (`Version 1.27.111 Chromium: 92.0.4515.131 (Official Build) (x86_64)`)
- macOS 11.5.1

**Comment by AlexeyOplachko** [comment]
We're currently doing migration to Angular 12, and tons of components are refactored. And this particular issue seems to be fixed. 
Current ETA for release is friday.

**Comment by emmceemoore** [comment]
That's good to hear! Best of luck with the migration.

**Comment by emmceemoore** [comment]
@AlexeyOplachko - Hope you are well! Just checking in to see if you have a rough estimate for when you might be able to finish the Angular 12 migration.

**Comment by adubovikov** [comment]
Please install homer-app-1.4.0 and test again

**Comment by adubovikov** [comment]
so, since no feedback, I will close the ticket
