### ISSUE TITLE
Use custom header for correlation ID?

### ISSUE THREAD

**Issue by pengweichu** [sipcapture/homer-app#436]
Hi, 

Say in my SIP server, for some scenarios, like MOH, transfer, ring group, there have a lot of legs that need to be correlated for a call, I have added an ` X-Unique-Id` header for these legs, when sending the SIP messages to HOMER( I integrated the HepAgent in our application), shall I use the value of header  `X-Unique-Id`  as the correlation ID?

On the HOMER server-side, how to set the mapping for the `X-Unique-Id`?

I've read this issue: https://github.com/sipcapture/homer-app/issues/278 and see there has an example as the below, how to modify it to support my `X-Unique-Id`?  Thanks

```

[
    {
       "source_field": "data_header.callid",
        "lookup_id": 1,
        "lookup_profile": "call",
        "append_sid": true,
        "lookup_field": "data_header->>'X-CID'",
        "lookup_range": [
            -300,
            200
        ]
    },
    {
        "source_field": "data_header.X-CID",
        "lookup_id": 1,
        "lookup_profile": "call",
        "append_sid": true,
        "lookup_field": "data_header->>'X-CID'",
        "lookup_range": [
            -300,
            200
        ]
    },
    {
        "source_field": "data_header.X-CID",
        "lookup_id": 1,
        "lookup_profile": "call",
        "append_sid": true,
        "lookup_field": "data_header->>'callid'",
        "lookup_range": [
            -300,
            200
        ]
    },
    {
        "source_field": "data_header.callid",
        "lookup_id": 1,
        "lookup_profile": "call",
        "lookup_field": "sid",
        "lookup_range": [
            -300,
            200
        ]
    }
]




```

**Comment by adubovikov** [comment]
> Understand, thanks, already start it! 

nop, you start the homer-app, but not the homer :-)

https://github.com/sipcapture/homer/stargazers

**Comment by pengweichu** [comment]
> > Understand, thanks, already start it!
> 
> nop, you start the homer-app, but not the homer :-)
> 
> https://github.com/sipcapture/homer/stargazers

Done! Now I get the bash installed, working on the custom header as your guide, have a good day!

**Comment by adubovikov** [comment]
Thanks :-) have a nice week end!
