### ISSUE TITLE
Capture ID issue

### ISSUE THREAD

**Issue by mcrgnt** [sipcapture/homer-app#437]
Hello.
(dist from homer-app repository v1.4.2)

capture agent starts with flags:
./heplify -hs 192.168.10.4:9060 -nt udp -hi 1001 -hn sip3 -n log
in this case i got human readable Capture ID in ui, 

but when i try to search by Capture ID i get postgres error:
homer_user@homer_data ERROR:  invalid input syntax for integer: "sip3"

According to heplify help options:
  -hi uint
        HEP node ID (default 2002)
  -hn string
        HEP node Name

Then i was try:
./heplify -hs 192.168.10.4:9060 -nt udp -hi 2001 -hn 2001 -n log
in this case i got integer Capture ID in ui which is not so usable

I have a question, how hn option should work? Does "HEP node Name" mean capture agent name? Anyway, we have some inconsistent data with input type and ui type.

**Comment by lmangani** [comment]
@mcrgnt should use integer identifiers with hi (capture_id). hn will only work with hepfliy/heplify-server but it is experimental and hence not documented for usage or supported uniformly as of yet.  If you have inconsistencies please open separate issues.

**Comment by adubovikov** [comment]
where do you see that issue? Is it error in homer-app?

**Comment by mcrgnt** [comment]
thx for reply, 

yes in homer-app, and i use hepfliy/heplify-server bunch.
i try like lmangani advised use only -hi flag, of course it's work.

So, if i set -hn flag they just overrides -hi


p.s.
i understand that is easy just close issue, but use names is better then int ids for humans
may be just add full support for node name in homer-ui? i mean add capture_name in search fields list and don't override hi flag if hn is set.
or add support node names with aliases, aka hash name->ip, cause now setting captureid in alias actually do nothing (may be add alias search field?)

again thx for reply

**Comment by adubovikov** [comment]
> thx for reply,
> 
> "Is it error in homer-app?" yes, i think so, because setting -hn flag overrides -hi (and types mismatch)
> 
> i use hepfliy/heplify-server/homer-app/homer-ui bunch.
> i try like lmangani advised use only -hi flag, of course it's works.
> 
> p.s.
> i understand that is easy just close issue, but use names is better then int ids for humans
> may be just add full support for node name in homer-ui? i mean add capture_name in search fields list and don't override hi flag if hn is set.
> or add support node names with aliases, aka hash name->ip, cause now setting captureid in alias actually do nothing (may be add alias search field?)
> 
> again thx for reply

@lmangani closed it because this is not an issue, since the feature is/was experimental and not fully supported in the homer-app/UI. So this was total correct. But just to make all happy, it should be open as a feature request in UI/homer-app :-)

**Comment by adubovikov** [comment]
so, just checked - good news here 

System ->Mapping -> call SIP click edit. Find the capture ID and change it. After it go to widget and reassign the field :-)

![HOMER-7-10-2 (1)](https://user-images.githubusercontent.com/4513061/133000716-3b85f4f6-eaba-44a2-b201-87e648f3d348.png)

once you will figure it out, don't forget to star us :-) 

https://github.com/sipcapture/homer/stargazers

**Comment by adubovikov** [comment]
@mcrgnt   Did it help ?

**Comment by microgiantya** [comment]
yes it works!

**Comment by adubovikov** [comment]
@microgiantya so, now is your move: please give us a star https://github.com/sipcapture/homer/stargazers

**Comment by mcrgnt** [comment]
Сделано))

**Comment by adubovikov** [comment]
two accounts ? :-) two stars ? ;-) Thank you!
