### ISSUE TITLE
LDAP reconnection loop issue

### ISSUE THREAD

**Issue by bmgante** [sipcapture/homer-app#438]
Hi

Tried this config and it works, just needed to set "skipverify:true".
`https://github.com/sipcapture/homer-app/wiki/Configuring-the-connection-of-the-LDAP-module-to-the-Active-Directory-(instead-classic-LDAP)`

However i am getting an error from time to time and when it starts anyone can login anymore. Homer-app service restart works as workaround but some time after it starts again...

```
{"level":"error","msg":"Dashboard has null in the name....","time":"2021-09-14T10:00:16Z"}
{"level":"error","msg":"Couldn't auth user: unable to read LDAP response packet: unexpected EOF","time":"2021-09-14T10:06:56Z"}
{"level":"error","msg":"Couldn't auth user: LDAP Result Code 200 \"Network Error\": ldap: connection closed","time":"2021-09-14T10:07:06Z"}
{"level":"error","msg":"Couldn't auth user: LDAP Result Code 200 \"Network Error\": ldap: connection closed","time":"2021-09-14T10:07:38Z"}
{"level":"error","msg":"Couldn't auth user: LDAP Result Code 200 \"Network Error\": ldap: connection closed","time":"2021-09-14T10:07:41Z"}
```

**Comment by adubovikov** [comment]
> Hi
> 
> 
> ```
> {"level":"error","msg":"Dashboard has null in the name....","time":"2021-09-14T10:00:16Z"}
> ```
check if one of your dashboard has bad name. This you can verify in your user's settings

> ```
> {"level":"error","msg":"Couldn't auth user: unable to read LDAP response packet: unexpected EOF","time":"2021-09-14T10:06:56Z"}
> {"level":"error","msg":"Couldn't auth user: LDAP Result Code 200 \"Network Error\": ldap: connection closed","time":"2021-09-14T10:07:06Z"}
> {"level":"error","msg":"Couldn't auth user: LDAP Result Code 200 \"Network Error\": ldap: connection closed","time":"2021-09-14T10:07:38Z"}
> {"level":"error","msg":"Couldn't auth user: LDAP Result Code 200 \"Network Error\": ldap: connection closed","time":"2021-09-14T10:07:41Z"}
> ```

looks like LDAP connection has been closed and couldn't reconnect. 

Please take this release and check if it will solve the reconnect issue:
https://github.com/sipcapture/homer-app/commit/4208272937deb2bcea238974a4142a3edd28e345

**Comment by bmgante** [comment]
Issue is not occurring since installed this release. Thanks
