### ISSUE TITLE
Problem with queries to Loki from Homer

### ISSUE THREAD

**Issue by Shkiperon** [sipcapture/homer-app#439]
Hi, I have an issue with homer-app 1.4.11 - when I run LogQL query `{job="asterisk",hostname="asterisk1"} |~ "888555000111"` from the window with call flow I get a lot of rows that look like a full export from my Loki database.
When I run the same query from the Grafana panel in my dashboard, I get 2 rows with the result I am looking for.

In the dump I see that Homer-App and Grafana are making different queries.

Homer-App:
`http://10.10.1.98:3100/loki/api/v1/query_range?end=1631879031000000000&limit=100&query=%7Bjob%3D%22asterisk%22%2Chostname%3D%22asterisk1%22%7D&regexp=~+%22888555000111%22&start=1631875431000000000`
![image](https://user-images.githubusercontent.com/38580109/133792171-6df0fabd-818e-4425-a94f-c1f1663ca73e.png)

Grafana:
`http://10.10.1.98:3100/loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bjob%3D%22asterisk%22%2Chostname%3D%22asterisk1%22%7D%20%7C~%20%22888555000111%22&start=1631875484000000000&end=1631879084000000000&step=2`
![image](https://user-images.githubusercontent.com/38580109/133792326-ee8e0854-642b-413d-a355-4a1efd2f9064.png)

As you can see - the queries are the same in the beginning, but different in the GET requests to the Loki database.
How to fix this problem?

**Comment by lmangani** [comment]
Thanks for the report. Fix in progress.

**Comment by adubovikov** [comment]
homer-app-1.4.12 should have the fix for it. Please install and confirm

**Comment by Shkiperon** [comment]
Now it works correct. Thank you for help :smiley:
