### ISSUE TITLE
Add support for SAML or oauth2 SSO

### ISSUE THREAD

**Issue by Moke** [sipcapture/homer-app#440]
Hopefully this is the correct place to register a feature request.

I would like to see SAML or oauth2 based SSO added to the homer7 products. The current available solution (ldap) is less desirable than being able to use Google or AzureAD as an idp.

**Comment by adubovikov** [comment]
@Moke the version 1.4.23 has oAuth2 support

here is the an example for google:

```
"oauth2": {
    "enable": false,
    "client_id": "1234565",
    "client_secret": "FAKE",
    "project_id": "Homer OAuth",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url":  "https://www.googleapis.com/oauth2/v1/certs",
    "redirect_uri": "http://localhost:80/api/v3/oauth2/auth",
    "service_redirect": "/api/v3/oauth2/redirect",
    "profile_url": "https://www.googleapis.com/oauth2/v1/userinfo",
    "provider_name": "google",
    "scope": ["email", "openid", "profile"],
    "provider_image": ""
  },
```

**Comment by Moke** [comment]
I am working on adapting your example to work with AzureAD.

**Comment by zpnielsen** [comment]
And I'm watching him do it :)

**Comment by Moke** [comment]
Doesn't look like im able to get it working. Here's the configuration.

```
 "oauth2": {
    "enable": true,
    "client_id": "********",
    "client_secret": "**",
    "project_id": "Homer OAuth",
    "auth_uri": "https://login.microsoftonline.com/***/oauth2/v2.0/authorize",
    "token_uri": "https://login.microsoftonline.com/common/v2.0/oauth2/token",
    "auth_provider_x509_cert_url": "https://login.microsoftonline.com/******/discovery/v2.0/keys",
    "redirect_uri": "https://homer.*****.com/api/v3/oauth2/auth",
    "service_redirect": "/api/v3/oauth2/redirect",
    "profile_url": "https://graph.microsoft.com/oidc/userinfo",
    "provider_name": "azuread",
    "scope": ["email", "openid", "profile"]
  }
```


Even though i am able to successfully see the configuration using 

`/usr/local/bin/homer-app -show-current-config`


I am being redirected to google for oauth2 instead of the auth_uri defined.

**Comment by Moke** [comment]
It would appear that [on line 127 of homer-ui/src/app/components/login/login.component.ts](https://github.com/sipcapture/homer-ui/blob/34428a41533b46d525154fbb7d7aca718838b90e/src/app/components/login/login.component.ts#L127) the redirect is hardcoded to contain an invalid URL prefix of `http://homer.null.qxip.net`

```
    goOauth(type) {
        // this.router.navigate([type.url], {relativeTo: this.route}).then;
        this.router.navigate([]).then((result) => {
            window.location.href = `http://homer.null.qxip.net${type.url}`;
        });
    }
```

I suspect that this is causing my problem.

**Comment by adubovikov** [comment]
Oops. Let us fix it asap

**Comment by adubovikov** [comment]
@Moke can you please check homer-app-1.4.24 ? Thank you!

**Comment by Moke** [comment]
Having a problem with the final step in the authentication. It's redirecting to / with the ?token param but failing with a 404 HTTP response.

**Comment by adubovikov** [comment]
did you configure the api to retrieve your profile ?

**Comment by adubovikov** [comment]
@Moke are you able join us on Matrix ? 
 https://matrix.to/#/#sipcapture_homer:gitter.im

**Comment by adubovikov** [comment]
so, with 1.4.25 it works as should! Thank you @Moke !

**Comment by Moke** [comment]
Here is my latest and working configuration to use Azure AD with Homer. Sharing for anyone else.

```
 "oauth2": {
    "enable": true,
    "client_id": "****",
    "client_secret": "*****",
    "project_id": "AzureAD",
    "auth_uri": "https://login.microsoftonline.com/[AD TENANT GUID]/oauth2/v2.0/authorize",
    "token_uri": "https://login.microsoftonline.com/[AD TENANT GUID]/oauth2/v2.0/token",
    "auth_provider_x509_cert_url": "https://login.microsoftonline.com/[AD TENANT GUID]/discovery/keys",
    "redirect_uri": "https://homer.homer.net/api/v3/oauth2/auth",
    "service_redirect": "https://homer.homer.net/api/v3/oauth2/redirect",
    "profile_url": "https://graph.microsoft.com/oidc/userinfo",
    "provider_name": "microsoft",
    "scope": ["email", "openid", "profile"],
    "provider_image": ""
  }
```

**Comment by adubovikov** [comment]
@Moke thank you so much!

**Comment by adubovikov** [comment]
@Moke please star us :-) https://github.com/sipcapture/homer/stargazers

**Comment by adubovikov** [comment]
@Moke https://github.com/sipcapture/homer-app/commit/44839ca084c6aa764183f713dad52a02c838f994 

here is gravatar support
