### ISSUE TITLE
Search form results - not in date and time range

### ISSUE THREAD

**Issue by solarmon** [sipcapture/homer-app#444]
Hi,

I have experienced some sort of caching issue with the form search results - in homer-webapp 1.4.16

I had specified a date and time range and applied an empty form search, and the results are as expected.

![image](https://user-images.githubusercontent.com/46369787/137490938-ad04dca8-b7e8-4757-aae0-485c8459195d.png)

However, when I changed the search form to set only "INVITE" for the SIP Method, the results returned seems to fall outside of the specific date and time range:

![image](https://user-images.githubusercontent.com/46369787/137491042-e11f4b51-e6f1-4a9e-8418-b34dddbb1290.png)

I then noticed that if I went to the Admin Settings page and back again, without changing any settings, the search results returned was OK - it was displaying only INVITES and it was within the date and time range.

 Since then I had not been able to reproduce this specific issue. However, there seems to be some general caching issue when switching between AND and OR mode, which gets resolved when going to the Admin Settings page and back out again - the search results differ when you do this.

**Comment by adubovikov** [comment]
@solarmon do you have save issue in the latest release ?
