### ISSUE TITLE
Filter by Capture ID does not return any results

### ISSUE THREAD

**Issue by agrigorjevs** [sipcapture/homer-app#449]
Hello,

When trying to search in WEB messages by Capture ID - it never return any results.

Doesn't matter if the Capture ID is int or string (we are using hep node names instead of numeric ID's on heplify agents).

At the same time if just searching without filter and filtering capture ID on the search result itself (frontend filter) - it works.
<img width="1789" alt="Screenshot 2021-10-20 at 13 17 21" src="https://user-images.githubusercontent.com/39706760/138075300-976dc33f-16fe-4db6-ba23-c20c57c3c4e3.png">
<img width="1790" alt="Screenshot 2021-10-20 at 13 18 30" src="https://user-images.githubusercontent.com/39706760/138075464-35c27239-2169-48c8-a08c-50c2dfb261ba.png">

**Comment by adubovikov** [comment]
@agrigorjevs unfortunately I couldn't reproduce it in the latest homer-app. Whats version do you use ?
