### ISSUE TITLE
echo: http: panic serving 192.168.11.221:64820: interface conversion: interface {} is map[string]interface {}, not string

### ISSUE THREAD

**Issue by ar45** [sipcapture/homer-app#454]
Nov 05 02:14:47 homer homer-app[26586]: time="2021-11-05T02:14:47Z" level=info msg="SELECT * FROM \"user_settings\"  WHERE (category = 'dashboard' AND (username = $1 and param = $2))" module=gorm type=sql
Nov 05 02:14:47 homer homer-app[26586]: time="2021-11-05T02:14:47Z" level=info msg="SELECT count(*) FROM \"user_settings\"  WHERE (category = 'dashboard' AND (username = $1 and param = $2))" module=gorm type=sql
Nov 05 02:14:47 homer homer-app[26586]: time="2021-11-05T02:14:47Z" level=info msg="SELECT * FROM \"user_settings\"  WHERE (category = 'dashboard' AND (username = $1 OR (data ->> 'shared' = 'true' OR data ->> 'shared' = '1')))" module=gorm type=sql
Nov 05 02:14:47 homer homer-app[26586]: time="2021-11-05T02:14:47Z" level=info msg="SELECT * FROM \"alias\"  WHERE (status = true)" module=gorm type=sql
Nov 05 02:14:47 homer homer-app[26586]: time="2021-11-05T02:14:47Z" level=info msg="SELECT * FROM \"mapping_schema\"  WHERE (partid = $1)" module=gorm type=sql
Nov 05 02:14:47 homer homer-app[26586]: echo: http: panic serving 192.168.1.122:64820: interface conversion: interface {} is map[string]interface {}, not string
Nov 05 02:14:47 homer homer-app[26586]: goroutine 114 [running]:
Nov 05 02:14:47 homer homer-app[26586]: net/http.(*conn).serve.func1(0xc000121220)
Nov 05 02:14:47 homer homer-app[26586]:         /usr/local/go/src/net/http/server.go:1804 +0x153
Nov 05 02:14:47 homer homer-app[26586]: panic(0xd14f20, 0xc0003e1710)
Nov 05 02:14:47 homer homer-app[26586]:         /usr/local/go/src/runtime/panic.go:971 +0x499
Nov 05 02:14:47 homer homer-app[26586]: github.com/sipcapture/homer-app/data/service.buildQuery(0xc00048e720, 0x2, 0x2, 0x0, 0xc0002f3000, 0xe73, 0x1000, 0x0, 0x98, 0x14, ...)
Nov 05 02:14:47 homer homer-app[26586]:         /app/data/service/search.go:129 +0x4439
Nov 05 02:14:47 homer homer-app[26586]: github.com/sipcapture/homer-app/data/service.(*SearchService).SearchData(0xc000504280, 0xc00036b000, 0xc00041d188, 0xc000625700, 0x5, 0xc0002e4990, 0xc00041d088, 0x58979b, 0xc00041d108, 0xc00041d048)
Nov 05 02:14:47 homer homer-app[26586]:         /app/data/service/search.go:362 +0x7e5
Nov 05 02:14:47 homer homer-app[26586]: github.com/sipcapture/homer-app/controller/v1.(*SearchController).SearchData(0xc000502450, 0xf5bed8, 0xc0003deb80, 0xc0003deb80, 0xdf9460)
Nov 05 02:14:47 homer homer-app[26586]:         /app/controller/v1/search.go:96 +0x605
Nov 05 02:14:47 homer homer-app[26586]: github.com/sipcapture/homer-app/auth.MiddlewareRes.func1(0xf5bd08, 0xc00016a000, 0x4, 0xd10620)
Nov 05 02:14:47 homer homer-app[26586]:         /app/auth/middleware.go:27 +0x242
Nov 05 02:14:47 homer homer-app[26586]: github.com/labstack/echo/v4/middleware.JWTWithConfig.func1.1(0xf5bd08, 0xc00016a000, 0x2, 0x2)
Nov 05 02:14:47 homer homer-app[26586]:         /go/pkg/mod/github.com/labstack/echo/v4@v4.5.0/middleware/jwt.go:238 +0x3ca
Nov 05 02:14:47 homer homer-app[26586]: github.com/labstack/echo/v4.(*Echo).add.func1(0xf5bd08, 0xc00016a000, 0x1, 0x0)
Nov 05 02:14:47 homer homer-app[26586]:         /go/pkg/mod/github.com/labstack/echo/v4@v4.5.0/echo.go:544 +0x62
Nov 05 02:14:47 homer homer-app[26586]: github.com/labstack/echo/v4/middleware.GzipWithConfig.func1.1(0xf5bd08, 0xc00016a000, 0x0, 0x0)
Nov 05 02:14:47 homer homer-app[26586]:         /go/pkg/mod/github.com/labstack/echo/v4@v4.5.0/middleware/compress.go:67 +0x73a
Nov 05 02:14:47 homer homer-app[26586]: github.com/labstack/echo/v4/middleware.StaticWithConfig.func1.1(0xf5bd08, 0xc00016a000, 0xf387e0, 0xc0002e44e0)
Nov 05 02:14:47 homer homer-app[26586]:         /go/pkg/mod/github.com/labstack/echo/v4@v4.5.0/middleware/static.go:195 +0x89a
Nov 05 02:14:47 homer homer-app[26586]: main.GrafanaHeader.func1(0xf5bd08, 0xc00016a000, 0xe29aec, 0x1b)
Nov 05 02:14:47 homer homer-app[26586]:         /app/main.go:1677 +0x97
Nov 05 02:14:47 homer homer-app[26586]: github.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1(0xf5bd08, 0xc00016a000, 0x4, 0x4)
Nov 05 02:14:47 homer homer-app[26586]:         /go/pkg/mod/github.com/labstack/echo/v4@v4.5.0/middleware/cors.go:186 +0x1016
Nov 05 02:14:47 homer homer-app[26586]: github.com/labstack/echo/v4.(*Echo).ServeHTTP.func1(0xf5bd08, 0xc00016a000, 0x889a01, 0xc0004846c0)
Nov 05 02:14:47 homer homer-app[26586]:         /go/pkg/mod/github.com/labstack/echo/v4@v4.5.0/echo.go:648 +0x111
Nov 05 02:14:47 homer homer-app[26586]: github.com/labstack/echo/v4/middleware.RewriteWithConfig.func1.1(0xf5bd08, 0xc00016a000, 0x1, 0x1)
Nov 05 02:14:47 homer homer-app[26586]:         /go/pkg/mod/github.com/labstack/echo/v4@v4.5.0/middleware/rewrite.go:72 +0x103
Nov 05 02:14:47 homer homer-app[26586]: github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0004be240, 0xf46910, 0xc000158620, 0xc0000b0100)
Nov 05 02:14:47 homer homer-app[26586]:         /go/pkg/mod/github.com/labstack/echo/v4@v4.5.0/echo.go:654 +0x2bc
Nov 05 02:14:47 homer homer-app[26586]: net/http.serverHandler.ServeHTTP(0xc0001580e0, 0xf46910, 0xc000158620, 0xc0000b0100)
Nov 05 02:14:47 homer homer-app[26586]:         /usr/local/go/src/net/http/server.go:2867 +0xa3
Nov 05 02:14:47 homer homer-app[26586]: net/http.(*conn).serve(0xc000121220, 0xf49300, 0xc0000328c0)
Nov 05 02:14:47 homer homer-app[26586]:         /usr/local/go/src/net/http/server.go:1932 +0x8cd
Nov 05 02:14:47 homer homer-app[26586]: created by net/http.(*Server).Serve
Nov 05 02:14:47 homer homer-app[26586]:         /usr/local/go/src/net/http/server.go:2993 +0x39b
N

**Comment by adubovikov** [comment]
Hi, thank you, can you please share your search request ?
You can find it in F12 -> Network tab

i.e.:
![Screenshot from 2021-11-05 07-35-40](https://user-images.githubusercontent.com/4513061/140468691-7cfcf20c-12c5-454d-90f9-9e1c2e650d82.png)

**Comment by adubovikov** [comment]
can you please install homer-app-1.4.24 and re-check ? 

In your case it will generate an Error with description of your map search

**Comment by adubovikov** [comment]
@ar45 please provide us a feedback if it works or not

**Comment by ar45** [comment]
Thanks @adubovikov 
I cleared my session and reset all my settings already and now it seems to be working.

If it happens again I'll reopen and supply the parameters within the post request.

Thank you

**Comment by adubovikov** [comment]
super! Enjoy!
