### ISSUE TITLE
JSON dashboard provided in dashboard_home doesn't seem to work

### ISSUE THREAD

**Issue by gedia** [sipcapture/homer-app#455]
Hello,

I've tested the dashboard_home feature to provide new users with a default dashboard upon first login, but it doesn't seem to work:
```
  "dashboard_settings": {
    "_comment": "Here you can define a customs dashboards home",
    "dashboard_home": "/usr/local/homer/etc/dashboard_home.json"
  },
```
I'm attaching the json used to this ticket. It was produced by homer-ui's visual editor (renamed to .txt to allow github upload):
[dashboard_home.json.txt](https://github.com/sipcapture/homer-app/files/7491522/dashboard_home.json.txt)

This provided json is indeed imported to create entries in user_settings when a new user logs in, but they get a blank home dashboard in the GUI when they log-in. Additionally, in the GUI "user settings", the "Name" and "param" columns are empty despite these fields seemingly being populated in the attached json file.

Is this some sort of bug, or are dashboards created using the GUI editor not suitable for export and need further editing to be used? Thanks!

**Comment by adubovikov** [comment]
looks like you have to provide only data object :-)

**Comment by adubovikov** [comment]
here is the example: https://github.com/sipcapture/homer-app/blob/master/migration/jsonschema/jsonschema.go#L25

**Comment by adubovikov** [comment]
and the example is correct

https://github.com/sipcapture/homer-app/blob/master/etc/dashboard_home.json.example

**Comment by gedia** [comment]
Geez do you ever sleep @adubovikov ?

Thanks I'll try it out :-)

**Comment by adubovikov** [comment]
Robots are never sleeps :-)

**Comment by gedia** [comment]
OK, so with the data object only in the custom home JSON file, home dashboard generation seems to work for new logins.

However, I've noticed that when a user logs in, multiple copies of dashboards get created (sometimes two, sometimes three, but never one), not only for the home dashboard but also for the default "smartsearch" dashboard. Perhaps this affects LDAP users only? I haven't tried with local users.

Should I open a separate ticket for this?

**Comment by adubovikov** [comment]
Yes, please do

**Comment by gedia** [comment]
OK, I'm closing this
