### ISSUE TITLE
Display aliases in QoS tab

### ISSUE THREAD

**Issue by gedia** [sipcapture/homer-app#457]
Hello,

It would be useful if aliases would also be used instead of IPs in the QoS tab of a dialog view, e.g. here:
![image](https://user-images.githubusercontent.com/15806134/140696844-8638a7ee-1973-4209-a035-fd1bec2328a4.png)

Ideally, the same rules should apply as for SIP entities, i.e. resolve captureID values when there are multiple alias entries for the same IP. The port setting should either be ignored, or the user should be expected to use '0' in the respective column for these aliases as it wouldn't make much sense to restrict resolution to specific ports for RTP streams. I don't really have a preference, I'm only mentioning this for consideration.

**Comment by gedia** [comment]
Also, the same functionality could be considered for the "Session Info" tab. However, I'd advise against replacing the IPs with their aliases in this panel. Instead, I'd rather they were printed alongside the IPs, perhaps in a lighter shade of grey so as not to introduce too many distracting elements in the UI.

**Comment by kYroL01** [comment]
Duplicated issue - Already implemented in the last Homer version
