### ISSUE TITLE
OR logic - timestamp included in search

### ISSUE THREAD

**Issue by ghmj2417** [sipcapture/homer-app#459]
Is it intentional to include the timestamp part of the OR search?

For example, I set orlogic: true, and add params dstIP and srcPort for the search.  I set the timestamp for the past 24 hours.  I am seeing the results for the dstIP and srcPort, but I am also seeing all of the records for the past 24 hours.  I didn't expect this behavior.  I think most of us would only want the results for the search params of dstIP and srcPort.

**Comment by lmangani** [comment]
Sounds like a potential bug indeed - investigating

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/commit/f2cdde3b471d6e5422621655ca2e6a02dd2aaf62

**Comment by adubovikov** [comment]
@RFbkak37y3kIY the bug with AND/OR still valid - switcher doesn't reset the value and it always sends "true"

**Comment by ghmj2417** [comment]
Thank you for the app fix @adubovikov!

Are you referring to the UI issue that I created? https://github.com/sipcapture/homer-ui/issues/562

**Comment by adubovikov** [comment]
@ghmj2417 ah, yes, you did it! In this case I will close the ticket. 
please star us here: https://github.com/sipcapture/homer/stargazers
