### ISSUE TITLE
swagger_codegen and swagger.json fails

### ISSUE THREAD

**Issue by oej** [sipcapture/homer-app#461]
Using the python app swagger_codegen parsing of swagger.json fails

```
  File "/usr/local/lib/python3.9/site-packages/swagger_codegen/parsing/loaders.py", line 61, in add_x_names
    for name, schema in schema["components"]["schemas"].items():
KeyError: 'components'
```

**Comment by oej** [comment]
https://pypi.org/project/swagger-codegen/

**Comment by AlexeyOplachko** [comment]
Hi, since our swagger was generated with go-swagger it's a OpenApi 2.x (Swagger 2) while that python library supports only OpenApi 3.x(aka Swagger 3) which is not backwards compatible.

So most likely that's your source of a problem.

**Comment by oej** [comment]
Ok, will try to find something compliant with 2.x. Thanks!

**Comment by AlexeyOplachko** [comment]
Feel free to reopen an issue if this doesn't fix your problem :)
