### ISSUE TITLE
Different Flow view for after BYE

### ISSUE THREAD

**Issue by solarmon** [sipcapture/homer-app#462]
Hi,

I have a Homer 7.10.10 setup. This issues occurs on two separate Homer servers - opensips is sending HEP capture traffic to both.

The issue I'm experiencing is that, for the same callid (and correlation_id), when I click on callid of the BYE packet, it shows a different Flow view compared with when I click the callid of any packets before the BYE paket.

![image](https://user-images.githubusercontent.com/46369787/148938994-425cf139-a3fe-4471-bc24-6bd5dcb2969a.png)

In this example, this is for a long duration call - nearly 6 hours. 

And on this occasion it is just showing the flow for after the BYE.

In another occasion, when I click before the BYE it shows the Flow up to (not including) the BYE, and when I click on the BYE it shows the complete Flow including and after the BYE.

I can try updating Homer to the latest version, if that resolves the issue?

**Comment by lmangani** [comment]
Could you please do confirm if this is still an issue with the latest version, otherwise the patch and investigation might diverge

**Comment by solarmon** [comment]
I updated to Homer 7.10.15 and it seems to have the same issue for me.

**Comment by solarmon** [comment]
I changed the lookback/lookforward range (in Admin > Mapping > Protocol > Correlation) for "call SIP" to:

```
"lookup_range": [
            -6000,
            4000
        ]
```

And that seems to have resolved the issue.

What is the implications on performance and resources by of having a wide range?

**Comment by lmangani** [comment]
@solarmon the implications as you suspected is an increased resource usage per query, but you can observe the setup consumption and judge if this is a critical increase or not - being an ondemand query it should not impact you much unless dozens of users leverage it concurrently. You should find the minimal "sweet spot"

**Comment by lmangani** [comment]
Closing as resolved, suggestions/docs contributions are welcome on the subject!
