### ISSUE TITLE
JWT Errors On 1.4.29

### ISSUE THREAD

**Issue by anthonywittig** [sipcapture/homer-app#465]
Hello - this is probably missing a lot of critical information, please let me know what to add. 🙏 

We have two servers running `heplify-server` and `homer-app`. When we updated `homer-app` to `1.4.29` (from `1.4.27`) we started seeing a lot of JWT errors in the browser console, e.x.:
```
Uncaught (in promise): invalid or expired jwt

Uncaught (in promise): missing or malformed jwt
```
We'd get a 401 on these and be redirected to the login page. Sometimes folks could get past the login page, but within a couple of mouse clicks they'd be redirected to the login page.

Here are the settings I think might be related:
```
  "auth_settings": {
    "_comment": "The type param can be internal, ldap, http_auth",
    "jwt_secret": some string UUID,
    "token_expire": 1200,
    "type": "internal"
  },
  "http_auth": {
    "skipverify": true,
    "url": "http://localhost:1323"
  },
```

Any help would be greatly appreciated, thanks!

**Comment by adubovikov** [comment]
@anthonywittig let us check it asap

**Comment by adubovikov** [comment]
@anthonywittig unfortunately couldn't reproduce it in our lab.
can you please enable debug log and see if u see any errors ?

**Comment by anthonywittig** [comment]
I'll try that out off hours (for now we've scaled down to one host and things are working).

**Comment by adubovikov** [comment]
please regenerate jwt_sescret using "uuid" and clean the cache in your browser (F12->disable cache)

**Comment by anthonywittig** [comment]
Is there somewhere I can find out more about the `auth_settings`? Each host should have a unique `jwt_secret`, right?

**Comment by adubovikov** [comment]
@anthonywittig thats correct, but if you have cluster - you should have same between all your hosts

**Comment by anthonywittig** [comment]
That solved my issue 🤦 , thanks for your quick response and help! ⭐

**Comment by adubovikov** [comment]
you are welcome :-) please star us also here https://github.com/sipcapture/homer/stargazers
