### ISSUE TITLE
Calls are correclty correlated, but flow diagram only shows invites of other calls?

### ISSUE THREAD

**Issue by zimmerya** [sipcapture/homer-app#466]
I have read through the wiki and the other issues to set the mapping for my call structure and homer works really nicely. The only problem I have is that the flowchart only shows all messages of the selected call, the messages of the correlated calls don't get shown at all, except for the invites. Here a screenshot:
![homer7flowScreenshot](https://user-images.githubusercontent.com/98062318/152080774-e446fa9a-25d6-4215-bdc0-a4032ea0d931.png)

As you can see: only the messages of the purple call are displayed in full, the yellow and blue calls only display their invite messages. Here the flowchart, when clicking on a message of the yellow call:
![homer7flowScreenshot2](https://user-images.githubusercontent.com/98062318/152080821-d2f2efa4-8cd1-4a42-936b-572e639e1284.png)

I would like to have every message of every correlated call displayed in one flow chart. So it looks like this (i omitted the blue one but it should be displayed in full as well):
![homer7flowDream](https://user-images.githubusercontent.com/98062318/152081872-a565406c-90d1-481e-9fda-452d4f0c4822.png)

 How do I do this? Is there a special setting to activate? Is my mapping wrong? The three calls should be correctly correlated, as the ids of the three calls are displayed on the bottom of the screenshots. Any help would be appreciated.

**Comment by adubovikov** [comment]
the mapping is ok, just overcorrelated because same number ?
