### ISSUE TITLE
Unable to run homer-app (homer-ui) from subdirectory

### ISSUE THREAD

**Issue by radicaldrew** [sipcapture/homer-app#467]
when running homer-app from a sub directory such as <ip>/homer the assets are unable to load.
angular base href is defaulted to /
![screen96](https://user-images.githubusercontent.com/8816264/153278770-aab3a468-f569-4d7a-adb0-45ba956792f2.jpg)
possible solution is to update the package.json of homer-ui with base-href in build.
"build": "ng build --base-href ${BASE_HREF:-/} .....

**Comment by radicaldrew** [comment]
created a pull request for this under homer-ui repo
[](https://github.com/sipcapture/homer-ui/pull/573)

**Comment by adubovikov** [comment]
closed as completed
