### ISSUE TITLE
Issue with shared links for Homer 7.10.17

### ISSUE THREAD

**Issue by AlexeyLilichenko** [sipcapture/homer-app#469]
After update from **Homer 7.10.16** to **Homer 7.10.17** bug appeared.

If I search **call A**, then check its **Flow**, then press **Export**->**Share Link**. 

I do same for **call B**, and check both **Shared links** in browser I will see **same results for both links** (result last saved in localStorage, not the result for shared link).

**To force this shared links work, I must manually clear **localStorage** data in browser.**

In **Homer 7.10.16** I could open both links in different tabs and see correct result for each shared link.

**Comment by AlexeyLilichenko** [comment]
Additional details:
homer-app 1.4.30  - was OK
homer-app 1.4.32 - bug appear

Shared link example:
http://<homer_IP>:9082/search/result/dashboard/home?%7B%22timestamp%22:%7B%22from%22:1644996892037,%22to%22:1644997492037%7D,%22param%22:%7B%22search%22:%7B%221_call%22:%7B%22id%22:444170,%22callid%22:%5B%226169623b564f9a0939d1dc0403a65e89@<my_voip_server_IP>:5060%22,%227cf90fb100f6d33d4b3dd76571ee1e64@<voip_provider_IP>:5060%22%5D,%22uuid%22:%5B%5D%7D%7D,%22location%22:%7B%7D,%22transaction%22:%7B%22call%22:true,%22registration%22:false,%22rest%22:false%7D,%22id%22:%7B%7D,%22timezone%22:%7B%22value%22:-180,%22name%22:%22Local%22%7D%7D%7D=

At least filter by **SIP Callid** not working

**Comment by lmangani** [comment]
Thanks for your report @AlexeyLilichenko we are investigating
