### ISSUE TITLE
Strange username format validation in user settings

### ISSUE THREAD

**Issue by agrigorjevs** [sipcapture/homer-app#470]
Hello,

We have users created and also LDAP usernames with such format - firstname.lastname. Creation of such usernames is allowed.

But when you try to add a new user setting - it does not allow dot in the usernames.

<img width="799" alt="Screenshot 2022-02-22 at 15 30 04" src="https://user-images.githubusercontent.com/39706760/155149658-96fd5d5b-9cc1-4289-beb4-8ee3dcbf47fa.png">

Also, another thing, which is not related to user settings, but to aliases - is the alias name requirement to have at least 3 symbols - previously it didn't have this validation (or validation as a whole) and we have already alias names with 2 symbols.
Is there a reason really to have 3 symbols at least?

**Comment by kYroL01** [comment]
1. The issue for "firstname.lastname" is resolved in the last Homer
2. The minimum number of characters allowed is 3 for security reasons.
