### ISSUE TITLE
Trouble With OR Logic

### ISSUE THREAD

**Issue by jvb187** [sipcapture/homer-app#471]
Hello,

I can not seem to get the OR logic working properly. When I set my query to OR, I see the local storage object is updated properly:

`
{
    "fields": [
        {
            "name": "protocol_header.srcIp",
            "value": "xx.xx.xx.xx",
            "func": null,
            "type": "string",
            "hepid": 1
        },
        {
            "name": "protocol_header.dstIp",
            "value": "xx.xx.xx.xx",
            "func": null,
            "type": "string",
            "hepid": 1
        }
    ],
    "protocol_id": "1_call",
    "location": {
        "value": [
            "XX"
        ],
        "mapping": "node"
    },
    "orlogic": true,
    "archive": false
}
`

However, the payload that is sent when I press Search does not reflect this:

`
{
    "config": {},
    "param": {
        "transaction": {},
        "limit": 200,
        "orlogic": false,
        "search": {
            "1_call": [
                {
                    "name": "protocol_header.srcIp",
                    "value": "xx.xx.xx.xx",
                    "func": null,
                    "type": "string",
                    "hepid": 1
                },
                {
                    "name": "protocol_header.dstIp",
                    "value": "xx.xx.xx.xx",
                    "func": null,
                    "type": "string",
                    "hepid": 1
                }
            ]
        },
        "location": {
            "node": [
                "XX"
            ]
        },
        "timezone": {
            "value": -180,
            "name": "Local"
        }
    },
    "timestamp": {
        "from": 1645642440000,
        "to": 1645642740000
    }
}
`

No matter what I do, the orlogic in the payload sent is always FALSE.

I tried this on a few different Homer instances, all of which are the latest Homer-App and UI version 7.10.18. I have tried clearing local storage and hard refreshing the page, but have not had any luck. I also tried Chrome and Firefox.

Is there something I am missing to get the OR logic working properly?

**Comment by adubovikov** [comment]
I think it was fixed already. Can you please pull the latest version and check again ?
