### ISSUE TITLE
Docker Image tags

### ISSUE THREAD

**Issue by Farid-19** [sipcapture/homer-app#472]
Hi! This is my first time posting a issue. Althought I am not sure if this is the correct repository to post on, if not, please correct me :)

We would like to use the docker image for Homer 7 webapp (https://hub.docker.com/r/sipcapture/webapp/), however I notice that the image itself has no "stable" tags defined, except for **slim** & **latest**:

Would it be possible to create tags for this?

Many thanks!

**Comment by lmangani** [comment]
Our versions [are tagged on ghcr](https://github.com/sipcapture/homer/pkgs/container/homer-app) so if that's important to you, I suggest to switch over using ghcr images.
