### ISSUE TITLE
How to create ui user (admin deleted by mistake)

### ISSUE THREAD

**Issue by hb9eue** [sipcapture/homer-app#475]
Hi List

'Somebody' managed to 'delete' the admin and support UI users, probably leaving our installation without user.

/usr/local/bin/homer-app allows to reset the passwort for a user. But can I create an user?

-Benoit-

**Comment by lmangani** [comment]
Hi @hb9eue 
This is available in the [readme](https://github.com/sipcapture/homer-app#create-user)
Let us know if it doesn't work for your case.
