### ISSUE TITLE
Docker image doesn't appear to include Swagger file

### ISSUE THREAD

**Issue by danlshields** [sipcapture/homer-app#478]
In Settings, the API documentation doesn't load, the API responds to the request to `/doc/api/json` with a `400` error, with a `{"data":{},"message":"swagger file couldn't be found"}` body.
https://github.com/sipcapture/homer-app/blob/f957fc9c5ffc634fee27a62429d8d40edd32e7f1/main.go#L721-L731
<img width="879" alt="Screen Shot 2022-04-22 at 10 59 47" src="https://user-images.githubusercontent.com/3648371/164761078-d000d548-4857-472f-9f2b-1baa73068636.png">

**Comment by adubovikov** [comment]
you can set the real host here:

https://github.com/sipcapture/homer-app/blob/master/etc/webapp_config.json#L48

**Comment by danlshields** [comment]
> you can set the real host here:
> 
> https://github.com/sipcapture/homer-app/blob/master/etc/webapp_config.json#L48

@adubovikov I'm afraid I don't understand, the problem isn't the API host shown in the API documentation, it's that there is no swagger file at all. It doesn't even get as far as to use `config.Setting.SWAGGER.ApiHost`...
