### ISSUE TITLE
date format

### ISSUE THREAD

**Issue by m-j-b** [sipcapture/homer-app#481]
The date format on the Widget Result tab is dd/MM/yyyy HH:mm:ss e.g. 07/06/2022 08:47:37 Can this be changed? Ideally I'd like to show milliseconds as well.

![widget-result-date-format](https://user-images.githubusercontent.com/70200455/177759578-1b051d83-e0a9-41d7-b6b8-5bdd3b067a1d.png)
.

**Comment by m-j-b** [comment]
Thanks, that works great:

![new_date_format_settings](https://user-images.githubusercontent.com/70200455/184605307-d9497869-ac90-436a-ae52-d19d44ef364e.png)

![new_date_format_widget](https://user-images.githubusercontent.com/70200455/184605325-9962263f-023f-4e36-8e05-f916371d340c.png)

**Comment by andr-04** [comment]
It's very helpful information and should be extracted into Wiki document, like a lot of descriptions to other config settings!

I'm new with Homer and my brain is blowing about the dirty and carelessness documentation… 🤯

**Comment by lmangani** [comment]
@andr-04

> I'm new with Homer and my brain is blowing about the dirty and carelessness documentation… 🤯

Classic opensource entitlement. Want great docs? Roll up your sleeves and contribute some.

**Comment by andr-04** [comment]
> Roll up your sleeves and contribute some.

I can do it one time, but it will not cover tons of other regular questions.

Why you as developers, for example @m-j-b in this issue, gives answers here instead of putting them to Wiki at least and leaving here the link to the Wiki? It's a really simple approach, but much more helpful and makes care of users and community overall. It's absurd to turn solved issues into a store room of knowledge.

**Comment by lmangani** [comment]
> I can do it one time, but it will not cover tons of other regular questions.

If everyone covered their own question, we would have 100s of up to date documentation pages on the wiki. But most people come demand what they want when they need it but are not willing to help the next guy by improving documentation. This is opensource, and It's up to users to break this selfish cycle.
