### ISSUE TITLE
Capture ID is set to integer in the default mapping

### ISSUE THREAD

**Issue by husam212** [sipcapture/homer-app#482]
Searching by capture ID with alphanumeric characters doesn't work out of the box, changing the field `type` in the mappings to `string` fixes the issue, I'm not sure if this is a bug or it's intentionally set to `integer` by default.

**Comment by kYroL01** [comment]
Hi @husam212 . Thanks for this question.
Yes by default is intentionally set to `integer` because most of the HEP agent use the capture ID as a string, but if you use [heplify](https://github.com/sipcapture/heplify) you can set this value also as an alphanumerical string (option `-hn stringName`)
