### ISSUE TITLE
How do I find out register requests sent from a particular IP? 

### ISSUE THREAD

**Issue by vcidst** [sipcapture/homer-app#486]
I'm using the "Registration Search Widget" currently it only allows me to filter by Call ID. I'm trying to see Register attempts filtered by source IP or destination IP. Is there a way I can do that?

I tried filtering in the Source IP / Destination IP column but I do not see any results since the request isn't on the current page.

**Comment by lmangani** [comment]
@vcidst did you add the relative fields to the search widget? This is done through the form.

**Comment by lmangani** [comment]
Please be so kind to star the repository if you use our software and ask support.

**Comment by vcidst** [comment]
Thank you @lmangani that helped! I've starred the repository as well :)
