### ISSUE TITLE
How to change or update new Password for admin user Homer UI via PG Database.

### ISSUE THREAD

**Issue by PJ111288** [sipcapture/homer-app#492]
How to change or update new Password for admin user Homer UI via PG Database.

**Comment by lmangani** [comment]
Hello @PJ111288 mind github issues are not a google search form - please make a effort to CTRL-F before submitting.
The answer is in the [readme](https://github.com/sipcapture/homer-app#reset-ui-password-for-any-user) 😄

**Comment by PJ111288** [comment]
@lmangani  : ManyThanks for guding it.
