### ISSUE TITLE
Multi node, flow of multiple session-id

### ISSUE THREAD

**Issue by mcebey1891** [sipcapture/homer-app#494]
Hi,

I have a system made up of a web-app and two heplify-servers (with their own database).
Using the node field I can search for SIP messages belonging to the two nodes, but if I then select session-id from different nodes, when selecting a session-id, in the flow it only shows those of the node where the session-id comes from and not all selected session-id.

Could you implement that all messages are displayed regardless of the node where they come from?

Thank's

**Comment by nickakt** [comment]
Hello, 

Have the same issue 

Are there any implementetion?

**Comment by lmangani** [comment]
what have you attempted?

**Comment by adubovikov** [comment]
@nickakt @mcebey1891 can you paste here the API request that UI does ? You can grab it in the webconsole

**Comment by nickakt** [comment]
Hello, 

Sure 

`{"param":{"transaction":{"call":true,"registration":false,"rest":false},"limit":200,"orlogic":false,"search":{"1_call":{"id":10336348,"callid":["ff5d0eb0-2185-123c-989b-000c29a7b55e"]}},"location":{"node":["sg"]},"timezone":{"value":-180,"name":"Local"}},"timestamp":{"from":1675772707843,"to":1675773307843}}`

I didn't find how to change `"location":{"node":["sg"]} >>>> "location":{"node":["sg", "nl"]}`

**Comment by nickakt** [comment]
@lmangani Hello, Sorry 

 I tried the same this that described I the very first message "Build sip flow for calls that located on different databases "

I have a system made up of a web-app and two heplify-servers (with their own database).
Using the node field I can search for SIP messages belonging to the two nodes, but if I then select session-id from different nodes, when selecting a session-id, in the flow it only shows those of the node where the session-id comes from and not all selected session-id.

**Comment by adubovikov** [comment]
so, during search, you have selected two nodes and after you click on one message it selected only one ?

**Comment by nickakt** [comment]
nope, 
 
I have a web-app and two heplify-servers (with their own database).

For example:
We have a Call:  A-leg is located in A-database(sg) and B-Leg is located in B-database(nl). 
When we search for this call we can locate both legs. But when we press Session ID we expect that SIP FLOW will be builded for both legs by X-CID but It doesn't happen. 
When both legs of the call are located in one database A-database(sg), the sip flow builds as expected. We see both legs. 

The question is how to build one sipflow if the call legs located on diferent databases

**Comment by adubovikov** [comment]
Do you have in your call's mapping this record:


```
 {
        "id": "node",
        "name": "Node",
        "type": "string",
        "index": "none",
        "form_type": "multiselect",
        "form_api": "/database/node/list",
        "system_param": true,
        "mapping": "param.location.node",
        "position": 23,
        "skip": true,
        "hide": true
    }
```

**Comment by adubovikov** [comment]
or like this:

   ```
{
        "id": "node",
        "name": "Node",
        "type": "string",
        "index": "none",
        "form_type": "multiselect",
        "form_default": [
            {
                "value": "node1",
                "name": "Node1"
            },
            {
                "value": "node2",
                "name": "Node2"
            }
        ],
        "system_param": true,
        "mapping": "param.location.node",
        "position": 23,
        "skip": true,
        "hide": true
    }
```

**Comment by adubovikov** [comment]
![image](https://user-images.githubusercontent.com/4513061/217287045-692408f2-c14f-4f55-a76c-86c9e4f3ec5f.png)

And after you select Node

**Comment by mcebey1891** [comment]
Hi,
I have this configuration:
```
{
        "id": "node",
        "name": "Node",
        "type": "string",
        "index": "none",
        "form_type": "multiselect",
        "form_default": [
            {
                "value": "ims",
                "disabled": false,
                "name": "IMS"
            },
            {
                "value": "ngn",
                "disabled": false,
                "name": "NGN"
            }
        ],
        "_form_api": "/database/node/list",
        "system_param": true,
        "mapping": "param.location.node",
        "position": 24,
        "skip": false,
        "hide": false
    }
```
And when I select both nodes:

![imagen](https://user-images.githubusercontent.com/54403048/217298395-31a576a2-dc7a-48d8-985e-bce91dcc2d68.png)

And select two different sessions:

![imagen](https://user-images.githubusercontent.com/54403048/217299157-d10ce77d-c3fe-4979-8334-24c2d19f083a.png)

It only shows the session that is clicked on and not both:

![imagen](https://user-images.githubusercontent.com/54403048/217300465-2d214aab-24e7-411f-807f-348f8d231a33.png)

I don't know how to collect the information you ask for. If you give me guidance, I collect it.

**Comment by nickakt** [comment]
Yes, thats what I have experiencing 

I belive it can be done by Mapping or in Advanced settings. Any guidance will be appreciated

**Comment by nickakt** [comment]
@mcebey1891

**Comment by lmangani** [comment]
> @mcebey1891 Hello.,
> 
> Made some workaround
> 
> added
> 
> `nodes = []string{}`
> 
> to
> 
> https://github.com/sipcapture/homer-app/blob/a1daf179646805cd1bf19f51a9d0c3e3cffb8bf0/data/service/search.go#L919

if there's a bug please submit a PR
