### ISSUE TITLE
Missing QoS data

### ISSUE THREAD

**Issue by kosza** [sipcapture/homer-app#498]
Hi,

I use VERSION: 1.4.37 of homer-app. On the tab qos some data is not displayed. The datas are in qos response, there is no javascript error and the qos is empty.
![image](https://user-images.githubusercontent.com/31093540/199839057-e09c0ef9-33d1-42ab-9f4b-8a8a11654940.png)

I attach the qos response, the ip's are modified.

[homer_qos.txt](https://github.com/sipcapture/homer-app/files/9933143/homer_qos.txt)

Not all RTCP data are affected. I have checked a working and a not working data but I see no difference.

Thanks for helping.
BR,
Szabolcs

**Comment by lmangani** [comment]
The `207` response needs an extended handler. Assigned to @RFbkak37y3kIY
