### ISSUE TITLE
hep_proto_1_registration and call legs

### ISSUE THREAD

**Issue by Gudeen** [sipcapture/homer-app#50]
Hi,
I'm testing heplify-server with homer7 UI, and heplify-server writes register messages to hep_proto_1_register, but the UI tries to select from hep_proto_1_registration ("ERROR:  relation "hep_proto_1_registration" does not exist").
How should I adjust the configuration, that heplify-server and the ui use the same table names?

Another issue I have, is that the A-Leg and B-Leg of a call are not connected in the UI ("Flow" only shows A-Leg or B-Leg separatly, not both together). This is working with the old Kamailio+homer5 setup, so I would expect that the pbx (FreeSwitch 1.9 with integrated HEP Capture Agent) sends the required information. I'm not sure whether this is an issue of my  heplify-server or homer-app config.

**Comment by lmangani** [comment]
Try adjust settings here and report if successful for a patch: `public/app/widgets/protosearch-widget/settings/data/proto_transactions.json`

As of correlation, this is an entirely different subject and mostly depends on your setup - there is no guessing possible, so please don't mix issues to avoid confusion.

**Comment by Gudeen** [comment]
just changing public/app/widgets/protosearch-widget/settings/data/proto_transactions.json didn't work yet. It still throws the same error when searching for registrations.

For the correlation issue I'll open a separate issue then, but could you tell me whether this should be related to heplify-server or homer-app? just that i'll post it in the right place...

**Comment by Gudeen** [comment]
I'm currently still stuck with the different homer7 hep_proto_1_registration/register table names in heplify-server and homer app.
Of course I could also easily change the table name in my heplify-server, but so far I'm not even sure which of both names you consider to be the correct one...

**Comment by lmangani** [comment]
@Gudeen this is being fixed

**Comment by khorsmann** [comment]
@lmangani and @adubovikov 
Hello,

i still try the same (kamailio and FreeSWITCH as agents) and hom7-hep-influx docker images (today 2019/02/21 version).

Still no luck with X-CID Correlation. Any hints or is that an homer5 only feature at the moment?

**Comment by adubovikov** [comment]
Hi Karsten,

unfortunately i can only give you an advice and link to the code. You can do any X-CID correlation, and here is the way:

https://github.com/sipcapture/homer-app/blob/master/seeds/02_Mapping.js#L434

you can take any header and make own correlation lookup in any tables:

{
      source_field: 'data_header.callid',
      lookup_id: 5,
      lookup_profile: 'default',
      lookup_field: 'data_header.x-cid',
      lookup_range: [-300, 200],
},

the last version of UI should also include "Mapping interface" Let me know if it doesn't

**Comment by negbie** [comment]
@Gudeen sorry I somehow overlooked this issue. Mby in such case you could open a ticket inside heplify-server repo too. I'm barely watching this repo. Anyway I changed the table name to hep_proto_1_registration so could you please try it again?

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
