### ISSUE TITLE
Search field value modification

### ISSUE THREAD

**Issue by kosza** [sipcapture/homer-app#500]
Hi,

Is there any method to modify search field value? Mapping can use script to add 'b2b_1' sting to the correlation_id. 
Example:
I want to search a call by ruri_user in e.164: 3699123456, where 36 is the cc, 99123456 is the subscriber number.
The script should modifies 3699123456 to +3699123456, 003699123456.

Thanks for your help.

**Comment by lmangani** [comment]
Why not just searching for `%3699123456` instead of manually mapping prefixes?

**Comment by kosza** [comment]
Because if the customer dials with national prefix (in Hungary it is `06`) the ruri will be `0699123456`. This is a fortunate case, `%699123456` will work but if the cc not ends digit `6` it won't.

**Comment by lmangani** [comment]
There are no national formats in e.164

**Comment by kosza** [comment]
Yes. This is why I would like to use e.164 format is search. But the ruri_user can be several types.

**Comment by kosza** [comment]
For my problem the `%` is a good solution. So I close the issue.

Thanks for your advice.
