### ISSUE TITLE
Postgres SSL

### ISSUE THREAD

**Issue by idanacontaqt** [sipcapture/homer-app#514]
hey, what are the options of SSL the app can connect to postgres db node? and where are the settings for it?

i don't see it at the webconfig.json at /etc in github repo.

thank you

**Comment by adubovikov** [comment]
The param is ->

"usessl": true,
or
"sslmode": true

in the database section

**Comment by idanacontaqt** [comment]
what if the postgress require ca? or full ca? will it still work with the parameters? what's the location the app reads for certs?
