### ISSUE TITLE
Homer UI - API Request of export "Share Link"

### ISSUE THREAD

**Issue by idanam-del** [sipcapture/homer-app#515]
hey, i didnt find in api docs and its not shown in the web console when i click the "share link" button.

I would like in my own API to pop up a "share link" window(via api request to homer api) of a x-cid call when i click it in my own cdr.

Is it in the api docs? is it possible when i use x-cid as a parameter and not a session ID of homer?(the x-cid is mapped in homer config)

**Comment by hrhashmi** [comment]
HI @idanam-del 

you can find API docs in HOMER-UI (Settings -> API Documentation). 

![image](https://user-images.githubusercontent.com/117178483/235841813-86f4f361-2396-4eb3-966c-6614325825f3.png)
