### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by negbie** [sipcapture/homer-app#52]
Hi,
I wanted to take a closer look at the performance and noticed this in the logs:
omer-webapp      | FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
homer-webapp      |  1: node::Abort() [node]
homer-webapp      |  2: 0x8ccf9c [node]
homer-webapp      |  3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
homer-webapp      |  4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
homer-webapp      |  5: v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [node]
homer-webapp      |  6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [node]
homer-webapp      |  7: v8::internal::String::Flatten(v8::internal::Handle<v8::internal::String>, v8::internal::PretenureFlag) [node]
homer-webapp      |  8: v8::String::WriteUtf8(char*, int, int*, int) const [node]
homer-webapp      |  9: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [node]
homer-webapp      | 10: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [node]
homer-webapp      | 11: 0x8e9444 [node]
homer-webapp      | 12: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
homer-webapp      | 13: 0xb0d72c [node]
homer-webapp      | 14: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
homer-webapp      | 15: 0x3222ca0042fd
homer-webapp      | 
homer-webapp      | <--- Last few GCs --->
homer-webapp      | 
homer-webapp      | [48:0x31d2070]  2062045 ms: Mark-sweep 1237.1 (1448.2) -> 1237.0 (1460.2) MB, 900.9 / 0.0 ms  allocation failure GC in old space requested
homer-webapp      | [48:0x31d2070]  2063343 ms: Mark-sweep 1237.0 (1460.2) -> 1236.9 (1414.7) MB, 1296.6 / 0.0 ms  last resort GC in old space requested
homer-webapp      | [48:0x31d2070]  2064058 ms: Mark-sweep 1236.9 (1414.7) -> 1236.9 (1403.7) MB, 714.8 / 0.0 ms  last resort GC in old space requested
homer-webapp      | 
homer-webapp      | 
homer-webapp      | <--- JS stacktrace --->
homer-webapp      | 
homer-webapp      | ==== JS stack trace =========================================
homer-webapp      | 
homer-webapp      | Security context: 0x449c80a58b9 <JSObject>
homer-webapp      |     1: fromString(aka fromString) [buffer.js:314] [bytecode=0x3f3a7934bb59 offset=164](this=0x3fed53b022d1 <undefined>,string=0x127689b7e999 <Very long string[214953774]>,encoding=0x449c80b4e41 <String[4]: utf8>)
homer-webapp      |     2: from [buffer.js:177] [bytecode=0x3f3a7934b661 offset=11](this=0x17df161b5de9 <JSFunction Buffer (sfi = 0x449c80fda69)>,value=0x127689b7e999 <Very long string[214953774]>,encodingO...

Traffic is quite decent and database has about 10M call rows. For me it's not so clear why JavaScript runs out of memory. I did nothing special just picked a 24h timeframe.

**Comment by lmangani** [comment]
is this with a container or running on an actual system?

**Comment by negbie** [comment]
It's the recent container. I also noticed that heplify-server does not create good postgres indicies. For example I should create a index for create_date and payloadType. This is not related to this error but would help to boost the query performance.

**Comment by negbie** [comment]
Pulled it but couldn't reproduce it so far. Will close this issue and hope I can reproduce it to reopen.
