### ISSUE TITLE
Webapp Server not starting.

### ISSUE THREAD

**Issue by Gilbert2015** [sipcapture/homer-app#527]
During the deployment of the webapp server using the webapp docker image, I faced an error stating that the application could not write to the log file. Here is the log output from the deployment:

"The connection to the database was successful, but the application failed to open the log file."

Pre-Flight provisioning completed!
{"level":"info","msg":"init logging system","time":"2023-07-05T22:22:51Z"}
[33m 
CONNECT to DB ROOT STRING: [host=devperconacluster.development.svc.cluster.local user=postgres dbname=postgres sslmode=disable port=5432 pa]
 [0m
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
[31m 
HOMER - create db [homer_config] with [name=postgres] [0m

[35m(/homer-app/migration/migration.go:85)[0m 
[33m[2023-07-05 22:22:51][0m [31;1m pq: database "homer_config" already exists [0m

[35m(/homer-app/migration/migration.go:85)[0m 
[33m[2023-07-05 22:22:51][0m  [36;1m[0.46ms][0m  CREATE DATABASE homer_config OWNER postgres  
[36;31m[0 rows affected or returned ][0m 
[33m 
DONE [0m
[31m 
HOMER - show users [0m
	Role name	|	Attributes
------------------------------------------------
	homer_user	|		
	pgbouncer	|		
	pguser	|		
	postgres	|	superuser, create database	
	primaryuser	|		
[33m 
DONE [0m
{"level":"info","msg":"init logging system","time":"2023-07-05T22:22:51Z"}
[33m 
CONNECT to DB ROOT STRING: [host=devperconacluster.development.svc.cluster.local user=postgres dbname=postgres sslmode=disable port=5432 password=LFjcErEEFxKIoxACytbW9Nol]
 [0m
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
[31m 
HOMER - create db [homer_data] with [name=postgres] [0m
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied

[35m(/homer-app/migration/migration.go:85)[0m 
[33m[2023-07-05 22:22:51][0m [31;1m pq: database "homer_data" already exists [0m

[35m(/homer-app/migration/migration.go:85)[0m 
[33m[2023-07-05 22:22:51][0m  [36;1m[0.48ms][0m  CREATE DATABASE homer_data OWNER postgres  
[36;31m[0 rows affected or returned ][0m 
[33m 
DONE [0m
[31m 
HOMER - show users [0m
	Role name	|	Attributes
------------------------------------------------
	homer_user	|		
	pgbouncer	|		
	pguser	|		
	postgres	|	superuser, create database	
	primaryuser	|		
[33m 
DONE [0m
{"level":"info","msg":"init logging system","time":"2023-07-05T22:22:51Z"}
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
[32m 
HOMER - creating tables for the config DB [dbname=homer_config] [0m
[33m 
DONE [0m
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
{"level":"info","msg":"init logging system","time":"2023-07-05T22:22:51Z"}
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
[31m 
HOMER - filling tables for the config DB [dbname=homer_config] [0m
[33m 
DONE [0m
time="2023-07-05T22:22:51Z" level=info msg="SELECT * FROM \"versions\"  " module=gorm type=sql
Database provisioning completed!
{"level":"info","msg":"init logging system","time":"2023-07-05T22:22:51Z"}
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Successful ping: devperconacluster.development.svc.cluster.local, Type: data, Node: LocalNodeFailed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
[34m 
PostgreSQL version: 14.7
 [0m
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
time="2023-07-05T22:22:52Z" level=info msg="INSERT  INTO \"applications\" (\"guid\",\"name\",\"host\",\"version\",\"created_at\") VALUES ($1,$2,$3,$4,$5) ON CONFLICT (name,host) DO UPDATE SET version = EXCLUDED.version, guid = EXCLUDED.guid RETURNING \"applications\".\"id\"" module=gorm type=sql
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
[31m 
         ___              
        /__/\             
        \  \:\           
         \__\:\  
     ___ /  /::\     
    /__/\  /:/\:\     _____     
    \  \:\/:/__\/    |___  |    
     \  \::/            / /   
      \  \:\           / /             
       \  \:\         /_/               
        \__\/         

 [0m
[32m Version: homer-app 1.4.56. [0m
Failed to write to log, failed to acquite target io.Writer: failed to open file &{/usr/local/homer/homer-app_%Y%m%d%H%M.log [%!s(*strftime.stdlibFormat=&{/usr/local/homer/homer-app_20060102}) %!s(*strftime.hourPadded=&{48 false}) %!s(*strftime.stdlibFormat=&{04.log})]}: open /usr/local/homer/homer-app_202307050000.log: permission denied
{"time":"2023-07-05T22:22:52.129626336Z","level":"FATAL","prefix":"echo","file":"main.go","line":"880","message":"Couldn't start server"}

**Comment by adubovikov** [comment]
Please check the permissions for /usr/local/homer directory or start the homer-app under root

**Comment by Gilbert2015** [comment]
@adubovikov Thank you so much for your response. After setting the permission for /usr/local/homer, the application was able to write  log file. I am now getting the error message "level":"FATAL","prefix:"echo":"file":"main.go","line":"882","message":"Couldnt start server"
