### ISSUE TITLE
Keeping the widget in the result page

### ISSUE THREAD

**Issue by celya44** [sipcapture/homer-app#530]
Hi,
We recently upgrade our Homer into 7.10.29
Previously, we were able to do search (with the search panel on the left) and when hitting the Search button, result appeared on the right while keeping the search panel with value entered.
Now, result appear in a new page without the widget.

Is it possible to go back to the old behavior and keep the search panel up ? I tried a lot of settings without results.

Regard.

**Comment by adubovikov** [comment]
we are checking

**Comment by adubovikov** [comment]
![image](https://github.com/sipcapture/homer-app/assets/4513061/f97a981f-3b52-43b3-a194-d59980d25e34)

**Comment by AlexeyOplachko** [comment]
If "Results container" field is missing, in that case it'll send your results to a page. 
So if you want it to open results in a widget, you have to have that field, it is added by default, but could've been removed accidentally. 
![image](https://github.com/sipcapture/homer-app/assets/45398541/93e2fcb0-174c-4a1b-a863-8e844e7a873f)
![image](https://github.com/sipcapture/homer-app/assets/45398541/cc29c92d-0783-4891-9786-7ac74a0dab9a)

**Comment by celya44** [comment]
Thank you, it works as expected now !
Regards
