### ISSUE TITLE
Authentication to Grafana in widget

### ISSUE THREAD

**Issue by fabiantorress** [sipcapture/homer-app#534]
Hi,
I have both the user, pass and key set under Advanced for Grafana search, but these do not appear to be used when defining a grafana widget.
This is the error that I get when I try to define a new widget:
![image](https://github.com/sipcapture/homer-app/assets/107084379/5df94892-c616-496d-9c8d-57960ec938f7)

This is my configuration:
![image](https://github.com/sipcapture/homer-app/assets/107084379/d6812a51-7c4a-436f-81b7-c0b04538d542)

This is the log in grafana.log:
logger=context userId=0 orgId=0 uname= t=2023-07-19T18:05:21.485763481-04:00 level=info msg="Request Completed" method=GET path=/api/org status=401

Thanks

**Comment by hamidrhashmi** [comment]
Try adding the following lines in `grafana.ini`
```
[server]
domain = localhost
root_url = %(protocol)s://%(domain)s:%(http_port)s/
serve_from_sub_path = true

[security]
allow_embedding = true
```
and after restarting grafana, try adding grafana dashboard again in homer.

**Comment by fabiantorress** [comment]
I solve the issue by adding in the webapp_config.json the grafana token. But now I am facing another issue, when I try to display the widget I am seeing the following error on the screen:
![image](https://github.com/sipcapture/homer-app/assets/107084379/c340dfd2-85bc-49ff-ac6f-d3da6b1e59b2)

I try to add the following lines in grafana.ini but I does not work:
```
[server]
domain = localhost
root_url = %(protocol)s://%(domain)s:%(http_port)s/
serve_from_sub_path = true

[security]
allow_embedding = true
```
I have my grafana server running in the same server with my homer-app. This is my grafana config in webapp_config.json: 
```
  "grafana_config": {
    "enable": true,
    "help": "Settings for Grafana",
    "host": "http://127.0.0.1:3000",
    "path": "grafana",
    "proxy_check": "simple",
    "proxy_control": false,
    "token": "XXXXXXXXXXXXXXXXXXXXX"
  },
```

**Comment by lmangani** [comment]
@fabiantorress follow step 2 of the provided Grafana suggestions

**Comment by fabiantorress** [comment]
where are the Grafana suggestions?

**Comment by lmangani** [comment]
@fabiantorress in the screenshot you included with your update

**Comment by fabiantorress** [comment]
Thanks! It works, I am closing this issue
