### ISSUE TITLE
SQL identifiers and string literals aren't escaped in migration.go

### ISSUE THREAD

**Issue by grahamhoyes** [sipcapture/homer-app#537]
I'm working on setting up a Homer install backed by a Google Cloud SQL Postgres database which uses [IAM authentication](https://cloud.google.com/sql/docs/postgres/iam-logins). When doing so, the database user's username is of the form `my-service-account@my-project.iam`.

This causes issues with most of the code in [migrations/migration.go](https://github.com/sipcapture/homer-app/blob/master/migration/migration.go) due to a lack of escaping/quoting for identifiers with just using `fmt.Sprintf` - the `-` and `@`s are a syntax error:

```
postgres=# CREATE DATABASE homer_data OWNER my-service-account@my-project.iam;
ERROR:  syntax error at or near "-"
LINE 1: CREATE DATABASE homer_data OWNER my-service-account@my-proje...
                                           ^
postgres=# CREATE DATABASE homer_data OWNER account@my-project.iam;
ERROR:  syntax error at or near "@"
LINE 1: CREATE DATABASE homer_data OWNER account@my-project.iam;
                                                ^
```

For this to work properly, the username needs to be double-quoted:

```sql
CREATE DATABASE homer_data OWNER "my-service-account@my-project.iam";
```

A similar issue exists when [creating a new user](https://github.com/sipcapture/homer-app/blob/9794301373618b0f978aa2cf792a97695ec9f09c/migration/migration.go#L56) due to the password being unescaped - any `'`s in the password will cause a syntax error at best. Worst case, this code is also vulnerable to SQL injection if there is anywhere that untrusted/unsanitized user inputs are accepted.

I am unfamiliar with the go landscape and Homer's database layer - if parameter binding is possible, that would be the ideal solution. If not, [here is an example implementation](https://github.com/tlocke/pg8000/blob/753a06fd2567e402034fcaa633e00ac7cda6da61/pg8000/converters.py#L727) of proper quoting for identifiers (users, column names, database names, etc) and [here](https://github.com/tlocke/pg8000/blob/753a06fd2567e402034fcaa633e00ac7cda6da61/pg8000/converters.py#L769) for literal strings (like the password). Note that these are just examples I'm familiar with, be aware of that repo's BSD 3-Clause license.

Relevant logs from homer, with fake names:

```
CONNECT to DB ROOT STRING: [host=localhost user=my-service-account@my-project.iam dbname=postgres sslmode=disable port=5432 password=ignored_by_cloud_sql_proxy]
 
HOMER - create db [homer_config] with [name=my-service-account@my-project.iam]

(/homer-app/migration/migration.go:85)
[2023-10-26 17:36:56]  pq: syntax error at or near "-"

(/homer-app/migration/migration.go:85)
[2023-10-26 17:36:56]  [2.58ms]  CREATE DATABASE homer_config OWNER my-service-account@my-project.iam
```

**Comment by lmangani** [comment]
Hello @grahamhoyes feel free to submit a PR with any desired changes to achieve compatibility.

**Comment by grahamhoyes** [comment]
Some details on a possible fix, I am not familiar with go or gorm so there may be inaccuracies:
- I've only seen parameter binding with `?`, `%s`, `:name`, etc work for values, not identifiers. That seems to be backed up by [this stackoverflow post](https://stackoverflow.com/questions/75745602/how-to-remove-single-quotes-from-resultant-query-due-to-parameter-binding-in-gor). So binding with `?` could (and probably should) be used for the password when creating the user, but not elsewhere
- The issue `https://github.com/golang/go/issues/18478` (intentionally not linked to avoid a spammy backlink) has been open for many years on providing escaping in `database/sql`, which I believe gorm is built on. Seems unlikely that will go anywhere.
- The postgres docs on syntax are [here](https://www.postgresql.org/docs/current/sql-syntax-lexical.html). The important part, which is what the above examples from pg8000 do:
  > Quoted identifiers can contain any character, except the character with code zero. (To include a double quote, write two double quotes.)
- `github.com/lib/pq` has a `QuoteIdentifier` function [here](https://github.com/lib/pq/blob/3d613208bca2e74f2a20e04126ed30bcb5c4cc27/conn.go#L1657). That's probably exactly what we want. It doesn't cover the `\0`-containing edge case, but should be good enough.
