### ISSUE TITLE
Flow Default View - heading character limit 

### ISSUE THREAD

**Issue by alex-replicant** [sipcapture/homer-app#542]
Would it be maybe possible to make the character limit (displayed on the line for HEP-LOG events) configurable?
ie: currently, currently it  cuts off some text that user might be interested in:

![HEP-LOG-character limit](https://github.com/sipcapture/homer-app/assets/142171387/f4ef105c-0ae9-4f1b-9486-9ac1dafa8945)

If making it configurable is not an option,  would you be able to suggest where we can change this limit in our deployment?

Thank you in advance

**Comment by naqashsaeed** [comment]
I have tested this by upgrading Homer to latest version, and now I can see more information for LOG in flow tab.
@alex-replicant just upgrade your Homer to latest version and check.
![image](https://github.com/user-attachments/assets/38b7c852-1d2b-46d5-a3a9-50edf13bb5db)
