### ISSUE TITLE
relase tagging

### ISSUE THREAD

**Issue by systemcrash** [sipcapture/homer-app#546]
I know release tagging isn't everyone's favourite thing to do, but the 1.4.59 release tagged in November has assets fresh from a few days ago... confusing:

![Screenshot 2024-02-22 at 16 59 20](https://github.com/sipcapture/homer-app/assets/647633/dcaec5c9-0894-405e-bab1-1235fde75c4d)

Is this intended? That the latest versions inherits all the latest changes until... the next successive version?

Your [GH action](https://github.com/sipcapture/homer-app/actions/runs/7963623515/job/21739593208) for PR #545 logs this:
```
Run boxpositron/upload-multiple-releases@1.0.7
Found 4 asset(s)
homer-app
homer-app-1.4.59-amd64.deb
homer-app-1.4.59-amd64.rpm
homer-ui-1.4.59.tgz
Resolving tag
Release exists, overwriting assets.
Overwriting homer-app
Uploaded homer-app
Overwriting homer-app-1.4.59-amd64.deb
Uploaded homer-app-1.4.59-amd64.deb
Overwriting homer-app-1.4.59-amd64.rpm
Uploaded homer-app-1.4.59-amd64.rpm
Overwriting homer-ui-1.4.59.tgz
Uploaded homer-ui-1.4.59.tgz

```

**Comment by lmangani** [comment]
That's more or less the current status indeed. The CI/Release pipeline uses this floating release as a hooking point and not as a distribution medium for our setups which are all repository based or container based. If this is important and useful we can of course create new releases instead, but in order to do so we should move this last remaining pipeline to github actiions.

**Comment by systemcrash** [comment]
Just let the releaser auto-increment the version number when new features get added or PRs get merged, rather than keep adding features to the latest version release. master/latest is fine with everything. But nailing an image to a particular release version should be an option. That is, until you decide that enough features are worthy of a minor or major version bump. 

https://github.com/sipcapture/homer-app/blob/5327f33cfff127000e4581b28bc690d8d289fcd0/.github/workflows/build.yml#L72-L80

`DEFAULT_BUMP` should be something like `patch`

https://github.com/anothrNick/github-tag-action

**Comment by systemcrash** [comment]
Check also the warnings for your GH actions which run, and bump some of those actions to newer versions.

**Comment by adubovikov** [comment]
I hope now it works as expected:

![image](https://github.com/user-attachments/assets/b6150ef3-366c-4153-9297-e250d437d34c)
