### ISSUE TITLE
Question:  Is there an homer-UNinstall.sh script?

### ISSUE THREAD

**Issue by jagnetta** [sipcapture/homer-app#547]
Good day!

We're experimenting with homer, and redeployed it onto a new server.  Is there an uninstall script that I can use on the original server, or an uninstall procedure?

Thanks,
Jim Agnetta

**Comment by lmangani** [comment]
Hi @jagnetta 
We do not provide any specific uninstall procedure as this depends on the installation method. If you used containers, there's nothing to do other than deleting them and their storage volumes. If you used packages, uninstalling all the packages and removing the storage is usually all it takes.

**Comment by jagnetta** [comment]
Thank you, I used the install script, I think there's a log of what was installed in /tmp, I can work from there.

Thanks Lorenzo!  This issue can be closed.

Jim
