### ISSUE TITLE
Version 7.7 -- Widget result only 200 item displayed

### ISSUE THREAD

**Issue by toannguyen0908** [sipcapture/homer-app#548]
I'm using homer default dashboard. Unfortunately, in the widget results frame, only 200 item displayed. How to increase it?
![image](https://github.com/sipcapture/homer-app/assets/39041939/8bd9ba61-f61c-4266-ba64-469a2e42c415)

**Comment by lmangani** [comment]
Add limit to the widget, set it higher than 200
