### ISSUE TITLE
Not able to see all details of a call in a single trace

### ISSUE THREAD

**Issue by daniruddha29** [sipcapture/homer-app#549]
Hi,

We have homer 7 deployed on in our environment. We use it extensively. We are facing a weird issue. 
Environment : Homer 7 
Homer-app - VERSION: 1.4.59
heplify-server 1.59.4
Postgres 13.11 

When we look for details of a call, they are scattered all over instead in single trace. Not sure if this can give you context of the issue. 
Look at below screenshots (blurring out sensitive part ) -

One exemple :

Start of the trace :
<img width="622" alt="1" src="https://github.com/sipcapture/homer-app/assets/12055480/961725b6-8363-4939-9827-25886ee2d263">

End of the first part of the trace:
<img width="621" alt="2" src="https://github.com/sipcapture/homer-app/assets/12055480/3657ed78-557c-4728-bf14-d317072ea6d0">

Start of the second part of the trace:
<img width="2048" alt="3" src="https://github.com/sipcapture/homer-app/assets/12055480/fdc4ff81-680a-4d6e-b05a-87ea46edc055">

Real end of the tarce:
<img width="816" alt="4" src="https://github.com/sipcapture/homer-app/assets/12055480/9a46cf6e-54da-4fe7-a210-d233c06ed774">

The issue is that we need to have all in one trace to check the call

**Comment by lmangani** [comment]
> When we look for details of a call, they are scattered all over instead in single trace. Not sure if this can give you context of the issue.

The sessions appear to be normal and not "scattered" - you simply have a proxy in the middle of your sessions.

**Comment by daniruddha29** [comment]
Hi @lmangani  thank you so much for your quick answer. 
I am looking for any addition documentation on how this is defined (for displaying the calls). Any lead can be helpful.

**Comment by lmangani** [comment]
@daniruddha29 there are no "calls" in HOMER but rather SIP sessions containing SIP messages. You can search for messages, which belong into sessions and those sessions can relate to one another (if you have a proxy or b2bua) and represent a full end-to-end "call" - just think straight SIP and it'll make sense.

**Comment by daniruddha29** [comment]
@lmangani may be I am not to explain the issue correctly. is is possible if I can record a video and send you the link privately over your email or chat privately. Just to make sure, not exposing customer numbers and our IP addresses? 
This will be very helpful.

**Comment by daniruddha29** [comment]
@lmangani  thank you so much for your quick reply and help. We will surely check the options you said. As always, we love homer and actively using it 🥇
