### ISSUE TITLE
LOGIN Require Fields

### ISSUE THREAD

**Issue by lmangani** [sipcapture/homer-app#55]
When logging in, autofill credentials still cause the field required warnings to be displayed:

![image](https://user-images.githubusercontent.com/1423657/51427977-50a2cb00-1bfe-11e9-88e3-386edd12abe7.png)

**Comment by negbie** [comment]
Another minor thing. When user enters a too short you get a log line Error: child "password" fails because ["password" length must be at least 8 characters long]
but the user does not get a warning in the ui.

**Comment by lmangani** [comment]
@negbie this is a backend error and indeed, we should print it out
@sergibondarenko could you take care of this?

**Comment by sergibondarenko** [comment]
@lmangani sure, I'll do it later
The solution to the current issue is https://gist.github.com/pc035860/8018569
Some more discussion on this https://stackoverflow.com/questions/14965968/angularjs-browser-autofill-workaround-by-using-a-directive

@negbie your issue i unreleated to this one, please open a new issue in such cases in the future.

**Comment by negbie** [comment]
@sergibondarenko sure, sorry for this!
