### ISSUE TITLE
Building from source tagged release 1.4.59 build version 1.1.7

### ISSUE THREAD

**Issue by rnalrd** [sipcapture/homer-app#555]
Hello, I'm a package maintainer: I've downloaded the 1.4.9 tar.gz and built homer-app from source:

~ # homer-app -version
VERSION: 1.1.7

Is this related to #546 ?

**Comment by hamidrhashmi** [comment]
Version is mentioned correctly in [file](https://github.com/sipcapture/homer-app/blob/5327f33cfff127000e4581b28bc690d8d289fcd0/version.go#L4). Please check on your side. if you have correctly compiled and installed.

**Comment by rnalrd** [comment]
Found out the issue: in the sources there's a binary `homer-app` version 1.1.7:

```
~# ./release/homer-app_linux_amd64/homer-app --version
VERSION: 1.1.7
```

**Comment by adubovikov** [comment]
thank you - we will remove it
