### ISSUE TITLE
How to configured oauth2 (or sso or whatever) with Okta SSO

### ISSUE THREAD

**Issue by jagnetta** [sipcapture/homer-app#562]
Good morning,

I'm wondering if you have had any experience with okta-dev and their oauth2 authentication?

I've been trying to figure which parameters in the webapp_config.json file, especially the redirect uri

It's not a subject I'm very familiar with.  Any help is appreciated.

Thanks,
Jim Agnetta
jagtnetta@8x8.com

**Comment by jagnetta** [comment]
Hello, is there any guidance available for connecting oauth2 to okta?

THanks,
Jim

**Comment by lmangani** [comment]
@jagnetta okta integrations are quite tedious to configure, we won't be able to assist with unless a bug is reported

**Comment by jagnetta** [comment]
@lmangani - thanks for the follow-up.
