### ISSUE TITLE
OAuth2 with custom provider

### ISSUE THREAD

**Issue by fabio-manzo** [sipcapture/homer-app#563]
Hi all,
this is my configuration:
`  "oauth2": {
    "enable": true,
    "client_id": "XXX",
    "client_secret": "XXX",
    "project_id": "APP-XXX",
    "auth_uri": "https://XXX/authorize",
    "token_uri": "https://XXX/access_token",
    "redirect_uri": "https://homer/api/v3/oauth2",
    "profile_url": "https://XXX/userinfo",
    "provider_name": "auth",
    "scope": ["email", "openid", "profile"],
    "provider_image": ""
  },`

I get the login page, but when i get redirected to redirect + / + provider_name i get this page:
{"message":"invalid or expired jwt"}

I tried changing the redirect_uri as "https://homer/api/v3/oauth2/auth" and the provider_name as "myprovidername" but then I get:
{"data":{},"message":"Post \"https://XXX/access_token\": tls: failed to verify certificate: x509: certificate signed by unknown authority"}

**Comment by fabio-manzo** [comment]
Please anyone? The provider return a cookie with 2 values (bwen, wen), should I change something on my side? Or on the provider side?

**Comment by lmangani** [comment]
> Your report is appreciated. Please star this repository to motivate its developers! ⭐

![image](https://github.com/sipcapture/homer-app/assets/1423657/c5e28f9a-3049-416f-a288-0d93550490f9)

**Comment by fabio-manzo** [comment]
Hi, I already starred the project after the first message. I would like to do more but I'm not in position to take this choice by myself and considering the auth it's not working I cannot ask for it

**Comment by adubovikov** [comment]
so, the problem is that your provider uses self sign certificate, can you do/change it to letsencrypt ?

**Comment by adubovikov** [comment]
so as I wrote above, please use letsencrypt or add exception for your self generated certificate. The issue will be closed.
