### ISSUE TITLE
Search by reason_phrase / method text.

### ISSUE THREAD

**Issue by W1ck3dZA** [sipcapture/homer-app#573]
Is it possible to enable the option to search by reason_phrase or method text and not just the method codes like 403 or 404.

This use to be possible in Homer 5 UI but cant seem to get it working in Homer 7.

I would ideally like the option to search for different strings and also display them in results table.

Below is a sample of what I am referring to 

`SIP/2.0 403 Relayed Response:  Forbidden`

**Comment by naqashsaeed** [comment]
Hi @W1ck3dZA , You can use `SIP RAW` field to search  by reason_phrase or method text. However in result widget this field didn't show you any data but you can make a search through it in both smart search and through sip messages call search.
![image](https://github.com/user-attachments/assets/b53d1aa1-46e7-499d-84cc-78467c1e200f)

**Comment by W1ck3dZA** [comment]
> Hi @W1ck3dZA , You can use `SIP RAW` field to search by reason_phrase or method text. However in result widget this field didn't show you any data but you can make a search through it in both smart search and through sip messages call search. ![image](https://private-user-images.githubusercontent.com/110665986/387531981-b53d1aa1-46e7-499d-84cc-78467c1e200f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMTIyNjgsIm5iZiI6MTczMjAxMTk2OCwicGF0aCI6Ii8xMTA2NjU5ODYvMzg3NTMxOTgxLWI1M2QxYWExLTQ2ZTctNDk5ZC04NGNjLTc4NDY3YzFlMjAwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQxMDI2MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzViZjI5OGJhNjUwZjYyOTgxMGM0ZWYyNjc2NmFkYWNhYzU5OTViZDljYThhZTg4ZTk0YzIyYmNjYmI5ODQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EVfG6GdZ6RfbShyhFkx-s7nL5Op3I4JmCXc8Ypc2Ibc)

Thank you so much its works perfectly...
