### ISSUE TITLE
How to change the export PCAP names

### ISSUE THREAD

**Issue by phobospt** [sipcapture/homer-app#576]
Hi there,
Can I please get some pointers on how to change the export PCAP file names to include a string like CUSTOMSTRING-$SIP_FROM_USER-DATE-TIME.pcap?

I have been having a look at the API calls via Wireshark and I can see the that it was calling api/v3/export.call/messages/pcap

Can also see the attachment as export-YYYY-MM-DDTHH:MM:SSZ.pcap but the final saved file is export_CallID.pcap.

Some pointers on how to change these would be amazing thanks

**Comment by kYroL01** [comment]
Hello @phobospt , unfortunately, there's no possibility to change the pcap name from the API, since the implementation in hardcoded, and also for security reasons we cannot expose that part.

Best Regards
