### ISSUE TITLE
Limit db results

### ISSUE THREAD

**Issue by negbie** [sipcapture/homer-app#67]
Without DB limits and decent datasets you will kill/eat your host memory pretty fast.

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x12190dc [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewStruct(v8::internal::InstanceType) [node]

**Comment by negbie** [comment]
Should be fixed by https://github.com/sipcapture/homer-app/pull/89
at least for sip search

**Comment by adubovikov** [comment]
done
