### ISSUE TITLE
Avoid unnecessary api calls

### ISSUE THREAD

**Issue by negbie** [sipcapture/homer-app#69]
Without statistics widget there is still one call to
http://localhost:8880/api/v3/statistic/data 
on timeframe change. This results in errors when influxdb isn't present.

**Comment by lmangani** [comment]
Confirmed

**Comment by negbie** [comment]
This gets even worse on a simple timerange change in transaction window and results in 27 calls to 
http://localhost:8880/api/v3/search/call/data

![screenshot_20190130_153306](https://user-images.githubusercontent.com/20154956/51988187-6046cd00-24a4-11e9-9f0b-b9cabd26d64f.png)

**Comment by almukhametovd** [comment]
https://github.com/sipcapture/homer-app/pull/104
