### ISSUE TITLE
Last Search Cache

### ISSUE THREAD

**Issue by lmangani** [sipcapture/homer-app#7]
The last search parameters are not cached and reapplied on page refresh/reload as intended.
Edit: minimal feature as per ui-grid preferences

**Comment by lmangani** [comment]
Possible related to https://github.com/sipcapture/homer-app/issues/5 from cache perspective

**Comment by adubovikov** [comment]
the logic is same as in HEPIC or in H5 - on RELOAD we should send an API request to restore ALL profiles into memory. Same for search. Once you press the SEARCH button - we update the "search profile" ASAP (async process with API), that can be restored and used later.

**Comment by sergibondarenko** [comment]
@adubovikov @lmangani  
> on RELOAD

The whole app reload? Can you show me the place in the old app where it is implemented? 

> Once you press the SEARCH button - we update the "search profile" ASAP (async process with API), that can be restored and used later.

Do you mean this? https://gitlab.com/qxip/hepic-ui/blob/master/app/controllers/search/searchcallController.js#L57

**Comment by sergibondarenko** [comment]
This was solved by a series of PRs:
https://github.com/sipcapture/homer-app/pull/30
https://github.com/sipcapture/homer-app/pull/28
https://github.com/sipcapture/homer-app/pull/14
