### ISSUE TITLE
Multiple errors in transaction window

### ISSUE THREAD

**Issue by negbie** [sipcapture/homer-app#70]
Opened a transaction and saw in dev console:

TypeError: data.map is not a function
bundle.js:360599 Uncaught (in promise) TypeError: Cannot read property 'values' of undefined
    at CallDetailQos._configureChart (bundle.js:360599)

**Comment by adubovikov** [comment]
yes, @lmangani has opened the ticket https://github.com/sipcapture/homer-app/issues/63 for this

**Comment by negbie** [comment]
Close duplicate of https://github.com/sipcapture/homer-app/issues/63
