### ISSUE TITLE
Option to hide certain heptypes from flow

### ISSUE THREAD

**Issue by negbie** [sipcapture/homer-app#73]
Like RTCP

**Comment by lmangani** [comment]
Shall we add an option to the advanced keyvalue store to control what protocols are part of the tab resolution?

**Comment by negbie** [comment]
Sounds like a good way to do it. Just noticed that it could be distracting when you have a lot of different heptypes in one flow.

**Comment by adubovikov** [comment]
the best way make a drop down menu there you can enable/disable protocols on the flow.
