### ISSUE TITLE
Drop down menu glitch

### ISSUE THREAD

**Issue by ognyenius** [sipcapture/homer-app#92]
"Search results" page column drop down menu:
When column drop down menu is pressed the glitch is appearing below the settings icon in upper right corner of the table

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/47450374/53826562-21aba300-3f79-11e9-9662-b896562cfbfb.gif)

**Comment by adubovikov** [comment]
@ognyenius can you please check if the bug is still valid ?

**Comment by ognyenius** [comment]
@adubovikov yes. I tested it again. Still shows the same glitch.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/47450374/54039919-67a87700-41c4-11e9-9b93-c2826ce29d79.gif)

**Comment by ognyenius** [comment]
@adubovikov Yes. I tested it again. The bug is still unresolved as you can see in the screenshot
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/47450374/54041267-8bb98780-41c7-11e9-8e52-15b4de83fd8f.gif)
