### ISSUE TITLE
Last column menu overflow

### ISSUE THREAD

**Issue by ognyenius** [sipcapture/homer-app#93]
"Search result" page:
When drop down menu for the last column is pressed, it overflows

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/47450374/53827510-97187300-3f7b-11e9-83ca-4605e42aadba.gif)

**Comment by adubovikov** [comment]
@sergibondarenko can you please take a look at this ?

**Comment by almukhametovd** [comment]
https://github.com/sipcapture/homer-app/pull/100

**Comment by ognyenius** [comment]
Issue still not resolved. Would you show me an example of your fix? I tested it again and the last column still overflows. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/47450374/54042105-a4c33800-41c9-11e9-956b-254eef261c28.gif)

**Comment by almukhametovd** [comment]
This PR isn't merged 
https://github.com/sipcapture/homer-app/pull/100

**Comment by almukhametovd** [comment]
@ognyenius could you please recheck

**Comment by adubovikov** [comment]
@ognyenius can you please recheck ?

**Comment by ognyenius** [comment]
@adubovikov checked. works fine now. thanks!

**Comment by adubovikov** [comment]
super!
