### ISSUE TITLE
Search Results page - icons overflow

### ISSUE THREAD

**Issue by ognyenius** [sipcapture/homer-app#95]
Search Results page:
When "Group" feature is pressed at the column drop down menu "settings" icon overlaps "plus" (+) icon (at the upper left corner of the table) 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/47450374/53884394-cb437080-401b-11e9-907a-83d20fd2417e.gif)

**Comment by almukhametovd** [comment]
https://github.com/sipcapture/homer-app/pull/99
